/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KGSG_Not_Matched_With_UBI.java
 *
 * Created on Jul 2, 2013, 4:11:32 PM
 */

package atm;

/**
 *
 * @author welcome
 */
public class KGSG_Not_Matched_With_UBI extends javax.swing.JInternalFrame {
javax.swing.table.DefaultTableModel dtm;
    /** Creates new form KGSG_Not_Matched_With_UBI */
    public KGSG_Not_Matched_With_UBI() {
        initComponents();
        //jPanel1.setVisible(false);
        //jPanel2.setVisible(false);
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter=new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        String heading[]={"Sr. No","Date","Trans ID","Particular","Debit","Credit","Balance Amount","Comments"};
        dtm=new javax.swing.table.DefaultTableModel(heading,0);

        jTable1.setModel(dtm);
        jTable1.setRowHeight(25);
        javax.swing.table.TableColumn column;
        //jPanel2.setVisible(false);
//jTable1.getTableHeader().setFont(new Font("Vardana", Font.BOLD, 12));
        column=jTable1.getColumn("Sr. No");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(50);
        column=jTable1.getColumn("Trans ID");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(90);
        column=jTable1.getColumn("Date");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(90);
        column=jTable1.getColumn("Particular");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(270);
        column=jTable1.getColumn("Debit");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(97);
        column=jTable1.getColumn("Credit");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Balance Amount");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(120);
        column=jTable1.getColumn("Comments");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(220);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(186, 221, 221));
        setClosable(true);
        setIconifiable(true);
        setTitle("KGSG Report");

        jPanel2.setBackground(new java.awt.Color(250, 245, 216));
        jPanel2.setLayout(null);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel1.setText("Particular");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 70, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 20, 410, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel3.setText("Debit");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 160, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 70, 160, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel5.setText("Credit");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 70, 90, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 70, 140, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 1, 12));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(550, 20, 420, 80);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 490, 990, 120);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(78, 75, 71));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(20);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 90, 990, 390);

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setLayout(null);

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 0));
        jButton1.setText("KGSG Not Reconcile Records");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(20, 20, 490, 30);

        jButton3.setBackground(java.awt.Color.white);
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 51, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/Close1.gif"))); // NOI18N
        jButton3.setText("Cancel");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(520, 20, 450, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 10, 990, 70);

        jButton4.setBackground(java.awt.Color.white);
        jButton4.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton4.setText("Under Treatment");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(10, 620, 480, 30);

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton2.setText("Treatment Completed");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(560, 620, 440, 30);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        class task1 extends Thread
        {
            public void run()
            {
                try
                {
                    table();
                    Thread.sleep(1000);
                    
                }
                catch(Exception ex)
                {
                     System.out.println("error..."+ex);
                }

            }
       }
       task1 t1=new task1();
       t1.start();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            class task1 extends Thread
            {
                public void run()
                {
                    try
                    {
                        table();
                        Thread.sleep(1000);
                    }
                    catch(Exception ex)
                    {
                         System.out.println("error..."+ex);
                    }

                }
           }
       task1 t1=new task1();
       t1.start();
        }
}//GEN-LAST:event_jButton1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode()==10)
       {
           clr();
           jLabel2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
           jLabel4.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
           jLabel6.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
           jTextArea1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
           //jPanel1.setVisible(true);
       }
       
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        class task1 extends Thread
        {
            public void run()
            {
                try
                {
                     autoReversalProcess();
                     Thread.sleep(100);
                }
                catch(InterruptedException ex)
                {
                     System.out.println("error..."+ex);
                }
            }
        }
        task1 t1=new task1();
        t1.start();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        class task1 extends Thread
        {
            public void run()
            {
                try
                {
                     treatcpt();
                     Thread.sleep(100);
                }
                catch(InterruptedException ex)
                {
                     System.out.println("error..."+ex);
                }
            }
        }
        task1 t1=new task1();
        t1.start();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            class task1 extends Thread
            {
                public void run()
                {
                    try
                    {
                         autoReversalProcess();
                         Thread.sleep(100);
                    }
                    catch(InterruptedException ex)
                    {
                         System.out.println("error..."+ex);
                    }
                }
            }
            task1 t1=new task1();
            t1.start();
        }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            class task1 extends Thread
            {
                public void run()
                {
                    try
                    {
                         treatcpt();
                         Thread.sleep(100);
                    }
                    catch(InterruptedException ex)
                    {
                         System.out.println("error..."+ex);
                    }
                }
            }
            task1 t1=new task1();
            t1.start();
        }
    }//GEN-LAST:event_jButton2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

     private boolean table()
{
    String qry="";
        try
        {
            interfaceATM object1=null;
            try
            {
		object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
		System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                getIPaddress.changeIP();
		try
		{
			object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception ex)
		{
			System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
		}
            }
            //double total=0.0;
            java.math.BigDecimal bd=null;
            qry="Select tran_date,tran_id,particular,tran_debit_amt,tran_credit_amt,balance_amt,comment from kgsg_n_ubi where recon_status=0 and recon_status<>"+20+" ";
            System.out.println(qry);
            String load[][]=object1.getInformationDD(qry,7);
            System.out.println(load.length);
            String arr[]=null;
            //int total=0;
            dtm.setRowCount(0);
            if(load.length>0)
            {
                //System.out.println("hello111111111111111111111111111");
                arr=new String[8];
                for(int i=0;i<load.length;i++)
                {


                    arr[0]=""+(dtm.getRowCount()+1);
                    String dt[]=load[i][0].split("-");
                    String date=dt[2]+"-"+dt[1]+"-"+dt[0];
                    arr[1]=date;
                    arr[2]=load[i][1];
                    arr[3]=load[i][2];
                    arr[4]=load[i][3];
                    arr[5]=load[i][4];
                    arr[6]=load[i][5];
                    arr[7]=load[i][6];

                    dtm.addRow(arr);
                    System.out.println("hello   "+i);
                }

            }
            return true;
        }
        catch(Exception ae)
        {
            System.out.println("Error in Table method...."+ae);
        }
        return true;

}
    
    public void autoReversalProcess()
    {
        try
        {
            interfaceATM object1=null;
            try
            {
		object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
		System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                getIPaddress.changeIP();
		try
		{
			object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception ex)
		{
			System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
		}
            }
            String qry="";
            qry="update kgsg_n_ubi set comment='"+jTextArea1.getText()+"' where particular='"+jLabel2.getText()+"' and tran_debit_amt="+Double.valueOf(jLabel4.getText().trim())+" and tran_credit_amt="+Double.valueOf(jLabel6.getText().trim())+"";
            boolean bn=object1.saveInformation(qry);
            qry="update kgsg_n_ubi set comment='"+jTextArea1.getText()+"' where particular='"+jLabel2.getText()+"' and tran_debit_amt="+Double.valueOf(jLabel6.getText().trim())+" and tran_credit_amt="+Double.valueOf(jLabel4.getText().trim())+"";
            boolean bn1=object1.saveInformation(qry);
            System.out.println("inser qury process info....."+bn);
            if(bn==true && bn1==true)
            {
                javax.swing.JOptionPane.showMessageDialog(this,"!Congratulation\nAuto Reversal moving under treatment completed.");
                clr();
                table();
            }
        }
        catch(Exception ae)
        {
            System.out.println("Eror in autoReversalProcess....."+ae);
        }

    }
    public void clr()
    {
                jLabel2.setText("");
                jLabel4.setText("");
                jLabel6.setText("");
                jTextArea1.setText("");
    }

    /*public boolean search()
    {
        jButton1.setVisible(false);
        //jPanel2.setVisible(true);
        String qry="";
        try
        {
            interfaceATM object1=null;
            try
            {
		object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
		System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                getIPaddress.changeIP();
		try
		{
			object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception ex)
		{
			System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
		}
            }
            //double total=0.0;
            java.math.BigDecimal bd=null;
            qry="Select tran_date,tran_id,particular,tran_debit_amt,tran_credit_amt,balance_amt from kgsg_n_ubi where recon_status=0 and recon_status<>"+10+" and recon_status<>"+20+" ";
            System.out.println(qry);
            String load[][]=object1.getInformationDD(qry,6);
            System.out.println(load.length);
            String arr[]=null;
            //int total=0;
            dtm.setRowCount(0);
            if(load.length>0)
            {
                //System.out.println("hello111111111111111111111111111");
                arr=new String[7];
                for(int i=0;i<load.length;i++)
                {


                    arr[0]=""+(dtm.getRowCount()+1);
                    String dt[]=load[i][0].split("-");
                    String date=dt[2]+"-"+dt[1]+"-"+dt[0];
                    arr[1]=date;
                    arr[2]=load[i][1];
                    arr[3]=load[i][2];
                    arr[4]=load[i][3];
                    arr[5]=load[i][4];
                    arr[6]=load[i][5];
                    if(arr[3].equalsIgnoreCase(jTextField1.getText().trim()))
                    {
                        dtm.addRow(arr);

                    }


                    
                    System.out.println("hello   "+i);
                }

            }
            return true;
        }
        catch(Exception ae)
        {
            System.out.println("Error in Table method...."+ae);
        }
        return true;
    }*/
    public boolean treatcpt()
    {
        try
        {
            interfaceATM object1=null;
            try
            {
		object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
		System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                getIPaddress.changeIP();
		try
		{
			object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception ex)
		{
			System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
		}
            }
            String qry="update kgsg_n_ubi set comment='"+jTextArea1.getText()+"',recon_status="+20+" where particular='"+jLabel2.getText()+"' and tran_debit_amt="+Double.valueOf(jLabel4.getText().trim())+" and tran_credit_amt="+Double.valueOf(jLabel6.getText().trim())+"";
            boolean bn=object1.saveInformation(qry);
            qry="update kgsg_n_ubi set comment='"+jTextArea1.getText()+"',recon_status="+20+" where particular='"+jLabel2.getText()+"' and tran_debit_amt="+Double.valueOf(jLabel6.getText().trim())+" and tran_credit_amt="+Double.valueOf(jLabel4.getText().trim())+"";
            boolean bn1=object1.saveInformation(qry);
            System.out.println("inser qury process info....."+bn);
            if(bn==true && bn1==true)
            {
                javax.swing.JOptionPane.showMessageDialog(this,"!Congratulation\nAuto reversal treatment moving process completed.");
                clr();
                table();
            }

        }
        catch(Exception ae)
        {
            System.out.println("Error in Table method...."+ae);
        }
        return true;
    }
}
