/*
 * BirthCertificate.java
 *
 * Created on June 11, 2011, 11:09 AM
 */



/**
 *
 * @author  Administrator
 */
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import java.rmi.*;
import java.awt.geom.*;
import javax.print.PrintService;
import java.awt.print.*;
import javax.print.attribute.*;
import java.awt.font.*;
import java.util.*;
public class BirthCertificate extends javax.swing.JInternalFrame 
{
    
    /** Creates new form BirthCertificate */

	int d=0,m=0,y=0;
	String date,arr1[],month,year;
	ZedInterface inf;

	public BirthCertificate(JDesktopPane dp) 
	{
        	initComponents();
        	desk=dp;
		try
		{	
			//zedint=(ZedInterface)Naming.lookup(getIPaddress.IP());
			
	try
							{
								inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
				
				
							}
							catch(Exception e)
							{
									System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
							getIPaddress.changeIP();
									try
									{
										inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
											
										
									}
									catch(Exception ex)
									{
										System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/ExtendZedServer  ..."+ex);
									}
							}					
			
			
			
			
			int Maxid=0;
			Maxid=inf.getMaxValue("select MAX(certificateNo) from birthCertificate");
			if(Maxid!=0)
			{	
				jLabel2.setText(""+(Maxid+1));
			}
			else
			{	
				jLabel2.setText(""+1);
			}
			Date dt=new Date();
			d=dt.getDate();
			m=1+dt.getMonth();
			y=1900+dt.getYear();
			date=d+"/"+m+"/"+y;
			jLabel11.setText(date);
			jLabel14.setText(date);
			jLabel4.setText(date);
			jButton6.setEnabled(false);	
		}
		catch(Exception e)
		{
			System.out.println("Error" +e);
		}
	}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setBackground(new java.awt.Color(60, 220, 220));
        setClosable(true);
        setTitle("Birth Certificate");
        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        jLabel1.setText("Certificate No.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 80, 20);

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 10, 70, 20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Date ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 10, 40, 20);

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 10, 100, 20);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar.gif")));
        jButton1.setToolTipText("Set Date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jPanel1.add(jButton1);
        jButton1.setBounds(340, 5, 30, 30);

        jLabel5.setText("Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 50, 90, 20);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jPanel1.add(jTextField1);
        jTextField1.setBounds(100, 50, 270, 19);

        jPanel2.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Residence Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 11), new java.awt.Color(0, 0, 204)));
        jLabel6.setText("Vill . /  Mohalla");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 20, 120, 20);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jPanel2.add(jTextField2);
        jTextField2.setBounds(140, 20, 210, 19);

        jLabel7.setText("Post . /  Block");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 50, 120, 20);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jPanel2.add(jTextField3);
        jTextField3.setBounds(140, 50, 210, 19);

        jLabel8.setText("District");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 80, 120, 20);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jPanel2.add(jTextField4);
        jTextField4.setBounds(140, 80, 210, 19);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 110, 360, 110);

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jPanel1.add(jTextField5);
        jTextField5.setBounds(100, 230, 270, 19);

        jLabel9.setText("Child Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 230, 90, 20);

        jLabel15.setText("Wife Of");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 80, 90, 20);

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });

        jPanel1.add(jTextField7);
        jTextField7.setBounds(100, 80, 270, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 380, 260);

        jPanel3.setLayout(null);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        jLabel10.setText("Hospital Registration No.");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 10, 150, 20);

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });

        jPanel3.add(jTextField6);
        jTextField6.setBounds(150, 10, 220, 19);

        jLabel11.setBackground(new java.awt.Color(255, 204, 204));
        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("jLabel11");
        jLabel11.setOpaque(true);
        jPanel3.add(jLabel11);
        jLabel11.setBounds(150, 40, 150, 20);

        jLabel12.setText("Date Of Registration ");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 40, 140, 20);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar.gif")));
        jButton2.setToolTipText("Set Date");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jPanel3.add(jButton2);
        jButton2.setBounds(300, 35, 30, 30);

        jLabel13.setText("Date Of Issue");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 80, 140, 20);

        jLabel14.setBackground(new java.awt.Color(255, 204, 204));
        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("jLabel14");
        jLabel14.setOpaque(true);
        jPanel3.add(jLabel14);
        jLabel14.setBounds(150, 80, 150, 20);

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar.gif")));
        jButton3.setToolTipText("Set Date");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jButton3.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jButton3VetoableChange(evt);
            }
        });

        jPanel3.add(jButton3);
        jButton3.setBounds(300, 75, 30, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 280, 380, 110);

        jPanel4.setLayout(null);

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.gif")));
        jButton5.setMnemonic('s');
        jButton5.setText("Save");
        jButton5.setToolTipText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });

        jPanel4.add(jButton5);
        jButton5.setBounds(10, 10, 110, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PRINT.GIF")));
        jButton6.setMnemonic('p');
        jButton6.setText("Print");
        jButton6.setToolTipText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        jPanel4.add(jButton6);
        jButton6.setBounds(140, 10, 110, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.gif")));
        jButton7.setMnemonic('c');
        jButton7.setText("Close");
        jButton7.setToolTipText("Close");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });

        jPanel4.add(jButton7);
        jButton7.setBounds(260, 10, 110, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 400, 380, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jButton3VetoableChange
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3VetoableChange

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10) {
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            //date
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            //date of issue
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            //date of reg.
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10) {
            dispose();
        }
    }//GEN-LAST:event_jButton7KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10) {
            //print
            printBirth b=new printBirth(desk);
        }
    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
        //print
        printBirth b=new printBirth(desk);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10) {
            //save
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
       //save
       saveButton();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        //date of issue.
        		Cal calender=new Cal();
 				jLabel14.setText(calender.getdate());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        //date of reg.
        	Cal calender=new Cal();
 			jLabel11.setText(calender.getdate());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
// TODO add your handling code here:
         if(evt.getKeyCode()==10) {
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
// TODO add your handling code here:
         if(evt.getKeyCode()==10) {
            jTextField6.requestFocus();
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
// TODO add your handling code here:
         if(evt.getKeyCode()==10) {
            jTextField5.requestFocus();
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
// TODO add your handling code here:
         if(evt.getKeyCode()==10) {
            jTextField4.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
// TODO add your handling code here:
         if(evt.getKeyCode()==10) {
            jTextField3.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) 
    {//GEN-FIRST:event_jTextField1KeyPressed
	// TODO add your handling code here:
     	 if(evt.getKeyCode()==10) {
            jTextField7.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) 
    {	//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
    	Cal calender=new Cal();
 		jLabel4.setText(calender.getdate());
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    
    JDesktopPane desk;
    // End of variables declaration//GEN-END:variables
	private boolean saveButton()
	{
		try
		{	
			boolean flag=true;
			arr1=new String[11];
			arr1[0]=jLabel2.getText();
			arr1[1]=jLabel4.getText();
			arr1[2]=jTextField1.getText();
			arr1[3]=jTextField7.getText();
			arr1[4]=jTextField2.getText();
			arr1[5]=jTextField3.getText();
			arr1[6]=jTextField4.getText();
			arr1[7]=jTextField5.getText();
			arr1[8]=jTextField6.getText();
			arr1[9]=jLabel11.getText();
			arr1[10]=jLabel14.getText();
			if(arr1[2].trim().length()==0)
			{	
				JOptionPane.showMessageDialog(jTextField5," Please Input Name ","Error",JOptionPane.ERROR_MESSAGE);		
				jTextField1.requestFocus();
				flag=false;
				return false;
			}
			if(arr1[3].trim().length()==0)
			{	
				JOptionPane.showMessageDialog(jTextField5,"Please Input Husband Name","Error",JOptionPane.ERROR_MESSAGE);		
				jTextField7.requestFocus();
				flag=false;
				return false;
			}
			if(arr1[4].trim().length()==0)
			{	
				JOptionPane.showMessageDialog(jTextField5,"Please Input Village Name","Error",JOptionPane.ERROR_MESSAGE);		
				jTextField2.requestFocus();
				flag=false;
				return false;
			}
			if(arr1[5].trim().length()==0)
			{	
				JOptionPane.showMessageDialog(jTextField5,"Please Input Post ","Error",JOptionPane.ERROR_MESSAGE);		
				jTextField3.requestFocus();
				flag=false;
				return false;
			}
			if(arr1[6].trim().length()==0)
			{	
				JOptionPane.showMessageDialog(jTextField5,"Please Input District Name","Error",JOptionPane.ERROR_MESSAGE);		
				jTextField4.requestFocus();
				flag=false;
				return false;
			}
			if(arr1[7].trim().length()==0)
			{	
				JOptionPane.showMessageDialog(jTextField5,"Please Input Child Name","Error",JOptionPane.ERROR_MESSAGE);		
				jTextField5.requestFocus();
				flag=false;
				return false;
			}
			if(arr1[8].trim().length()==0)
			{	
				JOptionPane.showMessageDialog(jTextField5,"Please Input Hospital Registration No","Error",JOptionPane.ERROR_MESSAGE);		
				jTextField6.requestFocus();
				flag=false;
				return false;
			}
			if(flag)
			{
				String name=inf.getSingleValue("select wardCatName from wardCategory where wardCatName='"+arr1[1]+"'");	
				
			
				{	
					int Maxid=0;
					Maxid=inf.getMaxValue("select MAX(certificateNo) from birthCertificate");	
					if(Maxid!=0)
					{	
						arr1[0]=""+(Maxid+1);
					}
					else
					{	
						arr1[0]="1";
					}
					//...
					jLabel2.setText(arr1[0]);
					//...
					String str[]=new String[3];
					arr1[1]=jLabel4.getText();
					str=arr1[1].split("/");
					date=str[0];
					month=str[1];
					year=str[2];
					arr1[1]=month+"/"+date+"/"+year;
				
					arr1[2]=jTextField1.getText();
					arr1[3]=jTextField7.getText();
					arr1[4]=jTextField2.getText();
					arr1[5]=jTextField3.getText();
					arr1[6]=jTextField4.getText();
					arr1[7]=jTextField5.getText();
					arr1[8]=jTextField6.getText();
				
					arr1[9]=jLabel11.getText();
					str=arr1[9].split("/");
					date=str[0];
					month=str[1];
					year=str[2];
					arr1[9]=month+"/"+date+"/"+year;
				
					arr1[10]=jLabel14.getText();
					str=arr1[10].split("/");
					date=str[0];
					month=str[1];
					year=str[2];
					arr1[10]=month+"/"+date+"/"+year;
					int res=JOptionPane.showConfirmDialog(null,"Are You Sure ?");
					if(res==JOptionPane.YES_OPTION)
					{
						inf.executeUpdateQuery("insert into birthCertificate values("+Integer.parseInt(arr1[0])+",#"+arr1[1]+"#,'"+arr1[2]+"','"+arr1[3]+"','"+arr1[4]+"','"+arr1[5]+"','"+arr1[6]+"','"+arr1[7]+"','"+arr1[8]+"',#"+arr1[9]+"#,#"+arr1[10]+"#)");
						JOptionPane.showMessageDialog(this,"Certificate Creation Successful.");
						jButton5.setEnabled(false);
						jButton6.setEnabled(true);
						jButton6.requestFocus();
					}
					
				}
			}
		}
		catch(Exception sql)
		{
			System.out.println("Error...." +sql);
		}
		return true;	
	}	
    
    //printing starts....................
    class printBirth extends JFrame 
   {
        	JInternalFrame pchallanf;
	        Container contentPane;
        	GridBagLayout gbl;
	        GridBagConstraints gbc;
        	JButton printButton;
	        JButton pageSetupButton,exitButton;

			PrintPanel canvas;
	        PageFormat pageFormat;

        	public printBirth(JDesktopPane desk)
        	{
                pchallanf=new JInternalFrame("Printing of Invoice",false,true,true,true);
                contentPane=pchallanf.getContentPane();
				gbl=new GridBagLayout();
				gbc=new GridBagConstraints();
                contentPane.setLayout(new BorderLayout());

                addWindowListener(new WindowAdapter()
                {
                        public void windowClosing(WindowEvent e)
                        {
                                System.exit(0);
                        }
                }
                );

                canvas=new PrintPanel();
                contentPane.add(canvas,"Center");
                JPanel buttonPanel = new JPanel();
                buttonPanel.setLayout(new GridLayout(2,1));

                //pageSetupButton.addActionListener(this);

                contentPane.add(buttonPanel,"East");

                                PrinterJob printJob=PrinterJob.getPrinterJob();
                                double width=7.1*72;//8.27 * 72;
                                double height=9.7*72;//(11.69 * 72);
                                Paper paper=new Paper();                                
                                paper.setSize(width,height);

                                PageFormat page=new PageFormat();
                                paper.setImageableArea(5,10,paper.getWidth(),paper.getHeight());
                                //page.setOrientation(PageFormat.LANDSCAPE);
                                page.setPaper(paper);
                                pageFormat=printJob.defaultPage(page);
                                pageFormat.setPaper(paper);
                                printJob.setPrintable(canvas,pageFormat);
								
                                try
                                {
										System.out.println("W="+paper.getWidth()+"H="+paper.getHeight());
										currentpg=1;
										printJob.print();
	                            }
                                catch(Exception exception)
                                {
                                        JOptionPane.showMessageDialog(this,exception);
                                }
        		}
	}
	
	
		int currentpg,totalpg, rem;
	boolean firsttime=false;
	boolean complete=false;
	int currentrec=0,startno=0,endno=0;
  class PrintPanel extends JPanel implements Printable
	{
        //Connection connection;
        //Statement st,st1;
        //ResultSet rs,rs1;
        int page=100;
		TextLayout layout;
		Font f,f1,f2,f3,f4,f5,f6;
		Graphics2D g2;
		int row=0;		
		FontRenderContext context;
        
        
        public PrintPanel()
        {
                //ChallanNo=JOptionPane.showInputDialog(null,"Enter Challan Number:");
        }
        public void paintComponent(Graphics g)
        {
                super.paintComponent(g);
                Graphics2D g2=(Graphics2D)g;
                drawPage(g2);
        }
        public int print(Graphics g,PageFormat pf,int page) throws PrinterException
        {
                if(page>=1)
                        return Printable.NO_SUCH_PAGE;
                Graphics2D g2=(Graphics2D)g;
                g2.setPaint(Color.black);
                g2.translate(pf.getImageableX(),pf.getImageableY());
                //g2.draw(new Rectangle2D.Double(0,0,pf.getImageableWidth(),pf.getImageableHeight()));
                System.out.println("W1="+pf.getImageableWidth()+"H1="+pf.getImageableHeight());
                drawPage(g2);
                return Printable.PAGE_EXISTS;
        }
        
    
        public void drawPage(Graphics2D g2)
        {
			this.g2=g2;
			//System.out.println("inside draw page..."+totalamt);	
			
            context=g2.getFontRenderContext();
            f1=new Font("Times New Roman",Font.BOLD,10);
            //f1=new Font("Arial",Font.BOLD,120);
            f2=new Font("Arial",Font.PLAIN,9);
            f3=new Font("Arial",Font.PLAIN,12);
            f4=new Font("Arial",Font.BOLD,10);
            f5=new Font("Times New Roman",Font.PLAIN,15);
            f6=new Font("Times New Roman",Font.BOLD,11);
            Font f7=new Font("Times New Roman",Font.BOLD,15);
            Font f8=new Font("Times New Roman",Font.BOLD,20);
            Font f9=new Font("Times New Roman",Font.BOLD,18);
            FontMetrics fm;
            GeneralPath clipShape=new GeneralPath();

            String str=" fdfg dfg dfg";
            String str1="d fgf dgdfg df";                                        
            g2.setFont(f1);
            layout=new TextLayout(str,f1,context);
            AffineTransform transform=AffineTransform.getTranslateInstance(10,20);
			
			if(firsttime==false)
			{
				firsttime=true;
			}
			else
			{			
		        try
        		{
        			System.out.println("dhananjay.............1");
        			
        			
		        	/*FinDatab1aseFile dbfile1=new FinDatab1aseFile();
					Connection con1=dbfile1.connectDatab1ase();
					Statement st=con1.createStatement();								
					con1.close();*/
					
					System.out.println("dhananjay.............2");
					
					/*Datab1aseFile confile=new Datab1aseFile();
					Connection connection=confile.connectDatab1ase();
					Statement stobj=connection.createStatement();
					stobj.close();
					connection.close();								
					System.out.println("dhananjay.............3");*/
					
					fm=g2.getFontMetrics();				
					String temp="";
		            int top=120;
		            
		            if(currentpg==1)
		            {
		            
						System.out.println("s......");
						
					

		            g2.setFont(f8);
		            fm=g2.getFontMetrics();
		            temp=" BIRTH CERTIFICATE ";
		            layout=new TextLayout(temp,f8,context);
		            g2.drawString(temp,(510-fm.stringWidth(temp))/2,top);
		            
		            top+=2;
					g2.setFont(f6);
					g2.drawLine(80,top,450,top);
		            
		            
		            
		            top+=40;
		            g2.setFont(f7);
		            fm=g2.getFontMetrics();
		            temp="No. "+jLabel2.getText();
		            layout=new TextLayout(temp,f7,context);
		            g2.drawString(temp,20,top);
		      
		                   
		            /*g2.setFont(f7);
		            fm=g2.getFontMetrics();
		            temp=jLabel3.getText();
		            layout=new TextLayout(temp,f7,context);
		            g2.drawString(temp,300,top);*/
		            
		            g2.setFont(f7);
		            java.util.Date dt=new java.util.Date();
		            fm=g2.getFontMetrics();				
		            //temp="Date :  "+dt.getDate()+"/"+(dt.getMonth()+1)+"/"+(dt.getYear()+1900);
		            temp="Date :  "+jLabel4.getText();
		            layout=new TextLayout(temp,f7,context);
        		    g2.drawString(temp,(465-fm.stringWidth(temp)),top);
        		    
        		    top+=2;
					g2.setFont(f6);
					g2.drawLine(40,top,80,top);
					g2.drawLine(400,top,465,top);
        		    
		            top+=40;
		            
		            
		            g2.setFont(f3);
		            fm=g2.getFontMetrics();
                    temp="This is to certify that ";
		            layout=new TextLayout(temp,f7,context);
        		    g2.drawString(temp,20,top);
		            
		            
		            g2.setFont(f7);
		            fm=g2.getFontMetrics();
                    temp=jTextField1.getText();
		            layout=new TextLayout(temp,f7,context);
        		    g2.drawString(temp,170,top);
					
   				    g2.setFont(f3);
					fm=g2.getFontMetrics();
					temp="  wife of ";
					layout=new TextLayout(temp,f3,context);
				    g2.drawString(temp,(465-fm.stringWidth(temp)),top);
				    
				    top+=2;
					g2.setFont(f6);
					g2.drawLine(135,top,410,top);
					//g2.drawLine(430,top,450,top);
					
					top+=30;
								
					g2.setFont(f7);
					fm=g2.getFontMetrics();
					temp=jTextField7.getText();
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,20,top);
					
					
					
					g2.setFont(f3);
					fm=g2.getFontMetrics();
					String temp1="            "+jTextField2.getText();
					temp="residence of Vill./Mohalla ";
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,(320-fm.stringWidth(temp)),top);
					System.out.println(""+(465-fm.stringWidth(temp1)-fm.stringWidth(temp)-10));
					
					g2.setFont(f7);
					fm=g2.getFontMetrics();
					temp="     "+jTextField2.getText();
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,(465-fm.stringWidth(temp)),top);
					
					top+=2;
					g2.setFont(f6);
					g2.drawLine(20,top,170,top);
					g2.drawLine(320,top,465,top);
					
					
					top+=30;
					
					g2.setFont(f3);
					fm=g2.getFontMetrics();
					temp="P.O./Block ";
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,20,top);
					
					
									
					g2.setFont(f7);
					fm=g2.getFontMetrics();
					temp=jTextField3.getText();
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,100,top);
					
					g2.setFont(f3);
					fm=g2.getFontMetrics();
					temp="District ";
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,240,top);
					
					g2.setFont(f7);
					fm=g2.getFontMetrics();
					temp=jTextField4.getText();
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,(465-fm.stringWidth(temp)),top);
					
					top+=2;
					g2.setFont(f6);
					g2.drawLine(85,top,220,top);
					g2.drawLine(300,top,465,top);
					
					///
					top+=30;
					
					g2.setFont(f3);
					fm=g2.getFontMetrics();
					temp="given birth to ";
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,20,top);
					
					
									
					g2.setFont(f7);
					fm=g2.getFontMetrics();
					temp=jTextField5.getText();
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,100,top);
					
					g2.setFont(f3);
					fm=g2.getFontMetrics();
					temp="child.";
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,290,top);
					
					
					top+=2;
					g2.setFont(f6);
					g2.drawLine(95,top,275,top);
					//
					top+=40;
					
					g2.setFont(f4);
					fm=g2.getFontMetrics();
					temp="Hospital Registration No.";
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,20,top);
					
					
					g2.setFont(f7);
					fm=g2.getFontMetrics();
					temp=jTextField6.getText();
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,150,top);
					
					top+=2;
					g2.setFont(f6);
					g2.drawLine(145,top,300,top);
					
					//....
					top+=30;
					
					g2.setFont(f4);
					fm=g2.getFontMetrics();
					temp="Date Of Registration";
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,20,top);
					
					
					g2.setFont(f7);
					fm=g2.getFontMetrics();
					temp=jLabel11.getText();
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,150,top);
					
					top+=2;
					g2.setFont(f6);
					g2.drawLine(145,top,300,top);
					
					//...
					top+=30;
					
					g2.setFont(f4);
					fm=g2.getFontMetrics();
					temp="Date Of Issue";
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,20,top);
					
					
					g2.setFont(f7);
					fm=g2.getFontMetrics();
					temp=jLabel14.getText();
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,150,top);
					
					top+=2;
					g2.setFont(f6);
					g2.drawLine(145,top,300,top);
					
					//...
					top+=40;
					
					g2.setFont(f4);
					fm=g2.getFontMetrics();
					temp="Signature ";
					layout=new TextLayout(temp,f7,context);
					g2.drawString(temp,290,top);
					
					
					top+=2;
					g2.setFont(f6);
					g2.drawLine(350,top,490,top);
					
					}
         		}
         		catch(Exception x)
         		{
	        		System.out.println("Error2193821..."+x);
         		}
         
         	}
      	}
	}
}
