/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StaffLeaveReport.java
 *
 * Created on Feb 18, 2014, 11:30:43 AM
 */

//package idholder;
import java.rmi.*;
/**
 *
 * @author welcome
 */
public class StaffLeaveReport extends javax.swing.JInternalFrame {
static javax.swing.table.DefaultTableModel dtm;
ZedInterface inf;
    /** Creates new form StaffLeaveReport */
    public StaffLeaveReport() {
        initComponents();
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter=new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        System.out.println(6);
        String heading[]={"Sr.No.","Staff Name","Leave From Date","Leave To Date","Leave Purpose"};
        dtm=new javax.swing.table.DefaultTableModel(heading,0);
        jTable1.setModel(dtm);
        jTable1.setRowHeight(25);
        javax.swing.table.TableColumn column;
        System.out.println(1);
        column=jTable1.getColumn("Sr.No.");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(45);
        column=jTable1.getColumn("Staff Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(225);
        column=jTable1.getColumn("Leave From Date");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(100);
        System.out.println(2);
        column=jTable1.getColumn("Leave To Date");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Leave Purpose");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(340);
        loadLeave();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Staff Leave Information Report");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 810, 520);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void loadLeave()
    {
        try
        {
            try
            {
		inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
                System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
		getIPaddress.changeIP();
                try
                {
                    inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
                }
                catch(Exception ex)
                {
                    System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/ExtendZedServer  ..."+ex);
		}
            }
            String arr[][]=inf.getResultSetAs_2D_Array("select * from staff_LeaveRegister",4);
            if(arr.length>0)
            {
                String arr1[]=new String[5];
                dtm.setRowCount(0);
                for(int i=0;i<arr.length;i++)
                {
                    arr1[0]=""+(i+1);
                    String scode=arr[i][0];
                    String qry="select s_Name from staff_Details where s_Code="+Integer.parseInt(scode)+"";
                    arr1[1]=inf.getSingleValue(qry);
                    String itm[]=arr[i][1].split(" ");
                    String itm1[]=itm[0].split("-");
                    arr1[2]=itm1[2]+"-"+itm1[1]+"-"+itm1[0];

                    itm=arr[i][2].split(" ");
                    itm1=itm[0].split("-");
                    arr1[3]=itm1[2]+"-"+itm1[1]+"-"+itm1[0];
                    arr1[4]=arr[i][3];
                    /*System.out.println("arr[0][6]="+arr[0][6]);
                    String itm[]=arr[i][6].split(" ");
                    String itm1[]=itm[0].split("-");
                    String tm[]=itm[1].split(":");
                    int hour=Integer.parseInt(tm[0]);*/
                    dtm.addRow(arr1);
                }
            }
        }
        catch(Exception ae)
        {
            System.out.println("Error in load leave method "+ae);
        }
    }
}
