/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Item_Screen.java
 *
 * Created on Dec 6, 2013, 2:18:28 PM
 */

package golden_shoap;

/**
 *
 * @author user1
 */
public class Item_Screen extends javax.swing.JInternalFrame {
    /** Creates new form Item_Screen */
    javax.swing.table.DefaultTableModel dtm;
       public Item_Screen() {
        initComponents();
        //load the table in JFrame "start"
            dtm=new javax.swing.table.DefaultTableModel();
            javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
            CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
            CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
            CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            javax.swing.table.TableColumn column;
            String heading1[]={"S.No","Items Name","Item Unit"};
            dtm=new javax.swing.table.DefaultTableModel(heading1,0);
            jTable1.setModel(dtm);
            column=jTable1.getColumn("S.No");
            column.setCellRenderer(CRCenter);
            column.setPreferredWidth(8);
            
            column=jTable1.getColumn("Items Name");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(200);

            column=jTable1.getColumn("Item Unit");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(100);

            //set items in item unit combo Box
                        String qry="select * from item_unit"  ;
                        String[][] data=Utility.getInformationDD(qry,1);
                      int length= data.length;
                      for(int i=0;i<length;i++)
                      {   jComboBox1.addItem(data[i][0]);
                      }
            //end
            loadItemsInTable();
             //"End load the table"
        

       }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Manage Items");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("New Item Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 25, 130, 25);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 25, 360, 25);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/savefile.gif"))); // NOI18N
        jButton1.setMnemonic('a');
        jButton1.setText("Add");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 110, 110, 30);

        jButton2.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.gif"))); // NOI18N
        jButton2.setMnemonic('u');
        jButton2.setText("Update");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 110, 120, 30);

        jButton3.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.gif"))); // NOI18N
        jButton3.setMnemonic('d');
        jButton3.setText("Delete");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 110, 120, 30);

        jButton4.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.gif"))); // NOI18N
        jButton4.setMnemonic('c');
        jButton4.setText("Close");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(390, 110, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Existing Items");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 160, 140, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(255, 204, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 490, 320);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Item Unit");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 60, 100, 25);

        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 60, 110, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DeskTopTextureEdit11.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 520, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void loadItemsInTable()
    {   dtm.setRowCount(0);
        String qry="select * from item_master";
        String[][] data=Utility.getInformationDD(qry,2);
       int length= data.length;
       String arr[]=new String[3];
       for(int i=0;i<length;i++)
       {   arr[0]=""+(i+1);
           for(int j=0;j<2;j++)
           {   
               arr[j+1]=data[i][j];
           }
           dtm.addRow(arr);
       }
    }
    public boolean add()
    {
         double stockQuantity=0;
        double openingStock=0;
        int flag=0;
        String itemName=jTextField1.getText();
        if(itemName.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Plese enter item name." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            jTextField1.requestFocus();
        }
        else
        {
              String qry="select * from item_master";
              String[][] data=Utility.getInformationDD(qry,1);
              int length= data.length;
              for(int i=0;i<length;i++)
               {   if(data[i][0].equals(itemName))
                       {
                            flag=1;
                            break;

                       }
               }
           if(flag==0)
           {
            Utility.makeConnection();
            String qry1="insert into item_master values('"+itemName.toUpperCase()+"','"+(jComboBox1.getSelectedItem())+"','"+Master_Screen.userId+"')";
            Utility.saveInformation(qry1);
            String qry2="insert into stock_master values('"+itemName.toUpperCase()+"',"+stockQuantity+","+openingStock+")";
            Utility.saveInformation(qry2);
            loadItemsInTable();
            jTextField1.requestFocus();
            jTextField1.setText("");
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(this,"Item already exist." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                jTextField1.requestFocus();
            }
        }
        return true;
    }
    public boolean update()
    {
                        int flag=0;
                        Utility.makeConnection();
                        if(jTable1.getSelectedRow()!=(-1))
                        {
                        int selectedRow=jTable1.getSelectedRow();
                        String itemName=jTextField1.getText();
                        String selectedItemName=""+jTable1.getValueAt(selectedRow,1);
                        if(itemName.isEmpty())
                        {
                            javax.swing.JOptionPane.showMessageDialog(this,"Item name does not blank." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                            jTextField1.requestFocus();
                            jTextField1.setText(selectedItemName);

                        }
                        else
                        {            //to restrict duplicate entry start
                                     String qry1="select * from item_master";
                                     String[][] data=Utility.getInformationDD(qry1,2);
                                      int length= data.length;
                                     for(int i=0;i<length;i++)
                                      {   if(data[i][0].equals(itemName)&& data[i][1].equals(jComboBox1.getSelectedItem()))
                                          {
                                             flag=1;
                                             break;
                                           }
                                       }
                                     //End
                              if(flag==0)
                              {
                                 int check=javax.swing.JOptionPane.showConfirmDialog(this,"Are you sure to update item name ?" ,"Confirm Window",javax.swing.JOptionPane.YES_NO_OPTION,javax.swing.JOptionPane.QUESTION_MESSAGE);
                                 if(check==javax.swing.JOptionPane.YES_OPTION)
                                 {    String qry="update item_master set item_name='"+itemName.toUpperCase()+"',item_unit='"+(jComboBox1.getSelectedItem())+"' where item_name='"+selectedItemName+"'";
                                      String qry2="update stock_master set item_name='"+itemName.toUpperCase()+"' where item_name='"+selectedItemName+"'";
                                      Utility.saveInformation(qry);
                                      Utility.saveInformation(qry2);
                                      jTextField1.requestFocus();
                                      loadItemsInTable();
                                      jTextField1.setText("");
                                 }
                                 if(check==javax.swing.JOptionPane.NO_OPTION)
                                 {
                                      jTextField1.setText(selectedItemName);
                                 }
                              }
                              else
                              {
                                javax.swing.JOptionPane.showMessageDialog(this,"Item already exist." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                jTextField1.requestFocus();
                                jTextField1.setText(selectedItemName);

                              }
                        }
                     }
                 else
                    {
                         javax.swing.JOptionPane.showMessageDialog(this,"Please select item from the table. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                         jTextField1.requestFocus();
                    }
        return true;
    }
    public boolean delete()
    {
        String itemName=jTextField1.getText();
        if(itemName.equalsIgnoreCase(""))
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Plese select item name from the table." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            jTextField1.requestFocus();
        }
        else
        {
             int flag=0;
             String qry1="select * from item_master";
             String[][] data=Utility.getInformationDD(qry1,1);
             int length= data.length;
             for(int i=0;i<length;i++)
             {  if(data[i][0].equals(itemName))
                {
                   flag=1;
                   break;
                }
             }
            if(flag==1)
            {
                Utility.makeConnection();
                String qry="delete * from item_master where item_name='"+itemName+"'";
                String qry2="delete * from stock_master where item_name='"+itemName+"'";

                int check=javax.swing.JOptionPane.showConfirmDialog(this,"Are you sure you want to delete item name ?" ,"Confirm Window",javax.swing.JOptionPane.YES_NO_OPTION,javax.swing.JOptionPane.QUESTION_MESSAGE);
                if(check==javax.swing.JOptionPane.YES_OPTION)
                {
                    Utility.saveInformation(qry);
                    Utility.saveInformation(qry2);
                    loadItemsInTable();
                    jTextField1.setText("");
                    jTextField1.requestFocus();
                }
                if(check==javax.swing.JOptionPane.NO_OPTION)
                {
                    jTextField1.requestFocus();
                }
             }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(this,"Item does not exist. Please select from the table. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                jTextField1.requestFocus();
            }
        }
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        add();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        delete();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int selectedRow=jTable1.getSelectedRow();
        String itemName=""+jTable1.getValueAt(selectedRow,1);
        jTextField1.setText(itemName);
        jTextField1.requestFocus();
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            add();

        }




    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            update();

        }

    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
           delete();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
                    this.dispose();
        }


    }//GEN-LAST:event_jButton4KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton1.requestFocus();
        }

    }//GEN-LAST:event_jComboBox1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
