/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Purja_Details.java
 *
 * Created on Dec 12, 2013, 3:52:09 PM
 */

package golden_shoap;

/**
 *
 * @author user1
 */
public class Purja_Details extends javax.swing.JDialog {
javax.swing.table.DefaultTableModel dtm;
int gPurjaNumber=0;
    /** Creates new form Purja_Details */
    public Purja_Details(java.awt.Frame parent, boolean modal,int purjaNumber) {
        super(parent, modal);
        initComponents();
        gPurjaNumber=purjaNumber;
        dtm=new javax.swing.table.DefaultTableModel();

            javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
            CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
            CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
            CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            javax.swing.table.TableColumn column;
            String heading1[]={"S.No","Item Name","Polish Type","Quantity","Q_Unit","Weight","W_Unit","Rate","R_Unit","Amount"};
            dtm=new javax.swing.table.DefaultTableModel(heading1,0);
            jTable1.setModel(dtm);
            column=jTable1.getColumn("S.No");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(40);

            column=jTable1.getColumn("Item Name");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(150);

            column=jTable1.getColumn("Polish Type");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(80);

            column=jTable1.getColumn("Quantity");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(50);
            
            column=jTable1.getColumn("Q_Unit");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(70);

            column=jTable1.getColumn("Weight");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(50);
            
            column=jTable1.getColumn("W_Unit");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(50);

            column=jTable1.getColumn("Rate");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(50);

            column=jTable1.getColumn("R_Unit");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(50);

            column=jTable1.getColumn("Amount");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(80);

            loadData();
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purja Details");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBackground(new java.awt.Color(250, 250, 215));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(235, 217, 254));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 90, 20);

        jLabel2.setBackground(new java.awt.Color(235, 217, 254));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(880, 10, 60, 20);

        jLabel4.setBackground(new java.awt.Color(235, 217, 254));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(510, 10, 235, 20);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel5.setText("Total Amount (In Rs)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(680, 360, 150, 20);

        jLabel6.setBackground(new java.awt.Color(235, 217, 254));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(840, 360, 100, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel9.setText("Customer Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(410, 10, 100, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel7.setText("Receiving Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 100, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel8.setText("Purja Number ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(790, 10, 90, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(255, 204, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 930, 295);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DeskTopTextureEdit.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 960, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
   public void loadData()
 {     dtm.setRowCount(0);
       int count=0;
       String date="";
       String qry="Select rec_date from polish_details where purja_number="+gPurjaNumber+"";
       String dd=Utility.getSingleValue(qry);
       String d[]=dd.split(" ");
       String d1[]=d[0].split("-");
       date=d1[2]+"-"+d1[1]+"-"+d1[0];
       jLabel1.setText(date);
       jLabel2.setText(""+gPurjaNumber);
       qry="Select ac_code from polish_details where purja_number="+gPurjaNumber+"";
       int accountCode=Integer.parseInt(Utility.getSingleValue(qry));
                            //jLabel3.setText(cid);
       qry="Select ac_name from ac_master where ac_code="+accountCode+"";
       String cName=Utility.getSingleValue(qry);
       jLabel4.setText(cName);

       qry="Select * from polish_details where purja_number="+gPurjaNumber+"";
                            String load[][]=Utility.getInformationDD(qry, 15);
                            System.out.println(qry+" length="+load.length);
                            double total=0;
                            String totamt="";
                            int itemno=0;
                            String arr[];
                            if(load.length>0)
                            {
                                arr=new String[10];
                                    for(int i=0;i<load.length;i++)
                                    {
                                        arr[0]=""+(i+1);
                                        arr[1]=load[i][3];
                                        arr[2]=load[i][4];
                                        arr[3]=load[i][5];
                                        arr[4]=load[i][6];
                                        arr[5]=load[i][7];
                                        arr[6]=load[i][8];
                                        arr[7]=load[i][10];
                                        arr[8]=load[i][11];
                                        arr[9]=load[i][13];

                                        total=total+Double.valueOf(arr[9]);
                                        
                                  java.math.BigDecimal bd=new java.math.BigDecimal(arr[3]);
                                  arr[3]=(""+bd);//.setScale(2,5));
                                  bd=new java.math.BigDecimal(arr[5]);
                                  arr[5]=(""+bd.setScale(2,5));
                                  bd=new java.math.BigDecimal(arr[7]);
                                  arr[7]=(""+bd.setScale(2,5));
                                  bd=new java.math.BigDecimal(arr[9]);
                                  arr[9]=(""+bd.setScale(2,5));

                                        dtm.addRow(arr);
                                    }
                            }
                            java.math.BigDecimal bd=new java.math.BigDecimal(total);
                            jLabel6.setText(""+bd.setScale(2,5));

 }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
