/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KGSG_Not_Matched_With_UBI.java
 *
 * Created on Jul 2, 2013, 4:11:32 PM
 */

package atm;

/**
 *
 * @author welcome
 */
public class KGSG_Not_Matched_With_UBI extends javax.swing.JInternalFrame {
javax.swing.table.DefaultTableModel dtm;
    /** Creates new form KGSG_Not_Matched_With_UBI */
    public KGSG_Not_Matched_With_UBI() {
        initComponents();
        //jPanel1.setVisible(false);
        //jPanel2.setVisible(false);
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter=new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        String heading[]={"Sr. No","Date","Trans ID","Particular","Debit","Credit","Balance Amount"};
        dtm=new javax.swing.table.DefaultTableModel(heading,0);

        jTable1.setModel(dtm);
        jTable1.setRowHeight(25);
        javax.swing.table.TableColumn column;
        //jPanel2.setVisible(false);
//jTable1.getTableHeader().setFont(new Font("Vardana", Font.BOLD, 12));
        column=jTable1.getColumn("Sr. No");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(50);
        column=jTable1.getColumn("Trans ID");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(90);
        column=jTable1.getColumn("Date");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(90);
        column=jTable1.getColumn("Particular");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(270);
        column=jTable1.getColumn("Debit");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(97);
        column=jTable1.getColumn("Credit");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Balance Amount");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(120);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(186, 221, 221));
        setClosable(true);
        setIconifiable(true);
        setTitle("KGSG Report");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(179, 212, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 255), new java.awt.Color(204, 0, 204), new java.awt.Color(255, 102, 0))));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel1.setText("Particular");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 200, 20);

        jLabel2.setBackground(new java.awt.Color(245, 215, 245));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 320, 20);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel3.setText("Debit");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 50, 160, 20);

        jLabel4.setBackground(new java.awt.Color(245, 215, 245));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 160, 20);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel5.setText("Credit");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 50, 140, 20);

        jLabel6.setBackground(new java.awt.Color(245, 215, 245));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 70, 140, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 1, 12));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(360, 10, 470, 80);

        jButton4.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton4.setText("Done");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 100, 820, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 515, 840, 140);

        jTable1.setFont(new java.awt.Font("Verdana", 1, 12));
        jTable1.setForeground(new java.awt.Color(78, 75, 71));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(5, 60, 835, 450);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 12));
        jButton1.setForeground(new java.awt.Color(153, 51, 0));
        jButton1.setText("KGSG Not Reconcile Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 10, 280, 30);

        jButton3.setFont(new java.awt.Font("Verdana", 1, 12));
        jButton3.setForeground(new java.awt.Color(153, 51, 0));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 10, 240, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 50, 850, 2);

        jButton2.setFont(new java.awt.Font("Verdana", 1, 12));
        jButton2.setForeground(new java.awt.Color(153, 51, 0));
        jButton2.setText("KGSG Reconcile Records");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(13, 10, 290, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        class task1 extends Thread
        {
            public void run()
            {
                try
                {
                    table();
                    Thread.sleep(1000);
                    
                }
                catch(Exception ex)
                {
                     System.out.println("error..."+ex);
                }

            }
       }
       task1 t1=new task1();
       t1.start();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            class task1 extends Thread
            {
                public void run()
                {
                    try
                    {
                        table();
                        Thread.sleep(1000);
                    }
                    catch(Exception ex)
                    {
                         System.out.println("error..."+ex);
                    }

                }
           }
       task1 t1=new task1();
       t1.start();
        }
}//GEN-LAST:event_jButton1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode()==10)
       {
           jLabel2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
           jLabel4.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
           jLabel6.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
           //jPanel1.setVisible(true);
       }
       
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        autoReversalProcess();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        class task1 extends Thread {
            public void run() {
                try {
                    table1();
                    Thread.sleep(1000);
                } catch(Exception ex) {
                    System.out.println("error..."+ex);
                }

            }
        }
        task1 t1=new task1();
        t1.start();
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10) {
            class task1 extends Thread {
                public void run() {
                    try {
                        table1();
                        Thread.sleep(100);
                    } catch(Exception ex) {
                        System.out.println("error..."+ex);
                    }

                }
            }
        }
}//GEN-LAST:event_jButton2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

     private boolean table()
{
    String qry="";
        try
        {
            interfaceATM object1=null;
            try
            {
		object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
		System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                getIPaddress.changeIP();
		try
		{
			object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception ex)
		{
			System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
		}
            }
            //double total=0.0;
            java.math.BigDecimal bd=null;
            qry="Select tran_date,tran_id,particular,tran_debit_amt,tran_credit_amt,balance_amt from kgsg_n_ubi where recon_status=0 and recon_status<>"+10+" and recon_status<>"+20+" ";
            System.out.println(qry);
            String load[][]=object1.getInformationDD(qry,6);
            System.out.println(load.length);
            String arr[]=null;
            //int total=0;
            dtm.setRowCount(0);
            if(load.length>0)
            {
                //System.out.println("hello111111111111111111111111111");
                arr=new String[7];
                for(int i=0;i<load.length;i++)
                {


                    arr[0]=""+(dtm.getRowCount()+1);
                    String dt[]=load[i][0].split("-");
                    String date=dt[2]+"-"+dt[1]+"-"+dt[0];
                    arr[1]=date;
                    arr[2]=load[i][1];
                    arr[3]=load[i][2];
                    arr[4]=load[i][3];
                    arr[5]=load[i][4];
                    arr[6]=load[i][5];


                    dtm.addRow(arr);
                    System.out.println("hello   "+i);
                }

            }
            return true;
        }
        catch(Exception ae)
        {
            System.out.println("Error in Table method...."+ae);
        }
        return true;

}
    private boolean table1()
{
    String qry="";
        try
        {
            interfaceATM object1=null;
            try
            {
		object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
		System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                getIPaddress.changeIP();
		try
		{
			object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception ex)
		{
			System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
		}
            }
            //double total=0.0;
            java.math.BigDecimal bd=null;
            qry="Select tran_date,tran_id,particular,tran_debit_amt,tran_credit_amt,balance_amt from kgsg_n_ubi where recon_status="+2+"";
            System.out.println(qry);
            String load[][]=object1.getInformationDD(qry,6);
            System.out.println(load.length);
            String arr[]=null;
            //int total=0;
            dtm.setRowCount(0);
            if(load.length>0)
            {
                //System.out.println("hello111111111111111111111111111");
                arr=new String[7];
                for(int i=0;i<load.length;i++)
                {


                    arr[0]=""+(dtm.getRowCount()+1);
                    String dt[]=load[i][0].split("-");
                    arr[1]=dt[2]+"-"+dt[1]+"-"+dt[0];
                    arr[2]=load[i][1];
                    arr[3]=load[i][2];
                    arr[4]=load[i][3];
                    arr[5]=load[i][4];
                    arr[6]=load[i][5];


                    dtm.addRow(arr);
                    System.out.println("hello   "+i);
                }

            }
            return true;
        }
        catch(Exception ae)
        {
            System.out.println("Eror in Save Information111....."+ae);
        }
        return true;

}
    public void autoReversalProcess()
    {
        try
        {
            //jButton1.setEnabled(false);
            //jButton2.setEnabled(false);
            //jButton3.setEnabled(false);
            interfaceATM object1=null;
            try
            {
		object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
		System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                getIPaddress.changeIP();
		try
		{
			object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception ex)
		{
			System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
		}
            }
            String qry="select entry_no from kgsg_n_ubi where particular='"+jLabel2.getText()+"' and tran_debit_amt="+Double.valueOf(jLabel4.getText().trim())+" and tran_credit_amt="+Double.valueOf(jLabel6.getText().trim())+"";
            String sr=object1.getSingleValue(qry);
            qry="insert into kgsg_autoreversal values("+Integer.parseInt(sr)+",'"+jTextArea1.getText()+"')";
            boolean bn=object1.saveInformation(qry);
            System.out.println("inser qury process info....."+bn);
            if(bn==true)
            {
                qry="update kgsg_n_ubi set recon_status="+20+" where particular='"+jLabel2.getText()+"' and recon_status="+0+" and tran_debit_amt="+Double.valueOf(jLabel4.getText().trim())+" and tran_credit_amt="+Double.valueOf(jLabel6.getText().trim())+"";
                System.out.println(qry);
                boolean bn1=object1.saveInformation(qry);
                System.out.println("first update qury process info....."+bn1);
                qry="update kgsg_n_ubi set recon_status="+20+" where particular='"+jLabel2.getText()+"' and recon_status="+0+" and tran_debit_amt="+Double.valueOf(jLabel6.getText().trim())+" and tran_credit_amt="+Double.valueOf(jLabel4.getText().trim())+"";
                System.out.println(qry);
                boolean bn2=object1.saveInformation(qry);
                System.out.println("second update qury process info....."+bn2);
                javax.swing.JOptionPane.showMessageDialog(this,"!Congratulation\nAuto Reversal moveing process completed.");
                clr();
                table();
            }

        }
        catch(Exception ae)
        {
            System.out.println("Eror in autoReversalProcess....."+ae);
        }

    }
    public void clr()
    {
                jLabel2.setText("");
                jLabel4.setText("");
                jLabel6.setText("");
                jTextArea1.setText("");
    }

    /*public boolean search()
    {
        jButton1.setVisible(false);
        //jPanel2.setVisible(true);
        String qry="";
        try
        {
            interfaceATM object1=null;
            try
            {
		object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
		System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                getIPaddress.changeIP();
		try
		{
			object1=(interfaceATM)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception ex)
		{
			System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
		}
            }
            //double total=0.0;
            java.math.BigDecimal bd=null;
            qry="Select tran_date,tran_id,particular,tran_debit_amt,tran_credit_amt,balance_amt from kgsg_n_ubi where recon_status=0 and recon_status<>"+10+" and recon_status<>"+20+" ";
            System.out.println(qry);
            String load[][]=object1.getInformationDD(qry,6);
            System.out.println(load.length);
            String arr[]=null;
            //int total=0;
            dtm.setRowCount(0);
            if(load.length>0)
            {
                //System.out.println("hello111111111111111111111111111");
                arr=new String[7];
                for(int i=0;i<load.length;i++)
                {


                    arr[0]=""+(dtm.getRowCount()+1);
                    String dt[]=load[i][0].split("-");
                    String date=dt[2]+"-"+dt[1]+"-"+dt[0];
                    arr[1]=date;
                    arr[2]=load[i][1];
                    arr[3]=load[i][2];
                    arr[4]=load[i][3];
                    arr[5]=load[i][4];
                    arr[6]=load[i][5];
                    if(arr[3].equalsIgnoreCase(jTextField1.getText().trim()))
                    {
                        dtm.addRow(arr);

                    }


                    
                    System.out.println("hello   "+i);
                }

            }
            return true;
        }
        catch(Exception ae)
        {
            System.out.println("Error in Table method...."+ae);
        }
        return true;
    }*/
}
