/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Chhat_Ka_Cash.java
 *
 * Created on Mar 27, 2014, 5:26:12 PM
 */

package golden_shoap;

/**
 *
 * @author welcome
 */
public class Chhat_Ka_Cash extends javax.swing.JInternalFrame {
javax.swing.table.DefaultTableModel dtm1;

    /** Creates new form Chhat_Ka_Cash */
    public Chhat_Ka_Cash() {
        initComponents();

            dtm1=new javax.swing.table.DefaultTableModel();
            dtm1=new javax.swing.table.DefaultTableModel();
            javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
            CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
            CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
            CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            javax.swing.table.TableColumn column;
           String heading2[]={"S.No","Voucher Number","Amount","Jama / Nikala","Comment"};
            dtm1=new javax.swing.table.DefaultTableModel(heading2,0);
            jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
            jTable1.setModel(dtm1);
            column=jTable1.getColumn("S.No");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(40);

            column=jTable1.getColumn("Voucher Number");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(110);

            column=jTable1.getColumn("Amount");

            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(80);

            column=jTable1.getColumn("Jama / Nikala");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(100);

            

            column=jTable1.getColumn("Comment");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(150);

            setDate();
            setSerialNumber();
            tableData();

            //remaining balance
                double accountCode=5;
                String qry="select ac_cr from ac_smry where ac_code="+accountCode+"";
                double acCr=Double.valueOf(Utility.getSingleValue(qry));

                qry="select ac_Dr from ac_smry where ac_code="+accountCode+"";
                double acDr=Double.valueOf(Utility.getSingleValue(qry));

                jLabel6.setText(""+(acDr-acCr));
            //end


            
        //setVoucherNumber();
        //comboItem1();
        //comboItem2();
        //tableData();
        jComboBox1.addItem("Jama");
        jComboBox1.addItem("Nikala");

        jComboBox2.addItem("CASH POLISH");
        jComboBox2.addItem("CASH PRODUCT");
        jComboBox2.setSelectedItem("CASH POLISH");


        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Chhat Ka Transaction");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setText("Cash jama/nikala");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 120, 30);

        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(300, 90, 160, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12));
        jButton1.setMnemonic('0');
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 240, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Comment");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 170, 120, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12));
        jButton2.setMnemonic('c');
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 240, 140, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(150, 170, 310, 60);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel7.setText("Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 100, 30);

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jLabel6.setOpaque(true);
        jLabel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel6KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 130, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("Serial No");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 10, 60, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(420, 10, 40, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 10, 100, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/golden_shoap/calander.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(250, 10, 32, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel13.setText("From Account");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 50, 100, 30);

        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(150, 50, 140, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setText("Remaining Balance");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 130, 120, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 454, 310);

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(150, 90, 140, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lite_wallpaper_1600_wallpapersuggest_com-1280x960.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 610);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 470, 410);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextArea1.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jLabel6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel6KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel6KeyPressed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==10)
        {
                if(Utility.isDouble(jTextField1.getText()))
                {       dateValidation();

                }
                else
                {
                    javax.swing.JOptionPane.showMessageDialog(this,"Invalid Entry, Please try again " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    jTextField1.requestFocus();
                }
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Utility.isDouble(jTextField1.getText()))
        {       dateValidation();
                jTextField1.requestFocus();
                
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Invalid Entry, Please try again " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        calenderDate();
        tableData();

    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
             this.dispose();
        }
    }//GEN-LAST:event_jButton2KeyPressed

        // TODO add your handling code here:


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


     public void setDate()
    {
        java.util.Date dt=new java.util.Date();
        int date=dt.getDate();
        int month=dt.getMonth()+1;
        int year=dt.getYear()+1900;
        String d=""+date;
        if(d.length()==1)
        {
            d=0+d;
        }
        String setDate=d+"-"+month+"-"+year;
        jLabel8.setText(setDate);

    }
    
     public boolean save()
    {
               //int purjaNumber=0;                   // for amount validation
                              double amount=0;
                              int byAccount=0;
                              int toAccount=0;
                              amount=Double.valueOf(jTextField1.getText());

                              /*int serialNumber=0;
                              String qry="select max(voucher_number) from receive_voucher where voucher_type='Contra'";
                              String str=Utility.getSingleValue(qry);
                              int serialNo=Integer.parseInt(str);*/
                              setSerialNumber();

                              String date=jLabel8.getText();
                              String d[]=date.split("-");
                              date=d[1]+"/"+d[0]+"/"+d[2];

                              String qry="select ac_code from ac_master where ac_name='"+jComboBox2.getSelectedItem()+"'";
                              int code=Integer.parseInt(Utility.getSingleValue(qry));

                              if(jComboBox1.getSelectedItem().toString().equals("Jama"))
                              {
                                  byAccount=code;
                                  toAccount=5;
                              }
                              else
                              {
                                  byAccount=5;
                                  toAccount=code;
                              }
                             
                              System.out.println("Dateeeeeeeeeeeeeeeeeeee="+date);
                             int purjaNumber=0;
                             boolean b=true;
                             if(Double.valueOf(jTextField1.getText())>Double.valueOf(jLabel6.getText()) && (jComboBox1.getSelectedItem().equals("Nikala")) )
                             {
                                 b=false;
                             }
                             if(b==true)
                             {
                                                   qry="insert into receive_voucher values('Contra',"+Integer.parseInt(jLabel10.getText())+",'"+date+"',"+byAccount+","+toAccount+","+amount+",'"+(jTextArea1.getText())+"','"+purjaNumber+"')";
                                                  boolean bn=Utility.saveInformation(qry);
                                                  if(bn==true)
                                                  {
                                                      //to manage ac_smry table
                                                                qry="select ac_cr from ac_smry where ac_code="+byAccount+"";
                                                                double acCr=Double.valueOf(Utility.getSingleValue(qry));
                                                                acCr=(acCr+amount);
                                                                // java.math.BigDecimal bd=new java.math.BigDecimal(acDr);
                                                                // acDr=Double.valueOf((""+bd.setScale(2,5)));
                                                                qry="Update ac_smry set ac_cr="+acCr+" where ac_code="+byAccount+"";
                                                                Utility.saveInformation(qry);

                                                                qry="select ac_Dr from ac_smry where ac_code="+toAccount+"";
                                                                double acDr=Double.valueOf(Utility.getSingleValue(qry));
                                                                acDr=(acDr+amount);
                                                                qry="Update ac_smry set ac_dr="+acDr+" where ac_code="+toAccount+"";
                                                                Utility.saveInformation(qry);


                                                      jTextField1.setText("");
                                                      jTextArea1.setText("");
                                                      //setVoucherNumber();
                                                      jTextField1.requestFocus();
                                                      jComboBox1.setSelectedItem("Jama");

                                                      //remaining balance
                                                                double accountCode=5;
                                                                qry="select ac_cr from ac_smry where ac_code="+accountCode+"";
                                                                acCr=Double.valueOf(Utility.getSingleValue(qry));

                                                                qry="select ac_Dr from ac_smry where ac_code="+accountCode+"";
                                                                acDr=Double.valueOf(Utility.getSingleValue(qry));

                                                                jLabel6.setText(""+(acDr-acCr));
                                                            //end

                                                                //remaining balance
                                                                accountCode=9;
                                                                qry="select ac_cr from ac_smry where ac_code="+accountCode+"";
                                                                acCr=Double.valueOf(Utility.getSingleValue(qry));

                                                                qry="select ac_Dr from ac_smry where ac_code="+accountCode+"";
                                                                acDr=Double.valueOf(Utility.getSingleValue(qry));

                                                              
                                                            //end


                                                                tableData();


                                                       return true;

                                                  }
                                                  else
                                                  {
                                                      return false;
                                                  }
                               }
                               else
                                {
                                    javax.swing.JOptionPane.showMessageDialog(this,"Sorry Remaining balance is not sufficient" ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                    return false;
                                }

     }

      public void setSerialNumber()
    {
        try
        {
                    int serialNumber=0;
                    String qry="select max(voucher_number) from receive_voucher where voucher_type='Contra'";
                    String str=Utility.getSingleValue(qry);
                     if(str==null)
                     {   jLabel10.setText("1");
                     }
                    else
                     {
                        serialNumber=Integer.parseInt(str);
                        jLabel10.setText(""+(serialNumber+1));

                    }
        }
        catch(NullPointerException npe)
        {
            System.out.println(npe);
        }
   }

public void tableData()
{
        dtm1.setRowCount(0);
        String qry=null;
        //int toAccount=9;
        String date1=null;
        String d[]=jLabel8.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        System.out.println("Cunstructor="+date1);
        qry="Select voucher_number,voucher_amount,by_ac,voucher_comment from receive_voucher where voucher_date=#"+date1+"# and voucher_type='Contra'";
        System.out.println(qry);
        String load[][]=Utility.getInformationDD(qry,4);
        //double total=0;
        String arr[];
        if(load.length>0)
        {   arr=new String[5];
            for(int i=0;i<load.length;i++)
            {
                            arr[0]=""+(i+1);
                            arr[1]=load[i][0];
                            arr[2]=load[i][1];
                            if(load[i][2].equals("5"))
                            {
                                arr[3]="Nikala";
                            }
                            else
                            {
                                arr[3]="Jama";
                            }
                            arr[4]=load[i][3];

                           dtm1.addRow(arr);
            }
         }

    }

public void dateValidation()
    {
        String qry="select max(voucher_number)from receive_voucher where voucher_type='Contra'";
        String lastVoucherNumber=Utility.getSingleValue(qry);
        System.out.println("Voucher Number"+lastVoucherNumber);
        if(lastVoucherNumber==null)
        {
            boolean b=save();
                if(b==true)
                {
                    javax.swing.JOptionPane.showMessageDialog(this,"Transaction Successfully completed. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
        }
        else
        {   String date=jLabel8.getText();
            String d[]=date.split("-");
            date=d[1]+"-"+d[0]+"-"+d[2];
            System.out.println("date1="+date);
            qry="select voucher_number from receive_voucher where voucher_type='Contra'and voucher_number="+lastVoucherNumber+" and voucher_date<=#"+date+"#";
            String vno=Utility.getSingleValue(qry);
            System.out.println("Vno="+Utility.getSingleValue(qry));
            if(vno.length()==0)
            {
                        System.out.println("Return.... true");
                        javax.swing.JOptionPane.showMessageDialog(this,"In this back date transaction is not allowed." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else
            { System.out.println("Return.... false");
              boolean b=save();
                if(b==true)
                {
                    javax.swing.JOptionPane.showMessageDialog(this,"Transaction Successfully completed. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }


public void calenderDate()
{
     Calender c=new Calender();
    jLabel8.setText(c.getdate());

}

}
