/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * View_Polish_Transaction.java
 *
 * Created on Dec 31, 2013, 2:36:13 PM
 */

package golden_shoap;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author user1
 */
public class Profit_Loss extends javax.swing.JInternalFrame {
javax.swing.table.DefaultTableModel dtm;
    /** Creates new form View_Polish_Transaction */
    public Profit_Loss() {
        initComponents();
            java.util.Date dt=new java.util.Date();
            int date=dt.getDate();
            int month=dt.getMonth()+1;
            int yr=dt.getYear()+1900;
            String setDate=date+"-"+month+"-"+yr;
            jLabel3.setText(setDate);
            jLabel5.setText(setDate);
            
            dtm=new javax.swing.table.DefaultTableModel();
            javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
            CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
            CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
            CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            javax.swing.table.TableColumn column;
            String heading1[]={"S.No","Voucher Number","Date","Against","Jama","Nikala","Balance"};
            dtm=new javax.swing.table.DefaultTableModel(heading1,0);
            jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
            jTable1.setModel(dtm);
            column=jTable1.getColumn("S.No");
            column.setCellRenderer(CRCenter);
            column.setPreferredWidth(50);

            column=jTable1.getColumn("Voucher Number");
            column.setCellRenderer(CRCenter);
            column.setPreferredWidth(120);


            column=jTable1.getColumn("Date");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(100);


            column=jTable1.getColumn("Against");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(140);


            column=jTable1.getColumn("Jama");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(115);

            column=jTable1.getColumn("Nikala");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(115);

            column=jTable1.getColumn("Balance");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(115);


            jLabel6.setText("0.00");
            jLabel9.setText("0.00");
            jLabel1.setText("0.00");

            //To display day Opening in text box
            //displayOpening();
            //end
            jTable1.setEnabled(false);

            //jButton4.setEnabled(false);
            //hide opening of account
           // jLabel10.setVisible(false);
            //jTextField1.setVisible(false);
            //End

           // comboItem1();
            jComboBox1.addItem("POLISH");
            jComboBox1.addItem("PRODUCT");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Profit & Loss window");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(204, 0, 204));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(235, 217, 254));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 10, 100, 25);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel2.setText("Date ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 10, 40, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/golden_shoap/cal.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 10, 30, 25);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("To");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 10, 20, 25);

        jLabel5.setBackground(new java.awt.Color(235, 217, 254));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(270, 10, 100, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/golden_shoap/cal.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 10, 30, 25);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel11.setText("Account Name");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(420, 10, 110, 30);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(540, 10, 190, 30);

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(10, 10, 20, 23);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 10, 740, 50);

        jButton3.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.gif"))); // NOI18N
        jButton3.setMnemonic('d');
        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 70, 400, 30);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel10.setText("Opening Amount");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(430, 70, 110, 23);

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(550, 70, 190, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 760, 110);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(255, 204, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 760, 450);

        jLabel6.setBackground(new java.awt.Color(235, 217, 254));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 590, 110, 25);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(660, 620, 110, 30);

        jLabel1.setBackground(new java.awt.Color(235, 217, 254));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 590, 110, 25);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("=");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(640, 594, 20, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(510, 590, 20, 30);

        jLabel9.setBackground(new java.awt.Color(235, 217, 254));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(660, 590, 110, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DeskTopTextureEdit11.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -10, 810, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        Calender c=new Calender();
        jLabel3.setText(c.getdate());
        //end
}//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        Calender c=new Calender();
        jLabel5.setText(c.getdate());
      
}//GEN-LAST:event_jButton2MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        boolean b=getData();
        if(b==false)
        { javax.swing.JOptionPane.showMessageDialog(this,"Sorry !!!!!!! there is no transaction");
          jLabel9.setText(jTextField1.getText());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
  
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
                boolean b=getData();
                if(b==false)
                { javax.swing.JOptionPane.showMessageDialog(this,"Sorry !!!!!!! there is no transaction");
                  jLabel9.setText(jTextField1.getText());
                }
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.selectAll();
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            jLabel3.setEnabled(false);
        }
        else
        {
            jLabel3.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

  
    public void comboItem1()
    {
                        

                      String qry="select ac_name from ac_master where ac_group_code<>11 and ac_group_code<>12 and ac_code>10 order by ac_name";
                      String[][] data=Utility.getInformationDD(qry,1);
                      int length= data.length;
                      for(int i=0;i<length;i++)
                      {   jComboBox1.addItem(data[i][0]);
                      }
    }


 public boolean getData()
 {
        double qq=calculateOpening();
        double voucher=voucherOpening();
//      double totalWork=totalwork();
        double totalPayment=totalPayment1();
        System.out.println("totalPayment"+totalPayment);
        
        double v[]=voucherOpening1();
        System.out.println("voucherOpening1"+(v[0]-v[1]));
        
        double paymentDues=paymentDues1();
        System.out.println("paymentDues============="+paymentDues);



        double receiveDues1=receiveDues1();
        System.out.println("receiveDues1;;;;;;;============="+receiveDues1);
        jTextField1.setText(""+(qq+voucher));
        //System.out.println("ext=="+jTextField1.getText());
        dtm.setRowCount(0);
        int a=0;

        double opening=Double.valueOf(jTextField1.getText());

        String qry=null;
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];

        String accountName=""+jComboBox1.getSelectedItem();
        qry="select ac_category_code from ac_category where ac_category_name='"+accountName+"'";
        int acCategoryCode=Integer.parseInt(Utility.getSingleValue(qry));
        
        if(jCheckBox1.isSelected())
        {
            jLabel3.setEnabled(false);
            qry="Select * from receive_voucher where voucher_date<=#"+date2+"# order by voucher_date";
            System.out.println(qry);
        }
        else
        {
            qry="Select * from receive_voucher where voucher_date>=#"+date1+"# and voucher_date<=#"+date2+"# order by voucher_date";
            System.out.println(qry);
        }

        String load[][]=Utility.getInformationDD(qry,8);
        System.out.println("Length="+load.length);

        double jama=0;
        double nikala=0;
        int byAccountCode=0;
        String arr[];
        System.out.println("Hiiiiiiiiiiiiooooooooo");
        if(load.length>0)
        {
            arr=new String[7];
            boolean flag=true;
            boolean check=false;
            for(int i=0;i<load.length;i++)
            {
                    qry="select ac_code from ac_master where ac_category_code="+acCategoryCode+"";
                    String data[][]=Utility.getInformationDD(qry,1);
                    for(int j=0;j<data.length;j++)
                    {
                        if((data[j][0].equals(load[i][3]))||(data[j][0].equals(load[i][4])))
                        {
                                    byAccountCode=Integer.parseInt((data[j][0]));
                                    check=true;
                                    break;
                        }
                    }
                    if(check==true)
                    {
                            if(flag==true)
                            {
                                    if(opening>=0)
                                    {
                                        arr[4]=""+opening;
                                        dtm.addRow(arr);
                                        jama=opening;
                                        flag=false;
                                    }
                                    else
                                    {
                                        arr[5]=""+(-opening);
                                        dtm.addRow(arr);
                                        nikala=(-opening);
                                        flag=false;
                                    }
                                    i=-1;
                            }
                            else
                            {
                                    arr[4]="";
                                    arr[5]="";
                                    arr[0]=""+(i+1);
                                    arr[1]=load[i][1];
                                    String da[]=load[i][2].split(" ");
                                    String da1[]=da[0].split("-");
                                    arr[2]=da1[2]+"-"+da1[1]+"-"+da1[0];

                                    //to enter name of Against Account
                                    if((load[i][0].equals("Payment")))
                                    {       qry="select ac_name from ac_master where ac_code="+(Integer.parseInt(load[i][4]))+"";
                                            arr[3]=(Utility.getSingleValue(qry));
                                    }
                                    else
                                    {   
                                         qry="select ac_name from ac_master where ac_code="+(Integer.parseInt(load[i][3]))+"";
                                         System.out.println("========================"+Utility.getSingleValue(qry));
                                         arr[3]=""+(Utility.getSingleValue(qry));
                                    }
                                    //End
                                   if(load[i][0].equals("Payment"))
                                    {
                                                    nikala=nikala+(Double.valueOf(load[i][5]));
                                                    java.math.BigDecimal bd=new java.math.BigDecimal(load[i][5]);
                                                    arr[5]=(""+bd.setScale(2,5));
                                    }
                                    if(load[i][0].equals("Receive"))
                                    {
                                                    jama=jama+(Double.valueOf(load[i][5]));
                                                    //java.math.BigDecimal bd=new java.math.BigDecimal(jama);
                                                    //arr[4]=(""+bd.setScale(2,5));
                                                    arr[4]=""+jama;
                                   
                                    }
                                    //For balance
                                    
                                     if(arr[4].equals(""))
                                     {
                                        if(arr[5].length()<=0)
                                        {
                                            arr[5]=""+0;
                                        }
                                         opening=opening-(Double.valueOf(arr[5]));
                                         arr[6]=""+opening;
                                         
                                     }
                                     else
                                     {
                                        if(arr[4].length()<=0)
                                        {
                                            arr[4]=""+0;
                                        }
                                        opening=opening+(Double.valueOf(arr[4]));
                                         arr[6]=""+opening;
                                     }
                                    
                                   dtm.addRow(arr);
                                   
                            }
                            check=false;
                         }
                    }

        
              
            java.math.BigDecimal bd=new java.math.BigDecimal(nikala);
            jLabel6.setText(""+bd.setScale(2,5));
            bd=new java.math.BigDecimal(jama);
            jLabel1.setText(""+bd.setScale(2,5));

            jLabel9.setText(""+(jama-nikala));

            if((jama-nikala)>=0)
            {
                jLabel8.setText("Profit");
                jLabel8.setForeground(Color.BLUE);

            }
            else
            {
                jLabel8.setText("Loss");
                jLabel8.setForeground(Color.RED);

            }
           double xx=profitLoss();
           System.out.println("Profit and loss="+xx);
           return true;
         }
        else
        {
            jLabel6.setText("0.00");
            jLabel9.setText("0.00");
            jLabel1.setText("0.00");
            return false;
        }

    }
 
 public double calculateOpening()
 {
                double accountSmryOpening=0;
                String catagoryName=""+jComboBox1.getSelectedItem();
                String qry="select ac_category_code from ac_category where ac_category_name='"+catagoryName+"'";
                int acCategoryCode=Integer.parseInt(Utility.getSingleValue(qry));

                qry="select ac_code from ac_master where ac_category_code="+acCategoryCode+"";
                System.out.println(qry);
                String data[][]=Utility.getInformationDD(qry,1);
                for(int i=0;i<data.length;i++)
                {
                                    qry="Select ac_opening,opening_status from ac_smry where ac_code="+data[i][0]+"";
                                    System.out.println(qry);
                                    String data1[][]=Utility.getInformationDD(qry,2);
                                    if(data1.length>0)
                                    {
                                                    if(data1[0][1].equals("Udhaar Hai"))
                                                    {
                                                        accountSmryOpening=(accountSmryOpening+(Double.valueOf(data1[0][0])));
                                                    }
                                                    else
                                                    {
                                                         accountSmryOpening=(accountSmryOpening-(Double.valueOf(data1[0][0])));
                                                    }
                                    }
                }
                return  accountSmryOpening;
 }

 //
 public double voucherOpening()
 {
        String qry=null;
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];

        String accountName=""+jComboBox1.getSelectedItem();
        qry="select ac_category_code from ac_category where ac_category_name='"+accountName+"'";
        int acCategoryCode=Integer.parseInt(Utility.getSingleValue(qry));
        //System.out.println("By Account"+byAccountCode);

       if(jCheckBox1.isSelected()==false)
       {
            qry="Select * from receive_voucher where voucher_date<#"+date1+"# order by voucher_date";
            System.out.println(qry);
       }
        String load[][]=Utility.getInformationDD(qry,8);
        System.out.println("Length="+load.length);

        double jama=0;
        double nikala=0;
        int byAccountCode=0;
        if(load.length>0)
        {
            boolean flag=true;
            boolean check=false;
            for(int i=0;i<load.length;i++)
            {
                    qry="select ac_code from ac_master where ac_category_code="+acCategoryCode+"";
                    String data[][]=Utility.getInformationDD(qry,1);
                    for(int j=0;j<data.length;j++)
                    {
                        if((data[j][0].equals(load[i][3]))||(data[j][0].equals(load[i][4])))
                        {
                                    byAccountCode=Integer.parseInt((data[j][0]));
                                    check=true;
                                    break;
                        }
                    }
                    if(check==true)
                    {
                                    if((Double.valueOf(load[i][3])==byAccountCode))
                                    {   nikala=nikala+(Double.valueOf(load[i][5]));
                                        java.math.BigDecimal bd=new java.math.BigDecimal(load[i][5]);
                                    }
                                    else
                                    {
                                        jama=jama+(Double.valueOf(load[i][5]));
                                    }
                    }
                    check=false;
               }
     }
    return (jama-nikala);

 }
 //total amount that are taken in the date range
 public double totalReceive1()
 {
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];

        double totalAmount=0;

        String accountName=""+jComboBox1.getSelectedItem();
        String qry="select ac_category_code from ac_category where ac_category_name='"+accountName+"'";
        int acCategoryCode=Integer.parseInt(Utility.getSingleValue(qry));

        System.out.println(".......................................ok................................");

        qry="select ac_code from ac_master where ac_category_code="+acCategoryCode+"";
        String data[][]=Utility.getInformationDD(qry,1);
        for(int i=0;i<data.length;i++)
        {
                    if(acCategoryCode==1)
                    {
                        if(jCheckBox1.isSelected())
                        {
                            jLabel3.setEnabled(false);
                            qry="Select payable_amount from polish_details where rec_date<=#"+date2+"# ac_code="+Integer.parseInt(data[i][0])+" order by rec_date";
                            System.out.println(qry);
                        }
                        else
                        {
                            qry="Select payable_amount from polish_details where rec_date>=#"+date1+"# and rec_date<=#"+date2+"# and ac_code="+Integer.parseInt(data[i][0])+" order by rec_date";
                            System.out.println(qry);
                        }
                    }
                    String load[][]=Utility.getInformationDD(qry,1);
                    for(int j=0;j<load.length;j++)
                    {
                                totalAmount=totalAmount+Double.valueOf(load[j][0]);
                    }

        }
        return totalAmount;

 }
 //Total amount that are given in the date range
 public double totalPayment1()
 {
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];

        double totalAmount=0;

        String accountName=""+jComboBox1.getSelectedItem();
        String qry="select ac_category_code from ac_category where ac_category_name='"+accountName+"'";
        int acCategoryCode=Integer.parseInt(Utility.getSingleValue(qry));

        System.out.println(".......................................ok................................");

        qry="select ac_code from ac_master where ac_category_code="+acCategoryCode+"";
        String data[][]=Utility.getInformationDD(qry,1);
        for(int i=0;i<data.length;i++)
        {
                    if(acCategoryCode==1)
                    {
                        if(jCheckBox1.isSelected())
                        {
                            jLabel3.setEnabled(false);
                            qry="Select payable_amount from purchase_polish_materials where purchasing_date<=#"+date2+"# ac_code="+Integer.parseInt(data[i][0])+" order by purchasing_date";
                            System.out.println(qry);
                        }
                        else
                        {
                            qry="Select payable_amount from purchase_polish_materials where purchasing_date>=#"+date1+"# and purchasing_date<=#"+date2+"# and ac_code="+Integer.parseInt(data[i][0])+" order by purchasing_date";
                            System.out.println(qry);
                        }
                    }
                    String load[][]=Utility.getInformationDD(qry,1);
                    //System.out.println("load ..............................................."+(load.length));
                    for(int j=0;j<load.length;j++)
                    {
                                totalAmount=totalAmount+Double.valueOf(load[j][0]);
                    }

        }
        return totalAmount;

 }

//Total receive and paid amount in the date range
public double[] voucherOpening1()
 {
        String qry=null;
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];

        String accountName=""+jComboBox1.getSelectedItem();
        qry="select ac_category_code from ac_category where ac_category_name='"+accountName+"'";
        int acCategoryCode=Integer.parseInt(Utility.getSingleValue(qry));

        if(jCheckBox1.isSelected())
        {
            jLabel3.setEnabled(false);
            qry="Select * from receive_voucher where voucher_date<=#"+date2+"# and (voucher_type<>'Contra') order by voucher_date";
            System.out.println(qry);
        }
        else
        {
            qry="Select * from receive_voucher where voucher_date>=#"+date1+"# and voucher_date<=#"+date2+"# and (voucher_type<>'Contra') order by voucher_date";
            System.out.println(qry);
        }

        String load[][]=Utility.getInformationDD(qry,8);

        double jama=0;
        double nikala=0;
        int byAccountCode=0;
        String arr[];

        if(load.length>0)
        {
            arr=new String[7];
            boolean check=false;
            for(int i=0;i<load.length;i++)
            {
                    qry="select ac_code from ac_master where ac_category_code="+acCategoryCode+"";
                    String data[][]=Utility.getInformationDD(qry,1);
                    for(int j=0;j<data.length;j++)
                    {
                        if((data[j][0].equals(load[i][3]))||(data[j][0].equals(load[i][4])))
                        {
                                    byAccountCode=Integer.parseInt((data[j][0]));
                                    check=true;
                                    break;
                        }

                    }
                    if(check==true)
                    {

                                    if(load[i][0].equals("Payment"))
                                    {
                                                    nikala=nikala+(Double.valueOf(load[i][5]));
                                                    java.math.BigDecimal bd=new java.math.BigDecimal(load[i][5]);
                                                    arr[5]=(""+bd.setScale(2,5));
                                    }
                                    if(load[i][0].equals("Receive"))
                                    {
                                                    jama=jama+(Double.valueOf(load[i][5]));
                                                    java.math.BigDecimal bd=new java.math.BigDecimal(load[i][5]);
                                                    arr[4]=(""+bd.setScale(2,5));
                                    }
                    }
            }
     }
     double arr1[]=new double[2];
     arr1[0]=jama;
     arr1[1]=nikala;
     return arr1;
 }
//Current dues in the market that are given
public double paymentDues1()
{
        String qry=null;
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];
        //double arr[]=new double[2];
        String accountName=""+jComboBox1.getSelectedItem();
        qry="select ac_category_code from ac_category where ac_category_name='"+accountName+"'";
        int acCategoryCode=Integer.parseInt(Utility.getSingleValue(qry));
        //System.out.println("By Account"+byAccountCode);
        if(jCheckBox1.isSelected())
        {
            jLabel3.setEnabled(false);
            qry="Select * from receive_voucher where voucher_date<=#"+date2+"# and voucher_type='Payment' order by voucher_date";
            System.out.println(qry);
        }
        else
        {
            qry="Select * from receive_voucher where voucher_date>=#"+date1+"# and voucher_date<=#"+date2+"# and voucher_type='Payment' order by voucher_date";
            System.out.println(qry);
        }
        String load[][]=Utility.getInformationDD(qry,8);
        System.out.println("Length="+load.length);
        //double jama=0;
        double nikala=0;
        int byAccountCode=0;
        if(load.length>0)
        {
            boolean flag=true;
            boolean check=false;
            for(int i=0;i<load.length;i++)
            {
                    qry="select ac_code from ac_master where ac_category_code="+acCategoryCode+" and ac_group_code=12";
                    String data[][]=Utility.getInformationDD(qry,1);
                    for(int j=0;j<data.length;j++)
                    {
                        if((data[j][0].equals(load[i][3]))||(data[j][0].equals(load[i][4])))
                        {
                                    byAccountCode=Integer.parseInt((data[j][0]));
                                    check=true;
                                    break;
                        }
                    }
                    if(check==true)
                    {               System.out.println("byAccountCode"+byAccountCode);
                                    if((Double.valueOf(load[i][4])==byAccountCode))
                                    {   nikala=nikala+(Double.valueOf(load[i][5]));
                                        java.math.BigDecimal bd=new java.math.BigDecimal(load[i][5]);
                                    }
                    }
                    check=false;
            }
        }
        System.out.println("Nikala;;;;;;;;;"+nikala);
       double totalPayment1=totalPayment1();
       double paymentDues=(totalPayment1()-nikala);
       return paymentDues;


}
//Current Dues in the market that are taken
public double receiveDues1()
{
        double v[]=voucherOpening1();
        double receiveDues=(totalReceive1()-v[0]);
        return receiveDues;
}
//Current profit and loss
public double profitLoss()
{
        double v[]=voucherOpening1();

        System.out.println("diffPaidRceive="+v[0]);
        System.out.println("Total paid="+v[1]);
        double diffPaidRceive=(v[0]-v[1]);
        System.out.println("diffPaidRceive="+diffPaidRceive);
        double totalReceive=totalReceive1();
        System.out.println("totalReceive="+totalReceive);
        double toReceive=(totalReceive-receive());
        System.out.println("toReceive="+toReceive);
        double totalPayment=totalPayment1();
        double toPayment=(totalPayment-Paid());
        System.out.println("toPayment="+toPayment);
        double diffToPaidRceive=(toReceive-toPayment);
        System.out.println("diffToPaidRceive="+diffToPaidRceive);
        double profitLoss=(diffPaidRceive+diffToPaidRceive);
        return profitLoss;
}
public double Paid()
{

        String qry=null;
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];

        String accountName=""+jComboBox1.getSelectedItem();
        qry="select ac_category_code from ac_category where ac_category_name='"+accountName+"'";
        int acCategoryCode=Integer.parseInt(Utility.getSingleValue(qry));

        if(jCheckBox1.isSelected())
        {
            jLabel3.setEnabled(false);
            qry="Select * from receive_voucher where voucher_date<=#"+date2+"# and (voucher_type='Payment') order by voucher_date";
            System.out.println(qry);
        }
        else
        {
            qry="Select * from receive_voucher where voucher_date>=#"+date1+"# and voucher_date<=#"+date2+"# and (voucher_type='Payment') order by voucher_date";
            System.out.println(qry);
        }

        String load[][]=Utility.getInformationDD(qry,8);

        //double jama=0;
        double nikala=0;
        int byAccountCode=0;
        String arr[];

        if(load.length>0)
        {
            arr=new String[7];
            boolean check=false;
            for(int i=0;i<load.length;i++)
            {
                    qry="select ac_code from ac_master where ac_category_code="+acCategoryCode+" and ac_group_code=12";
                    String data[][]=Utility.getInformationDD(qry,1);
                    for(int j=0;j<data.length;j++)
                    {
                        if((data[j][0].equals(load[i][3]))||(data[j][0].equals(load[i][4])))
                        {
                                    byAccountCode=Integer.parseInt((data[j][0]));
                                    check=true;
                                    break;
                        }
                    }
                    if(check==true)
                    {
                                    if(load[i][0].equals("Payment"))
                                    {
                                                    nikala=nikala+(Double.valueOf(load[i][5]));
                                                    java.math.BigDecimal bd=new java.math.BigDecimal(load[i][5]);
                                                    arr[5]=(""+bd.setScale(2,5));
                                    }
                    }
            }
     }
     return nikala;

}

public double receive()
{
        double totalWork=totalReceive1();
        double v[]=voucherOpening1();
        double totalReceive=(v[0]);
        if(totalReceive>totalWork)
        {
            return totalWork;
        }
        else
        {
            return totalReceive;
        }
}




}
