/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Single_PolishUser_Report.java
 *
 * Created on Jan 3, 2014, 12:04:55 PM
 */

package golden_shoap;

/**
 *
 * @author user1
 */
public class Single_PolishUser_Report extends javax.swing.JInternalFrame {
javax.swing.table.DefaultTableModel dtm;
javax.swing.table.DefaultTableModel dtm1;
    /** Creates new form Single_PolishUser_Report */
    public Single_PolishUser_Report() {
        initComponents();
        java.util.Date dt=new java.util.Date();
            int date=dt.getDate();
            int month=dt.getMonth()+1;
            int yr=dt.getYear()+1900;
            String setDate=date+"-"+month+"-"+yr;
            jLabel3.setText(setDate);
            jLabel5.setText(setDate);
            jLabel20.setText("0.00");
            dtm=new javax.swing.table.DefaultTableModel();
            dtm1=new javax.swing.table.DefaultTableModel();
            javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
            CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
            CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
            CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            javax.swing.table.TableColumn column;
            
            String heading1[]={"S.No","Purja No","Receiving Date","No Of Items","Discount","Payable Amount"};
            dtm=new javax.swing.table.DefaultTableModel(heading1,0);
            jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
            jTable1.setModel(dtm);
            
            column=jTable1.getColumn("S.No");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(50);

            column=jTable1.getColumn("Purja No");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(60);

            column=jTable1.getColumn("Receiving Date");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(110);
             
            column=jTable1.getColumn("No Of Items");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(78);

            column=jTable1.getColumn("Discount");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(75);


            column=jTable1.getColumn("Payable Amount");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(115);
            //Second table
            String heading2[]={"S.No","Voucher Number","Receiving Date","Amount"};
            dtm1=new javax.swing.table.DefaultTableModel(heading2,0);
            jTable2.setAutoResizeMode(jTable2.AUTO_RESIZE_OFF);
            jTable2.setModel(dtm1);
            column=jTable2.getColumn("S.No");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(60);
          
            column=jTable2.getColumn("Voucher Number");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(140);

            column=jTable2.getColumn("Receiving Date");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(150);

            column=jTable2.getColumn("Amount");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(128);
            jLabel7.setText("0.00");
            combo1();
            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Polish Customer Lekha Jokha");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 70, 970, 10);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel1.setText("Customer Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 110, 25);

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(230, 20, 140, 25);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel2.setText("Date");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(400, 20, 40, 25);

        jLabel3.setBackground(new java.awt.Color(235, 217, 254));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(440, 20, 110, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/golden_shoap/cal.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(550, 20, 30, 25);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel4.setText("To");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(590, 20, 30, 25);

        jLabel5.setBackground(new java.awt.Color(235, 217, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(620, 20, 110, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/golden_shoap/cal.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(730, 20, 30, 25);

        jButton3.setFont(new java.awt.Font("Arial", 1, 14));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.gif"))); // NOI18N
        jButton3.setMnemonic('s');
        jButton3.setText("View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(770, 20, 200, 25);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel6.setText("Opening (in Rs)");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(730, 90, 110, 20);

        jLabel7.setBackground(new java.awt.Color(235, 217, 254));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(850, 90, 120, 20);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.gif"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(370, 20, 25, 25);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel19.setText("Opening (in Rs)");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(260, 90, 110, 20);

        jLabel20.setBackground(new java.awt.Color(235, 217, 254));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel20.setOpaque(true);
        jPanel2.add(jLabel20);
        jLabel20.setBounds(380, 90, 120, 20);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(130, 20, 90, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 980, 120);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(255, 204, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(3, 120, 490, 420);

        jTable2.setFont(new java.awt.Font("Arial", 0, 12));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setRowHeight(20);
        jTable2.setSelectionBackground(new java.awt.Color(255, 204, 255));
        jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(500, 120, 480, 420);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel9.setText("Total Business");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(230, 550, 150, 20);

        jLabel10.setBackground(new java.awt.Color(235, 217, 254));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 550, 110, 20);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel11.setText("Total Collection");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(760, 550, 110, 20);

        jLabel12.setBackground(new java.awt.Color(235, 217, 254));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(880, 550, 100, 20);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel13.setText("Total Difference  =");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(230, 590, 130, 20);

        jLabel14.setBackground(new java.awt.Color(235, 217, 254));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(380, 590, 110, 20);

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("-");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(500, 590, 20, 20);

        jLabel16.setBackground(new java.awt.Color(235, 217, 254));
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel16.setOpaque(true);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(530, 590, 110, 20);

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("=");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(650, 590, 20, 20);

        jLabel18.setBackground(new java.awt.Color(235, 217, 254));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel18.setOpaque(true);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(680, 590, 100, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 980, 650);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DeskTopTextureEdit.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 990, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        Calender c=new Calender();
        jLabel3.setText(c.getdate());
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        Calender c=new Calender();
        jLabel5.setText(c.getdate());
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText("0.00");
        boolean b=table1Data();
        boolean c=table2Data();
        if(b==false && c==false)
        {
                javax.swing.JOptionPane.showMessageDialog(this,"Error !!!!!!!! " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode()==10)
      {
            jLabel7.setText("");
            boolean b=table1Data();
            boolean c=table2Data();
            if(b==false && c==false)
            {
                    javax.swing.JOptionPane.showMessageDialog(this,"Error !!!!!!!! " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
      }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        combo1();
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10) {
            combo1();
        }
}//GEN-LAST:event_jButton7KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
          int row=jTable1.getSelectedRow();
        String str=""+jTable1.getValueAt(row,1);
        int purjaNumber=Integer.parseInt(str);
        System.out.println(" purjaNumber============="+ purjaNumber);

        //To call purja Details window
                        Purja_Detail ob=new  Purja_Detail(purjaNumber);
                        ob.setBounds(5,100,1020, 523);
                        Master_Screen.jDesktopPane1.add(ob);
                        ob.setVisible(true);
    }//GEN-LAST:event_jTable1MousePressed

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       //setOpening();
        if(jComboBox1.getSelectedIndex()>0)
        {
                boolean b=table1Data();
                boolean c=table2Data();
                if(b==false && c==false)
                {
                        javax.swing.JOptionPane.showMessageDialog(this,"Error !!!!!!!! " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
       String name=(jTextField1.getText()).trim();
       jComboBox1.removeAllItems();
       int accountCategory=1;
       int accountGroup=11;
       String qry="select ac_name from ac_master where ac_group_code="+accountGroup+" and ac_category_code="+accountCategory+" and ac_name like '"+jTextField1.getText()+"%' order by ac_name";
                      String[][] data=Utility.getInformationDD(qry,1);
                      int length= data.length;
                      if(length>0)
                      {
                          for(int i=0;i<length;i++)
                          {   jComboBox1.addItem(data[i][0]);
                          }
                      }
    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

public void combo1()
{
                      jComboBox1.removeAllItems();
                      int accountCategory=1;
                      int accountGroup=11;
                      String qry="select ac_name from ac_master where ac_group_code="+accountGroup+" and ac_category_code="+accountCategory+" order by ac_name";
                      String[][] data=Utility.getInformationDD(qry,1);
                      int length= data.length;
                      for(int i=0;i<length;i++)
                      {   jComboBox1.addItem(data[i][0]);
                      }
}
public boolean table1Data()
{       dtm.setRowCount(0);
        String qry=null;
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];
        String name=""+jComboBox1.getSelectedItem();
        qry="select ac_code from ac_master where ac_name='"+name+"'";
        int accountCode=Integer.parseInt(Utility.getSingleValue(qry));
         System.out.println("Code"+accountCode);

        qry="Select distinct purja_number from polish_details where rec_date>=#"+date1+"# and rec_date<=#"+date2+"# and ac_code="+accountCode+" order by purja_number desc";
        String load[]=Utility.getResultSetAs_1D_Array(qry);
        double total=0;
        String totamt="";
        int itemno=0;
        int toAccount=9;
        String arr[];
        if(load.length>0)
        {   
            arr=new String[6];
            for(int i=0;i<load.length;i++)
            {       
                            arr[0]=""+(i+1);
                            arr[1]=load[i];
                            qry="Select distinct rec_date from polish_details where ac_code="+accountCode+" and purja_number="+(Integer.parseInt(arr[1]))+"";
                            arr[2]=Utility.getSingleValue(qry);
                            String da[]=arr[2].split(" ");
                            String da1[]=da[0].split("-");
                            arr[2]=da1[2]+"-"+da1[1]+"-"+da1[0];
                            System.out.println("Date="+arr[2]);
                            qry="select discount,payable_amount from polish_details where purja_number="+Integer.parseInt(arr[1])+"";
                            String la[][]=Utility.getInformationDD(qry,2);
                           /* double amt=0;
                            if(la.length>0)
                            {
                                for(int k=0;k<la.length;k++)
                                {
                                    amt=Double.valueOf(la[k])+amt;
                                }
                            }*/
                            arr[3]=""+la.length;
                            java.math.BigDecimal bd=new java.math.BigDecimal(la[0][0]);
                            arr[4]=""+bd.setScale(2,5);
                            bd=new java.math.BigDecimal(la[0][1]);
                            arr[5]=""+bd.setScale(2,5);

                            total=total+(Double.valueOf(arr[5]));

                            dtm.addRow(arr);

            }
         }
        
                        /*qry="Select payable_amount from polish_details where ac_code="+accountCode+" ";
                        String vAmount[]=Utility.getResultSetAs_1D_Array(qry);
                        double allTotal=0;
                            for(int i=0;i<vAmount.length;i++)
                            {
                                            allTotal=allTotal+(Double.valueOf(vAmount[i]));
                            }
                        System.out.println("allTotal amount ="+allTotal);*/
                       //to manage opening
                        qry="Select payable_amount from polish_details where ac_code="+accountCode+" and rec_date<#"+date1+"#";
                        String data[][]=Utility.getInformationDD(qry,1);
                        double opening=0;
                        if(data.length!=0)
                        {
                                    for(int i=0;i<data.length;i++)
                                    {
                                        opening=opening+(Double.valueOf(data[i][0]));
                                    }
                        }
                        java.math.BigDecimal bd=new java.math.BigDecimal(opening);
                         jLabel20.setText(""+bd.setScale(2,5));
                        //end
        bd=new java.math.BigDecimal(total);
        jLabel10.setText(""+bd.setScale(2,5));
        bd=new java.math.BigDecimal(total+Double.valueOf(jLabel20.getText()));
        jLabel14.setText(""+bd.setScale(2,5));
        //bd=new java.math.BigDecimal(allTotal-total);
       // jLabel20.setText(""+bd.setScale(2,5));
        return true;
    }
public boolean table2Data()
{
        dtm1.setRowCount(0);
        String qry=null;
        int toAccount=9;
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];
        String name=""+jComboBox1.getSelectedItem();
        qry="select ac_code from ac_master where ac_name='"+name+"'";
        int accountCode=Integer.parseInt(Utility.getSingleValue(qry));
        System.out.println("By Code"+accountCode);

        qry="Select voucher_number,voucher_date,voucher_amount from receive_voucher where voucher_date>=#"+date1+"# and voucher_date<=#"+date2+"# and by_ac="+accountCode+" and to_ac="+toAccount+" order by voucher_date desc";
        String load[][]=Utility.getInformationDD(qry,3);
        double total=0;
        String arr[];
        if(load.length>0)
        {
            arr=new String[4];
            for(int i=0;i<load.length;i++)
            {
                            arr[0]=""+(i+1);
                            arr[1]=load[i][0];
                            arr[2]=load[i][1];
                            String da[]=arr[2].split(" ");
                            String da1[]=da[0].split("-");
                            arr[2]=da1[2]+"-"+da1[1]+"-"+da1[0];
                            java.math.BigDecimal bd=new java.math.BigDecimal(load[i][2]);
                            arr[3]=""+bd.setScale(2,5);
                            total=total+(Double.valueOf(arr[3]));
                            dtm1.addRow(arr);
            }
            
                        

           
        }
        /*else
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Sorry !!!!!!!! There are no transaction between these date." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);

        }*/
       /* qry="Select voucher_amount from receive_voucher where voucher_date<=#"+date2+"# and by_ac="+accountCode+" and voucher_type='Receive'";

             String vAmount[]=Utility.getResultSetAs_1D_Array(qry);
             double allTotal=0;
             if(vAmount.length>0)
             {
                         for(int i=0;i<vAmount.length;i++)
                         {
                                    allTotal = allTotal + (Double.valueOf(vAmount[i]));

                         }
                         System.out.println(jLabel7.getText()+"  allTotal amount ="+allTotal);
            }*/
             //to manage opening
                        //qry="Select voucher_amount from receive_voucher where by_ac="+accountCode+" and voucher_date<#"+date1+"# and voucher_type='Receive'";
                        qry="Select voucher_amount from receive_voucher where voucher_date<#"+date1+"# and by_ac="+accountCode+" and voucher_type='Receive'";
                        String data[][]=Utility.getInformationDD(qry,1);
                        double opening=0;
                        if(data.length!=0)
                        {
                                    for(int i=0;i<data.length;i++)
                                    {
                                        opening=opening+(Double.valueOf(data[i][0]));
                                    }
                        }
                         java.math.BigDecimal bd=new java.math.BigDecimal(opening);
                         jLabel7.setText(""+bd.setScale(2,5));
               //End

            bd=new java.math.BigDecimal(total);
            jLabel12.setText(""+bd.setScale(2,5));
            bd=new java.math.BigDecimal(total+Double.valueOf(jLabel7.getText()));
            jLabel16.setText(""+bd.setScale(2,5));
            bd=new java.math.BigDecimal((Double.valueOf(jLabel14.getText())-Double.valueOf(jLabel16.getText())));
            jLabel18.setText(""+bd.setScale(2,5));

            

        return true;
}
    public void comboCustomerName()
    {                 int accountCategory=1;
                      int accountGroup=11;
                      String qry="select ac_name from ac_master where ac_group_code="+accountGroup+" and ac_category_code="+accountCategory+"";
                      String[][] data=Utility.getInformationDD(qry,1);
                      int length= data.length;
                      for(int i=0;i<length;i++)
                      {   jComboBox1.addItem(data[i][0]);
                      }

    }

}
