/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Police_customer_work.java
 *
 * Created on Dec 12, 2013, 10:25:21 AM
 */

package golden_shoap;
import java.math.RoundingMode;
import java.sql.*;
import javax.swing.table.AbstractTableModel;
/**
 *
 * @author user1
 */
public class Receive_Polish_work extends javax.swing.JInternalFrame {
 javax.swing.table.DefaultTableModel dtm;
 int gPurjaNumber=0;
// static int sNo=0;
    /** Creates new form Police_customer_work */
    public Receive_Polish_work(int purjaNumber1) {
        initComponents();
            gPurjaNumber=purjaNumber1;
            dtm=new javax.swing.table.DefaultTableModel();
            javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
            CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
            CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
            CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            javax.swing.table.TableColumn column;
            String heading1[]={"S.No","Payment Apply","Item Name","Polih Type","Quantity","Unit","Weight Bef/polish","Unit","Weight Af/Polish","Rate","Unit","Amount"};
            dtm=new javax.swing.table.DefaultTableModel(heading1,0);
            jTable1.setModel(dtm);
            column=jTable1.getColumn("S.No");
            column.setCellRenderer(CRCenter);
            column.setPreferredWidth(35);

            column=jTable1.getColumn("Payment Apply");
            column.setCellRenderer(CRCenter);
            column.setPreferredWidth(90);

            column=jTable1.getColumn("Item Name");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(170);

            column=jTable1.getColumn("Polih Type");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(90);

            column=jTable1.getColumn("Quantity");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(60);

            column=jTable1.getColumn("Unit");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(80);

            column=jTable1.getColumn("Weight Bef/polish");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(80);

            column=jTable1.getColumn("Unit");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(50);

            column=jTable1.getColumn("Weight Af/Polish");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(80);

            column=jTable1.getColumn("Rate");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(60);

            column=jTable1.getColumn("Unit");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(80);

            column=jTable1.getColumn("Amount");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(95);
            //for zerox of payable amount
            jLabel22.setVisible(false);
            //End
            jLabel11.setText(""+purjaNumber1);
            String qry="Select rec_date,ac_code from polish_details where purja_number="+purjaNumber1+"";
            //to set date
            String data[][]=Utility.getInformationDD(qry,2);
            String d[]=(data[0][0]).split(" ");
            String d1[]=d[0].split("-");
            jLabel10.setText((d1[2]+"-"+d1[1]+"-"+d1[0]));
            //End
            qry="select ac_name from ac_master where ac_code="+(Integer.parseInt(data[0][1]))+"";
            String name=Utility.getSingleValue(qry);
            jLabel4.setText(name);
            jTextField7.setText("0");
            //load data on the table
            loadData(purjaNumber1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setClosable(true);
        setIconifiable(true);
        setTitle("Receive Polish Work");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("Receiving Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 20, 90, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Purja Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(840, 20, 90, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Select Customer's A/C");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 20, 130, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 990, 240);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel21.setText("Total Amount( in Rs)");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(760, 330, 140, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/receive2.png"))); // NOI18N
        jButton3.setMnemonic('f');
        jButton3.setText("Deliver & Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 350, 200, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/receive2.png"))); // NOI18N
        jButton4.setMnemonic('r');
        jButton4.setText("Deliver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(220, 350, 140, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.gif"))); // NOI18N
        jButton6.setMnemonic('c');
        jButton6.setText("Cloce");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(520, 350, 140, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 460, 980, 10);

        jLabel10.setBackground(new java.awt.Color(102, 255, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("jLabel10");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(550, 20, 90, 23);

        jLabel11.setBackground(new java.awt.Color(102, 255, 102));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("jLabel11");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(930, 20, 70, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jLabel12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel12KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(640, 20, 30, 23);

        jTextField4.setFont(new java.awt.Font("Arial", 1, 12));
        jTextField4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        jTextField4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jTextField4.setOpaque(true);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(900, 330, 100, 20);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PRINT.GIF"))); // NOI18N
        jButton5.setMnemonic('p');
        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 350, 140, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 60, 1020, 10);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel16.setText("Discount ( in Rs)");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(760, 390, 110, 20);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel17.setText("Paid Amount (in Rs)");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(760, 470, 120, 20);

        jTextField5.setFont(new java.awt.Font("Arial", 1, 12));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 255))); // NOI18N
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField5MousePressed(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(900, 390, 100, 23);

        jTextField6.setBackground(new java.awt.Color(236, 233, 216));
        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Arial", 1, 12));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField6MousePressed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(900, 420, 100, 23);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel18.setText("Payable Amount");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(760, 420, 130, 20);

        jTextField7.setFont(new java.awt.Font("Arial", 1, 12));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 255))); // NOI18N
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField7MousePressed(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(900, 470, 100, 20);

        jLabel20.setText("Rounding value  ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(760, 360, 100, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(900, 360, 100, 20);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(780, 460, 40, 0);
        getContentPane().add(jLabel23);
        jLabel23.setBounds(780, 480, 0, 0);

        jLabel4.setBackground(new java.awt.Color(102, 255, 102));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 20, 210, 23);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel6.setText("Old Paid  Amount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 474, 130, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(600, 474, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
     public void check()
    {   int rowCount=jTable1.getRowCount();
        int row= jTable1.getSelectedRow();
           if(row>=0 && row<=rowCount)
           {          
                                    String cc=""+jTable1.getValueAt(row,8);
                                    boolean bn=Utility.isDouble(cc);
                                    if(bn==true)
                                    {   if(Double.valueOf(cc)==0)
                                            {
                                            jTable1.setValueAt("",row,8);
                                            }
                                    }
                                    jTable1.editCellAt(row,8);
                       
           }
    }
    public void loadData(int purjaNumber)
    {
       dtm.setRowCount(0);
       int count=0;
       String qry="Select * from polish_details where purja_number="+purjaNumber+"";
                            String load[][]=Utility.getInformationDD(qry, 15);
                            System.out.println(qry+" length="+load.length);
                            double total=0;
                            String totamt="";
                            int itemno=0;
                            String arr[];
                            if(load.length>0)
                            {
                                arr=new String[12];
                                    for(int i=0;i<load.length;i++)
                                    {
                                        arr[0]=""+(i+1);
                                        arr[1]=load[i][12];
                                        arr[2]=load[i][3];
                                        arr[3]=load[i][4];
                                        arr[4]=load[i][5];
                                        arr[5]=load[i][6];
                                        arr[6]=load[i][7];
                                        arr[7]=load[i][8];
                                        arr[8]=load[i][9];
                                        arr[9]=load[i][10];
                                        System.out.println("Value="+load[i][10]);
                                        arr[10]=load[i][11];
                                        System.out.println("Value="+load[i][11]);
                                       
                                        arr[11]=load[i][13];

                                        total=total+Double.valueOf(arr[11]);
                                          
                                      java.math.BigDecimal bd=new java.math.BigDecimal(arr[6]);
                                      arr[6]=(""+bd.setScale(2,5));
                                      bd=new java.math.BigDecimal(arr[8]);
                                      arr[8]=(""+bd.setScale(2,5));
                                      bd=new java.math.BigDecimal(arr[9]);
                                      arr[9]=(""+bd.setScale(2,5));
                                      bd=new java.math.BigDecimal(arr[11]);
                                      arr[11]=(""+bd.setScale(2,5));
                                       
                                      dtm.addRow(arr);
                                    }
                            }
                                                             int count1=dtm.getRowCount();
                                                             double oldAmount=0;
                                                             double newAmount=0;
                                                             double discount=0;
                                                             for(int i=0;i<count1;i++)
                                                             {
                                                                oldAmount=Double.valueOf(""+dtm.getValueAt(i,11));
                                                                newAmount= newAmount+oldAmount;
                                                             } 
                                                              java.math.BigDecimal bd4=new java.math.BigDecimal(newAmount);
                                                              jTextField4.setText(""+bd4.setScale(2,5));
                                                              double payableAmount=Double.valueOf(""+bd4.setScale(0,java.math.BigDecimal.ROUND_HALF_UP));
                                                              if(jTextField5.getText().isEmpty()==false)
                                                              {
                                                                  if(Utility.isDouble(jTextField5.getText()))
                                                                  {
                                                                    discount=Double.valueOf(jTextField5.getText());
                                                                  }
                                                              }
                                                              payableAmount=payableAmount-discount;
                                                              bd4=new java.math.BigDecimal(payableAmount);
                                                              jTextField6.setText(""+bd4.setScale(2,5));
                                                             
                                                              discount();
                                                              //label22 visibility false
                                                              jLabel22.setText(""+bd4.setScale(2,5));
                                                              double rounding=((Double.valueOf(jTextField4.getText()))-(Double.valueOf(jTextField6.getText())));
                                                              bd4=new java.math.BigDecimal(rounding);
                                                              jLabel9.setText(""+bd4.setScale(2,5));
                                                              paidAmount();
                          

 }
    public void payableAmount()
    {
                            String qry="Select payable_amount from polish_details where purja_number="+gPurjaNumber+"";
                            double payableAmount=Double.valueOf(Utility.getSingleValue(qry));
                            java.math.BigDecimal bd4=new java.math.BigDecimal(payableAmount);
                            jTextField6.setText(""+bd4.setScale(2,5));
    }
   public void edetingTotal()
    {
         int count1=dtm.getRowCount();
         double oldAmount=0;
         double newAmount=0;
         double discount=0;
         for(int i=0;i<count1;i++)
         {
            oldAmount=Double.valueOf(""+dtm.getValueAt(i,11));
            newAmount= newAmount+oldAmount;
         }
          java.math.BigDecimal bd4=new java.math.BigDecimal(newAmount);
          jTextField4.setText(""+bd4.setScale(2,5));
          double payableAmount=Double.valueOf(""+bd4.setScale(0,java.math.BigDecimal.ROUND_HALF_UP));
          //System.out.println("P="+payableAmount);
           if(jTextField5.getText().isEmpty()==false)
           {
                 if(Utility.isDouble(jTextField5.getText()))
                  {
                        discount=Double.valueOf(jTextField5.getText());
                   }
            }
          // System.out.println("D="+discount);
          bd4=new java.math.BigDecimal((payableAmount-discount));
          jTextField6.setText(""+bd4.setScale(2,5));
          //label22 visibility false
          jLabel22.setText(""+payableAmount);
          //end
          double rounding=(payableAmount-(Double.valueOf(jTextField4.getText())));
          bd4=new java.math.BigDecimal(rounding);
          jLabel9.setText(""+bd4.setScale(2,5));
   }

     public void calenderDate()
    {   Calender c=new Calender();
        jLabel10.setText(c.getdate());
    }
     public void calculateTotal()
    {
       try
        {       int row=jTable1.getSelectedRow();
                String amount1="";
                String weight="";
                String paymentApply="";
                double rate=0;
                int totalRow=jTable1.getRowCount();
                //for weight
                        if((row==0))
                        {    weight=""+jTable1.getValueAt(totalRow-1,8);
                             rate=Double.valueOf(""+jTable1.getValueAt(totalRow-1,9));
                             paymentApply=""+jTable1.getValueAt(totalRow-1,1);
                        }
                        else
                        {   weight=""+jTable1.getValueAt(row-1,8);
                            rate=Double.valueOf(""+jTable1.getValueAt(row-1,9));
                            paymentApply=""+jTable1.getValueAt(row-1,1);
                         }
                if(paymentApply.equals("After Polish"))
                {
                    double amount=(rate*(Double.valueOf(weight)));
                    java.math.BigDecimal bd=new java.math.BigDecimal(amount);
                    amount1=""+(bd.setScale(2,5));
                   //for amount
                     if((row==0))
                        {   jTable1.setValueAt(amount1, totalRow-1, 11);}
                     else
                        {jTable1.setValueAt(amount, row-1, 11);}
                }
       }
        catch(Exception ex)
       {
         System.out.println(ex)   ;
       }
    }
   public void errorMsg()
    {
        javax.swing.JOptionPane.showMessageDialog(this,"Error..... Enter valid weight." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
   public void discount()
   {                        String qry="Select discount from polish_details where purja_number="+gPurjaNumber+"";
                            double discount=Double.valueOf(Utility.getSingleValue(qry));
                            java.math.BigDecimal bd4=new java.math.BigDecimal(discount);
                            jTextField5.setText(""+bd4.setScale(2,5));
                            jLabel23.setText(""+discount);
    }
   public void paidAmount()
  {                         String qry="Select voucher_amount from receive_voucher where purja_number="+gPurjaNumber+"";
                            String data=Utility.getSingleValue(qry);
                            if(data.isEmpty()|| data==null)
                            {jLabel7.setText("0");}
                            else
                            {      java.math.BigDecimal bd4=new java.math.BigDecimal(data);
                                   jLabel7.setText(""+bd4.setScale(2,5));
                            }
   }
   public boolean  ReceivePaidAmount()
   {   if(Utility.isDouble(jTextField7.getText())==true)
       {
       if((Double.valueOf(jTextField7.getText())>0) || (Double.valueOf(jLabel7.getText())>0))
        {
                      double totalPaidAmount=((Double.valueOf(""+jTextField7.getText())+(Double.valueOf(jLabel7.getText()))));
                      String byAccount=""+jLabel4.getText();
                      String qry="select ac_code from ac_master where ac_name='"+byAccount+"'";
                      int byAccountCode=Integer.parseInt(Utility.getSingleValue(qry));
                      int toAccountCode=9;
                      // update old paid amount and new paid amount in receive voucher table
                      if((Double.valueOf(jLabel7.getText()))>0 && (Double.valueOf(jTextField7.getText()))>0)
                      {
                       qry="Update receive_voucher set voucher_amount="+totalPaidAmount+" where purja_number="+gPurjaNumber+"";
                       System.out.println(qry);
                       boolean b=Utility.saveInformation(qry);
                       if(b==true)
                       {
                            accountPaidAmount();
                       }
                       //for Account updtion
                      }
                      if((Double.valueOf(jLabel7.getText()))==0 && (Double.valueOf(jTextField7.getText()))>0)
                      {       int voucherNumber=setVoucherNumber();
                              String date=""+jLabel10.getText();
                              qry="insert into receive_voucher values('receive',"+voucherNumber+",'"+date+"',"+byAccountCode+","+toAccountCode+","+totalPaidAmount+",' ',"+gPurjaNumber+")";
                              boolean bn=Utility.saveInformation(qry);
                              if(bn==true)
                               {
                                    accountPaidAmount();
                               }
                      }
              
         }

       }
       else
       {
            return false;
       }
         return true;
   }
   public boolean accountPaidAmount()
  {
           if(jTextField7.getText().isEmpty()==false)
           {
                 if(Utility.isDouble(jTextField7.getText()))
                  {
                        String byAccount=""+jLabel4.getText();
                        String qry="select ac_code from ac_master where ac_name='"+byAccount+"'";
                        int byAccountCode=Integer.parseInt(Utility.getSingleValue(qry));
                        int toAccountCode=9;
                        qry="select ac_cr from ac_smry where ac_code="+byAccountCode+"";
                        double acCr=Double.valueOf(Utility.getSingleValue(qry));
                        acCr=(acCr+(Double.valueOf(""+jTextField7.getText())));
                        qry="Update ac_smry set ac_cr="+acCr+" where ac_code="+byAccountCode+"";
                        Utility.saveInformation(qry);
                        //update cash account dr with new new paid amount
                        qry="select ac_Dr from ac_smry where ac_code="+toAccountCode+"";
                        double acDr=Double.valueOf(Utility.getSingleValue(qry));
                        acDr=(acDr+(Double.valueOf(""+jTextField7.getText())));
                        qry="Update ac_smry set ac_dr="+acDr+" where ac_code="+toAccountCode+"";
                        Utility.saveInformation(qry);
                    }
            }
           return true;
   }
    public int setVoucherNumber()
    {   int voucherNumber=0;
        try
        {           String qry="select max(voucher_number) from receive_voucher";
                    String str=Utility.getSingleValue(qry);
                     if(str==null)
                     { voucherNumber=1;}
                    else
                     {voucherNumber=(Integer.parseInt(str)+1);}
        }
        catch(NullPointerException npe)
        { System.out.println(npe);
        }
        return voucherNumber;
   }
    public boolean manageAccountDiscount()
    {      if(jTextField5.getText().isEmpty()==false)
           {
                 if(Utility.isDouble(jTextField5.getText()))
                  {

                            int acCode=8;
                            String qry="select discount from polish_details where purja_number="+gPurjaNumber+"";
                            double oldDiscount=Double.valueOf(Utility.getSingleValue(qry));
                            System.out.println("trueeeeeeeeeeeeeeee");
                            qry="select ac_dr from ac_smry where ac_code="+acCode+"";
                            double acDr=Double.valueOf(Utility.getSingleValue(qry));
                            acDr=(acDr-oldDiscount);
                            acDr=acDr+(Double.valueOf(jTextField5.getText()));
                            qry="Update ac_smry set ac_dr="+acDr+" where ac_code="+acCode+"";
                            boolean b=Utility.saveInformation(qry);
                            if(b==false)
                            {
                                    return false;
                            }
                  }
           }
           return true;
    }

   public boolean Update()
   {
              String date=jLabel10.getText();
              int purjaNumber=Integer.parseInt(jLabel11.getText());
              String accountName=""+jLabel4.getText();
              String qry="select ac_code from ac_master where ac_name='"+accountName+"'";
              int accountCode=Integer.parseInt(Utility.getSingleValue(qry));

              //manage Account CR and Dr
                            String acName=""+jLabel4.getText();
                            double newDiscount=0;
                            qry="select ac_dr from ac_smry where ac_code="+accountCode+"";
                            double acDr=Double.valueOf(Utility.getSingleValue(qry));
                            //formula for update (acDr+(newPayableAmount-oldPayableAmount))
                            qry="select payable_amount from polish_details where purja_number="+gPurjaNumber+"";
                            double oldPayableAmount=Double.valueOf(Utility.getSingleValue(qry));
                            double newPayableAmount=Double.valueOf(jTextField6.getText());
                            //System.out.println("npa=="+newPayableAmount);
                            acDr=((acDr-oldPayableAmount)+(newPayableAmount));
                            //System.out.println("acdr==="+acDr);
                            qry="Update ac_smry set ac_dr="+acDr+" where ac_code="+accountCode+"";
                            boolean b=Utility.saveInformation(qry);
                            if(b==false)
                            {
                                return false;
                            }
                            qry="select discount from polish_details where purja_number="+gPurjaNumber+"";
                            double oldDiscount=Double.valueOf(Utility.getSingleValue(qry));
                            //System.out.println("Od=="+oldDiscount);
                            if(jTextField7.getText().isEmpty()==false)
                            {
                                 if(Utility.isDouble(jTextField7.getText()))
                                 {
                                      newDiscount=Double.valueOf(jTextField5.getText());
                                 }
                            }
                            System.out.println("Nd=="+newDiscount);
                            qry="select ac_cr from ac_smry where ac_code="+10+"";
                            double acCr=Double.valueOf(Utility.getSingleValue(qry));
                            acCr=(acCr-(oldPayableAmount+oldDiscount))+((newPayableAmount+newDiscount));
                            System.out.println("acCr==="+acCr);

                            qry="Update ac_smry set ac_cr="+acCr+" where ac_code="+10+"";
                            b=Utility.saveInformation(qry);
                            if(b==false)
                            {
                                return false;
                            }
              //End
              int status=2;
              String itemName="";
              String polishType="";
              double quantity=0;
              String quantityUnit="";
              double weight=0;
              String weightUnit="";
              double rate=0;
              String rateUnit="";
              int row=dtm.getRowCount();
              double amount=0;
              double weightAfterPolish=0;
              String paymentApply="";
              boolean bn=false;
              for(int i=0;i<row;i++)
              {
                      itemName=""+dtm.getValueAt(i,2);
                      polishType=""+dtm.getValueAt(i,3);
                      quantity=Double.valueOf(""+dtm.getValueAt(i,4));
                      quantityUnit=(""+dtm.getValueAt(i,5));
                      weight=Double.valueOf(""+dtm.getValueAt(i,6));
                      weightUnit=(""+dtm.getValueAt(i,7));
                      weightAfterPolish=Double.valueOf(""+dtm.getValueAt(i,8));
                      rate=Double.valueOf(""+dtm.getValueAt(i,9));
                      rateUnit=(""+dtm.getValueAt(i,10));
                     
                      paymentApply=(""+dtm.getValueAt(i,1));
                      amount=Double.valueOf(""+dtm.getValueAt(i,11));

                      //Delete old Existing record of same purja number
                     qry="delete * from polish_details where purja_number="+gPurjaNumber+"";
                     bn=Utility.saveInformation(qry);
                     if(bn==false)
                     {
                         return false;
                     }
                      //Insert new record with update
                      qry="insert into polish_details values(#"+date+"#,"+purjaNumber+","+accountCode+",'"+itemName+"','"+polishType+"',"+quantity+",'"+quantityUnit+"',"+weight+",'"+weightUnit+"',"+weightAfterPolish+","+rate+",'"+rateUnit+"','"+paymentApply+"',"+amount+","+status+","+(Double.valueOf(jTextField5.getText()))+","+(Double.valueOf(jTextField6.getText()))+")";
                      bn=Utility.saveInformation(qry);
                      if(bn==false)
                      {
                          return false;
                      }
               }
                      //Delete old record and add new record with after weight
        return true;
 }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        check();
        calculateTotal();
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        int keyCode=evt.getKeyCode();
        if(keyCode>=65 && keyCode<=90 || keyCode>=97 && keyCode<=122)
        {
            errorMsg();
       }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if((jTextField7.getText()).isEmpty() == false && (jTextField5.getText()).isEmpty() == false)
        {
                 if((Double.valueOf(jTextField5.getText()))>(Double.valueOf(jTextField6.getText())))
                 {
                                javax.swing.JOptionPane.showMessageDialog(this,"Discount is greater than payable amount." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                jTextField5.requestFocus();
                 }
                 else if(Utility.isDouble((jTextField5.getText())) == true)
                 {
                        if(Utility.isDouble((jTextField7.getText()))==true)
                        {

                                       if(ReceivePaidAmount()==true && manageAccountDiscount() && Update()==true)
                                       { javax.swing.JOptionPane.showMessageDialog(this,"Record sucessfully save. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                       }
                        }
                        else
                        {javax.swing.JOptionPane.showMessageDialog(this,"Error..... Invalid paid amount.","Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                         jTextField7.requestFocus();
                        }
                  
                }
                else
                {javax.swing.JOptionPane.showMessageDialog(this,"Error..... Invalid discount.","Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                 jTextField5.requestFocus();
                }
            
        }
        else
        {javax.swing.JOptionPane.showMessageDialog(this,"Error..... paid amount and discount does not empty. Minimum  '0' is required.","Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
         jTextField7.requestFocus();
        }

        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String str=javax.swing.JOptionPane.showInputDialog(this, "Please enter Purja no.","Print Purja",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        boolean flag=false;
        if(str!=null || (str.isEmpty()==false))
        {   if(Utility.isInteger(str))
            {
                int purja=Integer.parseInt(str);
                String qry="select distinct purja_number from polish_details";
                String data[][]=Utility.getInformationDD(qry,1);
                for(int i=0;i<data.length;i++)
                {
                    int purjaNumber=Integer.parseInt(data[i][0]);
                    if(purjaNumber==purja)
                    {       flag=true;
                    }

                }
            }
        }
        if(flag==true)
        {
                        printchallan2 pt=new printchallan2(str);
        }
        else
        {
             javax.swing.JOptionPane.showMessageDialog(this,"Error... Please enter vlaid purja number . " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
         if((jTextField7.getText()).isEmpty() == false && (jTextField5.getText()).isEmpty() == false)
        {
                 if((Double.valueOf(jTextField5.getText()))>(Double.valueOf(jTextField6.getText())))
                 {
                                javax.swing.JOptionPane.showMessageDialog(this,"Discount is greater than payable amount." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                jTextField5.requestFocus();
                 }
                 else if(Utility.isDouble((jTextField5.getText())) == true)
                 {
                        if(Utility.isDouble((jTextField7.getText()))==true)
                        {

                                       if(ReceivePaidAmount()==true && manageAccountDiscount() && Update()==true)
                                       { javax.swing.JOptionPane.showMessageDialog(this,"Record sucessfully save. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                       }
                        }
                        else
                        {javax.swing.JOptionPane.showMessageDialog(this,"Error..... Invalid paid amount.","Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                         jTextField7.requestFocus();
                        }

                }
                else
                {javax.swing.JOptionPane.showMessageDialog(this,"Error..... Invalid discount.","Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                 jTextField5.requestFocus();
                }

        }
        else
        {javax.swing.JOptionPane.showMessageDialog(this,"Error..... paid amount and discount does not empty. Minimum  '0' is required.","Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
         jTextField7.requestFocus();
        }

   
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
                    if(evt.getKeyCode()==10)
                    {
                         String str=javax.swing.JOptionPane.showInputDialog(this, "Please enter Purja no.","Print Purja",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    boolean flag=false;
                    if(str!=null || (str.isEmpty()==false))
                    {   if(Utility.isInteger(str))
                        {
                            int purja=Integer.parseInt(str);
                            String qry="select distinct purja_number from polish_details";
                            String data[][]=Utility.getInformationDD(qry,1);
                            for(int i=0;i<data.length;i++)
                            {
                                int purjaNumber=Integer.parseInt(data[i][0]);
                                if(purjaNumber==purja)
                                {       flag=true;
                                }

                            }
                        }
                    }
                    if(flag==true)
                    {
                                    printchallan2 pt=new printchallan2(str);
                    }
                    else
                    {
                         javax.swing.JOptionPane.showMessageDialog(this,"Error... Please enter vlaid purja number . " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    }
                   }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        setPurjaNumber();
         if((dtm.getRowCount())>=1)
       {
        Update();
        String str=jLabel11.getText().trim();
        printchallan2 pt=new printchallan2(str);
        //setPurjaNumber();
       }
        else
       {
               javax.swing.JOptionPane.showMessageDialog(this,"Error... There is no record in the table. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if((dtm.getRowCount())>=1)
       {
        Update();
        String str=jLabel11.getText().trim();
        printchallan2 pt=new printchallan2(str);
        //setPurjaNumber();
       }
        else
       {
               javax.swing.JOptionPane.showMessageDialog(this,"Error... There is no record in the table. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jLabel12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel12KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel12KeyPressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        calenderDate();
}//GEN-LAST:event_jLabel12MouseClicked

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MousePressed
        // TODO add your handling code here:
        jTextField5.selectAll();
    }//GEN-LAST:event_jTextField5MousePressed

    private void jTextField6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField6MousePressed

    private void jTextField7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MousePressed
        // TODO add your handling code here:
        jTextField7.selectAll();
    }//GEN-LAST:event_jTextField7MousePressed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
                if(Utility.isBlank(jTextField5.getText())==false)
                {

                        if((Utility.isDouble(jTextField5.getText())))
                         {
                                     if((Double.valueOf(jTextField5.getText()))>0)
                                       {    double payableAmount=(Double.valueOf(jTextField4.getText()));
                                            java.math.BigDecimal bd4=new java.math.BigDecimal(payableAmount);
                                            payableAmount=Double.valueOf(""+bd4.setScale(0,java.math.BigDecimal.ROUND_HALF_UP));

                                            double a=((payableAmount)-(Double.valueOf(jTextField5.getText())));
                                            java.math.BigDecimal bd=new java.math.BigDecimal(a);
                                            jTextField6.setText(""+bd.setScale(2,5));
                                        }
                        }
                        else
                        {
                            if((evt.getKeyCode())==127 || (evt.getKeyCode())==8)
                            {
                            }
                            else
                            {

                              javax.swing.JOptionPane.showMessageDialog(this,"Discount is not valid." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                              String str=jTextField5.getText().substring(0, jTextField5.getText().length()-1);
                              jTextField5.setText(str);
                            }
                         }
                 }
               else
                {           double payableAmount=(Double.valueOf(jTextField4.getText()));
                            java.math.BigDecimal bd4=new java.math.BigDecimal(payableAmount);
                            payableAmount=Double.valueOf(""+bd4.setScale(0,java.math.BigDecimal.ROUND_HALF_UP));
                            java.math.BigDecimal bd=new java.math.BigDecimal(payableAmount);
                            jTextField6.setText(""+bd.setScale(2,5));
               }

                          


                
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        // TODO add your handling code here:
                       
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
      
        if(evt.getKeyCode() == 10 || evt.getKeyCode() == 40 || evt.getKeyCode() == 38)
        {
                        check();
                        calculateTotal();
                        edetingTotal();
        }
      

      
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
         
                 
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
                jButton4.requestFocus();
        }
    }//GEN-LAST:event_jTextField7KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

   
 boolean firsttime1=false;
    int purjano;
    class printchallan2
    {

                PrintPanel2 canvas;
	        java.awt.print.PageFormat pageFormat;

        	public printchallan2(String str)
        	{
                    purjano=Integer.parseInt(str);
                    System.out.println("print constructor");

                                canvas=new PrintPanel2();
                                java.awt.print.PrinterJob printJob=java.awt.print.PrinterJob.getPrinterJob();
                                double width=8.27 * 72;
                                double height=(11.69 * 72);

                                java.awt.print.Paper paper=new java.awt.print.Paper();

                                paper.setSize(width,height);

                                java.awt.print.PageFormat page=new java.awt.print.PageFormat();
                                page.setOrientation(java.awt.print.PageFormat.PORTRAIT);
                                paper.setImageableArea(5,10,paper.getWidth(),paper.getHeight());
                                page.setOrientation(java.awt.print.PageFormat.PORTRAIT);
                                page.setPaper(paper);
                                pageFormat=printJob.defaultPage(page);
                                pageFormat.setPaper(paper);
                                pageFormat.setOrientation(java.awt.print.PageFormat.PORTRAIT);
                                printJob.setPrintable(canvas,pageFormat);

                                try
                                {
					//no of pages
                                        printJob.print();
                                }
                                catch(Exception exception)
                                {
                                        javax.swing.JOptionPane.showMessageDialog(null,"error2="+exception);
                                }
                                //jButton5.setEnabled(true);
        		    }
	}//print class


    class PrintPanel2 extends javax.swing.JPanel implements java.awt.print.Printable
	{

        int page=100;
		java.awt.font.TextLayout layout;
		java.awt.Font f,f1,f2,f3,f4,f5,f6;
		java.awt.Graphics2D g2;
		int row=0;
		java.awt.font.FontRenderContext context;


        public PrintPanel2()
        {
                //ChallanNo=JOptionPane.showInputDialog(null,"Enter Challan Number:");
        }
        public void paintComponent(java.awt.Graphics g)
        {
                super.paintComponent(g);
                System.out.println("BPPRINT");
                java.awt.Graphics2D g2=(java.awt.Graphics2D)g;
                drawPage(g2);

        }

        public int print(java.awt.Graphics g,java.awt.print.PageFormat pf,int page) throws java.awt.print.PrinterException
        {
                if(page>=1)
                return java.awt.print.Printable.NO_SUCH_PAGE;
                java.awt.Graphics2D g2=(java.awt.Graphics2D)g;
                g2.setPaint(java.awt.Color.black);
                g2.translate(pf.getImageableX(),pf.getImageableY());

                System.out.println("W1="+pf.getImageableWidth()+"H1="+pf.getImageableHeight());

                //if(printflag==5)
                //{
                	drawPage(g2);
                //}

                return java.awt.print.Printable.PAGE_EXISTS;
        }
        public void drawPage(java.awt.Graphics2D g2)
        {
            this.g2=g2;
	    System.out.println("Hellospecial"+firsttime1);
            //System.out.println("inside draw page..."+totalamt);
            context=g2.getFontRenderContext();
            f1=new java.awt.Font("Times New Roman",java.awt.Font.BOLD,10);
            f2=new java.awt.Font("Arial",java.awt.Font.PLAIN,8);
            f3=new java.awt.Font("Arial",java.awt.Font.PLAIN,30);
            f4=new java.awt.Font("Arial",java.awt.Font.BOLD,10);
            f5=new java.awt.Font("Verdana",java.awt.Font.PLAIN,10);
            f6=new java.awt.Font("Verdana",java.awt.Font.BOLD,10);
            java.awt.Font f7=new java.awt.Font("Arial",java.awt.Font.BOLD,13);
            java.awt.Font f8=new java.awt.Font("Times New Roman",java.awt.Font.BOLD,25);
            java.awt.Font f9=new java.awt.Font("Arial narrow",java.awt.Font.PLAIN,2);
            java.awt.FontMetrics fm;
            java.awt.geom.GeneralPath clipShape=new java.awt.geom.GeneralPath();
            String str=" fdfg dfg dfg";
            String str1="d fgf dgdfg df";
            g2.setFont(f1);
            layout=new java.awt.font.TextLayout(str,f1,context);
            java.awt.geom.AffineTransform transform=java.awt.geom.AffineTransform.getTranslateInstance(10,20);

            g2.setFont(f2);
            fm=g2.getFontMetrics();

			if(firsttime1==false)
			{
				firsttime1=true;
            		}
                        else
                        {   firsttime1=false;
                            int top=20;
                            int i=0;
                            int j=0;
                            int z=0;
                            double receiveAmount=0;
                            double discount=0;
                            double payableAmount=0;
                            String date="";
                            int pur=purjano;
                            String qry="Select rec_date from polish_details where purja_number="+pur+"";
                            String dd=Utility.getSingleValue(qry);
                            String d[]=dd.split(" ");
                            String d1[]=d[0].split("-");
                            date=d1[2]+"-"+d1[1]+"-"+d1[0];
                            g2.setFont(f6);
                            fm=g2.getFontMetrics();
                            String temp="Receiving Dt : "+date;
                            g2.drawString(temp,15,top+10);
                            qry="Select ac_code from polish_details where purja_number="+pur+"";
                            int cid=Integer.parseInt(Utility.getSingleValue(qry));
                            qry="Select ac_name from ac_master where ac_code="+cid+"";
                            String accountName=""+(Utility.getSingleValue(qry));
                            temp="Customer Name : "+accountName;
                            g2.drawString(temp,200,top+10);
                            temp="Purja Number :"+purjano;
                            g2.drawString(temp,465,top+10);
                            top=top+25;
                            g2.drawLine(15, top, 575, top);
                            //for heading
                            top=top+15;
                            temp="S.No    Weight(B)   Item Name         Polish Type   Quantity   Weight(A)        Rate                  Amount";
                            g2.drawString(temp,15,top);
                            top=top+10;
                            g2.drawLine(15, top, 575, top);
                            //End
                            //for data printing
                            g2.setFont(f5);
                            fm=g2.getFontMetrics();
                            qry="Select * from polish_details where purja_number="+pur+"";
                            String load[][]=Utility.getInformationDD(qry,17);
                            double total=0;
                            double totamt=0;
                            String weight="";
                            String weightAP="";
                            String itemName="";
                            String polishType="";
                            String quantity="";
                            String unit="";
                            String rate="";
                            String rateUnit="";
                            String amount="";
                            String temp1="";
                            String temp2="";
                            String temp3="";
                            String temp4="";
                            String temp5="";
                            String temp6="";
                            String temp7="";
                            String temp8="";
                            String temp9="";
                            String temp10="";
                            String temp11="";
                            String temp12="";
                            String temp13="";
                            top=top+25;
                            if(load.length>0)
                            {
                                    for(i=0,j=(-10);i<load.length;i++,j=j+15)
                                    {
                                        weight=load[i][7];
                                        weightAP=load[i][9];
                                        itemName=load[i][3];
                                        polishType=load[i][4];
                                        quantity=load[i][5];
                                        unit=load[i][6];
                                        rate=load[i][10];
                                        rateUnit=load[i][11];
                                        amount=load[i][13];
                                        total=total+Double.valueOf(amount);
                                        temp4=(i+1)+".";
                                        //z=fm.stringWidth(temp4);
                                        java.math.BigDecimal bd=new java.math.BigDecimal(weight);
                                        temp5=""+bd.setScale(3,5);
                                        //weight after polish
                                        z=fm.stringWidth(temp13);
                                        bd=new java.math.BigDecimal(weightAP);
                                        temp13=""+bd.setScale(3,5);

                                        //End
                                        temp6=itemName;
                                        temp7=polishType;
                                        temp8=quantity;
                                        temp9=unit;
                                        bd=new java.math.BigDecimal(rate);
                                        temp10=""+bd.setScale(2,5);
                                        temp11=unit;
                                        bd=new java.math.BigDecimal(amount);
                                        temp12=""+bd.setScale(2,5);
                                        z=fm.stringWidth(temp4);
                                        g2.drawString(temp4,35-z,top+j);
                                        //to display weight in bold if rate*weight
                                        if(rateUnit.equals("Kg"))
                                        {           g2.setFont(f6);
                                                    z=fm.stringWidth(temp5);
                                                    g2.drawString(temp5,100-z,top+j);
                                                    g2.setFont(f5);
                                        }
                                        else
                                        {
                                                    z=fm.stringWidth(temp5);
                                                    g2.drawString(temp5,100-z,top+j);
                                        }
                                        g2.drawString(temp6,120,top+j);
                                        g2.drawString(temp7,220,top+j);
                                        if(rateUnit.equals("Kg")==false)
                                        {
                                                    g2.setFont(f6);
                                                    z=fm.stringWidth(temp8);
                                                    g2.drawString((temp8+" "),300-z,top+j);
                                                    g2.setFont(f5);
                                        }
                                        else
                                        {
                                                    z=fm.stringWidth(temp8);
                                                    g2.drawString((temp8+" "),300-z,top+j);
                                        }
                                        //b=fm.stringWidth(temp9);
                                        g2.drawString(temp9,306,top+j);
                                        z=fm.stringWidth(temp13);
                                        g2.drawString(temp13,370,top+j);

                                        z=fm.stringWidth(temp10);
                                        g2.drawString(temp10+" / ",450-z,top+j);
                                        //b=fm.stringWidth(temp11);
                                        g2.drawString(temp11,460,top+j);
                                        int a=fm.stringWidth(temp12);
                                        g2.drawString(temp12,570-a,top+j);
                                        //Start Coading for total balance(Down ward)

                                        //g2.drawString("Hiii",100,840);

                                }
                            }
                            int down=312;
                            str="select discount from polish_details where purja_number="+purjano+"";
                            discount=Double.valueOf(Utility.getSingleValue(str));
                            str="select payable_amount from polish_details where purja_number="+purjano+"";
                            payableAmount=(Double.valueOf(Utility.getSingleValue(str))+discount);
                            //To find roundingvalue
                            java.math.BigDecimal bd4=new java.math.BigDecimal(total);
                            double aa=Double.valueOf(""+bd4.setScale(0,java.math.BigDecimal.ROUND_HALF_UP));
                            Double rounding=(aa-total);

                                if(total>0)
                                {
                                                if(discount==0 && rounding==0)
                                                {

                                                }
                                                else if(rounding==0)
                                                {
                                                                     //for discount
                                                                    temp="Discount :";
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,(497-z),down-20 );
                                                                    java.math.BigDecimal bd=new java.math.BigDecimal(discount);
                                                                    temp=""+bd.setScale(2,5);
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,570-z,down-20 );

                                                                    //for total
                                                                    temp="Total Amount : ";
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,(500-z),(down-35) );
                                                                    bd=new java.math.BigDecimal(total);
                                                                    temp=""+bd.setScale(2,5);
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,570-z,(down-35));


                                                }
                                                else if(discount==0)
                                                {
                                                                    temp="Rounding : ";
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,(500-z),down-20);
                                                                    java.math.BigDecimal bd=new java.math.BigDecimal(rounding);
                                                                    temp=""+bd.setScale(2,5);
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,570-z,down-20 );

                                                                    //for total
                                                                    temp="Total Amount : ";
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,(500-z),(down-35) );
                                                                    bd=new java.math.BigDecimal(total);
                                                                    temp=""+bd.setScale(2,5);
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,570-z,(down-35));
                                                                    //for Rounding
                                                 }
                                                 else
                                                {
                                                                    //for discount
                                                                    temp="Discount :";
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,(497-z),down-20 );
                                                                    java.math.BigDecimal bd=new java.math.BigDecimal(discount);
                                                                    temp=""+bd.setScale(2,5);
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,570-z,down-20 );
                                                                    //rounding
                                                                    temp="Rounding : ";
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,(500-z),(down-35) );
                                                                    bd=new java.math.BigDecimal(rounding);
                                                                    temp=""+bd.setScale(2,5);
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,570-z,(down-35) );

                                                                    //for total
                                                                    temp="Total Amount : ";
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,(500-z),(down-50) );
                                                                    bd=new java.math.BigDecimal(total);
                                                                    temp=""+bd.setScale(2,5);
                                                                    z=fm.stringWidth(temp);
                                                                    g2.drawString(temp,570-z,(down-50));

                                                 }
                                  }
                            g2.drawLine(400, 300, 575,300);

                            //for net amount
                            if(discount==0 && rounding==0)
                            {
                                    temp="Total Amount : ";
                                     z=fm.stringWidth(temp);
                                    g2.drawString(temp,(500-z),315 );

                            }
                            else
                            {
                                    temp="Net Amount : ";
                                    z=fm.stringWidth(temp);
                                    g2.drawString(temp,(500-z),315 );
                            }

                            //str="select payable_amount from polish_details where purja_number="+purjano+"";
                            //payableAmount=Double.valueOf(Utility.getSingleValue(str));
                                    g2.setFont(f6);
                                    java.math.BigDecimal bd=new java.math.BigDecimal(payableAmount-discount);
                                    temp=""+bd.setScale(2,5);
                                    z=fm.stringWidth(temp);
                                    g2.drawString(temp,570-z,315 );
                                    g2.setFont(f5);
                            g2.drawLine(400, 320, 575,320);
                            //for old Amount
                            temp="Old Balance : ";
                            z=fm.stringWidth(temp);
                            g2.drawString(temp,(500-z),335);

                            qry="select ac_cr,ac_dr from ac_smry where ac_code="+cid+"";
                            String data1[][]=Utility.getInformationDD(qry,2);
                            double cr=Double.valueOf(data1[0][0]);
                            double dr=Double.valueOf(data1[0][1]);
                            double oldBalance=(dr-cr);
                                    bd=new java.math.BigDecimal(oldBalance);
                                    temp=""+bd.setScale(2,5);
                                    z=fm.stringWidth(temp);
                                    g2.drawString(temp,570-z,335 );
                                                      

                            //for received amount
                            temp="Received Amount : ";
                            z=fm.stringWidth(temp);
                            g2.drawString(temp,(500-z),355);

                            str="select voucher_amount from receive_voucher where purja_number="+purjano+"";
                            String paidAmount=""+Utility.getSingleValue(str);
                           // System.out.println("Helloooo");
                            if(paidAmount==null || paidAmount.isEmpty())
                            {       paidAmount="0";
                                    receiveAmount=0;
                                    bd=new java.math.BigDecimal(receiveAmount);
                                    temp=""+bd.setScale(2,5);
                                    z=fm.stringWidth(temp);
                                    g2.drawString(temp,570-z,355 );
                            }
                            else
                            {
                                    receiveAmount=Double.valueOf(paidAmount);
                                    bd=new java.math.BigDecimal(receiveAmount);
                                    temp=""+bd.setScale(2,5);
                                    z=fm.stringWidth(temp);
                                    g2.drawString(temp,570-z,355 );
                            }
                            g2.drawLine(15, 365, 575,365);
                            //for total items
                            fm=g2.getFontMetrics();
                            temp="Total Items : "+(i);
                            g2.drawString(temp,20,380);

                            //for Balance Account
                            double netAmount=(aa-discount);
                            temp="Balance Amount : ";
                            double receaveAmount=Double.valueOf(paidAmount);
                            z=fm.stringWidth(temp);
                            g2.drawString(temp,(500-z),380 );
                            double balanceAmount=((oldBalance+netAmount)-(receiveAmount));
                            bd=new java.math.BigDecimal(balanceAmount);
                            temp=""+bd.setScale(2,5);
                            z=fm.stringWidth(temp);
                            g2.setFont(f6);
                            g2.drawString(temp,570-z,380 );
                            g2.drawLine(15, (385), 575, (385));

System.out.println("Net Amount"+aa);

                        }
        }
    }
}
