/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Collection_Window.java
 *
 * Created on Nov 21, 2012, 4:04:10 PM
 */

package tagada;
import java.awt.Color;

/**
 *
 * @author user2
 */
public class Collection_Window extends javax.swing.JInternalFrame {
    Color cl1=new Color(232,232,164);
    Color cl3=new Color(255,255,204);

    /** Creates new form Collection_Window */
    public Collection_Window() {
        initComponents();
        java.util.Date dt=new java.util.Date();
        int date=dt.getDate();
        int month=dt.getMonth()+1;
        int year=dt.getYear()+1900;
        String setDate=date+"-"+month+"-"+year;
        jLabel8.setText(setDate);

        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        dtm=new javax.swing.table.DefaultTableModel();

        javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        javax.swing.table.TableColumn column;
        String heading1[]={"S.No.","Date of Collection","Amount","Staff Name","Route","Area","C_Code"};
        dtm=new javax.swing.table.DefaultTableModel(heading1,0);
        jTable1.setModel(dtm);

        column=jTable1.getColumn("S.No.");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(40);
        column=jTable1.getColumn("Date of Collection");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(120);
        column=jTable1.getColumn("Amount");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(60);
        column=jTable1.getColumn("Staff Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(110);
        column=jTable1.getColumn("Route");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Area");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(245);
        column=jTable1.getColumn("C_Code");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(80);
        
        loadInitialInfo();
        uploadDetail();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tagada.TagadaApp.class).getContext().getResourceMap(Collection_Window.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 180, 30);

        jComboBox1.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 20, 280, 30);

        jLabel2.setBackground(resourceMap.getColor("jLabel2.background")); // NOI18N
        jLabel2.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(500, 20, 150, 30);

        jLabel3.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 180, 30);

        jComboBox2.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox2.setName("jComboBox2"); // NOI18N
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(210, 60, 440, 30);

        jLabel4.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 180, 30);

        jComboBox3.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox3.setName("jComboBox3"); // NOI18N
        jComboBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox3KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(210, 100, 440, 30);

        jLabel7.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 140, 170, 30);

        jLabel8.setBackground(resourceMap.getColor("jLabel8.background")); // NOI18N
        jLabel8.setFont(resourceMap.getFont("jComboBox1.font")); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 140, 250, 30);

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 140, 30, 30);

        jButton2.setBackground(resourceMap.getColor("jButton2.background")); // NOI18N
        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton2FocusLost(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 200, 140, 35);

        jButton3.setBackground(resourceMap.getColor("jButton3.background")); // NOI18N
        jButton3.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton3.setMnemonic('C');
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setToolTipText(resourceMap.getString("jButton3.toolTipText")); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton3FocusLost(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(510, 200, 140, 35);

        jButton4.setBackground(resourceMap.getColor("jButton4.background")); // NOI18N
        jButton4.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton4FocusLost(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(360, 200, 140, 35);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 670, 250);

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(null);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setFont(resourceMap.getFont("jTable1.font")); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setName("jTable1"); // NOI18N
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 650, 280);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 290, 670, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        uploadDebitAmount();
        uploadDetail();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cal date=new Cal();
        jLabel8.setText(date.getdate());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox2.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox3.requestFocus();
        }
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_jComboBox3KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode()==10)
       {
           Save();
       }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            Save();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
        jTable1.setBackground(cl3);
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        // TODO add your handling code here:
        jTable1.setBackground(cl1);
    }//GEN-LAST:event_jTable1FocusLost

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
        // TODO add your handling code here:
        jButton2.setBackground(cl1);
    }//GEN-LAST:event_jButton2FocusGained

    private void jButton2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusLost
        // TODO add your handling code here:
        jButton2.setBackground(cl3);
    }//GEN-LAST:event_jButton2FocusLost

    private void jButton3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusGained
        // TODO add your handling code here:
        jButton3.setBackground(cl1);
    }//GEN-LAST:event_jButton3FocusGained

    private void jButton3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusLost
        // TODO add your handling code here:
        jButton3.setBackground(cl3);
    }//GEN-LAST:event_jButton3FocusLost

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        setCollection();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        updateCollection();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4FocusGained

    private void jButton4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4FocusLost

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4KeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_DELETE)
        {
            deleteCollection();
        }
    }//GEN-LAST:event_jTable1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    javax.swing.table.DefaultTableModel dtm;

private void loadInitialInfo()
{
    String qry="";
    try
    {
        qry="Select party_name from sale_Party_Master order by party_name asc";
        String load[][]=Utility.getInformationDD(qry,1);
        if(load.length>0)
        {
            jComboBox1.removeAllItems();
            for(int i=0;i<load.length;i++)
            {
                jComboBox1.addItem(load[i][0]);
            }
        }

        qry="Select staff_name from staff_Detail order by staff_name asc";
        load=Utility.getInformationDD(qry,1);
        if(load.length>0)
        {
            jComboBox2.removeAllItems();
            for(int i=0;i<load.length;i++)
            {
                jComboBox2.addItem(load[i][0]);
            }
        }

        qry="Select route_nm from route_Master order by route_nm asc";
        load=Utility.getInformationDD(qry,1);
        if(load.length>0)
        {
            jComboBox3.removeAllItems();
            for(int i=0;i<load.length;i++)
            {
                jComboBox3.addItem(load[i][0]);
            }
        }
    }


    catch(Exception e)
    {
        System.out.println("Error ! In  loadInitialInfo Method."+e);
    }
}

private void uploadDebitAmount()
{
    String qry="";
    try
    {
        qry="Select debit from party_Account where party_name='"+jComboBox1.getSelectedItem().toString()+"'";
        String load=Utility.getSingleValue(qry);

        if(load.length()>0)
        {
            jLabel2.setText(""+Double.valueOf(load));
        }
    }

    catch(Exception e)
    {
        System.out.println("Error ! In uploadDebitAmount Method."+e);
    }
}

boolean Save()
{
    String qry="";
    try
    {
       
        qry="Select Max(Collection_code) from collection_Detail";
        String getMax=Utility.getSingleValue(qry);
        int ind=0;
        if(getMax!=null)
        {
             ind=Integer.parseInt(getMax)+1;
        }
        else
        {
            ind=1;
        }
        String D[]=jLabel8.getText().split("-");
        String setDate=D[1]+"-"+D[0]+"-"+D[2];
        qry="Select staff_code from staff_Detail where staff_name='"+jComboBox2.getSelectedItem().toString()+"'";
        String getStaffCode=Utility.getSingleValue(qry);
        qry="insert into collection_Detail values("+ind+",'"+jComboBox1.getSelectedItem()+"','"+jComboBox3.getSelectedItem()+"',#"+setDate+"#,"+Double.valueOf(jLabel2.getText())+","+Integer.parseInt(getStaffCode)+")";
        boolean bn=Utility.saveInformation(qry);
        if(bn)
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Process Completed.");
            uploadDetail();
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            java.util.Date dt=new java.util.Date();
            int date=dt.getDate();
            int month=dt.getMonth()+1;
            int year=dt.getYear()+1900;
            setDate=date+"-"+month+"-"+year;
            jLabel8.setText(setDate);
        }

    }

    catch(Exception e)
    {
        System.out.println("Error ! Save Method."+e);
    }
    return true;

}

private void uploadDetail()
{
    String qry="";
    dtm.setRowCount(0);
    try
    {
        qry="Select * from collection_Detail where party_name='"+jComboBox1.getSelectedItem().toString()+"'";
        String load[][]=Utility.getInformationDD(qry,6);
        String arr[]=null;
        if(load.length>0)
        {
            arr=new String[7];
            for(int i=0;i<load.length;i++)
            {

                arr[0]=""+(dtm.getRowCount()+1)+".";

                String D[]=load[i][3].split(" ");
                String D1[]=D[0].split("-");
                String setDate=D1[2]+"-"+D1[1]+"-"+D1[0];
                arr[1]=setDate;

                arr[2]=""+Double.valueOf(load[i][4]);

                qry="Select staff_name from staff_Detail where staff_code="+Integer.parseInt(load[i][5]);
                String getStaffName=Utility.getSingleValue(qry);
                arr[3]=getStaffName;

                arr[4]=load[i][2];

                qry="Select area_name from area_Master where route_nm='"+load[i][2]+"'";
                String load1[][]=Utility.getInformationDD(qry,1);
                String area="";

                if(load1.length>0)
                {
                    for(int j=0;j<load1.length;j++)
                    {
                        if(area.equals(""))
                        {
                            area=load1[j][0];

                        }
                        else
                        {
                            area=area+", "+load1[j][0];
                        }
                    }
                }

                arr[5]=area;

                arr[6]=load[i][0];
                dtm.addRow(arr);
            }
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In  uploadDetail Method."+e);
    }
}

private void setCollection()
{
    int i=jTable1.getSelectedRow();

    jLabel2.setText(""+jTable1.getValueAt(i, 2));
    jLabel8.setText(""+jTable1.getValueAt(i, 1));
    jComboBox2.setSelectedItem(""+jTable1.getValueAt(i, 3));
    jComboBox3.setSelectedItem(""+jTable1.getValueAt(i, 4));
}

private void deleteCollection()
{
    String qry="";

    try
    {
        if(jTable1.getSelectedRowCount()<1)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please! Select a Record.");
        }

        else if(dtm.getRowCount() > 0)
        {
            int c=javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this Record?", "Delete Record", javax.swing.JOptionPane.YES_NO_OPTION);
            if(c==javax.swing.JOptionPane.YES_OPTION)
            {
                qry="delete * from collection_Detail where Collection_code='"+jTable1.getValueAt(jTable1.getSelectedRow(), 6)+"'";
                Utility.saveInformation(qry);

                dtm.setRowCount(0);
                uploadDetail();

                javax.swing.JOptionPane.showMessageDialog(this, "Record Deleted Successfully.");

                jComboBox1.setSelectedIndex(0);
                jComboBox1.setSelectedIndex(0);
                jComboBox1.setSelectedIndex(0);
                jLabel2.setText("00.00");
                jComboBox1.requestFocus();
            }
        }
    }

    catch(Exception ae)
    {
        System.out.println(ae);
    }
}

private void updateCollection()
{
    String qry="";

    if(jTable1.getSelectedRowCount()<1)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Record is not selected.");
    }

    else if(dtm.getRowCount() > 0)
    {
        qry="Select staff_code from staff_Detail where staff_name='"+jComboBox2.getSelectedItem().toString()+"'";
        String scode=Utility.getSingleValue(qry);

        int c=javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to update this Record?", "Update Record", javax.swing.JOptionPane.YES_NO_OPTION);
        if(c==javax.swing.JOptionPane.YES_OPTION)
        {
            String str=jLabel8.getText().trim();
            String D[]=str.split("-");
            String setDate=D[1]+"-"+D[0]+"-"+D[2];

            qry="update collection_Detail set party_name='"+jComboBox1.getSelectedItem().toString()+"', route_nm='"+jComboBox3.getSelectedItem().toString()+"', collection_date=#"+setDate+"#, amount="+Double.valueOf(jLabel2.getText())+", staff_code="+Integer.parseInt(scode)+" where Collection_code='"+(""+jTable1.getValueAt(jTable1.getSelectedRow(), 6))+"'";
            Utility.saveInformation(qry);

            dtm.setRowCount(0);
            uploadDetail();

            javax.swing.JOptionPane.showMessageDialog(this, "Record Updated Successfully.");
        }
    }
}
}
