/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * ac_master.java
 *
 * Created on Jan 31, 2014, 2:44:34 PM
 */
package giftcorner;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane.*;
/**
 *
 * @author user3
 */
public class ac_master extends javax.swing.JInternalFrame {
    /** Creates new form ac_master */
    public ac_master() {
        initComponents();
        String heading[]={"A/C Name","Group","contact No.","Opening Amt","A/C Typ"};
        dtm=new DefaultTableModel(heading,0);
        javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        jTable1.setModel(dtm);
        javax.swing.table.TableColumn column;
        column=jTable1.getColumn("A/C Name");
        column.setCellRenderer(CRCenter);
        //column.setPreferredWidth(10);
        column=jTable1.getColumn("Group");
        column.setCellRenderer(CRCenter);
        column=jTable1.getColumn("contact No.");
        column.setCellRenderer(CRCenter);
        column=jTable1.getColumn("Opening Amt");
        column.setCellRenderer(CRRight);
        column=jTable1.getColumn("A/C Typ");
        column.setCellRenderer(CRCenter);
        String typ[]={"SELECT","Dr","Cr"};
        for(int i=0;i<typ.length;i++){jComboBox2.addItem(typ[i]);}
        jComboBox1.addItem("SELECT");
        Connection con;
        Statement st,st2;
        ResultSet res,res1;
         try {
           Class.forName("com.mysql.jdbc.Driver").newInstance();
           con=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
           st=con.createStatement();
           res= st.executeQuery("select gp_nm from group_master");
           while(res.next()==true){
               //jComboBox1.addItem(res.getString(1));
           }
           st2=con.createStatement();
           res1=st2.executeQuery("select *from ac_details");
           while(res1.next()==true)
           {
              val[0]=res1.getString(1);
              val[1]=res1.getString(2);
              val[2]=res1.getString(3);
              val[3]=res1.getString(4);
              val[4]=res1.getString(5);
            //val[5]=res1.getString(6);
               dtm.addRow(val);
             }
            res.close();
            st.close();
            res1.close();
            st2.close();
            con.close();
        } catch (Exception ex) { System.out.println("error...."+ex); }

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("A/C Creation");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setText(" A/C Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 70, 20);

        jTextField1.setToolTipText("enter account name");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(90, 30, 200, 20);

        jLabel2.setText("Group");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 30, 40, 20);

        jLabel3.setText("Contact No.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 70, 20);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setToolTipText("please enter contact no");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(90, 80, 150, 20);

        jLabel4.setText("Opening Amt");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(260, 80, 80, 20);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setToolTipText("please enter opening amount");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(340, 80, 130, 20);

        jComboBox1.setToolTipText("select group");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(400, 30, 220, 20);

        jComboBox2.setToolTipText("please select a/c typ");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(540, 80, 80, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 180, 630, 250);

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/green button.png"))); // NOI18N
        jButton1.setText("Create");
        jButton1.setToolTipText("create account");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/green button2.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/green button1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 130, 100, 40);

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue button.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setToolTipText("close ");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue button2.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue button1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 130, 100, 40);

        jLabel5.setText("a/c Type ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(490, 80, 50, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wall.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 630, 440);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                    insert();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jComboBox1.requestFocus();
            }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
            jTextField3.requestFocus();
            jTextField3.selectAll();
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
            jComboBox2.requestFocus();
          
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
            jButton1.requestFocus();
            jButton1.setSelected(true);
           }
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
            jTextField4.requestFocus();
            jTextField4.selectAll();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
            insert();
        }
    }//GEN-LAST:event_jButton1KeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel dtm;
    private String ch="";
    double d;
    private String val[]=new String[5];
  public boolean pass(String r){
        try{
        d=Double.valueOf(r);
        return(true);
        }catch(Exception e){return(false);}
    }
public void insert(){
        boolean cn=pass(jTextField3.getText());
        boolean am=pass(jTextField4.getText());
        Connection con1;
        Statement st1,st2;
        ResultSet res1;
         if(ch.equals(jTextField1.getText())==true)
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Error :.."+"\n"+"Please enter account name","Error..",JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.selectAll();
                }else{
                    if("SELECT".equals(jComboBox1.getSelectedItem())==true)
                        {
                            javax.swing.JOptionPane.showMessageDialog(null,"Error :.."+"\n"+"Please select account group","Error..",JOptionPane.ERROR_MESSAGE);
                            jComboBox1.requestFocus();
                            }else{
                                if(ch.equals(jTextField3.getText())==true){
                                    javax.swing.JOptionPane.showMessageDialog(null, "Error :.."+"\n"+"Please enter contact no","Error..",JOptionPane.ERROR_MESSAGE);
                                    jTextField3.requestFocus();
                                    jTextField3.selectAll();
                                    }
                                else{
                                    if(cn==false)
                                    {
                                        javax.swing.JOptionPane.showMessageDialog(null, "Error :.."+"\n"+"Please enter only numbers in contact no field","Error..",JOptionPane.ERROR_MESSAGE);
                                        jTextField3.requestFocus();
                                        jTextField3.selectAll();
                                    }else{
                                    if(ch.equals(jTextField4.getText())==true){
                                        javax.swing.JOptionPane.showMessageDialog(null, "Error :.."+"\n"+"Please enter opening amount","Error..",JOptionPane.ERROR_MESSAGE);
                                        jTextField4.requestFocus();
                                        jTextField4.selectAll();
                                        }
                                    else{
                                        if(am==false)
                                         {
                                        javax.swing.JOptionPane.showMessageDialog(null, "Error :.."+"\n"+"Please enter only numbers in opening amount","Error..",JOptionPane.ERROR_MESSAGE);
                                        jTextField4.requestFocus();
                                        jTextField4.selectAll();
                                        }
                                       else{
                                        if("SELECT".equals(jComboBox2.getSelectedItem())==true)
                                        {
                                            javax.swing.JOptionPane.showMessageDialog(null, "Error :.."+"\n"+"Please select account typ","Error..",JOptionPane.ERROR_MESSAGE);
                                            jComboBox2.requestFocus();
                                        }else{
                                            try {
                                                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                                                    con1=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
                                                    st1=con1.createStatement();
                                                    st1.executeUpdate("insert into ac_details(ac_nm,gp_nm,contact_no,op_amt,drcr)values('"+jTextField1.getText()+"','"+jComboBox1.getSelectedItem()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jComboBox2.getSelectedItem()+"')");
                                                    st1.close();
                                                    con1.close();
                                                  //System.out.println("OK");
                                                  } catch (Exception ex) { javax.swing.JOptionPane.showMessageDialog(null,"account name= "+ jTextField1.getText()+" alredy existed in account","Error..",JOptionPane.ERROR_MESSAGE); }
                                                    insert_crdr();
                                                    dtm.setRowCount(0);
                                                 try {
                                                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                                                    con1=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
                                                    st2=con1.createStatement();
                                                    res1=st2.executeQuery("select *from ac_details");
                                                    while(res1.next()==true)
                                                    {
                                                        val[0]=res1.getString(1);
                                                        val[1]=res1.getString(2);
                                                        val[2]=res1.getString(3);
                                                        val[3]=res1.getString(4);
                                                        val[4]=res1.getString(5);
                                                        //val[5]=res1.getString(6);
                                                        dtm.addRow(val);
                                                        }
                                                      st2.close();
                                                      res1.close();
                                                      con1.close();
                                                      //System.out.println("OK");
                                                    } catch (Exception ex) { System.out.println("error.."+ex); }
                                                  jTextField1.requestFocus();
                                                  jTextField1.setText("");
                                                  jComboBox1.setSelectedIndex(0);
                                                  jTextField3.setText("");
                                                  jTextField4.setText("");
                                                  jComboBox2.setSelectedIndex(0);

                                          }
                                      }                                     
                                     }
                                  }
                                }
                            }
                }
 }
public void insert_crdr(){
    double i=Double.valueOf(jTextField4.getText());
    double d=0;
        String ac=jComboBox2.getSelectedItem().toString().toLowerCase();
        Connection con1;
        Statement st1;
        if(i>d)
        {
            if("dr".equals(ac))
              {
             try {
                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                    con1=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
                    st1=con1.createStatement();
                    st1.executeUpdate("insert into ac_smry(ac_nm,debit)values('"+jTextField1.getText()+"','"+jTextField4.getText()+"')");
                    st1.close();
                    con1.close();
                     //System.out.println("OK kkkkkkkkkk");
                     } catch (Exception ex){System.out.println(ex);}
                    }
                else {
                        try {
                     Class.forName("com.mysql.jdbc.Driver").newInstance();
                     con1=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
                     st1=con1.createStatement();
                     st1.executeUpdate("insert into ac_smry(ac_nm,credit)values('"+jTextField1.getText()+"','"+jTextField4.getText()+"')");
                     st1.close();
                     con1.close();
                     //System.out.println("oooooooooOK");
                      } catch (Exception ex){System.out.println(ex);}
                    }


        }

}
}