/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Item_category.java
 *
 * Created on Jan 15, 2014, 5:20:16 PM
 */

package giftcorner;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author user3
 */
public class Item_category extends javax.swing.JInternalFrame {
    /** Creates new form Item_category */
    public Item_category() {
        initComponents();
        //setLocationRelativeTo(null);
        jTextField1.requestFocus();
        String heading[]={"Sl.No.","Category Name"};
        dtm=new DefaultTableModel(heading,0);
        javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
        jTable1.setModel(dtm);
        javax.swing.table.TableColumn column;
        column=jTable1.getColumn("Sl.No.");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(5);
        column=jTable1.getColumn("Category Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(350);
         Connection con;
         Statement st;
       try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
            st=con.createStatement();
            ResultSet res= st.executeQuery("Select * from cat_master");
           while(res.next()==true)
           {            
            val[0]=res.getString(1);
            val[1]=res.getString(2);
            dtm.addRow(val);
           }
           res.close();
           st.close();
           con.close();
          }catch(Exception ex){ System.out.println("error"+ex); }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 51));
        setClosable(true);
        setIconifiable(true);
        setTitle("Item Category");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Enter Category Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 40, 140, 28);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(230, 40, 141, 24);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/savefile.gif"))); // NOI18N
        jButton1.setText("Save");
        jButton1.setToolTipText("save the data ");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 100, 90, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Close1.gif"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setToolTipText("close ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(240, 100, 100, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(51, 51, 255), null, null));
        jTable1.setForeground(new java.awt.Color(0, 0, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 102, 204));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(2, 170, 488, 250);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Existing Categories ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 140, 130, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pl1014066-light_color_commercial_vinyl_wallpaper_for_waiting_room_library.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 500, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -3, 500, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        count=dtm.getRowCount();
        count+=1;
        Connection con;
        Statement st;
       try {

           Class.forName("com.mysql.jdbc.Driver").newInstance();
            con=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
            st=con.createStatement();
            st.executeUpdate("insert into cat_master (cat_cd,cat_nm)values('"+count+"','"+jTextField1.getText().toUpperCase()+"')");
            jTextField1.setText("");
            dtm.setRowCount(0);
            ResultSet res= st.executeQuery("Select * from cat_master");

           while(res.next()==true)
           {
            val[0]=res.getString(1);
            val[1]=res.getString(2);
            dtm.addRow(val);
           }
            res.close();
            st.close();
            con.close();
           //System.out.println(count);
           }catch(Exception ex)
                {
                     javax.swing.JOptionPane.showMessageDialog(null, "item category  '"+jTextField1.getText()+"'  existed in database","Error..",JOptionPane.ERROR_MESSAGE);
                     jTextField1.requestFocus();
                     jTextField1.selectAll();
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
     String ch="";
        if(evt.getKeyCode()==evt.VK_ENTER)
     {
         if(ch.equals(jTextField1.getText())==true)
         {
             javax.swing.JOptionPane.showMessageDialog(null, "please enter item catagory name ","Error..",JOptionPane.ERROR_MESSAGE);
         }
 else
         jButton1.requestFocus();
        }

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER)
        {
            count=dtm.getRowCount();
            count+=1;
            Connection con;
            Statement st;
            try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
            st=con.createStatement();
            st.executeUpdate("insert into cat_master (cat_cd,cat_nm)values('"+count+"','"+jTextField1.getText().toUpperCase()+"')");
            jTextField1.setText("");
            dtm.setRowCount(0);
            ResultSet res= st.executeQuery("Select * from cat_master");
           while(res.next()==true)
           {
            val[0]=res.getString(1);
            val[1]=res.getString(2);
            dtm.addRow(val);
           }
           res.close();
           st.close();
           con.close();
           //System.out.println(count);
           }catch(Exception ex)
           {
               javax.swing.JOptionPane.showMessageDialog(null, "item category  '"+jTextField1.getText()+"'  existed in database","Error..",JOptionPane.ERROR_MESSAGE);}
               jTextField1.requestFocus();
               jTextField1.selectAll();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
  private DefaultTableModel dtm;
  int count;
  private String val[]=new String[2];
}
