/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * purcase_ms.java
 *
 * Created on May 13, 2014, 5:03:14 PM
 */
package giftcorner;
import java.math.BigInteger;
import java.sql.*;
import java.text.SimpleDateFormat;
/**
 *
 * @author user3
 */
public class purcase_ms extends javax.swing.JInternalFrame {
    /** Creates new form purchase_ms */
    public purcase_ms() {
        initComponents();
        SimpleDateFormat date=new SimpleDateFormat("dd-MM-yyyy");
        jXDatePicker1.setFormats(date);
        jXDatePicker2.setFormats(date);
        jXDatePicker1.setDate(new java.util.Date());
        jXDatePicker2.setDate(new java.util.Date());
        jXDatePicker1.setEditable(false);
        jXDatePicker2.setEditable(false);
        String head[]={"Sl.No.","Date","Bill No","Bill Ammount"};
        dtm=new javax.swing.table.DefaultTableModel(head,0);
        jTable1.setModel(dtm);
        jComboBox1.addItem("All");
        jComboBox2.addItem("All");
        try{
            Connection con;
            Statement st,st1;
            ResultSet res,res1;
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
            st=con.createStatement();
            res=st.executeQuery("select ac_nm from ac_details");
            while(res.next()==true)
            {
                jComboBox1.addItem(res.getString("ac_nm"));
                }
            st1=con.createStatement();
            res1=st1.executeQuery("select item_nm from item_mstr");
            while(res1.next()==true)
            {
                jComboBox2.addItem(res1.getString("item_nm"));
                }

        }catch(Exception e){System.out.print(e);}
        jLabel3.setVisible(false);
        jComboBox2.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Purchase Report");

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 80, 40, 20);

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });
        jPanel1.add(jXDatePicker1);
        jXDatePicker1.setBounds(140, 80, 110, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Party ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 80, 20);

        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(120, 20, 130, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Name ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 20, 70, 20);

        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(390, 20, 130, 20);

        jCheckBox1.setBackground(new java.awt.Color(51, 102, 0));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("From ");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(70, 80, 57, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(320, 80, 30, 20);
        jPanel1.add(jXDatePicker2);
        jXDatePicker2.setBounds(360, 80, 114, 22);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 140, 690, 10);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 10, 80, 30);

        jButton2.setText("Print ");
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 50, 80, 30);

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(590, 90, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 180, 690, 300);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Show Documents ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 170, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Ammount :-");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 500, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(590, 500, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        //SimpleDateFormat date=new SimpleDateFormat("dd-MM-yyyy");
      if(jCheckBox1.isSelected()==true)
        {
            jXDatePicker1.setEditable(true);
            jXDatePicker2.setEditable(true);
            }
            else{
                    jXDatePicker1.setEditable(false);
                    jXDatePicker2.setEditable(false);
                    }
       
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                  int date=jXDatePicker1.getDate().getDate();
                  int month=01+jXDatePicker1.getDate().getMonth();
                  int year=1900+jXDatePicker1.getDate().getYear();
                  String datef=""+year+"-"+month+"-"+date;

                  int date1=jXDatePicker2.getDate().getDate();
                  int month1=01+jXDatePicker2.getDate().getMonth();
                  int year1=1900+jXDatePicker2.getDate().getYear();
                  String datef1=""+year1+"-"+month1+"-"+date1;
                  String item=""+jComboBox1.getSelectedItem();
                  int row=dtm.getRowCount();
                  String deta[]=new String[4];
        try{
            Connection con;
            Statement st;
            ResultSet res;
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
            st=con.createStatement();
            if(item.equals("All")==true){
            res=st.executeQuery("select pur_date,pur_bill_no,put_total from pur_detail where pur_date between '"+datef+"' and '"+datef1+"'");
            while(res.next()==true)
            {
                deta[0]=""+(row+1);
                deta[1]=res.getString("pur_date");
                deta[2]=""+res.getInt("pur_bill_no");
                deta[3]=""+res.getDouble("put_total");
                dtm.addRow(deta);
                }
                    total();
            }
 else
    {
                

        }
        }catch(Exception e){System.out.println(e);}
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    // End of variables declaration//GEN-END:variables
    private javax.swing.table.DefaultTableModel dtm;
    private java.math.BigDecimal bd;
    private void total()
    {
        double to=0,to1;
        int row=dtm.getRowCount();
        for(int i=0;i<row;i++)
        {
            to1=Double.valueOf(""+jTable1.getValueAt(i, 3));
            to=to+to1;
            }
            bd=new java.math.BigDecimal(to);
            jLabel7.setText(""+bd.setScale(2,5));
        }
}
