/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * stock_report.java
 *
 * Created on Apr 29, 2014, 5:13:31 PM
 */

package giftcorner;

import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.ButtonGroup;

/**
 *
 * @author user3
 */
public class stock_report extends javax.swing.JInternalFrame {

    /** Creates new form stock_report */
    public stock_report() {
        initComponents();
        SimpleDateFormat df=new SimpleDateFormat("dd-MM-yyyy");
        jXDatePicker1.setFormats(df);
        jXDatePicker1.setDate(new java.util.Date());
        ButtonGroup bg1=new ButtonGroup();
        bg1.add(jRadioButton1);
        bg1.add(jRadioButton2);
        bg1.add(jRadioButton3);
        jRadioButton1.setSelected(true);
        String th[]={"Item Category","Item Name","Item Quantity","Batch No"};        
        dtm=new javax.swing.table.DefaultTableModel(th,0);
        javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        jTable1.setModel(dtm);
        javax.swing.table.TableColumn column;
        column=jTable1.getColumn("Item Category");
        column.setCellRenderer(CRCenter);
        column=jTable1.getColumn("Item Name");
        column.setCellRenderer(CRCenter);
        column=jTable1.getColumn("Item Quantity");
        column.setCellRenderer(CRRight);
        column=jTable1.getColumn("Batch No");
        column.setCellRenderer(CRCenter);
        Connection con;
        Statement st,st2;
        ResultSet res,res2;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
            st=con.createStatement();
            //st2=con.createStatement();
            res=st.executeQuery("select cat_nm from cat_master");
            while(res.next()==true)
            {
                jComboBox1.addItem(res.getString("cat_nm"));
                }
                /*res2=st2.executeQuery("select item_nm from item_mstr");
                while(res2.next()==true)
                    {
                        jComboBox2.addItem(res2.getString("item_nm"));
                        }*/
                 }catch(Exception ex){System.out.println("error in combo 1 "+ex);}
        }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Stock Report ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));
        jPanel1.setLayout(null);

        jLabel1.setText("Select Category ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 30, 100, 20);

        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(310, 30, 130, 20);

        jLabel2.setText("Select Item Name  ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 30, 110, 20);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(590, 30, 140, 20);

        jRadioButton1.setBackground(new java.awt.Color(153, 255, 51));
        jRadioButton1.setText("All");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(60, 90, 50, 23);

        jRadioButton2.setBackground(new java.awt.Color(153, 255, 51));
        jRadioButton2.setText("Only '0' Quantity ");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(140, 90, 120, 23);

        jRadioButton3.setBackground(new java.awt.Color(153, 255, 51));
        jRadioButton3.setText("Ignore '0' Quantity ");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(270, 90, 130, 23);

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue button.png"))); // NOI18N
        jButton1.setText("Show ");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue button2.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue button1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 80, 110, 40);

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/green button.png"))); // NOI18N
        jButton2.setText("print");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/green button2.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/green button1.png"))); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(610, 80, 110, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 140, 770, 10);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 750, 340);

        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Stock Report ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 144, 90, 20);

        jXDatePicker1.setEditable(false);
        jPanel1.add(jXDatePicker1);
        jXDatePicker1.setBounds(70, 30, 112, 22);

        jLabel4.setText("Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 30, 40, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String cat=""+jComboBox1.getSelectedItem();
        Connection con;
        Statement st,st2,st3;
        ResultSet res,res2,res3;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
            st=con.createStatement();
            if(cat.equals("ALL")==true)
            {
                 st=con.createStatement();
                 res=st.executeQuery("select item_nm from item_mstr");
                 while(res.next()==true)
                    {
                        jComboBox2.addItem(res.getString("item_nm"));
                        }
                 }
        else{
                jComboBox2.removeAllItems();
                st2=con.createStatement();
                st3=con.createStatement();
                res2=st2.executeQuery("select cat_cd from cat_master where cat_nm='"+cat+"'");
                if(res2.next()==true)
                {
                res3=st3.executeQuery("select item_nm from item_mstr where cat_cd="+res2.getInt("cat_cd")+"");
                
                while(res3.next()==true)
                    {
                        jComboBox2.addItem(res3.getString("item_nm"));
                        }
                }
                }
                 }catch(Exception ex){System.out.println("error in combo 2 "+ex);}
            
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   // TODO add your handling code here:
        dtm.setRowCount(0);
        int t=0;
        String itemnm=""+jComboBox2.getSelectedItem();
        String data[]=new String[4];
        Connection con;
        Statement st,st2,st3,st4,st5,st6;
        ResultSet res,res2,res3,res4,res5,res6;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/GiftCorner?user=GiftCorner&password=corner");
            st=con.createStatement();
                st2=con.createStatement();
                res=st.executeQuery("select item_cd from item_mstr where item_nm='"+itemnm+"'");
                if(res.next()==true)
                {       if(jRadioButton3.isSelected()==true)
                       {
                        res2=st2.executeQuery("select item_qty,batch_no from item_stock where item_cd="+res.getInt("item_cd"));
                        while(res2.next()==true)
                        {
                            data[0]=""+jComboBox1.getSelectedItem();
                            data[1]=itemnm;
                            data[2]=""+res2.getDouble("item_qty");
                            data[3]=res2.getString("batch_no");
                            dtm.addRow(data);
                        }
                  }
                    else{
                         if(jRadioButton2.isSelected()==true)
                             {
                            //System.out.println("Line 2545");
                            res2=st2.executeQuery("select item_qty,batch_no from item_stock where item_cd="+res.getInt("item_cd")+" and item_qty="+t+"");
                            while(res2.next()==true)
                                {
                                    data[0]=""+jComboBox1.getSelectedItem();
                                    data[1]=itemnm;
                                    data[2]=""+res2.getDouble("item_qty");
                                    data[3]=res2.getString("batch_no");
                                    dtm.addRow(data);
                                 }
                            }
                            else{
                                   if(jRadioButton1.isSelected()==true)
                                     {
                                        //int m=1;
                                        st3=con.createStatement();
                                        st4=con.createStatement();
                                        st5=con.createStatement();
                                        st6=con.createStatement();
                                        res3=st3.executeQuery("select * from item_stock");
                                        while(res3.next()==true)
                                        {                       
                                            res4=st4.executeQuery("select cat_cd,item_nm from item_mstr where item_cd="+res3.getInt("item_cd")+"");
                                            //"select cat_nm,item_nm,item_qty,batch_no from item_mstr,cat_master,item_stock where item_cd="+res3.getInt("item_cd"));
                                            if(res4.next()==true)
                                            {                            
                                                res5=st5.executeQuery("select cat_nm from cat_master where cat_cd="+res4.getInt("cat_cd")+"");
                                                if(res5.next()==true)
                                                    {
                                                        res6=st6.executeQuery("select item_qty,batch_no from item_stock where item_cd="+res3.getInt("item_cd")+" and batch_no='"+res3.getString("batch_no")+"'");
                                                        if(res6.next()==true)
                                                            {                                
                                                                data[0]=res5.getString("cat_nm");
                                                                data[1]=res4.getString("item_nm");
                                                                data[2]=""+res6.getDouble("item_qty");
                                                                data[3]=res6.getString("batch_no");
                                                                dtm.addRow(data);
                                                                }
                                                            }
                                                    }
                                            }
                                        }         
                                    }
                            }
                 }              
                }catch(Exception ex){System.out.println("error in combo 2 "+ex);}
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
    javax.swing.table.DefaultTableModel dtm;
}
