/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReceivedCashReport.java
 *
 * Created on May 11, 2012, 4:49:12 PM
 */

package railwaycashoffice;

import java.math.BigInteger;
import java.util.Vector;

/**
 *
 * @author Shweta
 */
public class SalaryReport extends javax.swing.JInternalFrame {
String month[]=null;
javax.swing.JDesktopPane dpp;
    /** Creates new form ReceivedCashReport */
    public SalaryReport(javax.swing.JDesktopPane dp) {
        initComponents();
        loadInitialInfo();
        dpp=dp;
        String monthList[]={"April","May","June","July","August","September","October","November","December","January","February","March"};
        month=monthList;
        
        for(int i=0;i<monthList.length;i++)
            jComboBox2.addItem(monthList[i]);
        jProgressBar1.setVisible(false);
        //jLabel4.setText("");
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);

        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter=new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        String head[]={"Sr.No.","Salary Date","PF No.","Employee Name","Gross Salary","Deductions","Net Salary"};
        dtm=new javax.swing.table.DefaultTableModel(head,0);
        jTable1.setModel(dtm);

        javax.swing.table.TableColumn column;

        column=jTable1.getColumn("Sr.No.");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(80);
        column=jTable1.getColumn("Salary Date");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("PF No.");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Employee Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(150);
        column=jTable1.getColumn("Gross Salary");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(120);
        column=jTable1.getColumn("Deductions");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(120);
        column=jTable1.getColumn("Net Salary");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(120);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(164, 187, 201));
        setClosable(true);
        setIconifiable(true);
        setTitle("Received Cash Report");
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Select Employee P.F. No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 170, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setToolTipText("Please select P.F. No.");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(180, 60, 170, 25);

        jPanel1.setBackground(new java.awt.Color(196, 167, 143));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 720, 320);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(20, 340, 720, 10);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(51, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("0.00");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(590, 360, 150, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Net Salary");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 360, 70, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("Total Deductions");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 360, 110, 30);

        jLabel10.setBackground(new java.awt.Color(204, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("0.00");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 360, 150, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setText("Gross Salary");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 360, 80, 30);

        jLabel12.setBackground(new java.awt.Color(204, 255, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("0.00");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(90, 360, 150, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 100, 760, 390);

        jButton2.setMnemonic('S');
        jButton2.setText("Show");
        jButton2.setToolTipText("Show Record");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton2FocusLost(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 60, 260, 30);

        jButton3.setMnemonic('C');
        jButton3.setText("Close");
        jButton3.setToolTipText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton3FocusLost(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(640, 20, 130, 70);

        jButton4.setMnemonic('P');
        jButton4.setText("Print");
        jButton4.setToolTipText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(510, 60, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("From");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 20, 120, 25);

        jComboBox2.setToolTipText("Please select P.F. No.");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox2FocusLost(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(150, 20, 170, 25);

        jComboBox3.setToolTipText("Please select P.F. No.");
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jComboBox3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox3FocusLost(evt);
            }
        });
        jComboBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox3KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(460, 20, 170, 25);

        jLabel8.setBackground(new java.awt.Color(255, 204, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("To");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 20, 120, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SDT=new setDataInTable();
        SDT.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        /*if(jTable1.getRowCount()>0)
        {
            printDataNew PD=new printDataNew();
        }*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            SDT=new setDataInTable();
            SDT.start();
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        /*if(evt.getKeyCode()==10)
        {
            if(jTable1.getRowCount()>0)
        {
            printDataNew PD=new printDataNew();
        }
        }*/
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
            this.dispose();
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:

}//GEN-LAST:event_jButton1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

}//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        int ind=jComboBox2.getSelectedIndex();
        jComboBox3.removeAllItems();
        for(;ind<month.length;ind++)
            jComboBox3.addItem(month[ind]);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        System.out.println("aaa....");
        if(evt.getClickCount()==1)
        {
            System.out.println("1.....");
            int row=jTable1.getSelectedRow();
            if(row>=0)
            {
                System.out.println("1.....2");
                String temp[]=(""+jTable1.getValueAt(row,1)).split("-");
                String salaryDate=temp[2]+"-"+temp[1]+"-"+temp[0];
                String pfNo=""+jTable1.getValueAt(row,2);
                SalaryWindow MNF=new SalaryWindow(pfNo,salaryDate);
                dpp.add(MNF);
                MNF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                MNF.setBounds(250,30, 900, 520);
                MNF.show();
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void jComboBox2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox2FocusGained
        // TODO add your handling code here:
        jComboBox2.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_jComboBox2FocusGained

    private void jComboBox2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox2FocusLost
        // TODO add your handling code here:
        jComboBox2.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_jComboBox2FocusLost

    private void jComboBox3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox3FocusGained
        // TODO add your handling code here:
        jComboBox3.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_jComboBox3FocusGained

    private void jComboBox3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox3FocusLost
        // TODO add your handling code here:
        jComboBox3.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_jComboBox3FocusLost

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        // TODO add your handling code here:
        jComboBox1.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        // TODO add your handling code here:
         jComboBox1.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
        // TODO add your handling code here:
         jButton2.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_jButton2FocusGained

    private void jButton2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusLost
        // TODO add your handling code here:
        jButton2.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_jButton2FocusLost

    private void jButton3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusGained
        // TODO add your handling code here:
        jButton3.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_jButton3FocusGained

    private void jButton3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusLost
        // TODO add your handling code here:
        jButton3.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_jButton3FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
javax.swing.table.DefaultTableModel dtm;
setDataInTable SDT;
private void loadInitialInfo()
{
    try
    {
        interfaceRailway inf=null;
		try
		{
			inf=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					inf=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);

				}
		}
        String qry="Select distinct(pfNo) from salaryinfo order by pfNo";
        String load[]=inf.getResultSetAs_1D_Array(qry, Main.year);
        if(load!=null)
        {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("All");
            for(int i=0;i<load.length;i++)
            {
                jComboBox1.addItem(load[i]);
            }
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method."+e);
    }

}
class setDataInTable extends Thread
{
    String qry="";
    public void run()
    {
         dtm.setRowCount(0);
         jLabel12.setText("0.00");
         jLabel10.setText("0.00");
         jLabel4.setText("0.00");
         try
         {

               interfaceRailway inf=null;
		try
		{
			inf=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					inf=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);

				}
		}
               String year="20"+Main.year.substring(0,2);;
               String mon=""+jComboBox2.getSelectedItem();
                if((mon.equalsIgnoreCase("January"))||(mon.equalsIgnoreCase("February"))||(mon.equalsIgnoreCase("March")))
                year="20"+Main.year.substring(2,4);

                String setDate1=year+"-"+getNumericMonth(""+jComboBox2.getSelectedItem())+"-"+"01";
                year="20"+Main.year.substring(0,2);;
                mon=""+jComboBox3.getSelectedItem();
                if((mon.equalsIgnoreCase("January"))||(mon.equalsIgnoreCase("February"))||(mon.equalsIgnoreCase("March")))
                year="20"+Main.year.substring(2,4);
                String setDate2=year+"-"+getNumericMonth(""+jComboBox3.getSelectedItem())+"-"+"01";
                String qry;

                if(jComboBox1.getSelectedIndex()!=0)
                    qry="select salaryDate,pfNo,empName,grossPay,totalDeduction,netPay from salaryinfo where pfNo='"+""+jComboBox1.getSelectedItem()+"' and salaryDate between '"+setDate1+"' and '"+setDate2+"'";
                else
                    qry="select salaryDate,pfNo,empName,grossPay,totalDeduction,netPay from salaryinfo where salaryDate between '"+setDate1+"' and '"+setDate2+"'";
                String load[][]=inf.getInformationDD(qry,6,Main.year);
                double totalGrossSalary=0.00,totalDeduction=0.00,totalNetSalary=0.00;
                if(load!=null)
                {
                    jProgressBar1.setVisible(true);
                    jProgressBar1.setMaximum(load.length);
                    jProgressBar1.setMinimum(0);
                    jProgressBar1.setValue(0);
                    String arr[]=new String[7];
                    int ind=0;
                    String str=" ";
                    for(int i=0;i<load.length;i++)
                    {
                        arr[0]=""+(++ind)+".";
                        
                        String dt[]=load[i][0].split("-");
                        arr[1]=dt[2]+"-"+dt[1]+"-"+dt[0];
                        arr[2]=load[i][1];
                        arr[3]=load[i][2];
                        arr[4]=(""+new java.math.BigDecimal(load[i][3]).setScale(2,5));
                        arr[5]=(""+new java.math.BigDecimal(load[i][4]).setScale(2,5));
                        arr[6]=(""+new java.math.BigDecimal(load[i][5]).setScale(2,5));
                        totalGrossSalary+=Double.valueOf(arr[4]);
                        totalDeduction+=Double.valueOf(arr[5]);
                        totalNetSalary+=Double.valueOf(arr[6]);
                        dtm.addRow(arr);

                        jProgressBar1.setValue(i+1);
                    }
                    jLabel12.setText(""+new java.math.BigDecimal(totalGrossSalary).setScale(2,5));
                    jLabel10.setText(""+new java.math.BigDecimal(totalDeduction).setScale(2,5));
                    jLabel4.setText(""+new java.math.BigDecimal(totalNetSalary).setScale(2,5));
                }
                if(dtm.getRowCount()<=0)
                        javax.swing.JOptionPane.showMessageDialog(null,"No record found.");


         }
         catch(Exception e)
         {
             System.out.println("Error ! In setDataInTable Class."+e);
         }






    }
    private String getNumericMonth(String mon)
    {
        if(mon.equalsIgnoreCase("January"))
            return "01";
        else if(mon.equalsIgnoreCase("February"))
            return "02";
        else if(mon.equalsIgnoreCase("March"))
            return "03";
        else if(mon.equalsIgnoreCase("April"))
            return "04";
        else if(mon.equalsIgnoreCase("May"))
            return "05";
        else if(mon.equalsIgnoreCase("June"))
            return "06";
        else if(mon.equalsIgnoreCase("July"))
            return "07";
        else if(mon.equalsIgnoreCase("August"))
            return "08";
        else if(mon.equalsIgnoreCase("September"))
            return "09";
        else if(mon.equalsIgnoreCase("October"))
            return "10";
        else if(mon.equalsIgnoreCase("November"))
            return "11";
        else if(mon.equalsIgnoreCase("December"))
            return "12";
        else
            return null;
    }

}
  /*     public class printDataNew {

        java.io.PrintWriter pw;

        public printDataNew() {


            try {
                String space = "";
                String temp = "";
                int rep = 0;
                int row = 0, maxrows = 68;
                java.io.FileOutputStream fos1 = null;
                try {
                    //fos=new java.io.FileOutputStream("LPT1");
                    fos1 = new java.io.FileOutputStream("LPT1");//LPT1");
                    System.out.println("inside find port...LPT1");

                } catch (Exception ex) {
                    System.out.println("port not found...");
                    fos1=new java.io.FileOutputStream("System1.in");//LPT1");

                }
                pw = new java.io.PrintWriter(fos1);
                row++;
                pw.println();
                row++;
                pw.println();
                row++;
                pw.println();
                row++;
                String str4 = "EASTERN RAILWAYS EMPLOYEE SALARY REPORT";
                for(int i=0;i<55;space+=" ",i++);
                pw.println(space+str4);
                row++;
                pw.println(space+"-------------------------------------");

                row++;
                pw.println();
                row++;
                space="";
                for(int i=0;i<10;space+=" ",i++);
                String st="From  "+jLabel2.getText()+"  To  "+jLabel8.getText();
                pw.println(space+st);
                row++;
                space="";
                for(int i=0;i<10;space+=" ",i++);
                java.util.Date dt=new java.util.Date();
                st="Date : "+dt.getDate()+(dt.getMonth()+1)+(dt.getYear()+1900);
                if(jComboBox1.getSelectedIndex()!=0)
                {
                    st+="       P.F. No."+""+jComboBox1.getSelectedItem();
                }
                pw.println(space+st);
                row++;
                pw.println();
                row++;
                pw.println("	  --------------------------------------------------------------------------------------------------------------");
                row++;
                pw.println("	  SR.No		Cashier No.                 Recieved Amount			Signature");
                row++;
               pw.println("	  --------------------------------------------------------------------------------------------------------------");
               row++;
               String six="	  ";
          //  for(int n=0;n<70;n++)
            // {
               for(int i=0;i<dtm.getRowCount();i++)
               {

                   pw.print(six+""+jTable1.getValueAt(i,0)+".");
                   String st1=""+jTable1.getValueAt(i,0);

                   int len1=st1.length();
                   String st2=""+jTable1.getValueAt(i,1);
                   int len2=st2.length();
                   space="";

                   for(int k=0;k<20-len1-len2;space+=" ",k++);
                   pw.print(space+jTable1.getValueAt(i,1));

                   String st3=""+jTable1.getValueAt(i,2);
                   int len3=st3.length();
                   space="";
                   for(int k=0;k<35-len3;space+=" ",k++);
                   pw.println(space+jTable1.getValueAt(i,2));

                   len1=0;
                   len2=0;
                   len3=0;

                   row++;
                   if(row%68==0)
                   {
                       for(int m=0;m<6;m++)
                       {
                           pw.println();
                           row++;
                       }


                        pw.println("	  --------------------------------------------------------------------------------------------------------------");
                        row++;
                        pw.println("	  SR.No		Cashier No.                 Recieved Amount			Signature");
                        row++;
                        pw.println("	  --------------------------------------------------------------------------------------------------------------");

                   }
              // }


            }
                pw.println("	  --------------------------------------------------------------------------------------------------------------");
                       row++;
                       pw.println();
                        row++;

                         String total="Total Amount   =  "+jLabel4.getText();
                        int len4=total.length();
                        space="";
                        for(int ii=0;ii<81-len4;space+=" ",ii++);
                        pw.println(space+total);
                        row++;
                        scroll(maxrows-row);

                pw.close();
                fos1.close();


            }
            catch(Exception ex)
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Exception In Printing "+ex);
            }

}
        public void scroll()
     	{
            for(int i=1;i<=6;i++)
            {
                pw.println();
            }
            System.out.println("inside unparameterised..scroll.............");
        }
        public void scroll(int n)
        {
            for(int i=1;i<=n;i++)
            {
                pw.println();
            }
       }

    }
*/
}
