/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DistributionReport.java
 *
 * Created on May 8, 2012, 3:51:04 PM
 */

package railwaycashoffice;

import java.math.BigInteger;

/**
 *
 * @author pratiksha
 */
public class DistributionReport extends javax.swing.JInternalFrame {

    /** Creates new form DistributionReport */
    public DistributionReport() {
        initComponents();
        jButton1.requestFocus();
        java.util.Date dt=new java.util.Date();
        int date=dt.getDate();
        int month=dt.getMonth()+1;
        int year=dt.getYear()+1900;
        String setDate=date+"-"+month+"-"+year;
        jLabel1.setText(setDate);
        jLabel2.setText(setDate);
        jLabel6.setText("0");
        jProgressBar1.setVisible(false);
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);

        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter=new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        String head[]={"Sr.No.","Date","Cashier No.","PMR No.","CO7","CO6","Party Name","Amount Type","Amount"};
        dtm=new javax.swing.table.DefaultTableModel(head,0);
        jTable1.setModel(dtm);
        javax.swing.table.TableColumn column;

        column=jTable1.getColumn("Sr.No.");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(60);
        column=jTable1.getColumn("Date");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(80);
        column=jTable1.getColumn("Cashier No.");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(60);
        column=jTable1.getColumn("PMR No.");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(60);
        column=jTable1.getColumn("CO7");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(60);
        column=jTable1.getColumn("CO6");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(60);
         column=jTable1.getColumn("Party Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(120);
        column=jTable1.getColumn("Amount Type");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(90);
        column=jTable1.getColumn("Amount");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(80);

        loadInitialInfo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(150, 178, 194));
        setClosable(true);
        setIconifiable(true);
        setTitle("Distribution Report");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sr.No.", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 710, 300);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(20, 320, 710, 10);

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("jLabel6");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(530, 340, 200, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Total Amount In Rs.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(390, 340, 140, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 110, 750, 360);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railwaycashoffice/images/calendar.png"))); // NOI18N
        jButton1.setToolTipText("Select starting date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 20, 30, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Select Department");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 120, 25);

        jComboBox1.setToolTipText("Please select department");
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 60, 340, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Cashier Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 20, 100, 25);

        jComboBox2.setToolTipText("Please select cashier number");
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(590, 20, 180, 25);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("From");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 20, 40, 20);

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("To");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 20, 30, 20);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railwaycashoffice/images/calendar.png"))); // NOI18N
        jButton4.setToolTipText("Select last date");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(450, 20, 30, 25);

        jButton2.setMnemonic('C');
        jButton2.setText("Close");
        jButton2.setToolTipText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 480, 360, 30);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 20, 160, 20);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 20, 160, 20);

        jButton3.setMnemonic('S');
        jButton3.setText("Show");
        jButton3.setToolTipText("Show Record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(490, 60, 280, 30);

        jButton5.setMnemonic('P');
        jButton5.setText("Print");
        jButton5.setToolTipText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 480, 360, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Cal calender=new Cal();
        String date1=calender.getdate();
        jLabel2.setText(date1);


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Cal calender=new Cal();
        String date1=calender.getdate();
        jLabel1.setText(date1);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

       SDT=new setDataInTable();
        SDT.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getRowCount()>0)
        {
            printDataNew PD=new printDataNew();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            Cal date1=new Cal();
        jLabel1.setText(date1.getdate());
        jButton4.requestFocus();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            Cal date1=new Cal();
        jLabel2.setText(date1.getdate());
        jComboBox2.requestFocus();
        }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
            jComboBox1.requestFocus();
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
            jButton3.requestFocus();
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            SDT=new setDataInTable();
        SDT.start();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        if(jTable1.getRowCount()>0)
        {
            printDataNew PD=new printDataNew();
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
            this.dispose();
    }//GEN-LAST:event_jButton2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    javax.swing.table.DefaultTableModel dtm;
     setDataInTable SDT;//=new setDataInTable();
    private void loadInitialInfo()
    {
        try
        {
           // interfaceRailway object1=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
            interfaceRailway object1=null;
		try
		{
			object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
				}
		}
            String qry="Select dp_name from department_detail order by dp_code";
            String load[]=object1.getResultSetAs_1D_Array(qry,Main.year);
            if(load!=null)
            {
                for(int i=0;i<load.length;i++)
                {
                    jComboBox1.addItem(load[i]);
                }
            }

            qry="Select cashier_number from cashier_detail order by cashier_number";
            load=object1.getResultSetAs_1D_Array(qry,Main.year);
            if(load!=null)
            {
                jComboBox2.addItem("All");
                for(int i=0;i<load.length;i++)
                {
                    jComboBox2.addItem(load[i]);
                }
            }

        }
        catch(Exception e)
        {
            System.out.println("Error ! In loadInitialInfo Method."+e);
        }
    }

   class setDataInTable extends Thread
    {
       String qry="";
       public void run()
       {
           dtm.setRowCount(0);
           jLabel6.setText("0.00");
            try
            {

                //interfaceRailway object1=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
                interfaceRailway object1=null;
		try
		{
			object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
				}
		}
                qry="Select dp_code from department_detail where dp_name='"+jComboBox1.getSelectedItem()+"'";
                String getDpCode=object1.getSigetngleValue(qry,Main.year);
                String getStr[]=jLabel1.getText().split("-");
                String setDate1=getStr[2]+"-"+getStr[1]+"-"+getStr[0];
                String getStr1[]=jLabel2.getText().split("-");
                String setDate2=getStr1[2]+"-"+getStr1[1]+"-"+getStr1[0];
                double tot=0.0;
                if(!jComboBox2.getSelectedItem().equals("All"))
                {
                    qry="Select cashier_code from cashier_detail where cashier_number="+Integer.parseInt(""+jComboBox2.getSelectedItem())+"";
                    String getCashierCode=object1.getSigetngleValue(qry,Main.year);
                    qry="Select edate,pmrno,CO7,CO6,partyname,amounttype,mix_amount from build_distribution where dp_code="+Integer.parseInt(getDpCode)+" and cashier_code="+Integer.parseInt(getCashierCode)+" and (edate>='"+setDate1+"' and edate<='"+setDate2+"') order by bill_Code";
                    String load[][]=object1.getInformationDD(qry,7,Main.year);

                    if(load.length>0)
                    {
                        jProgressBar1.setVisible(true);
                        jProgressBar1.setMaximum(load.length);
                        jProgressBar1.setMinimum(0);
                        jProgressBar1.setValue(0);
                        String arr[]=new String[9];
                        int ind=0;
                        for(int i=0;i<load.length;i++)
                        {
                            arr[0]=""+(++ind);
                            getStr=load[i][0].split("-");
                            setDate1=getStr[2]+"-"+getStr[1]+"-"+getStr[0];
                            arr[1]=setDate1;
                            //arr[2]=load[i][1];
                            arr[2]=""+jComboBox2.getSelectedItem();
                            arr[3]=load[i][1];
                            arr[4]=load[i][2];
                            arr[5]=load[i][3];
                            arr[6]=load[i][4];
                            arr[7]=load[i][5];
                            //arr[8]=load[i][6];
                            arr[8]=(""+new java.math.BigDecimal(Double.valueOf(load[i][6])).setScale(2,5));
                           tot=tot+Double.valueOf(load[i][6]);
                            dtm.addRow(arr);
                            jProgressBar1.setValue(i+1);
                        }
                        jLabel6.setText(""+new java.math.BigDecimal(tot).setScale(2,5));
                    }
                    if(dtm.getRowCount()==0)
                    {
                        javax.swing.JOptionPane.showMessageDialog(null,"No record found.");
                    
                    }

                }
                if(jComboBox2.getSelectedItem().equals("All"))
                {
                    qry="Select edate,cashier_code,pmrno,CO7,CO6,partyname,amounttype,mix_amount from build_distribution where dp_code="+Integer.parseInt(getDpCode)+" and (edate>='"+setDate1+"' and edate<='"+setDate2+"')";
                    String load[][]=object1.getInformationDD(qry,8,Main.year);

                    if(load.length>0)
                    {
                        jProgressBar1.setVisible(true);
                        jProgressBar1.setMaximum(load.length);
                        jProgressBar1.setMinimum(0);
                        jProgressBar1.setValue(0);
                        String arr[]=new String[9];
                        int ind=0;
                        for(int i=0;i<load.length;i++)
                        {
                            qry="select cashier_number from cashier_detail where cashier_code="+Integer.parseInt(load[i][1]);
                            String getCashierNo=object1.getSigetngleValue(qry,Main.year);
                            System.out.println("getCashierNo...."+getCashierNo);
                            arr[0]=""+(++ind);
                            getStr=load[i][0].split("-");
                            setDate1=getStr[2]+"-"+getStr[1]+"-"+getStr[0];
                            arr[1]=setDate1;
                            //arr[2]=load[i][1];
                            arr[2]=getCashierNo;
                            arr[3]=load[i][2];
                            arr[4]=load[i][3];
                            arr[5]=load[i][4];
                            arr[6]=load[i][5];
                            arr[7]=load[i][6];
                           // arr[8]=load[i][7];
                            arr[8]=(""+new java.math.BigDecimal(Double.valueOf(load[i][7])).setScale(2,5));
                              tot=tot+Double.valueOf(load[i][7]);
                            dtm.addRow(arr);
                            jProgressBar1.setValue(i+1);
                        }
                        jLabel6.setText(""+new java.math.BigDecimal(tot).setScale(2,5));
                      }
                    if(dtm.getRowCount()==0)
                    {
                        javax.swing.JOptionPane.showMessageDialog(null,"No record found.");
                     
                    }
                }
               
            }
            catch(Exception e)
            {
                System.out.println("Error ! In setDataInTable Method."+e);
            }
       }
    }


    public class printDataNew {

        java.io.PrintWriter pw;

        public printDataNew() {
            try {
                System.out.println("inside printing...");
                String space = "";
                String temp = "";
                int rep = 0;
                int row = 0, maxrows = 65;
                System.out.println("Start printing");
                java.io.FileOutputStream fos1 = null;
                try {
                    //fos=new java.io.FileOutputStream("LPT1");
                    fos1 = new java.io.FileOutputStream("test1.in");//LPT1");
                    System.out.println("inside find port...LPT1");

                } catch (Exception ex) {
                    System.out.println("port not found.....");
                    //fos=new java.io.FileOutputStream("System1.in");//LPT1");

                }
                pw = new java.io.PrintWriter(fos1);
                row++;
                pw.println();
                row++;


                pw.println("    Dr      ");
                row++;


                pw.println("----------------------------------------------------------------------------------------------------------------");
                row++;
                pw.println("  Pmr No.		CO7 No.		CO6 No.		Cashier No.		Amount	          Toatl Amount");
                row++;
                pw.println("----------------------------------------------------------------------------------------------------------------");
                row++;
                try
                {
                 //interfaceRailway object1=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
                    interfaceRailway object1=null;
		try
		{
			object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
				}
		}


                String str="select distinct(edate) from build_distribution";
                String str2[][]=object1.getInformationDD(str,1,Main.year);
              /*  for(int r=0;r<str2.length;r++)
                {
                    String str31="select distinct(amount) from build_distribution where edate='"+str2[r][0]+"'";
                    String str21[][]=object1.getInformationDD(str31,1,Main.year);

                    javax.swing.JOptionPane.showMes
                }*/


                for(int i=0;i<str2.length;i++)
                {


                    String str3="Select pmrno,CO7,CO6,cashier_code,amount from build_distribution where edate='"+str2[i][0]+"'";
                    String str4[][]=object1.getInformationDD(str3,5,Main.year);

                    pw.println("                                Date           "+str2[i][0]);
                    pw.println();
                    space="";

                    double db=0.0;
                    for(int j=0;j<str4.length;j++)
                    {

                        String qry="Select cashier_number from cashier_detail where cashier_code="+str4[j][3]+"";
                        String str7=object1.getSigetngleValue(qry, Main.year);


                        int len=("  "+str4[j][0]).length();

                        pw.print("  "+str4[j][0]);


                          int len1=("  "+str4[j][1]).length();
                          space="";
                          for(int iii=0;iii<32-len-len1; space+=" ",iii++);
                          pw.print(space+str4[j][1]);

                          int len2=("  "+str4[j][2]).length();
                          space="";
                          for(int iii=0;iii<18-len2; space+=" ",iii++);
                          pw.print(space+str4[j][2]);

                          int len3=("  "+str4[j][3]+str7).length();
                          space="";
                          for(int iii=0;iii<22-len3; space+=" ",iii++);
                          pw.print(space+str4[j][3]+"/"+str7);

                          int len4=("  "+str4[j][4]).length();
                          space="";

                          db=db+Double.valueOf(str4[j][4]);


                          //for(int iii=0;iii<22-len4; space+=" ",iii++);
                          //pw.println(space+str4[j][4]);

                          if(j==str4.length-1)
                          {
                              for(int iii=0;iii<22-len4; space+=" ",iii++);
                              pw.print(space+str4[j][4]);

                              String s=""+db;
                                int len5=s.length();
                              space="";
                              for(int iii=0;iii<22-len5; space+=" ",iii++);
                                pw.println(space+(""+(new java.math.BigDecimal(""+db).setScale(2,java.math.BigDecimal.ROUND_HALF_UP))));

                                len5=0;


                          }
                           else
                          {
                              for(int iii=0;iii<22-len4; space+=" ",iii++);
                              pw.println(space+str4[j][4]);
                           }

                           row++;
                           if(row%65==0)
                           {
                            for(int k=0;k<6;k++)
                            {
                                pw.println();
                                row++;
                            }
                           }



                          len=0;
                          len1=0;
                          len2=0;
                          len3=0;
                          len4=0;

/*

                          len=0;
                          len1=0;


                          /*

 space="";
                          for(int iii=0;iii<10; space+=" ",iii++);
                          pw.print(space+str4[j][1]);
                          space="";
                          for(int iii=0;iii<10; space+=" ",iii++);
                          pw.print(space+str4[j][2]);
                          space="";
                          for(int iii=0;iii<10; space+=" ",iii++);
                          pw.print(space+str4[j][3]);
                          space="";
                          for(int iii=0;iii<10; space+=" ",iii++);
                          pw.print(space+str4[j][4]);
                          space="";*/

                    }
                    pw.println();
                    row++;
                    if(row%56==0)
                        {
                            for(int k=0;k<6;k++)
                            {
                                pw.println();
                                row++;
                            }
                         }

                   // pw.println("----------------------------------------------------------------------------------------------------------------");
                    //row++;
                    /*if(row%56==0)
                        {
                            for(int k=0;k<6;k++)
                            {
                                pw.println();
                            }
                         }
*/
                //    pw.println("                    				Date         "+str2[i][0]);
                      row++;
                    pw.println("----------------------------------------------------------------------------------------------------------------");
                    row++;
                     if(row%65==0)
                        {
                            for(int k=0;k<6;k++)
                            {
                                pw.println();
                                row++;
                            }
                         }


                    pw.println();
                    row++;
                    space="";

                    //

                    }
                }
                catch(Exception ex)
                {
                    javax.swing.JOptionPane.showMessageDialog(null,"Exception "+ex);
                }

                scroll(maxrows-row);
                pw.close();
                fos1.close();
            }
            catch(Exception ex)
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Exception ex"+ex);
            }
        }
        public void scroll(int n)
        {
            for(int i=1;i<=n;i++)
            {
                pw.println();
            }
       }

        }
}
