/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BillPayment.java
 *
 * Created on May 25, 2013, 3:41:52 AM
 */

package telephonebillingsystem;

/**
 *
 * @author user2
 */
public class BillPayment extends javax.swing.JInternalFrame {
public javax.swing.table.DefaultTableModel dtm;
    /** Creates new form BillPayment */
    public BillPayment() {
        initComponents();
        java.util.Date dt=new java.util.Date();
        int date=dt.getDate();
        int month=dt.getMonth()+1;
        int year=dt.getYear()+1900;
        String setDate=date+"-"+month+"-"+year;
        jTextField8.setText(setDate);
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);

        String heading[]={"S.No","Cu Account No","Customer id","Curent Amnt","A/c Balance","Payment Date","Invoice No","Invoice Date","Amount Payable"};
        dtm=new javax.swing.table.DefaultTableModel(heading,0);
        jTable1.setModel(dtm);
        javax.swing.table.TableColumn column;


        column=jTable1.getColumn("S.No");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(40);
        column=jTable1.getColumn("Cu Account No");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(90);
        column=jTable1.getColumn("Customer id");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(70);
        column=jTable1.getColumn("Curent Amnt");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(70);
        column=jTable1.getColumn("Payment Date");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(70);
        column=jTable1.getColumn("A/c Balance");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(70);
        column=jTable1.getColumn("Invoice No");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(60);
        column=jTable1.getColumn("Invoice Date");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(70);
        column=jTable1.getColumn("Amount Payable");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(80);
        load();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(telephonebillingsystem.TelephoneBillingSystemApp.class).getContext().getResourceMap(BillPayment.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jLabel1.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 25);

        jLabel2.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 110, 25);

        jTextField1.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jTextField1.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 10, 130, 25);

        jTextField2.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jTextField2.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 40, 130, 25);

        jLabel3.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 40, 120, 25);

        jLabel4.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 70, 110, 25);

        jTextField3.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jTextField3.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(380, 40, 110, 25);

        jTextField4.setEditable(false);
        jTextField4.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jTextField4.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jTextField4.setText(resourceMap.getString("jTextField4.text")); // NOI18N
        jTextField4.setName("jTextField4"); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(380, 70, 90, 25);

        jButton1.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 70, 20, 25);

        jLabel5.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel5.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 100, 110, 25);

        jTextField5.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jTextField5.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jTextField5.setText(resourceMap.getString("jTextField5.text")); // NOI18N
        jTextField5.setName("jTextField5"); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(120, 100, 130, 25);

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 100, 110, 25);

        jTextField6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jTextField6.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jTextField6.setText(resourceMap.getString("jTextField6.text")); // NOI18N
        jTextField6.setName("jTextField6"); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(380, 100, 110, 25);

        jTextField7.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jTextField7.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jTextField7.setText(resourceMap.getString("jTextField7.text")); // NOI18N
        jTextField7.setName("jTextField7"); // NOI18N
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(120, 70, 130, 25);

        jLabel7.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel7.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 70, 110, 25);

        jLabel8.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel8.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 10, 100, 25);

        jTextField8.setEditable(false);
        jTextField8.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jTextField8.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jTextField8.setText(resourceMap.getString("jTextField8.text")); // NOI18N
        jTextField8.setName("jTextField8"); // NOI18N
        getContentPane().add(jTextField8);
        jTextField8.setBounds(380, 10, 90, 25);

        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 10, 20, 25);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setBackground(resourceMap.getColor("jTable1.background")); // NOI18N
        jTable1.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 185, 480, 320);

        jButton3.setFont(resourceMap.getFont("jButton5.font")); // NOI18N
        jButton3.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jButton3.setIcon(resourceMap.getIcon("jButton3.icon")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 145, 230, 27);

        jButton5.setFont(resourceMap.getFont("jButton5.font")); // NOI18N
        jButton5.setForeground(resourceMap.getColor("jTextField3.foreground")); // NOI18N
        jButton5.setIcon(resourceMap.getIcon("jButton5.icon")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(250, 145, 240, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField2.requestFocus();
            loadini();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField7.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField5.requestFocus();
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Cal c=new Cal();
        jTextField8.setText(c.getdate());
        //set=c.getdate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
             Cal c=new Cal();
            jTextField8.setText(c.getdate());
            jTextField3.requestFocus();
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cal c=new Cal();
            jTextField4.setText(c.getdate());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
             Cal c=new Cal();
            jTextField4.setText(c.getdate());
            jTextField6.requestFocus();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton3.requestFocus();
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            save();
        }
    }//GEN-LAST:event_jButton3KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    private void loadini()
    {
        try
        {
            System.out.println("i am in load ini method");
            String qry="Select Customer_Id from MasterBillCreation where CustomerAccountNo="+Integer.parseInt(jTextField1.getText().trim())+" ";
            String cuid=Utility.getSingleValue(qry);
            System.out.println(cuid);
            jTextField2.setText(cuid);
            qry="Select PreviousAmount from MasterBillCreation where CustomerAccountNo="+Integer.parseInt(jTextField1.getText().trim())+" and status=0 ";
            String pre=Utility.getSingleValue(qry);
            qry="Select UsageCharge from MasterBillCreation where CustomerAccountNo="+Integer.parseInt(jTextField1.getText().trim())+" and status=0 ";
            String usage=Utility.getSingleValue(qry);
            qry="Select Curent_Amount from MasterBillCreation where CustomerAccountNo="+Integer.parseInt(jTextField1.getText().trim())+" and status=0 ";
            String cmt=Utility.getSingleValue(qry);
            jTextField7.setText(cmt);
            double tot=Double.valueOf(pre)+Double.valueOf(usage)+Double.valueOf(cmt);
            jTextField5.setText(""+tot);
            qry="Select Invoice_Date from MasterBillCreation where CustomerAccountNo="+Integer.parseInt(jTextField1.getText().trim())+" and status=0 ";
            String ind=Utility.getSingleValue(qry);
            String D[]=ind.split("-");
            String dd[]=D[2].split(" ");//+"-"+D[1]+"-"+D[0];
            String setDate=dd[0]+"-"+D[1]+"-"+D[0];
            jTextField4.setText(setDate);
            qry="Select Invoice_No from MasterBillCreation where CustomerAccountNo="+Integer.parseInt(jTextField1.getText().trim())+" and status=0 ";
            String ino=Utility.getSingleValue(qry);
            jTextField3.setText(ino);

            

        }
        catch(Exception ae)
        {
            System.out.println("Error in loadini method"+ae);
        }
    }
    private void load()
    {
        try
        {
            String D1[]=jTextField8.getText().split("-");
            String setDate1=D1[0]+"-"+D1[1]+"-"+D1[2];
            System.out.println(setDate1+"    "+jTextField8.getText());

            String qry="Select * from BillPayment ";
            String load[][]=Utility.getInformationDD(qry,8);
            String arr[]=null;
            if(load.length>0)
            {
                arr=new String[9];
                for(int i=0;i<load.length;i++)
                {
                    arr[0]=""+(dtm.getRowCount()+1);
                    arr[1]=load[i][0];
                    arr[2]=load[i][1];
                    arr[3]=load[i][2];
                    arr[4]=load[i][3];
                    String D[]=load[i][4].split("-");
                    String dd[]=D[2].split(" ");//+"-"+D[1]+"-"+D[0];
                    String setDate=dd[0]+"-"+D[1]+"-"+D[0];
                    arr[5]=setDate;
                    arr[6]=load[i][5];
                    D=load[i][6].split("-");
                    dd=D[2].split(" ");//+"-"+D[1]+"-"+D[0];
                    setDate=dd[0]+"-"+D[1]+"-"+D[0];
                    arr[7]=setDate;
                    arr[8]=load[i][7];
                    dtm.addRow(arr);
                }
            }
        }
        catch(Exception ae)
        {
            System.out.println("Error in load method........."+ae);
        }
    }
    public void save()
    {
        try
        {
            dtm.setRowCount(0);
            String D[]=jTextField8.getText().split("-");
            String setDate=D[1]+"-"+D[0]+"-"+D[2];
            String D1[]=jTextField4.getText().split("-");
            String setDate1=D1[1]+"-"+D1[0]+"-"+D1[2];
            String qry="insert into BillPayment values ("+Integer.parseInt(jTextField1.getText().trim())+",'"+(jTextField2.getText().trim())+"',"+Double.valueOf(jTextField7.getText().trim())+","+Double.valueOf(jTextField5.getText().trim())+",#"+setDate+"#,'"+jTextField3.getText().trim()+"',#"+setDate1+"#,"+Double.valueOf(jTextField6.getText().trim())+")";
            System.out.println(qry);
            boolean bn=Utility.saveInformation(qry);
            qry="update MasterBillCreation set status=1 where CustomerAccountNo="+Integer.parseInt(jTextField1.getText())+"";
            boolean bn1=Utility.saveInformation(qry);
            
            if(bn==true && bn1==true)
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Process Completed.....");
                load();
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField1.requestFocus();
            }
        }
        catch(Exception ae)
        {
            System.out.println("Error in save method"+ae);
        }
    }
}
