/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItemMaster.java
 *
 * Created on May 29, 2014, 2:23:42 PM
 */

package p3;

/**
 *
 * @author welcome
 */
public class ItemMaster extends javax.swing.JInternalFrame {
javax.swing.table.DefaultTableModel dtm;
    /** Creates new form ItemMaster */
    public ItemMaster(String uid,String cnm,String fyear) {
        initComponents();
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter=new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);


        String heading[]={"S.No.","Main Group","Sub Group","Item Group","Item Name","Single Unit","Compound Unit","Purchase Unit","Sale Unit","Rate","Rate Unit","Qty","Qty Unit","Current Qty","Current Qty Unit","Pseudo S.No."};
        dtm=new javax.swing.table.DefaultTableModel(heading,0);
        jTable1.setModel(dtm);

        javax.swing.table.TableColumn column;


        column=jTable1.getColumn("S.No.");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(45);
        column=jTable1.getColumn("Main Group");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(80);
        column=jTable1.getColumn("Sub Group");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(80);
        column=jTable1.getColumn("Item Group");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(80);
        column=jTable1.getColumn("Item Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(80);
        column=jTable1.getColumn("Single Unit");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Compound Unit");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(200);
        column=jTable1.getColumn("Purchase Unit");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Rate");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Rate Unit");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Qty");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Qty Unit");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Current Qty");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Current Qty Unit");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Pseudo S.No.");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        loadInitialInfo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Item Creation Window");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true), javax.swing.BorderFactory.createTitledBorder("")));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Select Item Group");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 120, 130, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(160, 120, 230, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(400, 20, 550, 440);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/savefile.gif"))); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(20, 490, 120, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/update.gif"))); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(150, 490, 120, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/dustbeen.gif"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(280, 490, 120, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Close1.gif"))); // NOI18N
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(530, 490, 110, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(160, 20, 230, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Select Main Group");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 120, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jComboBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox3KeyPressed(evt);
            }
        });
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(160, 70, 230, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Select Sub Group");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 70, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Enter Item");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 170, 90, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(160, 170, 230, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(20, 460, 380, 10);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Single Unit");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 220, 120, 30);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jComboBox4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox4KeyPressed(evt);
            }
        });
        jPanel2.add(jComboBox4);
        jComboBox4.setBounds(160, 220, 230, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Compound Unit");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 270, 120, 30);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox5KeyPressed(evt);
            }
        });
        jPanel2.add(jComboBox5);
        jComboBox5.setBounds(160, 270, 230, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel7.setText("Default unit apply at the time of purchase");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 320, 280, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel8.setText("Default unit apply at the time of sale");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 370, 270, 30);

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox6KeyPressed(evt);
            }
        });
        jPanel2.add(jComboBox6);
        jComboBox6.setBounds(310, 320, 80, 30);

        jComboBox7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox7KeyPressed(evt);
            }
        });
        jPanel2.add(jComboBox7);
        jComboBox7.setBounds(310, 370, 80, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 16));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Close1.gif"))); // NOI18N
        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(410, 490, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("Rate");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 420, 50, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(70, 420, 70, 30);

        jComboBox8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox8KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox8KeyTyped(evt);
            }
        });
        jPanel2.add(jComboBox8);
        jComboBox8.setBounds(320, 420, 70, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setText("Qty");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(230, 420, 30, 30);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(260, 420, 60, 30);

        jComboBox9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox9KeyPressed(evt);
            }
        });
        jPanel2.add(jComboBox9);
        jComboBox9.setBounds(140, 420, 70, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 970, 540);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedIndex()>0)
        getRecords();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        if(jComboBox3.getSelectedIndex()>0)
        {
            getRecords1();
            
            if(jComboBox3.getSelectedItem().toString().equals("Fuel"))
            {
                loadSingleUnit();
            }

            else if(jComboBox3.getSelectedItem().toString().equals("Lubricants"))
            {
                loadSingleUnit1();
            }
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()>0)
        {
            loadJTable();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
            this.dispose();
    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        saveValidation();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        resetInput();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
            resetInput();
    }//GEN-LAST:event_jButton7KeyPressed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        if(jComboBox4.getSelectedIndex()>0)
        {
            try
            {
                interfaceRailway object1=null;
                System.out.println("in loadInitial");
                try
                {
                    object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
                }
                catch(Exception e)
                {
                    System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                    getIPaddress.changeIP();
                    try
                    {
                        object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
                    }
                    catch(Exception ex)
                    {
                        System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
                    }
                }

                String qry="select style_no from unit_list where unit_nm='"+jComboBox4.getSelectedItem().toString()+"'";
                String arr=object1.getSigetngleValue(qry, Main.year);
                System.out.println("arr value="+arr);

                jComboBox5.removeAllItems();
                jComboBox5.addItem("Select");

                String qry1="select * from compound_unit_list where style_no="+Integer.parseInt(arr)+"";
                String arr2[][]=object1.getInformationDD(qry1, 7, Main.year);

                jComboBox5.removeAllItems();

                for(int i=0;i<arr2.length;i++)
                {
                    String arr1[]=new String[4];
                    arr1[0]=arr2[i][2];
                    arr1[1]=arr2[i][3];
                    arr1[2]=arr2[i][4];
                    arr1[3]=arr2[i][5];
                    String item=arr1[0]+" "+arr1[1]+" "+"="+" "+arr1[2]+" "+arr1[3];
                    jComboBox5.addItem(item);
                }

                String qry2="select unit_nm from unit_list where style_no="+Integer.parseInt(arr)+"";

                String arr3[]=object1.getResultSetAs_1D_Array(qry2, Main.year);

                jComboBox6.removeAllItems();
                jComboBox7.removeAllItems();
                jComboBox6.addItem("Select");
                jComboBox7.addItem("Select");

                if(arr3.length>0)
                {
                    for(int i=0;i<arr3.length;i++)
                    {
                        jComboBox6.addItem(arr3[i]);
                        jComboBox7.addItem(arr3[i]);
                    }
                }
            }
            catch(Exception e)
            {
                System.out.println("Error ! In loadInitialInfo Method "+e);
            }
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox3.requestFocus();
        }
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_jComboBox3KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox4.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jComboBox4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox5.requestFocus();
        }
    }//GEN-LAST:event_jComboBox4KeyPressed

    private void jComboBox5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox6.requestFocus();
        }
    }//GEN-LAST:event_jComboBox5KeyPressed

    private void jComboBox6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox7.requestFocus();
        }
    }//GEN-LAST:event_jComboBox6KeyPressed

    private void jComboBox7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jComboBox7KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        loadToWindow();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8KeyTyped

    private void jComboBox8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox8KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton3.requestFocus();
        }
    }//GEN-LAST:event_jComboBox8KeyPressed

    private void jComboBox9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox9KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField3.requestFocus();
        }
    }//GEN-LAST:event_jComboBox9KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox9.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox8.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        saveValidation();
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRowCount()<1)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a record to delete.");
        }

        else if(dtm.getRowCount() > 0)
        {
            int c=javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Delete record", javax.swing.JOptionPane.YES_NO_OPTION);
            if(c==javax.swing.JOptionPane.YES_OPTION)
            {
                delete();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
        if(jTable1.getSelectedRowCount()<1)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a record to delete.");
        }

        else if(dtm.getRowCount() > 0)
        {
            int c=javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Delete record", javax.swing.JOptionPane.YES_NO_OPTION);
            if(c==javax.swing.JOptionPane.YES_OPTION)
            {
                delete();
            }
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRowCount()<1)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Record is not selected.");
        }

        else if(dtm.getRowCount() > 0)
        {
            int c=javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to update this record?", "Update record", javax.swing.JOptionPane.YES_NO_OPTION);
            if(c==javax.swing.JOptionPane.YES_OPTION)
            {
                update();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            if(jTable1.getSelectedRowCount()<1)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Record is not selected.");
            }

            else if(dtm.getRowCount() > 0)
            {
                int c=javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to update this record?", "Update record", javax.swing.JOptionPane.YES_NO_OPTION);
                if(c==javax.swing.JOptionPane.YES_OPTION)
                {
                    update();
                }
            }
        }
    }//GEN-LAST:event_jButton4KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

private void loadInitialInfo()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
	try
	{
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
	}
	catch(Exception e)
	{
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
		object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
		System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
	}
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Select");
        String qry="select ItemGroup from group_master";
        String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);
        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                jComboBox1.addItem(arr[i]);
            }
        }
        jComboBox2.removeAllItems();
        //jComboBox2.addItem("Select");
        qry="select distinct(MainGroup) from group_master";
        arr=object1.getResultSetAs_1D_Array(qry, Main.year);
        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                jComboBox2.addItem(arr[i]);
            }
        }
        jComboBox3.removeAllItems();
        jComboBox3.addItem("Select");
        qry="select distinct(SubGroup) from group_master";
        arr=object1.getResultSetAs_1D_Array(qry, Main.year);
        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                jComboBox3.addItem(arr[i]);
            }
        }
        jComboBox4.removeAllItems();
        jComboBox5.removeAllItems();
        jComboBox6.removeAllItems();
        jComboBox7.removeAllItems();
        jComboBox8.removeAllItems();
        jComboBox9.removeAllItems();
	jComboBox4.addItem("Select");
        jComboBox5.addItem("Select");
	jComboBox6.addItem("Select");
	jComboBox7.addItem("Select");
        jComboBox8.addItem("Select");
        jComboBox9.addItem("Select");
	qry="select unit_nm from unit_list order by unit_nm";
	arr=object1.getResultSetAs_1D_Array(qry, Main.year);
	if(arr.length>0)
	{
	    for(int i=0;i<arr.length;i++)
	    {
	        jComboBox4.addItem(arr[i]);
                jComboBox6.addItem(arr[i]);
                jComboBox7.addItem(arr[i]);
                jComboBox8.addItem(arr[i]);
                jComboBox9.addItem(arr[i]);
	    }
	}

        qry="select * from compound_unit_list";
        String arr2[][]=object1.getInformationDD(qry, 7, Main.year);

        for(int i=0;i<arr2.length;i++)
        {
            String arr1[]=new String[4];
            arr1[0]=arr2[i][2];
            arr1[1]=arr2[i][3];
            arr1[2]=arr2[i][4];
            arr1[3]=arr2[i][5];
            String item=arr1[0]+" "+arr1[1]+" "+"="+" "+arr1[2]+" "+arr1[3];
            jComboBox5.addItem(item);
        }

        jComboBox2.requestFocus();
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method "+e);
    }

}

public void getRecords()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
	try
	{
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
	}
	catch(Exception e)
	{
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
		object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
		System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
	}
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Select");
        String qry="select ItemGroup from group_master where MainGroup='"+jComboBox2.getSelectedItem().toString()+"'";
        String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);
        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                jComboBox1.addItem(arr[i]);
            }
        }
        /*jComboBox2.removeAllItems();
        //jComboBox2.addItem("Select");
        qry="select distinct(MainGroup) from group_master";
        arr=object1.getResultSetAs_1D_Array(qry, Main.year);
        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                jComboBox2.addItem(arr[i]);
            }
        }*/
        jComboBox3.removeAllItems();
        jComboBox3.addItem("Select");
        qry="select distinct(SubGroup) from group_master where MainGroup='"+jComboBox2.getSelectedItem().toString()+"'";
        arr=object1.getResultSetAs_1D_Array(qry, Main.year);
        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                jComboBox3.addItem(arr[i]);
            }
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In getrecord Method "+e);
    }
}

public void getRecords1()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
	try
	{
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
	}
	catch(Exception e)
	{
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
		object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
		System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
	}
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Select");
        String qry="select ItemGroup from group_master where SubGroup='"+jComboBox3.getSelectedItem().toString()+"'";
        String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);
        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                jComboBox1.addItem(arr[i]);
            }
        }
        /*jComboBox2.removeAllItems();
        jComboBox2.addItem("Select");
        qry="select distinct(MainGroup) from group_master";
        arr=object1.getResultSetAs_1D_Array(qry, Main.year);
        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                jComboBox2.addItem(arr[i]);
            }
        }*/
        /*jComboBox3.removeAllItems();
        jComboBox3.addItem("Select");
        String qry="select distinct(SubGroup) from group_master where MainGroup='"+jComboBox2.getSelectedItem().toString()+"'";
        String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);
        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                jComboBox3.addItem(arr[i]);
            }
        }*/
    }
    catch(Exception e)
    {
        System.out.println("Error ! In getrecord Method "+e);
    }
}

public boolean addItem()
{
    if(jComboBox3.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Sub group.");
        jComboBox3.requestFocus();
        return false;
    }
    if(jComboBox1.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Item group.");
        jComboBox1.requestFocus();
        return false;
    }
    if(jTextField1.getText().isEmpty())
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Item name.");
        jTextField1.requestFocus();
        return false;
    }
    if(jComboBox4.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Single unit.");
        jComboBox4.requestFocus();
        return false;
    }
    if(jComboBox6.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Purchase unit.");
        jComboBox6.requestFocus();
        return false;
    }
    if(jComboBox7.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Sale unit.");
        jComboBox7.requestFocus();
        return false;
    }
    if(jTextField2.getText().isEmpty())
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Rate.");
        jTextField2.requestFocus();
        return false;
    }
    if(jComboBox9.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Rate unit.");
        jComboBox9.requestFocus();
        return false;
    }
    if(jTextField3.getText().isEmpty())
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Qty.");
        jTextField3.requestFocus();
        return false;
    }
    if(jComboBox8.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Qty unit.");
        jComboBox8.requestFocus();
        return false;
    }

    int c=dtm.getRowCount(),sno;

    if(c==0)
    {
        sno=0;
    }
    
    else
    {
        sno = Integer.parseInt("" + jTable1.getValueAt(c-1, 13));
    }

    System.out.println("sno="+sno);

    String arr[]=new String[14];
    arr[0]=""+(dtm.getRowCount()+1);
    arr[1]=jComboBox2.getSelectedItem().toString();
    arr[2]=jComboBox3.getSelectedItem().toString();
    arr[3]=jComboBox1.getSelectedItem().toString();
    arr[4]=jTextField1.getText().trim().toUpperCase();
    arr[5]=jComboBox4.getSelectedItem().toString();
    arr[6]=jComboBox5.getSelectedItem().toString();
    arr[7]=jComboBox6.getSelectedItem().toString();
    arr[8]=jComboBox7.getSelectedItem().toString();
    arr[9]=jTextField2.getText().trim();
    arr[10]=jComboBox9.getSelectedItem().toString();
    arr[11]=jTextField3.getText().trim();
    arr[12]=jComboBox8.getSelectedItem().toString();
    arr[13]=""+(sno+1);
    dtm.addRow(arr);
    javax.swing.JOptionPane.showMessageDialog(this, "Added successfully.");
    //resetInput();
    return true;
}

public boolean save()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }
        
        String qry="select max(sno) from item_manager";
        String str=object1.getSigetngleValue(qry, Main.year);

        if(str==null || str.isEmpty())
        {
            System.out.println(str);
            str="0";
        }

        int sno=Integer.parseInt(str);

        qry="insert into item_manager values("+(sno+1)+",'"+jComboBox2.getSelectedItem().toString().trim()+"','"+jComboBox3.getSelectedItem().toString().trim()+"','"+jComboBox1.getSelectedItem().toString().trim()+"','"+jTextField1.getText().trim()+"','"+jComboBox4.getSelectedItem().toString().trim()+"','"+jComboBox5.getSelectedItem().toString().trim()+"','"+jComboBox6.getSelectedItem().toString().trim()+"','"+jComboBox7.getSelectedItem().toString().trim()+"',"+Double.valueOf(jTextField2.getText().trim())+",'"+jComboBox9.getSelectedItem().toString().trim()+"',"+Double.valueOf(jTextField3.getText().trim())+",'"+jComboBox8.getSelectedItem().toString().trim()+"',"+Double.valueOf(jTextField3.getText().trim())+",'"+jComboBox8.getSelectedItem().toString().trim()+"')";

        boolean bn=object1.saveInformation(qry, Main.year);

        if(bn==true)
        {
            loadJTable();
            javax.swing.JOptionPane.showMessageDialog(this, "Saving process completed.");
        }
        
    }
    catch(Exception e)
    {
        System.out.println("Error ! In getrecord Method "+e);
    }
    return true;
}

public void loadSingleUnit()
{
    try
        {
            interfaceRailway object1=null;
            System.out.println("in loadInitial");
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
                System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                getIPaddress.changeIP();
                try
                {
                    object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
                }
                catch(Exception ex)
                {
                    System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
                }
            }

            String qry="select unit_nm from unit_list where style_no="+1+"";
            String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);

            jComboBox4.removeAllItems();
            jComboBox4.addItem("Select");

            if(arr.length>0)
            {
                for(int i=0;i<arr.length;i++)
                {
                    jComboBox4.addItem(arr[i]);
                }
            }
        }
        catch(Exception e)
        {
            System.out.println("Error! In getrecord Method "+e);
        }
}

public void loadSingleUnit1()
{
    try
        {
            interfaceRailway object1=null;
            System.out.println("in loadInitial");
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception e)
            {
                System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
                getIPaddress.changeIP();
                try
                {
                    object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
                }
                catch(Exception ex)
                {
                    System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
                }
            }

            String qry="select unit_nm from unit_list order by unit_nm";
            String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);

            jComboBox4.removeAllItems();
            jComboBox4.addItem("Select");

            if(arr.length>0)
            {
                for(int i=0;i<arr.length;i++)
                {
                    jComboBox4.addItem(arr[i]);
                }
            }
        }
        catch(Exception e)
        {
            System.out.println("Error ! In getrecord Method "+e);
        }
}

public void loadCompoundUnit(String unit)
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }

        String qry="select * from compound_unit_list";
        String arr[][]=object1.getInformationDD(qry, 7, Main.year);

        for(int i=0;i<arr.length;i++)
        {
            String arr1[]=new String[4];
            arr1[0]=arr[i][2];
            arr1[1]=arr[i][3];
            arr1[2]=arr[i][4];
            arr1[3]=arr[i][5];
            String item=arr1[0]+" "+arr1[1]+"="+arr1[2]+" "+arr1[3];
            jComboBox5.addItem(arr1);
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In getrecord Method "+e);
    }
}

public void resetInput()
{
    jComboBox2.setSelectedItem("Primary");
    jComboBox3.setSelectedItem("Select");
    jComboBox1.setSelectedItem("Select");
    jTextField1.setText("");
    jComboBox4.setSelectedItem("Select");
    jComboBox5.setSelectedItem("Select");
    jComboBox6.setSelectedItem("Select");
    jComboBox7.setSelectedItem("Select");
    jTextField2.setText("");
    jComboBox9.setSelectedItem("Select");
    jTextField3.setText("");
    jComboBox8.setSelectedItem("Select");
    jComboBox2.requestFocus();
}

public void loadJTable()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }

        dtm.setRowCount(0);
        String qry="select * from item_manager where ItemGroup='"+jComboBox1.getSelectedItem().toString()+"'";
        String arr[][]=object1.getInformationDD(qry, 15, Main.year);
        
        if(arr.length>0)
        {
            String arr1[]=new String[16];
            for(int i=0;i<arr.length;i++)
            {
                arr1[0]=""+(i+1);
                arr1[1]=arr[i][1];
                arr1[2]=arr[i][2];
                arr1[3]=arr[i][3];
                arr1[4]=arr[i][4];
                arr1[5]=arr[i][5];
                arr1[6]=arr[i][6];
                arr1[7]=arr[i][7];
                arr1[8]=arr[i][8];
                arr1[9]=arr[i][9];
                arr1[10]=arr[i][10];
                arr1[11]=arr[i][11];
                arr1[12]=arr[i][12];
                arr1[13]=arr[i][13];
                arr1[14]=arr[i][14];
                arr1[15]=arr[i][0];
                dtm.addRow(arr1);
            }
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method "+e);
    }
}

public void delete()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }

        if(dtm.getRowCount()>0)
        {
            int c=jTable1.getSelectedRow();
            String qry="delete from item_manager where sno="+jTable1.getValueAt(c, 15)+"";
            dtm.removeRow(c);

            boolean bn=object1.saveInformation(qry, Main.year);
            
            if(bn==true)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Deleting process completed.");
            }
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In getrecord Method "+e);
    }
}

public void loadToWindow()
{
    int i=jTable1.getSelectedRow();
    
    jComboBox2.setSelectedItem(jTable1.getValueAt(i, 1).toString());
    jComboBox3.setSelectedItem(jTable1.getValueAt(i, 2).toString());
    jComboBox1.setSelectedItem(jTable1.getValueAt(i, 3).toString());
    jTextField1.setText(jTable1.getValueAt(i, 4).toString());
    jComboBox4.setSelectedItem(jTable1.getValueAt(i, 5).toString());
    jComboBox5.setSelectedItem(jTable1.getValueAt(i, 6).toString());
    jComboBox6.setSelectedItem(jTable1.getValueAt(i, 7).toString());
    jComboBox7.setSelectedItem(jTable1.getValueAt(i, 8).toString());
    jTextField2.setText(jTable1.getValueAt(i, 9).toString());
    jComboBox9.setSelectedItem(jTable1.getValueAt(i, 10).toString());
    jTextField3.setText(jTable1.getValueAt(i, 11).toString());
    jComboBox8.setSelectedItem(jTable1.getValueAt(i, 12).toString());
}

public void update()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }

        if(dtm.getRowCount()>0)
        {
            int c=jTable1.getSelectedRow();
            String qry="delete from item_manager where sno="+jTable1.getValueAt(c, 15)+"";
            dtm.removeRow(c);

            boolean bn=object1.saveInformation(qry, Main.year);

            qry="select max(sno) from item_manager";
            String str=object1.getSigetngleValue(qry, Main.year);

            if(str==null || str.isEmpty())
            {
                System.out.println(str);
                str="0";
            }

            int sno=Integer.parseInt(str);

            qry="insert into item_manager values("+(sno+1)+",'"+jComboBox2.getSelectedItem().toString().trim()+"','"+jComboBox3.getSelectedItem().toString().trim()+"','"+jComboBox1.getSelectedItem().toString().trim()+"','"+jTextField1.getText().trim()+"','"+jComboBox4.getSelectedItem().toString().trim()+"','"+jComboBox5.getSelectedItem().toString().trim()+"','"+jComboBox6.getSelectedItem().toString().trim()+"','"+jComboBox7.getSelectedItem().toString().trim()+"',"+Double.valueOf(jTextField2.getText().trim())+",'"+jComboBox9.getSelectedItem().toString().trim()+"',"+Double.valueOf(jTextField3.getText().trim())+",'"+jComboBox8.getSelectedItem().toString().trim()+"',"+Double.valueOf(jTextField3.getText().trim())+",'"+jComboBox8.getSelectedItem().toString().trim()+"')";

            bn=object1.saveInformation(qry, Main.year);

            if(bn==true)
            {
                loadJTable();
                javax.swing.JOptionPane.showMessageDialog(this, "Update process completed.");
            }
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In getrecord Method "+e);
    }
}

public void saveValidation()
{
    if(jComboBox3.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Sub group.");
        jComboBox3.requestFocus();
    }

    else if(jComboBox1.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Item group.");
        jComboBox1.requestFocus();
    }

    else if(jTextField1.getText().trim().equals(""))
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Item name.");
        jTextField1.requestFocus();
    }

    else if(jComboBox4.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Single unit.");
        jComboBox4.requestFocus();
    }
    
    else if(jComboBox6.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Purchase unit.");
        jComboBox6.requestFocus();
    }

    else if(jComboBox7.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Sale unit.");
        jComboBox7.requestFocus();
    }

    else if(jTextField2.getText().trim().equals(""))
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Rate.");
        jTextField2.requestFocus();
    }

    else if(jComboBox9.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Rate unit.");
        jComboBox9.requestFocus();
    }

    else if(jTextField3.getText().trim().equals(""))
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Quantity.");
        jTextField3.requestFocus();
    }

    else if(jComboBox8.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Quantity unit.");
        jComboBox8.requestFocus();
    }

    else
    {
        save();
    }
}
}