/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ledger.java
 *
 * Created on Jun 7, 2014, 2:20:34 PM
 */

package p3;

/**
 *
 * @author welcome
 */
public class Ledger extends javax.swing.JInternalFrame {
javax.swing.table.DefaultTableModel dtm;
    /** Creates new form Ledger */
    public Ledger(String uid,String cnm,String fyear) {
        initComponents();
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter=new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);


        String heading[]={"S.No.","Ledger Name","Address","Contact No","TIN","PAN","Group Name","Opening Balance","Credit Unit","Account Type"};
        dtm=new javax.swing.table.DefaultTableModel(heading,0);
        jTable1.setModel(dtm);

        javax.swing.table.TableColumn column;


        column=jTable1.getColumn("S.No.");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(45);
        column=jTable1.getColumn("Ledger Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(150);
        column=jTable1.getColumn("Address");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(250);
        column=jTable1.getColumn("Contact No");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("TIN");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("PAN");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Group Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(150);
        column=jTable1.getColumn("Opening Balance");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(120);
        column=jTable1.getColumn("Credit Unit");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(80);
        column=jTable1.getColumn("Account Type");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(120);

        loadGroupName();
        loadJTable();
        
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Select");
        jComboBox2.addItem("Dr");
        jComboBox2.addItem("Cr");
        jTextField1.requestFocus();

        jTextField5.setText("0");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Ledger Master Creation");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(219, 219, 186));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true), javax.swing.BorderFactory.createTitledBorder("")));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(219, 219, 186));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Ledger");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 20, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Group");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 60, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Address");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 100, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Contact No.");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 190, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("TIN");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 230, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("PAN");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 270, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Opening Bal.");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 310, 100, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(120, 20, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("A/c");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(320, 20, 30, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(120, 60, 230, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(120, 100, 230, 80);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(120, 190, 230, 30);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(120, 230, 230, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField4);
        jTextField4.setBounds(120, 270, 230, 30);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField5);
        jTextField5.setBounds(120, 310, 160, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(280, 310, 70, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/savefile.gif"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(10, 420, 120, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/dustbeen.gif"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(130, 420, 110, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/refresh.gif"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(240, 420, 120, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(21, 22, 370, 470);

        jPanel4.setBackground(new java.awt.Color(219, 219, 186));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(400, 20, 550, 470);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 970, 510);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        saveValidation();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextArea1.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ESCAPE)
        {
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField3.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField4.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField5.requestFocus();
            jTextField5.setText("0");
            jTextField5.selectAll();
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox2.requestFocus();
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        saveValidation();
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRowCount()<1)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Record is not selected.");
        }

        else if(dtm.getRowCount() > 0)
        {
            int c=javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?\nIf you delete then summary details of this ledger also delete.", "Delete record", javax.swing.JOptionPane.YES_NO_OPTION);
            if(c==javax.swing.JOptionPane.YES_OPTION)
            {
                deleteRecord();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(jTable1.getSelectedRowCount()<1)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Record is not selected.");
        }

        else if(dtm.getRowCount() > 0)
        {
            int c=javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?", "Delete record", javax.swing.JOptionPane.YES_NO_OPTION);
            if(c==javax.swing.JOptionPane.YES_OPTION)
            {
                deleteRecord();
            }
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();

        jTextField1.setText(jTable1.getValueAt(i, 1).toString());
        jComboBox1.setSelectedItem(jTable1.getValueAt(i, 6).toString());
        jTextArea1.setText(jTable1.getValueAt(i, 2).toString());

        jTextField2.setText(jTable1.getValueAt(i, 3).toString());
        jTextField3.setText(jTable1.getValueAt(i, 4).toString());
        jTextField4.setText(jTable1.getValueAt(i, 5).toString());
        jTextField5.setText(jTable1.getValueAt(i, 7).toString());

        jComboBox2.setSelectedItem(jTable1.getValueAt(i, 8).toString());
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

private void loadGroupName()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
	try
	{
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
	}
	catch(Exception e)
	{
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
		object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
		System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
	}

        jComboBox1.removeAllItems();
	jComboBox1.addItem("Select");
	String qry="select group_name from ledger_group order by group_name";
	String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);
	if(arr.length>0)
	{
	    for(int i=0;i<arr.length;i++)
	    {
	        jComboBox1.addItem(arr[i]);
	    }
	}
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method "+e);
    }

}

public void loadJTable()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }

        String qry="select * from ledger";
        String arr[][]=object1.getInformationDD(qry, 10, Main.year);

        String arr1[]=new String[10];
        
        for(int i=0;i<arr.length;i++)
        {
            arr1[0]=""+(i+1);
            arr1[1]=arr[i][1];
            arr1[2]=arr[i][2];
            arr1[3]=arr[i][3];
            arr1[4]=arr[i][4];
            arr1[5]=arr[i][6];
            arr1[6]=arr[i][5];
            arr1[7]=arr[i][7];
            arr1[8]=arr[i][8];
            //arr1[9]=arr[i][9];
            arr1[9]="Not Defined";
            dtm.addRow(arr1);
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method "+e);
    }
}

public void saveValidation()
{
    if(jTextField1.getText().trim().equals(""))
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Ledger Name.");
        jTextField1.requestFocus();
    }

    else if(jComboBox1.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Group Name.");
        jComboBox1.requestFocus();
    }

    else if(jTextArea1.getText().trim().equals(""))
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Address.");
        jTextArea1.requestFocus();
    }

    else if(jComboBox2.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select Credit Unit.");
        jComboBox2.requestFocus();
    }

    else
    {
        /*if(jTable1.getSelectedRowCount()>0)
        {
            int c=javax.swing.JOptionPane.showConfirmDialog(this, "This information is already exists.", "Save Ledger", javax.swing.JOptionPane.YES_NO_OPTION);
            if(c==javax.swing.JOptionPane.YES_OPTION)
            {
                save();
            }
        }
        else
        {*/
            save();
        //}
    }
}

public boolean save()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }
        String qry="select Ledger_Name from ledger where Ledger_Name='"+jTextField1.getText().trim()+"'";
        String load[]=object1.getResultSetAs_1D_Array(qry, Main.year);
        if(load.length>0)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Ledger name already exists.\nPlease enter a new ledger name.");
            return false;
        }
        qry="select max(sno) from ledger";
        String str=object1.getSigetngleValue(qry, Main.year);

        if(str==null || str.isEmpty())
        {
            System.out.println(str);
            str="0";
        }

        boolean bn=false;

        int sno=Integer.parseInt(str);



        qry="select max(sno) from ledger_summary";
        str=object1.getSigetngleValue(qry, Main.year);

        if(str==null || str.isEmpty())
        {
            System.out.println(str);
            str="0";
        }

        int sn=Integer.parseInt(str);
        String ledger_name=jTextField1.getText();
        String group_name=jComboBox1.getSelectedItem().toString();

        String arr[]=jTextArea1.getText().split("\n");
        String str2="";
        for(int i=0;i<arr.length;i++)
        {
            str2+=arr[i]+" ";
        }

        String contact=jTextField2.getText();
        String tin=jTextField3.getText();
        String pan=jTextField4.getText();

        String unit=jComboBox2.getSelectedItem().toString();
        String acc_type="Not Defined";

        double op_bal=0;

        String opening=jTextField5.getText().trim();
        if(opening==null || opening.equals(""))
        {
            op_bal=0;
        }

        else if(object1.isDouble(opening) == false)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter opening balance in number format.");
            jTextField5.requestFocus();
            return false;
        }
        
        qry="insert into ledger values ("+(sno+1)+",'"+ledger_name+"','"+str2.trim()+"','"+contact+"','"+tin+"','"+group_name+"','"+pan+"',"+op_bal+",'"+unit+"','"+acc_type+"')";
        bn=object1.saveInformation(qry, Main.year);

        if(bn==true)
        {
            dtm.setRowCount(0);
            loadJTable();
            double dr=0,cr=0;
            if(jComboBox2.getSelectedIndex()==1)
            {
                dr=Double.valueOf(jTextField5.getText().trim());
                cr=0;
            }
            else if(jComboBox2.getSelectedIndex()==2)
            {
                cr=Double.valueOf(jTextField5.getText().trim());
                dr=0;
            }
            
            qry="insert into ledger_summary values ("+(sn+1)+",'"+ledger_name+"','"+group_name+"',"+dr+","+cr+")";
            System.out.println("qry="+qry);
            bn=object1.saveInformation(qry, Main.year);
            javax.swing.JOptionPane.showMessageDialog(this, "Saving process completed.");
            clearWindow();
        }

    }
    catch(Exception e)
    {
        System.out.println("Error ! In getrecord Method "+e);
    }
    return true;
}

public void clearWindow()
{
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextArea1.setText("");
    jComboBox1.setSelectedIndex(0);
    jComboBox2.setSelectedIndex(0);
    jTextField1.requestFocus();
}

public boolean redundantLedger()
{
    boolean check=false;
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }

        String qry="select Ledger_Name from ledger";
        String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);

        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                if(arr[i].equals(jTextField1.getText().trim())==true)
                    check=true;
            }
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method "+e);
    }

    return check;
}

public void deleteRecord()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }

        String qry="delete from ledger where Ledger_Name='"+jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString()+"'and Group_Name='"+jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString()+"'";
        boolean bn=object1.saveInformation(qry, Main.year);



        if(bn==true)
        {
            qry="delete from ledger_summary where Ledger_Name='"+jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString()+"'and Group_Name='"+jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString()+"'";
            bn=object1.saveInformation(qry, Main.year);
            dtm.setRowCount(0);
            loadJTable();
            clearWindow();
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method "+e);
    }
}
}
