/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Purchase_Ledger.java
 *
 * Created on Jun 6, 2014, 2:50:26 PM
 */

package p3;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author welcome
 */
public class Purchase_Ledger extends javax.swing.JInternalFrame {
javax.swing.table.DefaultTableModel dtm;
    /** Creates new form Purchase_Ledger */
    public Purchase_Ledger(String uid,String cnm,String fyear) {
        initComponents();

        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter=new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        String heading[]={"S.No.","Item","Storage","Qty","Unit","Rate","Discount %","Discount Rs.","Total"};
        dtm=new javax.swing.table.DefaultTableModel(heading,0);
        jTable1.setModel(dtm);

        javax.swing.table.TableColumn column;

        column=jTable1.getColumn("S.No.");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(45);
        column=jTable1.getColumn("Item");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(230);
        column=jTable1.getColumn("Storage");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Qty");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(80);
        column=jTable1.getColumn("Unit");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(50);
        column=jTable1.getColumn("Rate");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(90);
        column=jTable1.getColumn("Discount %");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(80);
        column=jTable1.getColumn("Discount Rs.");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(90);
        column=jTable1.getColumn("Total");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(100);

        loadInit();
        loadStorage();
        loadItem(); /*Fuel and Lubricant*/

        java.util.Date dt=new java.util.Date();
        int date=dt.getDate();
        int month=dt.getMonth()+1;
        int year=dt.getYear()+1900;
        int hour=dt.getHours();
        int min=dt.getMinutes();
        int sec=dt.getSeconds();
        String setdate=date+"-"+month+"-"+year;
        String d=""+date,m=""+month;
        if(d.length()==1)
            d="0"+d;
        if(m.length()==1)
            m="0"+m;
        setdate=d+"-"+m+"-"+year;
        System.out.println(setdate);
        jFormattedTextField1.setText(setdate);
        jFormattedTextField2.setText(setdate);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        MaskFormatter mask1=null;
        try{
            mask1=new MaskFormatter("##-##-####");
            mask1.setPlaceholderCharacter('_');
        }
        catch(Exception ae)
        {
            System.out.println("error in setting jFormating textField");
        }
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        MaskFormatter mask2=null;
        try{
            mask2=new MaskFormatter("##-##-####");
            mask2.setPlaceholderCharacter('_');
        }
        catch(Exception ae)
        {
            System.out.println("error in setting jFormating textField");
        }
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Purchase Ledger ");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(70, 87, 78));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true), javax.swing.BorderFactory.createTitledBorder("")));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(162, 185, 173));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Invoice No");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 20, 100, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(100, 20, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Supplier");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 70, 110, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(100, 70, 380, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("TIN");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 120, 70, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(100, 120, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Reference");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(510, 20, 70, 30);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(630, 20, 260, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Entry Date");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(270, 20, 80, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/calendar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(450, 20, 30, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Purchase Ledger");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(510, 70, 110, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(630, 70, 260, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("Delivery Date");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(270, 120, 90, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/calendar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(450, 120, 30, 30);

        jFormattedTextField1 = new javax.swing.JFormattedTextField(mask1);
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyPressed(evt);
            }
        });
        jPanel3.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(349, 20, 100, 30);

        jFormattedTextField2 = new javax.swing.JFormattedTextField(mask2);
        jFormattedTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField2KeyPressed(evt);
            }
        });
        jPanel3.add(jFormattedTextField2);
        jFormattedTextField2.setBounds(359, 120, 90, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/refresh.gif"))); // NOI18N
        jButton7.setText("Clear All");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(760, 120, 130, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel17.setText("Job Shift");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(510, 120, 110, 30);

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Day", "Night" }));
        jComboBox6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox6KeyPressed(evt);
            }
        });
        jPanel3.add(jComboBox6);
        jComboBox6.setBounds(630, 120, 120, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 10, 910, 180);

        jPanel4.setBackground(new java.awt.Color(162, 185, 173));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createCompoundBorder()));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Item Name");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 0, 110, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setText("Storage");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(240, 0, 80, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox3KeyPressed(evt);
            }
        });
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(240, 30, 110, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setText("Qty");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(360, 0, 50, 30);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel4.add(jTextField5);
        jTextField5.setBounds(360, 30, 60, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel13.setText("Unit");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(430, 0, 30, 30);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox4KeyPressed(evt);
            }
        });
        jPanel4.add(jComboBox4);
        jComboBox4.setBounds(430, 30, 80, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel14.setText("Rate");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(520, 0, 50, 30);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel4.add(jTextField6);
        jTextField6.setBounds(520, 30, 80, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setText("Discount %");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(610, 0, 80, 30);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel4.add(jTextField7);
        jTextField7.setBounds(610, 30, 70, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel16.setText("Discount Rs");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(690, 0, 80, 30);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        jPanel4.add(jTextField8);
        jTextField8.setBounds(690, 30, 80, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(790, 10, 100, 50);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jComboBox5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox5KeyPressed(evt);
            }
        });
        jPanel4.add(jComboBox5);
        jComboBox5.setBounds(20, 30, 210, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 200, 910, 70);

        jPanel5.setBackground(new java.awt.Color(162, 185, 173));
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 87, 78), 5, true), javax.swing.BorderFactory.createTitledBorder("")));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 280, 910, 320);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/savefile.gif"))); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(12, 610, 160, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/dustbeen.gif"))); // NOI18N
        jButton5.setText("Delete");
        jPanel2.add(jButton5);
        jButton5.setBounds(180, 610, 160, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/Close1.gif"))); // NOI18N
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(350, 610, 180, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total = ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(680, 610, 70, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("0.00");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(750, 610, 160, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 1, 930, 660);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cal c=new Cal();
        jFormattedTextField1.setText(c.getdate());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Cal c=new Cal();
        jFormattedTextField2.setText(c.getdate());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        saveValidation();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        saveValidation();
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:

        if(jTextField7.getText().trim().equals(""))
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter Discount %.");
        }

        else
        {
            setDiscount();
        }
    }//GEN-LAST:event_jTextField7FocusLost

    private void jComboBox3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField5.requestFocus();
        }
    }//GEN-LAST:event_jComboBox3KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField6.requestFocus();
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jComboBox4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField7.requestFocus();
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField8.requestFocus();
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton3.requestFocus();
        }
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jComboBox5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10) {
            jTextField5.requestFocus();
        }
}//GEN-LAST:event_jComboBox5KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jFormattedTextField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jFormattedTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_jFormattedTextField1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField3.requestFocus();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox2.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jFormattedTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jFormattedTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_jFormattedTextField2KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox6.requestFocus();
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        loadUnitName();

        if(jComboBox5.getSelectedIndex()>0)
        {
            String item_nm=jComboBox5.getSelectedItem().toString();
            loadStorage(item_nm);
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEnabled(true);
        jFormattedTextField1.setEnabled(true);
        jButton1.setEnabled(true);
        jTextField3.setEnabled(true);
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(true);
        jTextField2.setEnabled(true);
        jFormattedTextField2.setEnabled(true);
        jButton2.setEnabled(true);

        jTextField1.setText("");
        jFormattedTextField1.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jTextField2.setText("");
        jFormattedTextField2.setText("");
        jTextField1.requestFocus();
        dtm.setRowCount(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            jComboBox5.requestFocus();
        }
    }//GEN-LAST:event_jComboBox6KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            save();
        }
    }//GEN-LAST:event_jButton4KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

public void addItemJTable()
{
    jTextField1.setEnabled(false);
    jFormattedTextField1.setEnabled(false);
    jButton1.setEnabled(false);
    jTextField3.setEnabled(false);
    jComboBox1.setEnabled(false);
    jComboBox2.setEnabled(false);
    jTextField2.setEnabled(false);
    jFormattedTextField2.setEnabled(false);
    jButton2.setEnabled(false);
    String st="";
    if(jComboBox3.getSelectedIndex()>0)
        st=jComboBox3.getSelectedItem().toString();
    String item=jComboBox5.getSelectedItem().toString();
    String storage=st;
    int qty=Integer.parseInt(jTextField5.getText().trim());
    String unit=jComboBox4.getSelectedItem().toString();
    double rate=Double.valueOf(jTextField6.getText().trim());
    double total=qty*rate;
    double per=Double.valueOf(jTextField7.getText().trim());
    double dis=(total*per)/100;
    double total1=0;
    //double amt=total-dis;

    String arr[]=new String[9];
    arr[0]=""+(dtm.getRowCount()+1);
    arr[1]=item;
    arr[2]=storage;
    arr[3]=""+qty;
    arr[4]=unit;
    arr[5]=""+(new java.math.BigDecimal(Double.valueOf(rate)).setScale(2,java.math.BigDecimal.ROUND_HALF_UP));
    arr[6]=""+(new java.math.BigDecimal(Double.valueOf(per)).setScale(2,java.math.BigDecimal.ROUND_HALF_UP));
    arr[7]=""+(new java.math.BigDecimal(Double.valueOf(dis)).setScale(2,java.math.BigDecimal.ROUND_HALF_UP));
    arr[8]=""+(new java.math.BigDecimal(Double.valueOf(qty*rate-dis)).setScale(2,java.math.BigDecimal.ROUND_HALF_UP));

    dtm.addRow(arr);
    for(int i=0;i<dtm.getRowCount();i++)
    {
        total1=total1+Double.valueOf(jTable1.getValueAt(i, 8).toString());
    }
    jLabel10.setText(""+total1);
    javax.swing.JOptionPane.showMessageDialog(this, "Added successfully.");

    jComboBox5.requestFocus();
}

private void loadUnitName()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
	try
	{
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
	}
	catch(Exception e)
	{
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
		object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
		System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
	}

        jComboBox4.removeAllItems();
	String qry="select purchase_unit from item_manager where Item='"+jComboBox5.getSelectedItem().toString()+"'";
        String purchase_unit=object1.getSigetngleValue(qry, Main.year);
        jComboBox4.addItem(purchase_unit);
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method "+e);
    }

}

private void loadStorage()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
	try
	{
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
	}
	catch(Exception e)
	{
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
		object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
		System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
	}

        jComboBox3.removeAllItems();
	jComboBox3.addItem("Select");

        String qry="select TankName from tank_master order by TankName";
        String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);

        //jComboBox2.removeAllItems();
        //jComboBox2.addItem("Select");

        if(arr.length>0)
        {
            for(int i=0;i<arr.length;i++)
            {
                jComboBox3.addItem(arr[i]);
            }
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method "+e);
    }

}

public void setDiscount()
{
    int qty=Integer.parseInt(jTextField5.getText().trim());
    String unit=jComboBox4.getSelectedItem().toString();
    double rate=Double.valueOf(jTextField6.getText().trim());
    double total=qty*rate;
    double per=Double.valueOf(jTextField7.getText().trim());
    double dis=(total*per)/100;
    jTextField8.setText(""+dis);
    //double amt=total-dis;
    //jTextField9.setText(""+amt);
}

public void saveValidation()
{
    if(jTextField1.getText().isEmpty())
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please enter invoice number.");
        jTextField1.requestFocus();
    }
    else if(jFormattedTextField1.getText().isEmpty())
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please enter entry date.");
        jFormattedTextField1.requestFocus();
    }
    else if(jTextField3.getText().isEmpty())
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please enter reference.");
        jTextField3.requestFocus();
    }
    else if(jComboBox1.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please select supplier.");
        jComboBox1.requestFocus();
    }
    else if(jComboBox2.getSelectedIndex()==0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please select purchase ledger.");
        jComboBox2.requestFocus();
    }
    else if(jTextField2.getText().isEmpty())
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please enter TIN number.");
        jTextField2.requestFocus();
    }
    else if(jFormattedTextField2.getText().isEmpty())
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please enter delivery date.");
        jFormattedTextField2.requestFocus();
    }
    else if(jComboBox5.getSelectedIndex() == 0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please select Item Name.");
        jComboBox5.requestFocus();
    }

    else if(jTextField5.getText().trim().equals(""))
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please enter Quantity.");
        jTextField5.requestFocus();
    }

    
    else if(jTextField6.getText().trim().equals(""))
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please enter Rate.");
        jTextField6.requestFocus();
    }

    else if(jTextField7.getText().trim().equals(""))
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please enter Discount %.");
        jTextField7.requestFocus();
    }
    else
    {
        addItemJTable();
    }
}

private void loadItem()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
	try
	{
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
	}
	catch(Exception e)
	{
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
		object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
		System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
	}

        jComboBox5.removeAllItems();
	jComboBox5.addItem("Select");
	String qry="select Item from item_manager where subGroup='"+"Lubricants"+"'";
	String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);
	if(arr.length>0)
	{
	    for(int i=0;i<arr.length;i++)
	    {
	        jComboBox5.addItem(arr[i]);
	    }
	}

        qry="select Item from item_manager where subGroup='"+"Fuel"+"'";
	String arr2[]=object1.getResultSetAs_1D_Array(qry, Main.year);
	if(arr2.length>0)
	{
	    for(int i=0;i<arr2.length;i++)
	    {
	        jComboBox5.addItem(arr2[i]);
	    }
	}
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method "+e);
    }

}

public void loadStorage(String item_nm)
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }

        int status=0;

        String qry="select subGroup from item_manager where Item='"+item_nm+"'";
	String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);
	if(arr.length>0)
	{
	    for(int i=0;i<arr.length;i++)
	    {
                System.out.println(arr[i]);

	        if(arr[i].equals("Lubricants"))
                {
                    status=1;
                    break;
                }

                if(arr[i].equals("Fuel"))
                {
                    status=2;
                    break;
                }
	    }
	}

        if(status==1)
        {
            jComboBox3.setEnabled(false);
        }

        if(status==2)
        {
            jComboBox3.setEnabled(true);
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method "+e);
    }
}
public void loadInit()
{
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }

        int status=0;
        String qry="select Ledger_Name from ledger where Group_Name='"+"Suppliers"+"'";
	String arr[]=object1.getResultSetAs_1D_Array(qry, Main.year);
        jComboBox1.removeAllItems();
	if(arr.length>0)
	{
            jComboBox1.addItem("Select");
	    for(int i=0;i<arr.length;i++)
            {
                jComboBox1.addItem(arr[i]);
            }
	}

        qry="select Ledger_Name from ledger where Group_Name='"+"Purchase Account"+"'";
        System.out.println(qry);
	arr=object1.getResultSetAs_1D_Array(qry, Main.year);
        jComboBox2.removeAllItems();
	if(arr.length>0)
	{
            jComboBox2.addItem("Select");
	    for(int i=0;i<arr.length;i++)
            {
                jComboBox2.addItem(arr[i]);
            }
	}
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInit Method "+e);
    }
}
public boolean save()
{
    if(jTable1.getRowCount()<=0)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Error! Please add records which you want to add.");
        jTextField1.requestFocus();
        return false;
    }
    try
    {
        interfaceRailway object1=null;
        System.out.println("in loadInitial");
        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }
        String q="select max(sno) from purchase_ledger";
        String sn=object1.getSigetngleValue(q, Main.year);
        if(sn==null || sn.isEmpty())
        {
            sn="0";
        }
        int sno=Integer.parseInt(sn)+1;
        String invoice=jTextField1.getText().trim();
        String endate1[]=jFormattedTextField1.getText().split("-");
        String endate=endate1[2]+"-"+endate1[1]+"-"+endate1[0];
        String shift=jComboBox6.getSelectedItem().toString();
        String ref=jTextField3.getText().trim();
        String sup=jComboBox1.getSelectedItem().toString();
        String pur=jComboBox2.getSelectedItem().toString();
        String tin=jTextField2.getText().trim();
        String dedate1[]=jFormattedTextField2.getText().split("-");
        String dedate=dedate1[2]+"-"+dedate1[1]+"-"+dedate1[0];
        boolean bn=false;
        for(int i=0;i<dtm.getRowCount();i++)
        {
            String Itnm=jTable1.getValueAt(i, 1).toString();

            String storage;
            if(jComboBox3.isEnabled()==false)
                storage=" ";
            else
                storage=jTable1.getValueAt(i, 2).toString();
            
            String qty=jTable1.getValueAt(i, 3).toString();
            String unit=jTable1.getValueAt(i, 4).toString();
            String rate=jTable1.getValueAt(i, 5).toString();
            String dis=jTable1.getValueAt(i, 6).toString();
            String qry="insert into purchase_ledger values ("+sno+","+Integer.parseInt(invoice)+",'"+endate+"','"+shift+"','"+ref+"','"+sup+"','"+pur+"','"+tin+"','"+dedate+"','"+Itnm+"','"+storage+"',"+Double.valueOf(qty)+",'"+unit+"',"+Double.valueOf(rate)+","+Double.valueOf(dis)+")";
            System.out.println("qry="+qry);
            bn=object1.saveInformation(qry, Main.year);
        }
        if(bn==true)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Saving process completed.");
            dtm.setRowCount(0);

            String qry="select Debit_amt from ledger_summary where LedgerName='"+jComboBox2.getSelectedItem().toString()+"'";
            
            String str1=object1.getSigetngleValue(qry, Main.year);
            
            System.out.println(str1);

            double Debit_Amt=Double.valueOf(str1);
            System.out.println(Debit_Amt);
            double Purchase_Amt=Double.valueOf(jLabel10.getText().trim());
            System.out.println(Purchase_Amt);
            double Total_Amt=Debit_Amt+Purchase_Amt;
            System.out.println(Total_Amt);
            
            String qry2="update ledger_summary set Debit_amt="+Total_Amt+" where LedgerName='"+jComboBox2.getSelectedItem().toString()+"'";
            bn=object1.saveInformation(qry2, Main.year);
            
            String qry3="select qty from item_manager where Item='"+jComboBox5.getSelectedItem().toString()+"'";
            
            String str2=object1.getSigetngleValue(qry3, Main.year);
            
            System.out.println(str2);

            double ItemQty=Double.valueOf(str2);
            System.out.println(ItemQty);
            double AddQty=Double.valueOf(jTextField5.getText().trim());
            System.out.println(AddQty);
            double TotalQty=ItemQty+AddQty;
            System.out.println(TotalQty);

            String qry4="update item_manager set current_qty="+TotalQty+" where Item='"+jComboBox5.getSelectedItem().toString()+"'";
            bn=object1.saveInformation(qry4, Main.year);

            jTextField1.setEnabled(true);
            jFormattedTextField1.setEnabled(true);
            jButton1.setEnabled(true);
            jTextField3.setEnabled(true);
            jComboBox1.setEnabled(true);
            jComboBox2.setEnabled(true);
            jTextField2.setEnabled(true);
            jFormattedTextField2.setEnabled(true);
            jButton2.setEnabled(true);
            jTextField1.requestFocus();
        }
    }
    catch(Exception ae)
    {
        System.out.println("Error in save method"+ae);
    }
    return true;
}
}