/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Search.java
 *
 * Created on Jun 13, 2012, 3:10:48 PM
 */

package railwaycashoffice;

import java.awt.Color;

/**
 *
 * @author user2
 */
public class Search extends javax.swing.JInternalFrame {

    /** Creates new form Search */
    public Search() {
        initComponents();
        javax.swing.ButtonGroup bg=new javax.swing.ButtonGroup();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        jRadioButton1.setSelected(true);
        jRadioButton1.requestFocus();
        jLabel1.setEnabled(false);
        jButton1.setEnabled(false);
        java.util.Date dt=new java.util.Date();
        String curDate=dt.getDate()+"-"+(dt.getMonth()+1)+"-"+(dt.getYear()+1900);
        jLabel1.setText(curDate);
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter=new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        javax.swing.table.TableColumn column;
        String head[]={"Sr.No.","Issue Date","Dept. Name","CO6","Cashier No.","Party Name","Amount","Cheque No.","Bank Name"};
        dtm1=new javax.swing.table.DefaultTableModel(head,0);
        jTable1.setModel(dtm1);

        column=jTable1.getColumn("Sr.No.");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(50);
        column=jTable1.getColumn("Issue Date");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Dept. Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(90);
        column=jTable1.getColumn("CO6");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(80);
        column=jTable1.getColumn("Cashier No.");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(50);
        column=jTable1.getColumn("Party Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(120);
        column=jTable1.getColumn("Amount");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(120);
        column=jTable1.getColumn("Cheque No.");
        column.setCellRenderer(CRCenter);
        column.setPreferredWidth(100);
        column=jTable1.getColumn("Bank Name");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(150);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Search Option");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setLayout(null);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("By Cheque No.");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(20, 10, 170, 23);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jRadioButton2.setText("By Issue Date");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(20, 60, 170, 23);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("Please Enter Cheque No.");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(250, 10, 230, 30);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 54, 160, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railwaycashoffice/images/calendar.png"))); // NOI18N
        jButton1.setToolTipText("Select Issue Date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 53, 60, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setMnemonic('S');
        jButton2.setText("Show");
        jButton2.setToolTipText("Show Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 10, 130, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setMnemonic('C');
        jButton3.setText("Close");
        jButton3.setToolTipText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(590, 50, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 730, 90);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 120, 730, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {
            jButton1.setEnabled(false);
            jLabel1.setEnabled(false);
            jTextField1.setEnabled(true);
            jTextField1.setText("");
           //jRadioButton1.setForeground(java.awt.Color.BLUE);
        }
        else
        {
            //jRadioButton1.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected())
        {
            jButton1.setEnabled(true);
            jLabel1.setEnabled(true);
            jTextField1.setEnabled(false);
            jTextField1.setText("");
        //jRadioButton2.setForeground(java.awt.Color.BLUE);
        }
        else
        {
           // jRadioButton2.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Cal date1=new Cal();
           jLabel1.setText(date1.getdate());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
            jButton2.requestFocus();
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
             Cal date1=new Cal();
           jLabel1.setText(date1.getdate());
           jButton2.requestFocus();
        }

    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        showDetails();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            showDetails();
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
            this.dispose();
    }//GEN-LAST:event_jButton3KeyPressed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    javax.swing.table.DefaultTableModel dtm1;

    private boolean showDetails()
    {
        dtm1.setRowCount(0);
        try
        {
          //  interfaceRailway inf=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
            interfaceRailway inf=null;
		try
		{
			inf=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					inf=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
				}
		}
            String qry="select * from issuingchequedetail where ";
            if(jRadioButton1.isSelected())
            {
                if(jTextField1.getText().equals(""))
                {
                    javax.swing.JOptionPane.showMessageDialog(this,"Please Enter Cheque No.");
                    jTextField1.requestFocus();
                    return false;
                }
                long chequeNo=0;
                try
                {
                    chequeNo=Long.valueOf(jTextField1.getText());
                }
                catch(Exception e)
                {
                    javax.swing.JOptionPane.showMessageDialog(this,"Please Enter Cheque No. (Numbers only)");
                    jTextField1.requestFocus();
                    jTextField1.selectAll();
                    return false;
                }
                qry+="chequeno="+chequeNo+"";
            }
            else
            {
                String temp[]=jLabel1.getText().split("-");
                String date1=temp[2]+"-"+temp[1]+"-"+temp[0];
                qry+="issuingdate='"+date1+"'";
            }
            String data[][]=inf.getInformationDD(qry,6,Main.year);
            if(data!=null && data.length>0)
            {
                String tab[]=new String[9];
                for(int x=0;x<tab.length;x++)
                    tab[x]="";
                for(int i=0;i<data.length;i++)
                {
                    tab[0]=""+(i+1)+".";
                    String temp[]=data[i][1].split("-");
                    tab[1]=temp[2]+"-"+temp[1]+"-"+temp[0];
                    qry="select dp_name from department_detail where dp_code="+Integer.parseInt(data[i][0])+"";
                    tab[2]=inf.getSigetngleValue(qry,Main.year);
                    tab[3]=data[i][2];
                    qry="select cashier_code,partyname,amount from build_distribution where dp_code="+Integer.parseInt(data[i][0])+" and CO6="+Integer.parseInt(data[i][2])+"";
                    String data1[][]=inf.getInformationDD(qry,3,Main.year);
                    if(data1!=null && data1.length>0)
                    {
                        qry="select cashier_number from cashier_detail where cashier_code="+Integer.parseInt(data1[0][0])+"";
                        tab[4]=inf.getSigetngleValue(qry,Main.year);
                        tab[5]=data1[0][1];
                        tab[6]=""+(new java.math.BigDecimal(data1[0][2]).setScale(2,java.math.BigDecimal.ROUND_HALF_UP));
                    }
                    tab[7]=data[i][4];
                    tab[8]=data[i][3];
                    dtm1.addRow(tab);
                }
                return true;
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(this,"No Record Found.");
                return false;
            }
        }
        catch(Exception e)
        {
            System.out.println("Errrorrrrrr..."+e);
            return false;
        }
    }
}
