/*
 * PaymentMoneyToPurParty.java
 *
 * Created on May 6, 2011, 5:14 PM
 */

//package javaapplication2;
import java.rmi.*;
import javax.swing.*;
/**
 *
 * @author  user
 */
public class PaymentMoneyToPurParty extends javax.swing.JInternalFrame {
    
    /** Creates new form PaymentMoneyToPurParty */
    public PaymentMoneyToPurParty() {
        initComponents();
        
        jButton1.setIcon(new javax.swing.ImageIcon("icons\\attachment.gif"));
        jButton2.setIcon(new javax.swing.ImageIcon("icons\\exit.gif"));
        
        try
        {
        	ZedInterface inf=null;
ZedInterfaceForMedical uc=null;
try
{
	inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
	uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
}
catch(Exception e)
{
	System.out.println("Error with connection with server "+getIPaddress.IP()+" ...");
	getIPaddress.changeIP();
	try
	{
		inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
		uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
	}
	catch(Exception ex)
	{
		System.out.println("Error with connection with server  rmi://127.0.0.1/ExtendZedServer...");
	}
}
        	jComboBox1.removeAllItems();
            String arr[]=inf.getResultSetAs_1D_Array("select distinct(partyNm) from purchasePaymentSmry where purDueAmt>0 order by partyNm");
            if(arr!=null)
            {
            	for(int i=0;i<arr.length;i++)
            	{
            		if(arr[i].equals(""))
            		{}
            		else
            			jComboBox1.addItem(arr[i]);
            	}
            }
            jComboBox2.removeAllItems();
            arr=inf.getResultSetAs_1D_Array("select bookNo from purchasePaymentSmry where partyNm='"+""+jComboBox1.getSelectedItem()+"' and purDueAmt>0");
            if(arr!=null)
            {
            	for(int i=0;i<arr.length;i++)
            	{
            		jComboBox2.addItem(arr[i]);
            	}
            }
            jComboBox3.removeAllItems();
            arr=inf.getResultSetAs_1D_Array("select srNo from purchasePaymentSmry where partyNm='"+""+jComboBox1.getSelectedItem()+"' and bookNo='"+""+jComboBox2.getSelectedItem()+"' and purDueAmt>0");
            if(arr!=null)
            {
            	for(int i=0;i<arr.length;i++)
            	{
            		jComboBox3.addItem(arr[i]);
            	}
            }
            //String purNo=inf.getSingleValue("select purDueAmt ");
            String dueAmt=inf.getSingleValue("select purDueAmt from purchasePaymentSmry where partyNm='"+""+jComboBox1.getSelectedItem()+"' and bookNo='"+""+jComboBox2.getSelectedItem()+"' and srNo='"+""+jComboBox3.getSelectedItem()+"'");
            if(dueAmt!=null)
            	jTextField1.setText(dueAmt);
            else
            	jTextField1.setText("0");
            	
            //String query="select sum(purAmt) from purchasePaymentSmry where partyNm='"+jComboBox1.getSelectedItem()+"'";
            //System.out.println("pur Amt="+inf.getSingleValue(query));
            
        }
        catch(Exception e)
        {
        	System.out.println("Errorr.....skm...."+e);
        }    
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setClosable(true);
        setTitle("Paid Money To Party");
        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel1.setText("Select Party Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 140, 20);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel2.setText("Select Book No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 140, 20);

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel3.setText("Select Serial No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 140, 20);

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel4.setText("Enter Paid Amount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 140, 20);

        jComboBox1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jComboBox1.setMaximumRowCount(4);
        jComboBox1.setToolTipText("Please Select Party");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(180, 20, 210, 22);

        jComboBox2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jComboBox2.setMaximumRowCount(4);
        jComboBox2.setToolTipText("Please Select Book No.");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });

        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(180, 60, 210, 22);

        jComboBox3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jComboBox3.setMaximumRowCount(4);
        jComboBox3.setToolTipText("Please Select Serial No.");
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jComboBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox3KeyPressed(evt);
            }
        });

        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(180, 100, 210, 22);

        jTextField1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jTextField1.setForeground(new java.awt.Color(204, 0, 102));
        jTextField1.setToolTipText("Please Input Paid Amount");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 140, 210, 20);

        jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setMnemonic('P');
        jButton1.setText("Paid");
        jButton1.setToolTipText("Paid Amount]");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(60, 190, 110, 40);

        jButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setMnemonic('c');
        jButton2.setText("Close");
        jButton2.setToolTipText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        getContentPane().add(jButton2);
        jButton2.setBounds(220, 190, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            dispose();
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            save();
        }
            
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        save();
    }//GEN-LAST:event_jButton1ActionPerformed
	private boolean save()
	{
		try
        {
        	
        	if(jComboBox1.getSelectedIndex()==-1)
        	{
        		JOptionPane.showMessageDialog(null,"No Party Found To Pay Amount ?","Error !!!",JOptionPane.ERROR_MESSAGE);
        		jComboBox1.requestFocus();
        		return false;
        	}
        	if(jComboBox2.getSelectedIndex()==-1)
        	{
        		JOptionPane.showMessageDialog(null,"No Book No. Found To Pay Amount ?","Error !!!",JOptionPane.ERROR_MESSAGE);
        		jComboBox2.requestFocus();
        		return false;
        	}
        	if(jComboBox3.getSelectedIndex()==-1)
        	{
        		JOptionPane.showMessageDialog(null,"No Serial No. Found To Pay Amount ?","Error !!!",JOptionPane.ERROR_MESSAGE);
        		jComboBox3.requestFocus();
        		return false;
        	}
        	if(jTextField1.getText().trim().equals(""))
        	{
        		JOptionPane.showMessageDialog(null,"Please Enter Pay Amount ?","Error !!!",JOptionPane.ERROR_MESSAGE);
        		jTextField1.requestFocus();
        		return false;
        	}
        	double amt=0;
        	try
        	{
        		amt=Double.valueOf(jTextField1.getText());
        	}
        	catch(Exception e)
        	{
        		JOptionPane.showMessageDialog(null,"Please Enter Correct Pay Amount ?","Error !!!",JOptionPane.ERROR_MESSAGE);
        		jTextField1.requestFocus();
        		jTextField1.selectAll();
        		return false;
        	}
        	ZedInterface inf=null;
ZedInterfaceForMedical uc=null;
try
{
	inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
	uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
}
catch(Exception e)
{
	System.out.println("Error with connection with server "+getIPaddress.IP()+" ...");
	getIPaddress.changeIP();
	try
	{
		inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
		uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
	}
	catch(Exception ex)
	{
		System.out.println("Error with connection with server  rmi://127.0.0.1/ExtendZedServer...");
	}
}
        	//----1
        	inf.executeUpdateQuery("update purchasePaymentSmry set purDueAmt=purDueAmt-"+amt+" where partyNm='"+""+jComboBox1.getSelectedItem()+"' and bookNo='"+""+jComboBox2.getSelectedItem()+"' and srNo='"+""+jComboBox3.getSelectedItem()+"'");
        	//---2
        	java.util.Date dt=new java.util.Date();
        	String pno=inf.getSingleValue("select pNo from purchasePaymentSmry where partyNm='"+""+jComboBox1.getSelectedItem()+"' and bookNo='"+""+jComboBox2.getSelectedItem()+"' and srNo='"+""+jComboBox3.getSelectedItem()+"'");
        	
        	String paydt=(dt.getMonth()+1)+"/"+(dt.getDate())+"/"+(dt.getYear()+1900);
        	inf.executeUpdateQuery("insert into purchasePaymentDetails values("+Integer.parseInt(pno)+",'"+""+jComboBox1.getSelectedItem()+"','"+""+jComboBox2.getSelectedItem()+"','"+""+jComboBox3.getSelectedItem()+"',"+amt+",'"+paydt+"')");
        	JOptionPane.showMessageDialog(null,"Process Successful...");
        	jTextField1.setText("");
        	jComboBox1.removeAllItems();
            String arr[]=inf.getResultSetAs_1D_Array("select distinct(partyNm) from purchasePaymentSmry where purDueAmt>0 order by partyNm");
            if(arr!=null)
            {
            	for(int i=0;i<arr.length;i++)
            	{
            		if(arr[i].equals(""))
            		{}
            		else
            			jComboBox1.addItem(arr[i]);
            	}
            }
        	
		}
        catch(Exception ex)
		{
     		System.out.println("Error ...."+ex);
		}
		jComboBox1.requestFocus();
		return true;
	}
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
            jButton1.requestFocus();
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jComboBox3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox3KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
            jTextField1.requestFocus();
    }//GEN-LAST:event_jComboBox3KeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
            jComboBox3.requestFocus();
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
            jComboBox2.requestFocus();
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
// TODO add your handling code here:
		jTextField1.setText("");   	
       try
        {
        	ZedInterface inf=null;
ZedInterfaceForMedical uc=null;
try
{
	inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
	uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
}
catch(Exception e)
{
	System.out.println("Error with connection with server "+getIPaddress.IP()+" ...");
	getIPaddress.changeIP();
	try
	{
		inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
		uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
	}
	catch(Exception ex)
	{
		System.out.println("Error with connection with server  rmi://127.0.0.1/ExtendZedServer...");
	}
}
        	String dueAmt=inf.getSingleValue("select purDueAmt from purchasePaymentSmry where partyNm='"+""+jComboBox1.getSelectedItem()+"' and bookNo='"+""+jComboBox2.getSelectedItem()+"' and srNo='"+""+jComboBox3.getSelectedItem()+"'");
            if(dueAmt!=null)
            	jTextField1.setText(dueAmt);
            else
            	jTextField1.setText("0");
        }
        catch(Exception e)
        {
        	System.out.println("Error at jComboBox3.actionPerformed.."+e);
        }
            	
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
// TODO add your handling code here:
	jComboBox3.removeAllItems();
	try
        {
        	ZedInterface inf=null;
ZedInterfaceForMedical uc=null;
try
{
	inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
	uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
}
catch(Exception e)
{
	System.out.println("Error with connection with server "+getIPaddress.IP()+" ...");
	getIPaddress.changeIP();
	try
	{
		inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
		uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
	}
	catch(Exception ex)
	{
		System.out.println("Error with connection with server  rmi://127.0.0.1/ExtendZedServer...");
	}
}
            String arr[]=inf.getResultSetAs_1D_Array("select srNo from purchasePaymentSmry where partyNm='"+""+jComboBox1.getSelectedItem()+"' and bookNo='"+""+jComboBox2.getSelectedItem()+"'  and purDueAmt>0");
            if(arr!=null)
            {
            	for(int i=0;i<arr.length;i++)
            	{
            		jComboBox3.addItem(arr[i]);
            	}
            }
        }
        catch(Exception e)
        {
        	System.out.println("Error at jComboBox2.actionPerformed.."+e);
        }
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// TODO add your handling code here:
		jComboBox2.removeAllItems();
		try
        {
        	ZedInterface inf=null;
ZedInterfaceForMedical uc=null;
try
{
	inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
	uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
}
catch(Exception e)
{
	System.out.println("Error with connection with server "+getIPaddress.IP()+" ...");
	getIPaddress.changeIP();
	try
	{
		inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
		uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
	}
	catch(Exception ex)
	{
		System.out.println("Error with connection with server  rmi://127.0.0.1/ExtendZedServer...");
	}
}
            String arr[]=inf.getResultSetAs_1D_Array("select bookNo from purchasePaymentSmry where partyNm='"+""+jComboBox1.getSelectedItem()+"'  and purDueAmt>0");
            if(arr!=null)
            {
            	for(int i=0;i<arr.length;i++)
            	{
            		jComboBox2.addItem(arr[i]);
            	}
            }
        }
        catch(Exception e)
        {
        	System.out.println("Error at jComboBox1.actionPerformed.."+e);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
