/*
 * ListOfPurchaseing.java
 *
 * Created on May 15, 2010, 10:18 PM
 */

//package medretail;
import java.rmi.*;
/**
 *
 * @author  Deep Pal
 */
public class SaleDateWiseReport extends javax.swing.JInternalFrame {
    
    /** Creates new form ListOfPurchaseing */
    public SaleDateWiseReport(javax.swing.JDesktopPane jDesktopPane1) {
        initComponents();

        this.jDesktopPane1=jDesktopPane1;
        java.awt.Cursor cursor;
        cursor = new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR);
        
        jButton1.setCursor(cursor);
        jButton2.setCursor(cursor);
        jButton3.setCursor(cursor);
        jButton4.setCursor(cursor);
        jTable1.setCursor(cursor);

        vc=new java.util.Vector();
        
        String heading[]={"S.No.","Bill No.","Total Items","Total Amt.","Discount","Tax","Net Amt."};
        dtm1=new javax.swing.table.DefaultTableModel(heading,0);
        jTable1.setModel(dtm1);
                javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
       		javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
       		javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
      		CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
	       	CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
       		CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
      		javax.swing.table.TableColumn column;

      		column=jTable1.getColumn("S.No.");
      		column.setCellRenderer(CRRight);
       		column.setPreferredWidth(35);

      		column=jTable1.getColumn("Bill No.");
      		column.setCellRenderer(CRCenter);
       		column.setPreferredWidth(60);

                column=jTable1.getColumn("Total Items");
      		column.setCellRenderer(CRCenter);
       		column.setPreferredWidth(80);

                column=jTable1.getColumn("Total Amt.");
      		column.setCellRenderer(CRRight);
       		column.setPreferredWidth(130);

                column=jTable1.getColumn("Discount");
      		column.setCellRenderer(CRRight);
       		column.setPreferredWidth(130);

                column=jTable1.getColumn("Tax");
      		column.setCellRenderer(CRRight);
       		column.setPreferredWidth(130);

                column=jTable1.getColumn("Net Amt.");
      		column.setCellRenderer(CRRight);
       		column.setPreferredWidth(130);

                java.util.Date dt=new java.util.Date();
        jTextField1.setText(dt.getDate()+"/"+(dt.getMonth()+1)+"/"+(dt.getYear()+1900));
        jTextField2.setText(dt.getDate()+"/"+(dt.getMonth()+1)+"/"+(dt.getYear()+1900));
        selectedDate1=(dt.getMonth()+1)+"/"+dt.getDate()+"/"+(dt.getYear()+1900);
        selectedDate2=(dt.getMonth()+1)+"/"+dt.getDate()+"/"+(dt.getYear()+1900);
        
        java.awt.Dimension dm=java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        reshape(((dm.width-800)/2)-75,(dm.height-400)/2,790,395);
        jDesktopPane1.add(this);
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Sale Report - Date Wise");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel1.setText("Select Date ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 70, 20);

        jTextField1.setBackground(new java.awt.Color(232, 232, 169));
        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jTextField1.setForeground(new java.awt.Color(0, 51, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(100, 20, 90, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar.gif")));
        jButton1.setMnemonic('d');
        jButton1.setToolTipText("Click here to select reporting date");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(200, 20, 20, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.gif")));
        jButton2.setMnemonic('s');
        jButton2.setText("Show");
        jButton2.setToolTipText("show ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        getContentPane().add(jButton2);
        jButton2.setBounds(390, 13, 130, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.gif")));
        jButton3.setMnemonic('c');
        jButton3.setText("Close");
        jButton3.setToolTipText("close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        getContentPane().add(jButton3);
        jButton3.setBounds(660, 13, 110, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("Select me ");
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 760, 250);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow.gif")));
        jButton4.setMnemonic('n');
        jButton4.setText("Next >>");
        jButton4.setToolTipText("Select a bill and click here");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        getContentPane().add(jButton4);
        jButton4.setBounds(530, 13, 120, 30);

        jLabel2.setBackground(new java.awt.Color(192, 251, 251));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 320, 110, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 320, 110, 20);

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 320, 110, 20);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jLabel5.setText("to");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 20, 20, 14);

        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jCheckBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox1KeyPressed(evt);
            }
        });

        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(80, 20, 20, 20);

        jTextField2.setBackground(new java.awt.Color(232, 232, 169));
        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jTextField2.setForeground(new java.awt.Color(0, 51, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(250, 20, 90, 20);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar.gif")));
        jButton5.setMnemonic('d');
        jButton5.setToolTipText("Click here to select reporting date");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });

        getContentPane().add(jButton5);
        jButton5.setBounds(350, 20, 20, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
// TODO add your handling code here:
        jCheckBox1.setSelected(false);
        jTextField1.setEnabled(false);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_formInternalFrameOpened

    private void jCheckBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox1KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            if(jCheckBox1.isSelected())
        {
            jTextField1.setEnabled(true);
            jButton1.setEnabled(true);
        }
        else
        {
            jTextField1.setEnabled(false);
            jButton1.setEnabled(false);
        }
        }
    }//GEN-LAST:event_jCheckBox1KeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
// TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            jTextField1.setEnabled(true);
            jButton1.setEnabled(true);
        }
        else
        {
            jTextField1.setEnabled(false);
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
                    Cal X=new Cal();
                    jTextField2.setText(X.getdate());
                    selectedDate2=X.getmonth()+"/"+X.getday()+"/"+X.getyear();
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
        Cal X=new Cal();
        jTextField2.setText(X.getdate());
        selectedDate2=X.getmonth()+"/"+X.getday()+"/"+X.getyear();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
                    this.dispose();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
                    callNextScrean();
        }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            setDataInTable();
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
// TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
                    Cal X=new Cal();
                    jTextField1.setText(X.getdate());
                    selectedDate1=X.getmonth()+"/"+X.getday()+"/"+X.getyear();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// TODO add your handling code here:
        if(evt.getClickCount()==1)
        {
                    callNextScrean();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        callNextScrean();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        setDataInTable();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void setDataInTable()
    {
        try {
            /*ConnectDatabase cd=new ConnectDatabase();
            java.sql.Connection connection = cd.getConnection();
            java.sql.Statement st=connection.createStatement();
            java.sql.ResultSet rs=null;
            
            utilityClass uc=new utilityClass();*/
            int flag=0;
            ZedInterface inf=null;
ZedInterfaceForMedical uc=null;
try
{
	inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
	uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
}
catch(Exception e)
{
	System.out.println("Error with connection with server "+getIPaddress.IP()+" ...");
	getIPaddress.changeIP();
	try
	{
		inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
		uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
	}
	catch(Exception ex)
	{
		System.out.println("Error with connection with server  rmi://127.0.0.1/ExtendZedServer...");
	}
}
            while(dtm1.getRowCount()>0)     dtm1.removeRow(0);
            
            double temp=0,tDisAmt=0,tTaxAmt=0,tNetAmt=0;
            vc.removeAllElements();
            String query="select sNo,totalitems,totalAmt,disAmt,taxAmt,netAmt from saleSmry";
            System.out.println("1.........");
            String [][]rs=null;
            if(jCheckBox1.isSelected())
            {
		System.out.println("2.........");
		query+=" where entryDt>=#"+selectedDate1+"# and entryDt<=#"+selectedDate2+"# order by entryDt,sNo";
                System.out.println("Query="+query);
		//rs=st.executeQuery(query);
		rs=inf.getResultSetAs_2D_Array(query,6);
				}
            if(!jCheckBox1.isSelected())
            {
		System.out.println("3.........");
		query+=" where entryDt<=#"+selectedDate2+"# order by entryDt,sNo";
                System.out.println("Query="+query);
		//rs=st.executeQuery(query);
		rs=inf.getResultSetAs_2D_Array(query,6);
            }
            if(rs!=null)
            for(int i=0;i<rs.length;i++) {
                flag=1;
                String arr[]=new String[7];
                arr[0]=""+(dtm1.getRowCount()+1)+". ";
                arr[1]=rs[i][0];
                arr[2]=rs[i][1];
                arr[3]=""+(new java.math.BigDecimal(rs[i][2])).setScale(2,5);
                temp=Double.valueOf(rs[i][3]);
                arr[4]=""+(new java.math.BigDecimal(temp)).setScale(2,5);
                tDisAmt+=temp;
                temp=Double.valueOf(rs[i][4]);
                arr[5]=""+(new java.math.BigDecimal(temp)).setScale(2,5);
                tTaxAmt+=temp;
                temp=Double.valueOf(rs[i][5]);
                arr[6]=""+(new java.math.BigDecimal(temp)).setScale(2,5);
                tNetAmt+=temp;
                
                dtm1.addRow(arr);
                vc.addElement(arr[1]);
            }
            
            jLabel2.setText(""+(new java.math.BigDecimal(tDisAmt)).setScale(2,5));
            jLabel3.setText(""+(new java.math.BigDecimal(tTaxAmt)).setScale(2,5));
            jLabel4.setText(""+(new java.math.BigDecimal(tNetAmt)).setScale(2,5));
            
            //connection.close();
            if(flag==0) {
                javax.swing.JOptionPane.showMessageDialog(this,"Oh!\nNo sale bill found.","Information",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                jButton1.requestFocus();
            }
        } catch(Exception ex) {
            System.out.println("Error..783..."+ex);
        }        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        Cal X=new Cal();
        jTextField1.setText(X.getdate());
        selectedDate1=X.getmonth()+"/"+X.getday()+"/"+X.getyear();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void callNextScrean()
    {
    	try
        {
        	ZedInterface inf=null;
ZedInterfaceForMedical uc=null;
try
{
	inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
	uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
}
catch(Exception e)
{
	System.out.println("Error with connection with server "+getIPaddress.IP()+" ...");
	getIPaddress.changeIP();
	try
	{
		inf=(ZedInterface)Naming.lookup(getIPaddress.IP());
		uc=(ZedInterfaceForMedical)Naming.lookup(getIPaddress.IP());
	}
	catch(Exception ex)
	{
		System.out.println("Error with connection with server  rmi://127.0.0.1/ExtendZedServer...");
	}
}
		
        //utilityClass uc=new utilityClass();
        if(uc.isBlank(jTextField1.getText().trim()))
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Error!\nSelect billing date.","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            jButton1.requestFocus();
        }
        else if(jTable1.getSelectedRow()<0)
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Error!\nSelect a bill.","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            jTable1.requestFocus();
        }
        else
        {
            int sno=Integer.parseInt(""+vc.elementAt(jTable1.getSelectedRow()));
            ShowIndividualSaleBill emp=new ShowIndividualSaleBill(jDesktopPane1,sno,"saleSmry");
        }
        }
        catch(Exception ex)
		{
     		System.out.println("Error ...."+ex);
		}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    javax.swing.table.DefaultTableModel dtm1;
    String selectedDate1;
    String selectedDate2;
    java.util.Vector vc;
    javax.swing.JDesktopPane jDesktopPane1;
}
