/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * View_Polish_Transaction.java
 *
 * Created on Dec 31, 2013, 2:36:13 PM
 */

package golden_shoap;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author user1
 */
public class Chhat_Ka_Cash_Report extends javax.swing.JInternalFrame {
javax.swing.table.DefaultTableModel dtm;
    /** Creates new form View_Polish_Transaction */
    public Chhat_Ka_Cash_Report() {
        initComponents();
            java.util.Date dt=new java.util.Date();
            int date=dt.getDate();
            int month=dt.getMonth()+1;
            int yr=dt.getYear()+1900;
            String setDate=date+"-"+month+"-"+yr;
            jLabel3.setText(setDate);
            jLabel5.setText(setDate);
            
            dtm=new javax.swing.table.DefaultTableModel();
            javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
            CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
            CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
            CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            javax.swing.table.TableColumn column;
            String heading1[]={"S.No","Voucher Number","Date","Jama","Nikala","Comment"};
            dtm=new javax.swing.table.DefaultTableModel(heading1,0);
            jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
            jTable1.setModel(dtm);
            column=jTable1.getColumn("S.No");
            column.setCellRenderer(CRCenter);
            column.setPreferredWidth(80);

            column=jTable1.getColumn("Voucher Number");
            column.setCellRenderer(CRCenter);
            column.setPreferredWidth(135);


            column=jTable1.getColumn("Date");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(140);

            column=jTable1.getColumn("Jama");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(135);

            column=jTable1.getColumn("Nikala");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(145);

            column=jTable1.getColumn("Comment");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(200);


            jLabel6.setText("0.00");
            jLabel9.setText("0.00");
            jLabel1.setText("0.00");

            //To display day Opening in text box
            //displayOpening();
            //end
            jTable1.setEnabled(false);



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Chhat Ka Cash Report");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(204, 0, 204));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(235, 217, 254));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 10, 100, 25);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel2.setText("Date ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 40, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/golden_shoap/cal.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 10, 30, 25);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("To");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 10, 20, 25);

        jLabel5.setBackground(new java.awt.Color(235, 217, 254));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 10, 100, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/golden_shoap/cal.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 10, 30, 25);

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(470, 10, 140, 23);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel10.setText("Opening Amount");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 10, 110, 23);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 10, 620, 50);

        jButton3.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.gif"))); // NOI18N
        jButton3.setMnemonic('d');
        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 70, 190, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 640, 110);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(255, 204, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 640, 380);

        jLabel6.setBackground(new java.awt.Color(235, 217, 254));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(540, 520, 110, 25);

        jLabel1.setBackground(new java.awt.Color(235, 217, 254));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 520, 120, 25);

        jLabel9.setBackground(new java.awt.Color(235, 217, 254));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(540, 550, 110, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Total Difference");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 550, 100, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lite_wallpaper_1600_wallpapersuggest_com-1280x960.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -10, 660, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        Calender c=new Calender();
        jLabel3.setText(c.getdate());

        //To set Opening
        /*jTextField1.setEnabled(true);

        if((c.getdate()).equals(jLabel5.getText()))
        {
            String qry="Select opening from polish_transaction_opening where transaction_date=#"+(c.getdate())+"#";
            String data=Utility.getSingleValue(qry);
            if(data.length()>0)
            {
                jTextField1.setText(data);
            }
            else
            {
                jTextField1.setText("0.00");
            }

        }
        else
        {
            jTextField1.setEnabled(false);
        }*/

        //end
}//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        Calender c=new Calender();
        jLabel5.setText(c.getdate());
        /*jTextField1.setEnabled(true);
        if((c.getdate()).equals(jLabel3.getText()))
        {
            String qry="Select opening from polish_transaction_opening where transaction_date=#"+(c.getdate())+"#";
            String data=Utility.getSingleValue(qry);
            if(data.length()>0)
            {
                jTextField1.setText(data);
            }
            else
            {
                jTextField1.setText("0.00");
            }

        }
        else
        {
             jTextField1.setEnabled(false);
             
        }*/
}//GEN-LAST:event_jButton2MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        boolean b=getData();
        if(b==false)
        { javax.swing.JOptionPane.showMessageDialog(this,"Sorry !!!!!!! there is no transaction");
          jLabel9.setText(jTextField1.getText());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
  
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            getData();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.selectAll();
    }//GEN-LAST:event_jTextField1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

   /* public void displayOpening()
    {
        java.util.Date dt=new java.util.Date();
        int date=dt.getDate();
        int month=dt.getMonth()+1;
        int year=dt.getYear()+1900;
        String d=""+date;
        if(d.length()==1)
        {
            d=0+d;
        }
        String setDate=d+"-"+month+"-"+year;

        String qry="Select opening from polish_transaction_opening where transaction_date=#"+setDate+"#";
        String data=Utility.getSingleValue(qry);
        if(data.length()>0)
        {
            jTextField1.setText(data);
        }
        else
        {
            jTextField1.setText("0.00");

        }
    }*/

    /*public void opening()
    {
        //to find current date
        java.util.Date dt=new java.util.Date();
        int date=dt.getDate();
        int month=dt.getMonth()+1;
        int year=dt.getYear()+1900;
        String d=""+date;
        if(d.length()==1)
        {
            d=0+d;
        }
        String setDate=month+"-"+d+"-"+year;
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];
        //End
        //Opening
        if(date1.equals(date2))
        {
                            double opening=0;
                            if(Double.valueOf(jTextField1.getText())>0)
                            {
                                        opening=Double.valueOf(jTextField1.getText());

                                        //end
                                        //closing
                                        double closing=0;
                                        if(Utility.isDouble(jLabel9.getText()))
                                        {
                                               closing=Double.valueOf(jLabel9.getText());
                                        }
                                        //End

                                        String qry="Select opening from polish_transaction_opening where transaction_date=#"+date1+"#";
                                        String data=Utility.getSingleValue(qry);
                                        if(data.length()>0)
                                        {   System.out.println("Find");
                                            qry="update polish_transaction_opening set opening="+opening+" where transaction_date=#"+date1+"#";
                                            Utility.saveInformation(qry);
                                        }
                                        else
                                        {
                                            qry="insert into polish_transaction_opening values(#"+date1+"#,"+opening+","+closing+")";
                                            Utility.saveInformation(qry);
                                            System.out.println("Not Find");
                                        }
                            }
        }
    }*/
 public boolean getData()
    {   dtm.setRowCount(0);
        int a=0;
        //int toAccount=9;
        String qry=null;
        String date1=null,date2=null;
        String d[]=jLabel3.getText().split("-");
        date1=d[1]+"-"+d[0]+"-"+d[2];
        d=jLabel5.getText().split("-");
        date2=d[1]+"-"+d[0]+"-"+d[2];
        qry="Select * from receive_voucher where voucher_date>=#"+date1+"# and voucher_date<=#"+date2+"# and (voucher_type='Contra'and (by_ac=5 or to_ac=5)) order by voucher_date desc";
        System.out.println(qry);
        String load[][]=Utility.getInformationDD(qry,8);
        System.out.println("Length="+load.length);
        double jama=0;
        double nikala=0;
        String arr[];
        if(load.length>0)
        {
            arr=new String[6];
            for(int i=0;i<load.length;i++)
            {
                arr[4]="";
                arr[3]="";

                arr[0]=""+(i+1);
                arr[1]=load[i][1];
                String da[]=load[i][2].split(" ");
                String da1[]=da[0].split("-");
                arr[2]=da1[2]+"-"+da1[1]+"-"+da1[0];
                if((Double.valueOf(load[i][3])==5))
                {   nikala=nikala+(Double.valueOf(load[i][5]));
                    java.math.BigDecimal bd=new java.math.BigDecimal(load[i][5]);
                    arr[4]=(""+bd.setScale(2,5));
                   
                }
                else
                {
                    jama=jama+(Double.valueOf(load[i][5]));
                    java.math.BigDecimal bd=new java.math.BigDecimal(load[i][5]);
                    arr[3]=(""+bd.setScale(2,5));
                   
                }
                arr[5]=load[i][6];

                dtm.addRow(arr);
            }
              
            java.math.BigDecimal bd=new java.math.BigDecimal(nikala);
            jLabel6.setText(""+bd.setScale(2,5));
            bd=new java.math.BigDecimal(jama);
            jLabel1.setText(""+bd.setScale(2,5));
            jLabel9.setText(""+(jama-nikala));

          opening();



            /*double opening=0;
            if(Utility.isDouble(jTextField1.getText()))
            {
                 opening=Double.valueOf(jTextField1.getText());
            }
            //To manage opening when user select date range(opening does not add in the table)
            java.util.Date dt=new java.util.Date();
            int date=dt.getDate();
            int month=dt.getMonth()+1;
            int year=dt.getYear()+1900;
            String d1=""+date;
            if(d1.length()==1)
            {
                d1=0+d1;
            }
            //setDate is used to compare compare date1 and date2 in mm/dd/yyyy format
            String setDate=month+"-"+d1+"-"+year;
            System.out.println("Set Date"+setDate);
            System.out.println("Date 1  "+date1);
            System.out.println("Date 2  "+date2);

            if(date1.equals(date2))
            {   System.out.println("GGGGGGGGGGGG");
                bd=new java.math.BigDecimal(receiveTotal-paymentTotal+opening);
                jLabel9.setText(""+bd.setScale(2,5));
            }
            else
            {   System.out.println("GGGGGGGGGGGG1111111111111");
                bd=new java.math.BigDecimal(receiveTotal-paymentTotal);
                jLabel9.setText(""+bd.setScale(2,5));
                jTextField1.setEnabled(false);
            }
            //End

            //to insert opening and closing of current date in a polish_transaction_opening table
            opening();
            //end*/

            return true;
         }
        else
        {
            jLabel6.setText("0.00");
             //opening();
            jLabel9.setText("0.00");
            jLabel1.setText("0.00");
            opening();
            return false;
        }

       
    }
 public void opening()
 {

 //for opening
            double opening=0;
            String d[]=jLabel3.getText().split("-");
            String date1=d[1]+"-"+d[0]+"-"+d[2];

            String qry="Select * from receive_voucher where voucher_date<#"+date1+"# and voucher_type='Contra' order by voucher_date desc";
            System.out.println(qry);
            String load1[][]=Utility.getInformationDD(qry,8);

            //to set opening in the text field
            qry="select ac_opening,opening_status from ac_smry where ac_code=5";
            String data[][]=Utility.getInformationDD(qry,2);
            if(data.length!=0)
            {
                if(data[0][1].equals("Jama Hai"))
                {
                    opening=Double.valueOf(data[0][0]);
                }
                if(data[0][1].equals("Udhaar Hai"))
                {
                    opening=Double.valueOf(data[0][0]);
                    opening=(-opening);
                }
            }
            else
            {
                opening=0.00;
            }
            //end

            double jama=0;
            double nikala=0;
            if(load1.length>0)
            {   for(int i=0;i<load1.length;i++)
                {
                    if((Double.valueOf(load1[i][3])==5))
                    {   nikala=nikala+(Double.valueOf(load1[i][5]));
                    }
                    else
                    {
                        jama=jama+(Double.valueOf(load1[i][5]));
                    }
                }

                jTextField1.setText(""+(jama-nikala+opening));
            }
            else
            { jTextField1.setText(""+opening); }
            //End

 }

}

