 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Police_customer_work.java
 *
 * Created on Dec 12, 2013, 10:25:21 AM
 */

package golden_shoap;
import java.math.RoundingMode;
import java.sql.*;
/**
 *
 * @author user1
 */
public class Product_work extends javax.swing.JInternalFrame {
 javax.swing.table.DefaultTableModel dtm;
// static int sNo=0;
    /** Creates new form Police_customer_work */
    public Product_work() {
        initComponents();

         dtm=new javax.swing.table.DefaultTableModel();

            javax.swing.table.DefaultTableCellRenderer CRLeft = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRRight = new javax.swing.table.DefaultTableCellRenderer();
            javax.swing.table.DefaultTableCellRenderer CRCenter = new javax.swing.table.DefaultTableCellRenderer();
            CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
            CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
            CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            javax.swing.table.TableColumn column;
            String heading1[]={"S.No","Rate Apply On","Item Name","Quantity","Unit","Weight","Unit"};
            dtm=new javax.swing.table.DefaultTableModel(heading1,0);
            jTable1.setModel(dtm);
            column=jTable1.getColumn("S.No");
            column.setCellRenderer(CRCenter);
            column.setPreferredWidth(70);

            column=jTable1.getColumn("Rate Apply On");
            column.setCellRenderer(CRCenter);
            column.setPreferredWidth(100);

            column=jTable1.getColumn("Item Name");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(200);

            column=jTable1.getColumn("Quantity");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(100);

            column=jTable1.getColumn("Unit");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(180);

            column=jTable1.getColumn("Weight");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(130);

            column=jTable1.getColumn("Unit");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(60);

            /*column=jTable1.getColumn("Rate");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(60);*/

            /*column=jTable1.getColumn("Unit");
            column.setCellRenderer(CRLeft);
            column.setPreferredWidth(60);*/

            /*column=jTable1.getColumn("Amount");
            column.setCellRenderer(CRRight);
            column.setPreferredWidth(75);*/

            comboCustomerName();
            comboItemName();
          
            quantityCombo();
            applyOnCombo();
            setDate();
            jComboBox1.requestFocus();
            
           //for zerox of payable amount
            jLabel22.setVisible(false);
            //

            setPurjaNumber();

            //Product work
                jComboBox4.setSelectedItem("Groos");
                jComboBox5.setSelectedItem("Quantity");
                jComboBox2.requestFocus();

                jButton5.setEnabled(false);
                jButton3.setEnabled(false);
            //End

            
            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 182));
        setClosable(true);
        setIconifiable(true);
        setTitle("Product Work ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel1.setText("         Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 20, 80, 23);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel2.setText("Serial Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(580, 20, 100, 23);

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 20, 180, 23);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel5.setText("Item Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 80, 80, 23);

        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(340, 80, 180, 23);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 80, 60, 23);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton1.setMnemonic('e');
        jButton1.setText("Receive");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 130, 460, 23);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.gif"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 130, 30, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 740, 240);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/receive2.png"))); // NOI18N
        jButton3.setMnemonic('f');
        jButton3.setText("Finally Receive & Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 440, 200, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/receive1.png"))); // NOI18N
        jButton4.setMnemonic('r');
        jButton4.setText("Only Receive");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(220, 440, 170, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.gif"))); // NOI18N
        jButton6.setMnemonic('c');
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed1(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton6KeyReleased(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(580, 440, 170, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 490, 920, 10);

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("jLabel10");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 20, 90, 23);

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("jLabel11");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(680, 20, 70, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/golden_shoap/cal.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jLabel12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel12KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(530, 20, 30, 20);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(590, 80, 60, 23);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PRINT.GIF"))); // NOI18N
        jButton5.setMnemonic('p');
        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(400, 440, 170, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 60, 1020, 10);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel13.setText("Rate apply On");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 130, 100, 23);

        jComboBox4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox4KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(660, 80, 90, 23);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel14.setText("Weight");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 80, 60, 23);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 80, 120, 23);

        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jComboBox5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox5KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(110, 130, 120, 23);

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel19.setText(" Kg");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setOpaque(true);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(200, 80, 30, 23);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(780, 460, 40, 0);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.gif"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(190, 20, 25, 25);

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1277137333.or.23246.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(-50, -30, 840, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPurjaNumber()
    {
        try
        {
            int purjaNumber=0;
            String qry="select max(purja_number) from product_work";
            String str=Utility.getSingleValue(qry);
            System.out.println("Hiiiiii");
             if(str==null)
             {
                jLabel11.setText("1");
             }
            else
             {
                purjaNumber=Integer.parseInt(str);
                jLabel11.setText(""+(purjaNumber+1));
             }
        }
        catch(NullPointerException npe)
        {
            System.out.println(npe);
        }
    }

    public void setDate()
    {
        java.util.Date dt=new java.util.Date();
        int date=dt.getDate();
        int month=dt.getMonth()+1;
        int year=dt.getYear()+1900;
        String d=""+date;
        if(d.length()==1)
        {
            d=0+d;
        }
        String setDate=d+"-"+month+"-"+year;
        jLabel10.setText(setDate);

    }
    public void calenderDate()
    {
         Calender c=new Calender();
        jLabel10.setText(c.getdate());

    }
    public void comboCustomerName()
    {
                      jComboBox1.removeAllItems();
                      int accountCategory=2;
                      int accountGroup=19;
                      String qry="select ac_name from ac_master where ac_group_code="+accountGroup+" and ac_category_code="+accountCategory+" and ac_code>10 order by ac_name";
                      String[][] data=Utility.getInformationDD(qry,1);
                      int length= data.length;
                      for(int i=0;i<length;i++)
                      {   jComboBox1.addItem(data[i][0]);
                      }

    }
    public void comboItemName()
    {
                      String qry="select item_name from product_item_master order by item_name "  ;
                      String[][] data=Utility.getInformationDD(qry,1);
                      //jComboBox2.addItem("Select");
                      int length= data.length;
                      for(int i=0;i<length;i++)
                      {   jComboBox2.addItem(data[i][0]);
                      }

    }
    
    public void quantityCombo()
    {
                      String qry="select unit_name from polish_table_unit"  ;
                      String[][] data=Utility.getInformationDD(qry,1);
                     // jComboBox3.addItem("Select");
                      int length= data.length;
                      for(int i=0;i<length;i++)
                      {   jComboBox4.addItem(data[i][0]);
                      }

    }
     public void applyOnCombo()
    {
         jComboBox5.addItem("Weight");
         jComboBox5.addItem("Quantity");
     }


     public boolean save()
    {
         //Check the validation of discount and paid amount text box
                   //Discount
                   
          if((dtm.getRowCount())>0)
           {
                                      String date=jLabel10.getText();
                                      String d[]=date.split("-");
                                      date=d[1]+"-"+d[0]+"-"+d[2];
                                      //End
                                     
                                      int purjaNumber=Integer.parseInt(jLabel11.getText());
                                      String accountName=""+jComboBox1.getSelectedItem();
                                      String qry="select ac_code from ac_master where ac_name='"+accountName+"'";
                                      int accountCode=Integer.parseInt(Utility.getSingleValue(qry));

                                      //double paidAtReceive=Double.valueOf(jTextField7.getText());

                                      double newAmount=0;
                                      String receivingDate="1/1/1950";
                                      String itemName="";
                                      String polishType="";
                                      double quantity=0;
                                      String quantityUnit="";
                                      double weight=0;
                                      String weightUnit="";
                                      double rate=0;
                                      String rateUnit="";
                                      int row=dtm.getRowCount();
                                      double amount=0;
                                      String rateApplyOn="";
                                      //double weightAfterPolish=0;
                                      //String paymentApply="";
                                      boolean bn=false;
                                      //String cancle="No";
                                      //int quantityAfterPolish=0;
                                      for(int i=0;i<row;i++)
                                      {       rateApplyOn=""+dtm.getValueAt(i,1);
                                              itemName=""+dtm.getValueAt(i,2);
                                              quantity=Double.valueOf(""+dtm.getValueAt(i,3));
                                              quantityUnit=(""+dtm.getValueAt(i,4));
                                              weight=Double.valueOf(""+dtm.getValueAt(i,5));
                                              weightUnit=(""+dtm.getValueAt(i,6));
                                              //rate=Double.valueOf(""+dtm.getValueAt(i,6));
                                              rate=0;
                                              rateUnit="";//(""+dtm.getValueAt(i,7));
                                              //paymentApply=(""+dtm.getValueAt(i,1));
                                              amount=0;//Double.valueOf(""+dtm.getValueAt(i,8));
                                              //newAmount=newAmount+(Double.valueOf(amount));
                                              qry="insert into product_work values(#"+date+"#,"+purjaNumber+","+accountCode+",'"+itemName+"',"+quantity+",'"+quantityUnit+"',"+weight+",'"+weightUnit+"',"+rate+",'"+rateUnit+"',"+amount+",#"+receivingDate+"#,'"+rateApplyOn+"')";
                                              System.out.println(""+qry);
                                              bn=Utility.saveInformation(qry);
                                      }
        
                                        /*String acName=""+jComboBox1.getSelectedItem();

                                        qry="select ac_code from ac_master where ac_name='"+acName+"'";
                                        int acCode=Integer.parseInt(Utility.getSingleValue(qry));

                                        qry="select ac_dr from ac_smry where ac_code="+4+"";
                                        double acDr=Double.valueOf(Utility.getSingleValue(qry));
                                        acDr=acDr+(newAmount);
                                        qry="Update ac_smry set ac_dr="+acDr+" where ac_code="+4+"";
                                        Utility.saveInformation(qry);

                                        qry="select ac_cr from ac_smry where ac_code="+acCode+"";
                                        double acCr=Double.valueOf(Utility.getSingleValue(qry));
                                        acCr=acCr+(newAmount);
                                        qry="Update ac_smry set ac_cr="+acCr+" where ac_code="+acCode+"";
                                        Utility.saveInformation(qry);*/

                                     //End
                                              jTextField1.setText("");
                                              jTextField2.setText("");
                                            //  jTextField3.setText("");
                                              jComboBox4.setSelectedItem("Groos");
                                              jComboBox5.setSelectedItem("Quantity");
                                              //jComboBox6.setSelectedItem("Before Polish");
                                              jTextField1.requestFocus();
                                             dtm.setRowCount(0);
  
           }
           else
           {
                javax.swing.JOptionPane.showMessageDialog(this,"There is no record." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                jComboBox2.requestFocus();
                return false;
           }
         return true;
        }
    public void dataAddToTable()
    {   
      try
      {
             if((jTextField1.getText()).equals("")&& (jComboBox5.getSelectedItem().equals("Weight")))
             {
                javax.swing.JOptionPane.showMessageDialog(this,"Enter weight." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                jTextField1.requestFocus();
             }
             else if((jTextField2.getText()).equals("") && (jComboBox5.getSelectedItem().equals("Quantity")))
             {
                javax.swing.JOptionPane.showMessageDialog(this,"Enter item quantity. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                jTextField2.requestFocus();
             }
             else if((Utility.isInteger(jTextField2.getText()) == false) && (jComboBox5.getSelectedItem().equals("Quantity")))
             {

                javax.swing.JOptionPane.showMessageDialog(this,"Error.... Please enter item quantity in whole number formate. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                jTextField2.requestFocus();
             }
            /* else if((jTextField3.getText()).equals(""))
             {
                javax.swing.JOptionPane.showMessageDialog(this,"Enter rate. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                jTextField3.requestFocus();
             }*/
            /* else if(Utility.isDouble(jTextField3.getText()) == false)
             {
                javax.swing.JOptionPane.showMessageDialog(this,"Error.... Please enter valid rate. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                jTextField3.requestFocus();
             }*/
             else
             {
                                    //to set quantity = 0 if rate apply on weight and quantity is blank
                                    if(jComboBox5.getSelectedItem().equals("Quantity"))
                                    {
                                        if(jTextField1.getText().isEmpty())
                                        {
                                            jTextField1.setText("0");
                                        }
                                    }
              if((jButton1.getLabel()).equals("Receive"))
              {
                                 int sNo=(Integer.parseInt(""+jTable1.getRowCount())+1);

                                 String str[]=new String[7];
                                 str[0]=""+sNo;
                                 //str[1]=""+jComboBox6.getSelectedItem();
                                 str[1]=""+jComboBox5.getSelectedItem();
                                 str[2]=""+jComboBox2.getSelectedItem();
                                 str[3]=jTextField2.getText();
                                 // str[2]=""+jComboBox3.getSelectedItem();
                                
                                 str[4]=""+jComboBox4.getSelectedItem();
                                 java.math.BigDecimal bd=new java.math.BigDecimal(""+jTextField1.getText());
                                 str[5]=""+bd.setScale(3,5);
                                 str[6]="Kg";
                                 /*java.math.BigDecimal bd3=new java.math.BigDecimal(""+jTextField3.getText());
                                 str[6]=""+bd3.setScale(2,5);*/
                                // str[6]=""+jLabel8.getText();
                                 //to manage before polish and after polish
                                 //if((jComboBox6.getSelectedItem()).equals("Before Polish"))
                                // {
                                        /* double weight=0;
                                         if((jComboBox5.getSelectedItem()).equals("Weight"))
                                          {
                                                weight=(Double.valueOf(jTextField1.getText()));
                                          }
                                         else
                                         {
                                              weight =(Double.valueOf(jTextField2.getText()));
                                         }
                                         double rate =(Double.valueOf(jTextField3.getText()));
                                         double amount=(weight*rate);
                                         java.math.BigDecimal bd1=new java.math.BigDecimal(amount);
                                         str[7]=""+bd1.setScale(2,5);*/
                                         dtm.addRow(str);
                                   
                                 //end

                                                             
                                                              jTextField1.setText("");
                                                              jTextField2.setText("");
                                                              //jTextField3.setText("");
                                                              
                                                              jComboBox4.setSelectedItem("Groos");
                                                              jComboBox5.setSelectedItem("Quantity");
                                                              
                                                              jTextField1.requestFocus();

                 }
                else
                {
                    if(jTable1.getRowCount()>0)
                    {
                        if(jTable1.getSelectedRowCount()==1)
                        {

                                 int check=javax.swing.JOptionPane.showConfirmDialog(this,"Are you sure to update record ?" ,"Confirm Window",javax.swing.JOptionPane.YES_NO_OPTION,javax.swing.JOptionPane.QUESTION_MESSAGE);
                                 if(check==javax.swing.JOptionPane.YES_OPTION)
                                 {
                                    java.math.BigDecimal bd4=new java.math.BigDecimal(jTextField1.getText());
                                    String tweight=(""+bd4.setScale(3,5));
                                    /*bd4=new java.math.BigDecimal(jTextField3.getText());
                                    String trate=(""+bd4.setScale(2,5));*/

                                    int row=jTable1.getSelectedRow();
                                    //jTable1.setValueAt((""+jComboBox6.getSelectedItem()), row, 1);
                                    jTable1.setValueAt((""+jComboBox5.getSelectedItem()), row, 1);
                                    jTable1.setValueAt((""+jComboBox2.getSelectedItem()), row, 2);
                                    //jTable1.setValueAt((""+jComboBox3.getSelectedItem()), row, 2);
                                    jTable1.setValueAt((""+jTextField2.getText()), row, 3);
                                    jTable1.setValueAt((""+jComboBox4.getSelectedItem()), row, 4);
                                    jTable1.setValueAt((tweight), row, 5);
                                    //jTable1.setValueAt((""+trate), row, 6);
                                    jTable1.setValueAt((""+jLabel19.getText()), row, 6);
                                               /*  double weight=0;
                                                 if((jComboBox5.getSelectedItem()).equals("Weight"))
                                                  {
                                                                      weight=(Double.valueOf(jTextField1.getText()));
                                                  }
                                                 else
                                                 {
                                                                     weight =(Double.valueOf(jTextField2.getText()));
                                                  }
                                                                     double rate =(Double.valueOf(jTextField3.getText()));
                                                                     double amount=(weight*rate);
                                                                     bd4=new java.math.BigDecimal(amount);

                                                                     jTable1.setValueAt(((bd4.setScale(2,5))), row, 7);
                                                 */
                                                                     int count=dtm.getRowCount();
                                                                      jTextField1.setText("");
                                                                      jTextField2.setText("");
                                                                     // jTextField3.setText("");
                                                                     
                                                                      jComboBox4.setSelectedItem("Groos");
                                                                      //jComboBox6.setSelectedItem("Before Polish");
                                                                      jComboBox5.setSelectedItem("Quantity");
                                                                      jTextField1.requestFocus();
                                                                      jButton1.setLabel("Receive");

                                        }
                                         if(check==javax.swing.JOptionPane.NO_OPTION)
                                        {
                                          jTextField1.requestFocus();
                                        }
                        }
                      else
                        {
                          javax.swing.JOptionPane.showMessageDialog(this,"Error... please select rocord from the table that you want to update." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                    else
                    {
                      javax.swing.JOptionPane.showMessageDialog(this,"Error... There is no record in the table." ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    }

                }
             }
        }
        catch(NullPointerException ex)
        {
             javax.swing.JOptionPane.showMessageDialog(this,"All field must be entered. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        //jComboBox6.setEnabled(true);
     }

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode()==10)
        {
           jTextField1.requestFocus();
        }
        
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode()==10)
        {

                jTextField2.requestFocus();
        }

    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
               
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            dataAddToTable();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            dataAddToTable();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
              jComboBox4.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String str=jButton1.getLabel();
        if(str.equals("Receive"))
        {
            jButton1.setLabel("Update");
        }
        else
        {
            jButton1.setLabel("Receive");
            jTextField1.setText("");
             jTextField2.setText("");
             // jTextField3.setText("");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      // TODO add your handling code here:
      int row= jTable1.getSelectedRow();
      //jComboBox6.setSelectedItem(""+jTable1.getValueAt(row,1));
      jComboBox5.setSelectedItem(""+jTable1.getValueAt(row,1));
      jComboBox2.setSelectedItem(""+jTable1.getValueAt(row,2));
      //jComboBox3.setSelectedItem(""+jTable1.getValueAt(row,2));
      jTextField2.setText(""+jTable1.getValueAt(row,3));
      jComboBox4.setSelectedItem(""+jTable1.getValueAt(row,4));
      jTextField1.setText(""+jTable1.getValueAt(row,5));
      //jTextField3.setText(""+jTable1.getValueAt(row,6));
      jLabel19.setText("Kg");
      jButton1.setLabel("Update");
      /*if(jTable1.getValueAt(row,8).equals("Kg"))
      {
          jComboBox5.setSelectedItem("Weight");
      }
      else
      {
          jComboBox5.setSelectedItem("Quantity");
      }*/
      
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==127)
        {
            int check=javax.swing.JOptionPane.showConfirmDialog(this,"Are you sure to delete record ?" ,"Confirm Window",javax.swing.JOptionPane.YES_NO_OPTION,javax.swing.JOptionPane.QUESTION_MESSAGE);
             if(check==javax.swing.JOptionPane.YES_OPTION)
             {

                        int selectedRow= jTable1.getSelectedRow();
                        dtm.removeRow(selectedRow);

                         jTextField1.requestFocus();
                         jButton1.setLabel("Receive");
                         jTextField2.setText("");
                         //jTextField3.setText("");
                         jTextField1.setText("");
                         jComboBox4.setSelectedItem("Piece");
                         jComboBox5.setSelectedItem("Weight");
                         //jComboBox6.setSelectedItem("Before Weight");

              }
            if(check==javax.swing.JOptionPane.NO_OPTION)
             {
                 jTextField1.requestFocus();
            }

        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

       boolean b=save();
       if(b==true)
       {    javax.swing.JOptionPane.showMessageDialog(this,"Record sucessfully save. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            setPurjaNumber();
            //this.dispose();
       }
      
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String str=javax.swing.JOptionPane.showInputDialog(this, "Please enter Purja no.","Print Purja",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        boolean flag=false;
        if(str!=null || (str.isEmpty()==false))
        {   if(Utility.isInteger(str))
            {
                int purja=Integer.parseInt(str);
                String qry="select distinct purja_number from deliver_product_item ";
                String data[][]=Utility.getInformationDD(qry,1);
                for(int i=0;i<data.length;i++)
                {
                    int purjaNumber=Integer.parseInt(data[i][0]);
                    if(purjaNumber==purja)
                    {       flag=true;
                    }
                }
            }
        }
        if(flag==true)
        {
                        printchallan2 pt=new printchallan2(str);
        }
        else
        {
             javax.swing.JOptionPane.showMessageDialog(this,"Error... Please enter valid purja number . " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode()==10)
      {
       boolean b=save();
       if(b==true)
       {    javax.swing.JOptionPane.showMessageDialog(this,"Record sucessfully save. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            setPurjaNumber();
            //this.dispose();
       }
      }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
                        String str=javax.swing.JOptionPane.showInputDialog(this, "Please enter Purja no.","Print Purja",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        boolean flag=false;
                        if(str!=null || (str.isEmpty()==false))
                        {   if(Utility.isInteger(str))
                            {
                                int purja=Integer.parseInt(str);
                                String qry="select distinct purja_number from product_work";
                                String data[][]=Utility.getInformationDD(qry,1);
                                for(int i=0;i<data.length;i++)
                                {
                                    int purjaNumber=Integer.parseInt(data[i][0]);
                                    if(purjaNumber==purja)
                                    {       flag=true;
                                    }

                                }
                            }
                        }
                        if(flag==true)
                        {
                                        printchallan2 pt=new printchallan2(str);
                        }
                        else
                        {
                             javax.swing.JOptionPane.showMessageDialog(this,"Error... Please enter vlaid purja number . " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        }

        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       if((dtm.getRowCount())>=1)
       {
        save();
        String str=jLabel11.getText().trim();
        printchallan2 pt=new printchallan2(str);
        setPurjaNumber();
        this.dispose();
       }
        else
       {
               javax.swing.JOptionPane.showMessageDialog(this,"Error... There is no record in the table. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
        //for printing
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
                   if((dtm.getRowCount())>=1)
                   {
                    save();
                    String str=jLabel11.getText().trim();
                    printchallan2 pt=new printchallan2(str);
                    setPurjaNumber();
                    this.dispose();
                   }
                    else
                   {
                           javax.swing.JOptionPane.showMessageDialog(this,"Error... There is no record in the table. " ,"Message Box",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    }
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel12KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel12KeyPressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        calenderDate();
}//GEN-LAST:event_jLabel12MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10) {
            jComboBox2.requestFocus();
        }
}//GEN-LAST:event_jTextField1KeyPressed

    private void jComboBox4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10) {
            jComboBox5.requestFocus();
        }
}//GEN-LAST:event_jComboBox4KeyPressed

    private void jComboBox5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10) {
            jButton1.requestFocus();
        }
}//GEN-LAST:event_jComboBox5KeyPressed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
/*        if(jComboBox5.getSelectedItem().equals("Weight"))
        {          //jComboBox6.setEnabled(true);
            jLabel8.setText("Kg");
        }
        else
        {
            jLabel8.setText(""+jComboBox4.getSelectedItem());
        }
       if(jComboBox5.getSelectedItem().equals("Quantity"))
        {
            jComboBox6.setSelectedItem("Before Polish");
            //jComboBox6.setEnabled(false);
            //jTextField3.requestFocus();
        }*/

    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        comboCustomerName();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            comboCustomerName();
        }
    }//GEN-LAST:event_jButton7KeyPressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton6ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed1
        // TODO add your handling code here:
        this.dispose();


    }//GEN-LAST:event_jButton6ActionPerformed1

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButton6KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    boolean firsttime1=false;
    int purjano;
    class printchallan2
    {
                PrintPanel2 canvas;
	        java.awt.print.PageFormat pageFormat;

        	public printchallan2(String str)
        	{
                    purjano=Integer.parseInt(str);
                    System.out.println("print constructor");

                                canvas=new PrintPanel2();
                                java.awt.print.PrinterJob printJob=java.awt.print.PrinterJob.getPrinterJob();
                                double width=8.27 * 72;
                                double height=(11.69 * 72);

                                java.awt.print.Paper paper=new java.awt.print.Paper();

                                paper.setSize(width,height);

                                java.awt.print.PageFormat page=new java.awt.print.PageFormat();
                                page.setOrientation(java.awt.print.PageFormat.PORTRAIT);
                                paper.setImageableArea(5,10,paper.getWidth(),paper.getHeight());
                                page.setOrientation(java.awt.print.PageFormat.PORTRAIT);
                                page.setPaper(paper);
                                pageFormat=printJob.defaultPage(page);
                                pageFormat.setPaper(paper);
                                pageFormat.setOrientation(java.awt.print.PageFormat.PORTRAIT);
                                printJob.setPrintable(canvas,pageFormat);

                                try
                                {
					//no of pages
                                        printJob.print();
                                }
                                catch(Exception exception)
                                {
                                        javax.swing.JOptionPane.showMessageDialog(null,"error2="+exception);
                                }
                                //jButton5.setEnabled(true);
        		    }
	}//print class


    class PrintPanel2 extends javax.swing.JPanel implements java.awt.print.Printable
	{

        int page=100;
		java.awt.font.TextLayout layout;
		java.awt.Font f,f1,f2,f3,f4,f5,f6;
		java.awt.Graphics2D g2;
		int row=0;
		java.awt.font.FontRenderContext context;


        public PrintPanel2()
        {
                //ChallanNo=JOptionPane.showInputDialog(null,"Enter Challan Number:");
        }
        public void paintComponent(java.awt.Graphics g)
        {
                super.paintComponent(g);
                System.out.println("BPPRINT");
                java.awt.Graphics2D g2=(java.awt.Graphics2D)g;
                drawPage(g2);

        }

        public int print(java.awt.Graphics g,java.awt.print.PageFormat pf,int page) throws java.awt.print.PrinterException
        {
                if(page>=1)
                return java.awt.print.Printable.NO_SUCH_PAGE;
                java.awt.Graphics2D g2=(java.awt.Graphics2D)g;
                g2.setPaint(java.awt.Color.black);
                g2.translate(pf.getImageableX(),pf.getImageableY());

                System.out.println("W1="+pf.getImageableWidth()+"H1="+pf.getImageableHeight());

                //if(printflag==5)
                //{
                	drawPage(g2);
                //}

                return java.awt.print.Printable.PAGE_EXISTS;
        }
        public void drawPage(java.awt.Graphics2D g2)
        {
            this.g2=g2;
	    System.out.println("Hellospecial"+firsttime1);
            //System.out.println("inside draw page..."+totalamt);
            context=g2.getFontRenderContext();
            f1=new java.awt.Font("Times New Roman",java.awt.Font.BOLD,10);
            f2=new java.awt.Font("Arial",java.awt.Font.PLAIN,8);
            f3=new java.awt.Font("Arial",java.awt.Font.PLAIN,30);
            f4=new java.awt.Font("Arial",java.awt.Font.BOLD,10);
            f5=new java.awt.Font("Verdana",java.awt.Font.PLAIN,10);
            f6=new java.awt.Font("Verdana",java.awt.Font.BOLD,10);
            java.awt.Font f7=new java.awt.Font("Arial",java.awt.Font.BOLD,13);
            java.awt.Font f8=new java.awt.Font("Times New Roman",java.awt.Font.BOLD,25);
            java.awt.Font f9=new java.awt.Font("Arial narrow",java.awt.Font.PLAIN,2);
            java.awt.FontMetrics fm;
            java.awt.geom.GeneralPath clipShape=new java.awt.geom.GeneralPath();
            String str=" fdfg dfg dfg";
            String str1="d fgf dgdfg df";
            g2.setFont(f1);
            layout=new java.awt.font.TextLayout(str,f1,context);
            java.awt.geom.AffineTransform transform=java.awt.geom.AffineTransform.getTranslateInstance(10,20);

            g2.setFont(f2);
            fm=g2.getFontMetrics();

			if(firsttime1==false)
			{
				firsttime1=true;
            		}
                        else
                        {   firsttime1=false;
                            int top=20;
                            int i=0;
                            int j=0;
                            int z=0;
                            //double receiveAmount=0;
                            //double discount=0;
                            //double payableAmount=0;
                            String date="";
                            int pur=purjano;
                            String qry="Select rec_date from polish_details where purja_number="+pur+"";
                            String dd=Utility.getSingleValue(qry);
                            String d[]=dd.split(" ");
                            String d1[]=d[0].split("-");
                            date=d1[2]+"-"+d1[1]+"-"+d1[0];
                            g2.setFont(f6);
                            fm=g2.getFontMetrics();
                            String temp="Receiving Dt : "+date;
                            g2.drawString(temp,15,top+10);
                            qry="Select ac_code from product_work where purja_number="+pur+"";
                            int cid=Integer.parseInt(Utility.getSingleValue(qry));
                            qry="Select ac_name from ac_master where ac_code="+cid+"";
                            String accountName=""+(Utility.getSingleValue(qry));
                            temp="Customer Name : "+accountName;
                            g2.drawString(temp,200,top+10);
                            temp="Purja Number :"+purjano;
                            g2.drawString(temp,465,top+10);
                            top=top+25;
                            g2.drawLine(15, top, 575, top);
                            //for heading
                            top=top+15;
                            temp="S.No       Weight     Item Name                    Quantity          Quantity unit         Rate                  Amount";
                            g2.drawString(temp,15,top);
                            top=top+10;
                            g2.drawLine(15, top, 575, top);
                            //End
                            //for data printing
                            g2.setFont(f5);
                            fm=g2.getFontMetrics();
                            qry="Select * from polish_details where purja_number="+pur+"";
                            String load[][]=Utility.getInformationDD(qry,17);
                            double total=0;
                            double totamt=0;
                            String weight="";
                            String itemName="";
                       //     String polishType="";
                            String quantity="";
                            String unit="";
                            String rate="";
                            String rateUnit="";
                            String amount="";
                            String temp1="";
                            String temp2="";
                            String temp3="";
                            String temp4="";
                            String temp5="";
                            String temp6="";
                            String temp7="";
                            String temp8="";
                            String temp9="";
                            String temp10="";
                            String temp11="";
                            String temp12="";

                            top=top+25;
                            if(load.length>0)
                            {
                                    for(i=0,j=(-10);i<load.length;i++,j=j+15)
                                    {
                                        weight=load[i][6];
                                        itemName=load[i][2];
                                        //polishType=load[i][4];
                                        quantity=load[i][3];
                                        unit=load[i][4];
                                        rate=load[i][8];
                                        rateUnit=load[i][9];
                                        amount=load[i][10];
                                        total=total+Double.valueOf(amount);
                                        temp4=(i+1)+".";
                                        z=fm.stringWidth(temp4);
                                        java.math.BigDecimal bd=new java.math.BigDecimal(weight);
                                        temp5=""+bd.setScale(3,5);
                                        temp6=itemName;
                                        //temp7=polishType;
                                        temp7=quantity;
                                        temp8=unit;
                                        bd=new java.math.BigDecimal(rate);
                                        temp9=""+bd.setScale(2,5);
                                        temp10=rateUnit;
                                        bd=new java.math.BigDecimal(amount);
                                        temp11=""+bd.setScale(2,5);
                                        g2.drawString(temp4,40-z,top+j);
                                        //to display weight in bold if rate*weight
                                        
                                    }
                           }
                    }

     }


    }
}
