/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myplayer;

import java.awt.Color;
import java.awt.*;
import java.io.File;
import javax.swing.table.*;
import javax.swing.*;

/**
 *
 * @author Sanjay
 */
public class PlayList extends javax.swing.JInternalFrame {
javax.swing.table.DefaultTableModel dtm;

Color cl1;
Color cl2;
    /**
     * Creates new form PlayList
     */
    public PlayList(String sname, int min, int sec, File name[]) {
        initComponents();
        
        String top_heading="",song_name="",arr_item="";
        String arr[]=new String[1];
        int current_row=0;
        
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
//        jTable1.setEnabled(false);
        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        
        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        
        if(min/10==0 && sec/10==0)
        {
            top_heading="[Playlist - File Open]"+" "+"["+"0"+min+":"+"0"+sec+"]";
        }

        if(min/10==0 && sec/10!=0)
        {
            top_heading="[Playlist - File Open]"+" "+"["+"0"+min+":"+sec+"]";
        }

        if(min/10!=0 && sec/10==0)
        {
            top_heading="[Playlist - File Open]"+" "+"["+min+":"+"0"+sec+"]";
        }

        if(min/10!=0 && sec/10!=0)
        {
            top_heading="[Playlist - File Open]"+" "+"["+min+":"+sec+"]";
        }
        
        String heading[]={top_heading};
        dtm=new javax.swing.table.DefaultTableModel(heading,0);
        jTable1.setForeground(Color.white);
        jTable1.setPreferredSize(null);
        jTable1.setModel(dtm);

        javax.swing.table.TableColumn column;


        column=jTable1.getColumn(top_heading);
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(400);
        
        sname=sname.substring(sname.lastIndexOf('\\')+1, sname.length());
        
        for(int i=0;i<name.length;i++)
        {
            arr_item=""+name[i];
            song_name=arr_item.substring(arr_item.lastIndexOf('\\')+1, arr_item.length());
            
            if(sname.equals(song_name))
            {
                current_row=i;
                song_name=" Currentry Playing : "+song_name.trim();
            }
            
            arr[0]=song_name;
            dtm.addRow(arr);
        }
        
        System.out.println("Currentry playing, Song number : "+(current_row+1));
        
        ChangeColor color=new ChangeColor();
        color.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(350, 500));
        getContentPane().setLayout(null);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setForeground(new java.awt.Color(255, 255, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoscrolls(false);
        jTable1.setEditingColumn(0);
        jTable1.setEditingRow(0);
        jTable1.setPreferredSize(new java.awt.Dimension(338, 2000));
        jTable1.setRowHeight(17);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTable1MouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 360, 500);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 500);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myplayer/VLC/play.png"))); // NOI18N
        jButton1.setToolTipText("Play");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(5, 6, 29, 28);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myplayer/VLC/prev.png"))); // NOI18N
        jButton2.setToolTipText("Previous media");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(43, 6, 29, 28);

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myplayer/VLC/stop.png"))); // NOI18N
        jButton3.setToolTipText("Stop");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(76, 6, 29, 28);

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myplayer/VLC/next.png"))); // NOI18N
        jButton4.setToolTipText("Next media");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(109, 6, 29, 28);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Close");
        jButton6.setToolTipText("Close");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(294, 7, 65, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, 500, 364, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Sorry | This feature is not working.");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Sorry | This feature is not working.");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2)
        {
            System.out.println("Double Clicked");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Sorry | This feature is not working.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void jTable1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

class ChangeColor extends Thread
{
    public void run()
    {
        int i,j;
        
        jButton1.setEnabled(false);
        
        for(i=1;i<=10;i++)
        {
            cl1=new Color(100,100,i+200);
            cl2=new Color(200,100,i+100);

            if(i%2!=0)
            {
                jTable1.setBackground(cl1);
                jButton1.setBackground(cl1);
            }
            
            else
            {
                jTable1.setBackground(cl2);
                jButton1.setBackground(cl2);
            }
            
            try
            {
                Thread.sleep(4000);
            }

            catch(Exception ex)
            {
                System.out.println("ChangeColor : "+ex.getMessage());
            }
            
            if(i==10)
            {
                i=1;
            }
        }
    }
}

class ProgressRenderer extends JProgressBar implements TableCellRenderer
{
    // Constructor for ProgressRenderer.
    public ProgressRenderer(int min, int max)
    {
        super(min, max);
    }
    /* Returns this JProgressBar as the renderer
    for the given table cell. */
    public Component getTableCellRendererComponent(JTable jTable1, Object value, boolean isSelected, boolean hasFocus, int row, int column)
    {
        // Set JProgressBar's percent complete value.
        setValue((int) ((Float) value).floatValue());
        return this;
    }
}
}
