/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IntegratedCashReport.java
 *
 * Created on May 14, 2012, 1:08:24 PM
 */

package railwaycashoffice;

import java.awt.Color;
import java.math.BigInteger;
import java.io.*;

/**
 *
 * @author Shweta
 */
public class IntegratedCashReport extends javax.swing.JInternalFrame {

    /** Creates new form IntegratedCashReport */
    public IntegratedCashReport() {
        initComponents();
        java.util.Date dt=new java.util.Date();
        int date=dt.getDate();
        int month=dt.getMonth()+1;
        int year=dt.getYear()+1900;
        String setDate=date+"-"+month+"-"+year;
        jLabel2.setText(setDate);
        //jTextField4.setVisible(false);
       // jTextField5.setVisible(false);
        jProgressBar1.setVisible(false);
        jProgressBar2.setVisible(false);

      /*  jTextField6.setText("Chq-DFM/MGS");
        jTextField8.setText("Chq-PD/MGS");
        jTextField10.setText("Chq-Hajipur/MGS");*/
        jButton4.setVisible(false);
        //jTable3.setEnabled(false);

        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        javax.swing.table.DefaultTableCellRenderer CRLeft=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRRight=new javax.swing.table.DefaultTableCellRenderer();
        javax.swing.table.DefaultTableCellRenderer CRCenter=new javax.swing.table.DefaultTableCellRenderer();

        CRLeft.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        CRRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        CRCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        String head[]={"Sr.No.","Cashier No.","Purpose","Sign","Amount"};
        dtm=new javax.swing.table.DefaultTableModel(head,0);
        jTable1.setModel(dtm);

        javax.swing.table.TableColumn column;

        column=jTable1.getColumn("Sr.No.");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(60);

        column=jTable1.getColumn("Cashier No.");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(80);

        column=jTable1.getColumn("Purpose");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(150);

        column=jTable1.getColumn("Sign");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(50);

        column=jTable1.getColumn("Amount");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(180);




        jTable2.setAutoResizeMode(jTable2.AUTO_RESIZE_OFF);
        String head1[]={"Sr.No.","Cashier No.","Dues Retained","Bill Accounts"};
        dtm1=new javax.swing.table.DefaultTableModel(head1,0);
        jTable2.setModel(dtm1);

        //javax.swing.table.TableColumn column;

        column=jTable2.getColumn("Sr.No.");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(60);

        column=jTable2.getColumn("Cashier No.");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(80);

        column=jTable2.getColumn("Dues Retained");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(150);

        column=jTable2.getColumn("Bill Accounts");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(150);



        jTable3.setAutoResizeMode(jTable3.AUTO_RESIZE_OFF);
        String head2[]={"Assets","Amount"};
        dtm2=new javax.swing.table.DefaultTableModel(head2,0);
        jTable3.setModel(dtm2);
        
        column=jTable3.getColumn("Assets");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(130);
        column=jTable3.getColumn("Amount");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(120);

        
        jTable4.setAutoResizeMode(jTable3.AUTO_RESIZE_OFF);
        String head3[]={"Department","Cheque Amount"};
        dtm3=new javax.swing.table.DefaultTableModel(head3,0);
        jTable4.setModel(dtm3);

        column=jTable4.getColumn("Department");
        column.setCellRenderer(CRLeft);
        column.setPreferredWidth(100);

        column=jTable4.getColumn("Cheque Amount");
        column.setCellRenderer(CRRight);
        column.setPreferredWidth(100);

    
       //loadInitialInfo();
     
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Integrated Cash Report");
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporting Date");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 110, 25);

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 30, 160, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railwaycashoffice/images/calendar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 30, 30, 25);

        jPanel1.setBackground(new java.awt.Color(187, 181, 143));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 540, 170);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(20, 210, 540, 10);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 260, 540, 180);
        jPanel1.add(jProgressBar2);
        jProgressBar2.setBounds(20, 440, 540, 10);

        jLabel4.setBackground(new java.awt.Color(109, 157, 157));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("0");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 450, 130, 20);

        jLabel5.setBackground(new java.awt.Color(242, 210, 168));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Total Bill Amount (in Rs.)");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 450, 140, 20);

        jLabel6.setBackground(new java.awt.Color(94, 138, 138));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("0");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 450, 130, 20);

        jLabel7.setBackground(new java.awt.Color(242, 210, 168));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Total Due Amount(int Rs.)");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 450, 140, 20);

        jLabel11.setBackground(new java.awt.Color(255, 255, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Due Amount Calculation  :-");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 20, 240, 20);

        jLabel12.setBackground(new java.awt.Color(255, 255, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setText("Assets & Liabilities  :-");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 240, 240, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 80, 580, 490);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railwaycashoffice/images/show.gif"))); // NOI18N
        jButton2.setMnemonic('S');
        jButton2.setText("Show");
        jButton2.setToolTipText("Show Record");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton2FocusLost(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 30, 140, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railwaycashoffice/images/Close1.gif"))); // NOI18N
        jButton3.setMnemonic('C');
        jButton3.setText("Close");
        jButton3.setToolTipText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton3FocusLost(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(750, 30, 140, 30);

        jPanel2.setBackground(new java.awt.Color(164, 135, 113));
        jPanel2.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(255, 255, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Assets :-");
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 10, 260, 20);

        jButton4.setMnemonic('S');
        jButton4.setText("Save");
        jButton4.setToolTipText("Save Information");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(0, 470, 10, 20);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 30, 260, 280);

        jLabel9.setBackground(new java.awt.Color(204, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("0");
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(150, 320, 120, 25);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Total Amount (In Rs.)");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 320, 140, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(610, 210, 280, 360);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railwaycashoffice/images/PRINT.GIF"))); // NOI18N
        jButton5.setMnemonic('P');
        jButton5.setText("Print");
        jButton5.setToolTipText("Print Information");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton5FocusLost(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(600, 30, 140, 30);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(610, 80, 280, 90);

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("0.00");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(780, 174, 110, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Today's Cheque Amount");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(610, 174, 150, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cal date=new Cal();
        jLabel2.setText(date.getdate());
        jButton2.requestFocus();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loadTodaysCheques();
        uploadDetail();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     //   Save();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
             jButton2.requestFocus();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       new printReport();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
        // TODO add your handling code here:
        jButton2.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_jButton2FocusGained

    private void jButton2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusLost
        // TODO add your handling code here:
        jButton2.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_jButton2FocusLost

    private void jButton5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton5FocusGained
        // TODO add your handling code here:
        jButton5.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_jButton5FocusGained

    private void jButton5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton5FocusLost
        // TODO add your handling code here:
        jButton5.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_jButton5FocusLost

    private void jButton3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusGained
        // TODO add your handling code here:
        jButton3.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_jButton3FocusGained

    private void jButton3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusLost
        // TODO add your handling code here:
         jButton3.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_jButton3FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
javax.swing.table.DefaultTableModel dtm;
javax.swing.table.DefaultTableModel dtm1;
javax.swing.table.DefaultTableModel dtm2;
javax.swing.table.DefaultTableModel dtm3;

double amt=0.0;
String LieuAmt="0.00";
private void loadTodaysCheques()
{
    try
    {
        interfaceRailway object1=null;

        try
        {
            object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
        }
        catch(Exception e)
        {
            System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
            getIPaddress.changeIP();
            try
            {
                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
            }
            catch(Exception ex)
            {
                System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
            }
        }

        java.math.BigDecimal bd=new java.math.BigDecimal("0");
        String qry="Select dp_name,dp_code from department_detail order by dp_name";
        String load[][]=object1.getInformationDD(qry,2,Main.year);
        if(load!=null)
        {
            dtm3.setRowCount(0);
            String getStr[]=jLabel2.getText().split("-");
            String setDate1=getStr[2]+"-"+getStr[1]+"-"+getStr[0];
            String arr[]=new String[2];
            for(int i=0;i<load.length;i++)
            {
                System.out.println("i="+i);
                //qry="select sum(chq_amt) from dc_chq_details where dp_code="+Integer.parseInt(load[i][1])+" and receiving_date='"+setDate1+"'";
                qry="select sum(mix_amount) from build_distribution where dp_code="+Integer.parseInt(load[i][1])+" and edate='"+setDate1+"'";
                System.out.println("qry="+qry);
                String total_chq_amt=object1.getSigetngleValue(qry, Main.year);
                System.out.println("total_amt="+total_chq_amt);
                if(total_chq_amt!=null)
                {
                    arr[0]=load[i][0];
                    arr[1]=""+(new java.math.BigDecimal(total_chq_amt)).setScale(2, 5);
                    dtm3.addRow(arr);
                    bd=bd.add(new java.math.BigDecimal(total_chq_amt));
                }
            }
            jLabel13.setText(""+bd.setScale(2, 5));
        }
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method."+e);
    }

}
/*
private void loadInitialInfo()
{
    try
    {
        // interfaceRailway object1=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
        interfaceRailway object1=null;
		try
		{
                                object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
				}
		}

        String qry="Select dp_name from department_detail order by dp_code";
        String load[]=object1.getResultSetAs_1D_Array(qry,Main.year);
        if(load!=null)
        {
            jComboBox1.removeAllItems();
            for(int i=0;i<load.length;i++)
            {
                jComboBox1.addItem(load[i]);
            }
        }
      
    //    loadCashDetail();


    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadInitialInfo Method."+e);
    }

}*/

private void uploadDetail()
{
    dtm.setRowCount(0);
    dtm1.setRowCount(0);
    jLabel4.setText("0.00");
    jLabel6.setText("0.00");

    try
    {
        //interfaceRailway object1=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
        interfaceRailway object1=null;
		try
		{
			object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
				}
		}
        String qry="";//Select dp_code from department_detail where dp_name='"+(""+jComboBox1.getSelectedItem())+"'";
        //String getDpCode=object1.getSigetngleValue(qry,Main.year);

        qry="Select cashier_code from cashier_detail order by cashier_number asc";
        String load[]=object1.getResultSetAs_1D_Array(qry,Main.year);

        String getStr[]=jLabel2.getText().split("-");
        String setDate1=getStr[2]+"-"+getStr[1]+"-"+getStr[0];

        //if(getDpCode.length()>0)
        {
            String arr[]=new String[5];
            int ind=0,index=0;
            String getCurrentAmt[]=null;
            String getChequeAmt[]=null;
            String receivedAmt[]=null;

            double tot=0.0,dueamt=0.0;
            jProgressBar1.setVisible(true);
            jProgressBar1.setMaximum(load.length);
            jProgressBar1.setMinimum(0);
            jProgressBar1.setValue(0);

            for(int i=0;i<=load.length-1;i++)
            {
                double totalChequeAmt=0.00;
                 //String getCurrentAmt="",getChequeAmt="",receivedAmt="";
                qry="select cashier_number from cashier_detail where cashier_code="+Integer.parseInt(load[i]);
                String getCashierNo=object1.getSigetngleValue(qry,Main.year);
               // System.out.println("load[]"+load[i]);
                qry="select cashier_code from build_distribution where cashier_code ="+Integer.parseInt(load[i])+" and edate='"+setDate1+"'";
                //System.out.println("qry....."+qry);
                //javax.swing.JOptionPane.showMessageDialog(this,qry);
                String getCode=object1.getSigetngleValue(qry,Main.year);
                
                    System.out.println("come here..more then one time......");

                     for(int j=0;j<=4;j++)
                    {
                    //javax.swing.JOptionPane.showMessageDialog(null,"j.111......"+j);
                    if(j==0)
                    {
                        arr[0]=""+(++ind);
                        arr[1]=getCashierNo;
                    }
                    else
                    {
                        arr[0]="  ";
                        arr[1]="  ";
                    }
                    //if(j==0 && index>1)
                    if(j==0)
                    {
                        arr[2]="Last due amount";
                        arr[3]="+";
                        dueamt=dueAmount(load[i]);//,getDpCode);
                        System.out.println("dueamt....in upload method......"+dueamt);
                        arr[4]=(""+new java.math.BigDecimal(dueamt).setScale(2,5));
                    }
                    if(j==1)
                    {
                        arr[2]="Current amount";
                        arr[3]="+";
                        qry="select sum(mix_amount) from build_distribution where cashier_code="+Integer.parseInt(load[i])+" and edate='"+setDate1+"'";
                        getCurrentAmt=object1.getResultSetAs_1D_Array(qry,Main.year);
                        System.out.println("len..........."+getCurrentAmt[0]);
                        if(getCurrentAmt[0]!=null)
                        {
                           arr[4]=(""+new java.math.BigDecimal(Double.valueOf(getCurrentAmt[0])).setScale(2,5));
                        }
                        else
                           arr[4]="0.00";
                    }
                    
                    if(j==2)
                    {
                        //qry="Select distinct(bill_Code) from build_distribution where cashier_code="+Integer.parseInt(load[i])+" and dp_code="+Integer.parseInt(getDpCode)+" and edate='"+setDate1+"'";
                        qry="Select sum(chq_Amt) from build_distribution where cashier_code="+Integer.parseInt(load[i])+" and edate='"+setDate1+"'";
                        //String getBillCode[]=object1.getResultSetAs_1D_Array(qry, Main.year);
                        String totalChqAmt[]=object1.getResultSetAs_1D_Array(qry, Main.year);
                        if(totalChqAmt!=null)
                        {
                            System.out.println("inside if:"+totalChqAmt[0]);
                            if(totalChqAmt[0]!=null)
                                totalChequeAmt = Double.valueOf(totalChqAmt[0]);
                        }
                        arr[2]="Cheque amount";
                        arr[3]="-";
                        if(totalChequeAmt!=0)
                        {
                           arr[4]=(""+new java.math.BigDecimal(Double.valueOf(totalChequeAmt)).setScale(2,5));
                        }
                        else
                           arr[4]="0.00";
                    }
                    if(j==3)
                    {
                        /////////it should be today's AMOUNT
                        arr[2]="Total received amount";
                        arr[3]="-";
                        qry="Select sum(received_amount) from received_cash_detail where cashier_code="+Integer.parseInt(load[i])+" and edate='"+setDate1+"'";
                        receivedAmt=object1.getResultSetAs_1D_Array(qry,Main.year);
                       if(receivedAmt[0]!=null)// || receivedAmt.length>0)
                       {
                           arr[4]=(""+new java.math.BigDecimal(Double.valueOf(receivedAmt[0])).setScale(2,5));
                        }
                        else
                           arr[4]="0.00";
                    }
                    //if(j==4 && index>1)
                    if(j==4)
                    {
                        double currentAmt=0.0,dueamount=0.0,duetot=0.0,chequeamt=0.0,receiveAmt=0.0;
                        arr[2]="TOTAL DUE AMOUNT";
                        arr[3]="  ";

                        //if(getCurrentAmt!=null && getChequeAmt!=null && receivedAmt!=null)
                        if(getCurrentAmt[0]!=null)
                        {
                            currentAmt=Double.valueOf(getCurrentAmt[0]);
                            System.out.println("currentAmt...if......"+currentAmt);
                            dueamount=currentAmt+Double.valueOf(dueamt);
                            System.out.println("dueamount...if......"+dueamount);
                        }
                        else
                        {
                            dueamount=Double.valueOf(dueamt);
                            System.out.println("dueamount........."+dueamount);
                        }
                        //if(getChequeAmt[0]!=null)
                        System.out.println("totalChequeAmt....>>>."+totalChequeAmt);
                        if(totalChequeAmt!=0)
                        {
                           // dueamount=currentAmt-Double.valueOf(getChequeAmt[0]);
                            //chequeamt=Double.valueOf(getChequeAmt[0]);
                            chequeamt=totalChequeAmt;
                            System.out.println("chequeamt..if......."+chequeamt);
                        }
                        else
                        {
                            chequeamt=0.0;
                            System.out.println("chequeamt.else......."+chequeamt);
                        }

                        if(receivedAmt[0]!=null)
                        {
                            receiveAmt=Double.valueOf(receivedAmt[0]);
                            System.out.println("receiveAmt...1......"+receiveAmt);
                              receiveAmt=receiveAmt+chequeamt;
                            
                        }
                        else
                        {
                         receiveAmt=0;
                         System.out.println("receiveAmt...2......"+receiveAmt);
                           receiveAmt=receiveAmt+chequeamt;
                         }

                        //else if(getChequeAmt[0]!=null)
                        /*if(totalChequeAmt!=0)
                        {
                            receiveAmt=chequeamt;
                            System.out.println("receiveAmt...else......"+receiveAmt);
                        }*/
                      /*  if(dueamount>=receiveAmt)
                        {*/
                                tot=dueamount-receiveAmt;
                                System.out.println("tot..if......."+tot);
                      /*  }
                        else
                        {
                                tot=dueamount;
                        System.out.println("tot...else......"+tot);
                        }*/
                      //  System.out.println("tot 33333...."+setot);
                        if(tot!=0.0)
                            arr[4]=(""+new java.math.BigDecimal(tot).setScale(2,5));
                        else
                            arr[4]="0.00" ;
                      
                    }
                    dtm.addRow(arr);

                }

               // }

                jProgressBar1.setValue(i+1);

             //jLabel11.setText(""+new java.math.BigDecimal(totalDueAmt).setScale(3,java.math.BigDecimal.ROUND_HALF_UP));
          }
        }

//        loadDueAmount lD=new loadDueAmount();
//        lD.start();
    }
    catch(Exception e)
    {
        System.out.println("Error ! In uploadDetail Method."+e);
    }
        //loadDueAmount lD=new loadDueAmount();
        //lD.start();
        loadCashDetail();

}
private double dueAmount(String cashiercode)
{
    //javax.swing.JOptionPane.showMessageDialog(null,"Coming here....");;
    double amount=0.0,receivedamount=0.0,dueAmount=0.0,totalDueAmt=0.0,totdue=0.0,returningAmt=0.0,lastYearDueAmt=0.0;
    String load=cashiercode;
    //String dpCode=dpcode;
    try
    {
        String d1[]=jLabel2.getText().split("-");
        String setDate=d1[2]+"-"+d1[1]+"-"+d1[0];
        String deadDate=2000+"-"+1+"-"+1;
       // interfaceRailway object1=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
        interfaceRailway object1=null;
		try
		{
			object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
				}
		}
        String  qry="Select dueamount from opening_dueamount where cashier_code="+Integer.parseInt(load)+"";
        System.out.println("qry...........in due method...."+qry);
        String dueAmt=object1.getSigetngleValue(qry,Main.year);
        System.out.println("dueAmt........."+dueAmt);
        if(dueAmt.equals("")==false)// || dueAmt.length>0)
                  dueAmount=Double.valueOf(dueAmt);
        else
                    dueAmount=0.0;
        //else if(dueAmt.equals("")==true || dueAmt.length()==0)
          
        String getStr[]=jLabel2.getText().split("-");
        String setDate1=getStr[2]+"-"+getStr[1]+"-"+getStr[0];
        //qry="Select sum(amount) from build_distribution where cashier_code="+Integer.parseInt(load)+" and dp_code="+Integer.parseInt(dpCode)+" and (amounttype='"+"Cash"+"' and edate<'"+setDate1+"')";
        qry="Select sum(amount) from build_distribution where cashier_code="+Integer.parseInt(load)+"  and edate<'"+setDate1+"'";
        String amt=object1.getSigetngleValue(qry,Main.year);
        if(amt!=null )//|| amt.length>0)
                  amount=Double.valueOf(amt);
        else
                  amount=0.0;
        ///////////////////last year due amount calculation///////////
        //lastYearDueAmt=backDateCalculation(load);


        //////////////////////////////////////////////////////////////
                  //////sum of received amount///////////////
        qry="Select sum(received_amount) from received_cash_detail where cashier_code="+Integer.parseInt(load)+" and edate<'"+setDate1+"'";
        String receivedAmt=object1.getSigetngleValue(qry,Main.year);
        if(receivedAmt!=null)// || receivedAmt.length>0)
                  receivedamount=Double.valueOf(receivedAmt);
        else
            receivedamount=0.0;
       // else if(receivedAmt.length()==0 || receivedAmt.equals("")==true)
                  
        totdue=dueAmount+amount;
        System.out.println("in due amount method......"+totdue);
        //+lastYearDueAmt);
       // if(totdue>=receivedamount)
            totalDueAmt=totdue-receivedamount;
       /* else
            totalDueAmt=totdue;*/
            System.out.println("totalDueAmt................"+totalDueAmt);

        /////////////returning dues of closed challan/////////////////
        qry="Select edate from challan_detail where edate<'"+setDate+"' and cashier_code="+Integer.parseInt(load)+" and closing_status="+"1"+" order by edate asc";
        String loadDate[]=object1.getResultSetAs_1D_Array(qry,Main.year);
        System.out.println("loadDate...."+loadDate.length);
        if(loadDate!=null)
        {
            for(int i=0;i<loadDate.length;i++)
            {
                String D1[]=loadDate[i].split("-");
                String matchDate=D1[2]+"-"+D1[1]+"-"+D1[0];
                qry="Select sum(amount) from build_distribution where edate='"+matchDate+"' and paymentdate='"+deadDate+"' and cashier_code="+Integer.parseInt(load)+"";
                String getReturningAmount=object1.getSigetngleValue(qry,Main.year);
                System.out.println("getReturningAmount...5465656...."+getReturningAmount);
                if(getReturningAmount!=null && getReturningAmount.length()>0)
                {
                    returningAmt=returningAmt+Double.valueOf(getReturningAmount);
                }
             
            }
        }
        if(totalDueAmt>=returningAmt)
            totalDueAmt=totalDueAmt-returningAmt;
        /////////////////////////////////////////////////////////////
    }
    catch(Exception e)
    {
        System.out.println("Error ! In due Amount Method."+e);
    }
    return totalDueAmt;
}
class loadDueAmount extends Thread
{
    String qry="";
    public void run()
    {
         dtm1.setRowCount(0);
         try
         {
            ///  interfaceRailway object1=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
             interfaceRailway object1=null;
		try
		{
			object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
				}
		}
             //String qry="Select dp_code from department_detail where dp_name='"+(""+jComboBox1.getSelectedItem())+"'";
             //String getDpCode=object1.getSigetngleValue(qry,Main.year);

             String qry="Select cashier_code from cashier_detail order by cashier_number asc";
             String load[]=object1.getResultSetAs_1D_Array(qry,Main.year);

             String getStr[]=jLabel2.getText().split("-");
             String setDate1=getStr[2]+"-"+getStr[1]+"-"+getStr[0];

             //if(getDpCode.length()>0)
             {
                String arr[]=new String[4];
                int ind=0,index=0;
                String getCurrentAmt[]=null,getChequeAmt[]=null,receivedAmt[]=null,CurrentBill[]=null;
                double tot=0.0,dueamt=0.0,totdue=0.0,totcurrentAmt=0.0;
                jProgressBar2.setVisible(true);
                jProgressBar2.setMaximum(load.length);
                jProgressBar2.setMinimum(0);
                jProgressBar2.setValue(0);


                for(int i=0;i<=load.length-1;i++)
                {
                    double totalChequeAmt=0;
                    qry="select cashier_number from cashier_detail where cashier_code="+Integer.parseInt(load[i]);
                    String getCashierNo=object1.getSigetngleValue(qry,Main.year);
                    qry="select cashier_code from build_distribution where cashier_code ="+Integer.parseInt(load[i])+" and edate='"+setDate1+"'";
                //System.out.println("qry....."+qry);
                //javax.swing.JOptionPane.showMessageDialog(this,qry);
                    String getCode=object1.getSigetngleValue(qry,Main.year);
                //System.out.println("getCode[0].length...."+getCode.length());
                    double currentAmt=0.0,dueamount=0.0,chequeamt=0.0,receiveAmt=0.0;
                    if(getCode.length()==0 || getCode.equals(""))
                    {
                        index=1;
                        //System.out.println("index."+index);
                    }
                    else if(getCode.length()>0)
                    {
                        index=2;
                        //System.out.println("index."+index);
                    }
                    if(index==1)
                    {
                        double dueAmt=0.00;
                      //  System.out.println("come here........");
                        dueAmt=dueAmount(load[i]);//,getDpCode);
                        arr[0]=""+(++ind);
                        arr[1]=getCashierNo;
                        if(dueAmt<0)
                        {
                            arr[2]="0.00";
                            //code to add in 3rd table
                        }
                        else
                            arr[2]=(""+new java.math.BigDecimal(dueAmt).setScale(2,5));
                        arr[3]="0";
                        totdue=totdue+dueAmt;
                        dtm1.addRow(arr);
                    }
                    else if(index>1)
                    {
                        tot=0.0;
                         arr[0]=""+(++ind);
                         arr[1]=getCashierNo;
                         ///dues retained Calculation///////////
                         qry="select sum(mix_amount) from build_distribution where cashier_code="+Integer.parseInt(load[i])+" and  edate='"+setDate1+"'";
                         //System.out.println("qry...sum of.tot.........."+qry);
                         getCurrentAmt=object1.getResultSetAs_1D_Array(qry,Main.year);

                         qry="Select sum(chq_Amt) from build_distribution where cashier_code="+Integer.parseInt(load[i])+" and  edate='"+setDate1+"'";
                         String totalchqamt[]=object1.getResultSetAs_1D_Array(qry,Main.year);
                         if(totalchqamt!=null)
                             totalChequeAmt=Double.valueOf(totalchqamt[0]);

                         qry="Select sum(received_amount) from received_cash_detail where cashier_code="+Integer.parseInt(load[i])+" and edate='"+setDate1+"'";
                        System.out.println("qry....of received amt...."+qry);
                         receivedAmt=object1.getResultSetAs_1D_Array(qry,Main.year);
                         System.out.println("receivedAmt>>;;;;>>>>>>"+receivedAmt[0]);
                         dueamt=dueAmount(load[i]);//,getDpCode);
                        if(getCurrentAmt[0]!=null)
                        {
                            currentAmt=Double.valueOf(getCurrentAmt[0]);                            
                           dueamount=currentAmt+Double.valueOf(dueamt);
                           // System.out.println("dueamount..3434......"+dueamount);
                        }
                        else
                        {
                             currentAmt=0.0;
                             dueamount=currentAmt+Double.valueOf(dueamt);
                        }
                         if(totalChequeAmt!=0)
                        {
                              chequeamt=totalChequeAmt;
                        }
                        else
                        {
                            chequeamt=0.0;
                        }

                        if(receivedAmt[0]!=null)
                        {
                            receiveAmt=Double.valueOf(receivedAmt[0]);
                            receiveAmt=receiveAmt+chequeamt;
                            System.out.println("receiveAmt>>>>>>if>"+receiveAmt);
                        }
                        else
                        {
                             receiveAmt=0.0;
                              receiveAmt=receiveAmt+chequeamt;
                                 System.out.println("receiveAmt>>>>>>else>"+receiveAmt);
                        }
                        
                             
                                tot=dueamount-receiveAmt;
                                System.out.println("tot>>>if>>>>"+tot);
                        
                       
                        if(tot!=0.0)
                        {                            
                            if(tot<0)   //It means cashier have Ad. payment
                            {
                                String arr1[]=new String[2];
                                arr1[0]="Ad. By Cashier("+arr[1]+")";
                                arr1[1]=""+(new java.math.BigDecimal(Math.abs(tot))).setScale(2, 5);
                                dtm2.addRow(arr1);
                                java.math.BigDecimal tempbd1=new java.math.BigDecimal(jLabel9.getText());
                                tempbd1=tempbd1.add(new java.math.BigDecimal(arr1[1]));
                                System.out.println("jlabel9.gettext()="+jLabel9.getText());
                                System.out.println(""+tempbd1);
                                jLabel9.setText(""+tempbd1.setScale(2, 5));
                                
                                tot=0;
                                arr[2]="0.00";
                            }
                            else
                                arr[2] = ("" + new java.math.BigDecimal(tot).setScale(2, 5));
                        }
                        else
                            arr[2]="0.00" ;

                        totdue=totdue+tot;
                         ///////////////////////////////////////
                         //////Bill Accounts////////////////////

                         //qry="select sum(amount) from build_distribution where cashier_code="+Integer.parseInt(load[i])+" and (dp_code="+Integer.parseInt(getDpCode)+" and edate='"+setDate1+"')";
                          qry="select sum(mix_amount) from build_distribution where cashier_code="+Integer.parseInt(load[i])+" and  edate='"+setDate1+"'";
                         //System.out.println("qry...sum of.tot.........."+qry);
                         CurrentBill=object1.getResultSetAs_1D_Array(qry,Main.year);

                         if(CurrentBill!=null)
                         {
                              arr[3]=(""+new java.math.BigDecimal(Double.valueOf(CurrentBill[0])).setScale(2,5));
                              totcurrentAmt=totcurrentAmt+Double.valueOf(CurrentBill[0]);
                         }
                         else
                         {
                             arr[3]="0.00";
                         }

                         /////////////////////////////////////////
                         dtm1.addRow(arr);

                    }
                    jProgressBar2.setValue(i+1);
             }
            jLabel6.setText(""+new java.math.BigDecimal(totdue).setScale(2,5));
            jLabel4.setText(""+new java.math.BigDecimal(totcurrentAmt).setScale(2,5));
            jLabel4.requestFocus();
             
         }
             
        }
         catch(Exception e)
         {
             System.out.println("Error ! In loadDueAmount class."+e);
         }
         //loadCashDetail();
         

    }
}

/*private void uploadLastDetail()
{
    try
    {
        String D1[]=jLabel2.getText().split("-");
        String setDate=D1[2]+"-"+D1[1]+"-"+D1[0];
        //interfaceRailway object1=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
        interfaceRailway object1=null;
		try
		{
			object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
				}
		}
        String qry="Select dp_Code from department_detail where dp_Name='"+(""+jComboBox1.getSelectedItem())+"'";
        String getDpCode=object1.getSigetngleValue(qry,Main.year);

        if(getDpCode!=null || getDpCode.length()>0)
        {
            qry="Select AdvanceText1,Amount1,AdvanceText2,Amount2,AdvanceText3,Amount3,AdvanceText4,Amount4,AdvanceText5,Amount5,TotalAmount from integrated_assetsvalue where dp_Code="+Integer.parseInt(getDpCode)+" and edate='"+setDate+"'";
            String load[][]=object1.getInformationDD(qry,11,Main.year);
            if(load!=null && load.length>0)
            {
               jTextField4.setText(load[0][0]);
               jTextField5.setText(""+new java.math.BigDecimal(Double.valueOf(load[0][1])).setScale(2,5));
               jTextField6.setText(load[0][2]);
               jTextField7.setText(""+new java.math.BigDecimal(Double.valueOf(load[0][3])).setScale(2,5));
               jTextField8.setText(load[0][4]);
               jTextField9.setText(""+new java.math.BigDecimal(Double.valueOf(load[0][5])).setScale(2,5));
               jTextField10.setText(load[0][6]);
               jTextField11.setText(""+new java.math.BigDecimal(Double.valueOf(load[0][7])).setScale(2,5));
               jTextField12.setText(load[0][8]);
               jTextField13.setText(""+new java.math.BigDecimal(Double.valueOf(load[0][9])).setScale(2,5));
               jLabel8.setText(""+new java.math.BigDecimal(Double.valueOf(load[0][10])).setScale(2,5));
               jTextField4.requestFocus();
            }
        }

    }
    catch(Exception e)
    {
        System.out.println("Error ! In uploadLastDetail Method."+e);
    }

}*/

/*private boolean calculateAmount()
{
    double Amt1=0,Amt2=0,Amt3=0,Amt4=0,Amt5=0;
        if(jTextField5.getText().equals(""))
        {
            Amt1=0;
        }
        else
        {
            try
            {
                Amt1=Double.valueOf(jTextField5.getText());
            }
            catch(Exception e)
            {
                //System.out.println("Error..SKM R....."+e);
                javax.swing.JOptionPane.showMessageDialog(this,""+e+"\nPlease input cash amount ?","Error !!",javax.swing.JOptionPane.ERROR_MESSAGE);
                jTextField5.requestFocus();
                jTextField5.selectAll();
                return false;
            }
        }
        if(jTextField7.getText().equals(""))
        {
            Amt2=0;
        }
        else
        {
            try
            {
                Amt2=Double.valueOf(jTextField7.getText());
            }
            catch(Exception e)
            {
                //System.out.println("Error..SKM R....."+e);
                javax.swing.JOptionPane.showMessageDialog(this,""+e+"\nPlease input cash amount ?","Error !!",javax.swing.JOptionPane.ERROR_MESSAGE);
                jTextField7.requestFocus();
                jTextField7.selectAll();
                return false;
            }
        }
        if(jTextField9.getText().equals(""))
        {
            Amt3=0;
        }
        else
        {
            try
            {
                Amt3=Double.valueOf(jTextField9.getText());
            }
            catch(Exception e)
            {
                //System.out.println("Error..SKM R....."+e);
                javax.swing.JOptionPane.showMessageDialog(this,""+e+"\nPlease input cash amount ?","Error !!",javax.swing.JOptionPane.ERROR_MESSAGE);
                jTextField9.requestFocus();
                jTextField9.selectAll();
                return false;
            }
        }
        if(jTextField11.getText().equals(""))
        {
            Amt4=0;
        }
        else
        {
            try
            {
                Amt4=Double.valueOf(jTextField11.getText());
            }
            catch(Exception e)
            {
                //System.out.println("Error..SKM R....."+e);
                javax.swing.JOptionPane.showMessageDialog(this,""+e+"\nPlease input cash amount ?","Error !!",javax.swing.JOptionPane.ERROR_MESSAGE);
                jTextField11.requestFocus();
                jTextField11.selectAll();
                return false;
            }
        }
        if(jTextField13.getText().equals(""))
        {
            Amt5=0;
        }
        else
        {
            try
            {
                Amt5=Double.valueOf(jTextField13.getText());
            }
            catch(Exception e)
            {
                //System.out.println("Error..SKM R....."+e);
                javax.swing.JOptionPane.showMessageDialog(this,""+e+"\nPlease input cash amount ?","Error !!",javax.swing.JOptionPane.ERROR_MESSAGE);
                jTextField13.requestFocus();
                jTextField13.selectAll();
                return false;
            }
        }

        double totalAmt=Amt1+Amt2+Amt3+Amt4+Amt5+Double.valueOf(jTextField1.getText())+Double.valueOf(jTextField2.getText())+Double.valueOf(jTextField3.getText());
        jLabel8.setText(""+(new java.math.BigDecimal(totalAmt).setScale(2,java.math.BigDecimal.ROUND_HALF_UP)));
  
return true;
}*/
private void loadCashDetail()
{
    dtm2.setRowCount(0);
    try
    {
        String qry="";
        String D1[]=jLabel2.getText().split("-");
        String setDate1=D1[2]+"-"+D1[1]+"-"+D1[0];
        //javax.swing.JOptionPane.showMessageDialog(null,"date>>"+setDate1);
        //interfaceRailway object1=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
        interfaceRailway object1=null;
		try
		{
			object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
		}
		catch(Exception e)
		{
				System.out.println("Error at the time of connection with server "+getIPaddress.IP()+"..."+e);
				getIPaddress.changeIP();
				try
				{
					object1=(interfaceRailway)java.rmi.Naming.lookup(getIPaddress.IP());
				}
				catch(Exception ex)
				{
					System.out.println("Error at the time of connection with server ip-rmi//127.0.0.1/railwayMethods  ..."+ex);
				}
		}
        java.math.BigDecimal bdTot=new java.math.BigDecimal("0");
        java.math.BigDecimal bd=new java.math.BigDecimal("0");
        qry="Select asset,amount from fixedassets order by asset";
        String load[][]=object1.getInformationDD(qry,2,Main.year);
        if(load!=null)
        {
            String arr[]=new String[2];
            for(int i=0;i<load.length;i++)
            {
                arr[0]=load[i][0];
                arr[1]=load[i][1];
                bdTot=bdTot.add(new java.math.BigDecimal(load[i][1]));
                dtm2.addRow(arr);
            }

        }
     
        String reportdatearr[]=jLabel2.getText().split("-");
        String reportdate=reportdatearr[2]+"-"+reportdatearr[1]+"-"+reportdatearr[0];
        qry="select cash_amt from dc_cash_in_hand where rec_date<='"+reportdate+"' order by rec_date desc";
        String arrtemp[]=object1.getResultSetAs_1D_Array(qry, Main.year);
        String getAmt="";
        if(arrtemp!=null)
            if(arrtemp.length>0)
                getAmt=arrtemp[0];
        System.out.println(qry+"\ngetAmt....cash in hand..."+getAmt);
        String arr[]=new String[2];
        if(getAmt.equals("")== false)// || getAmt!=null)
        {
            
            bd=bd.add(new java.math.BigDecimal(getAmt));
            arr[0]="Cash In Hand";
            arr[1]=""+bd;
            bdTot=bdTot.add(bd);
            dtm2.addRow(arr);
        }
        else
        {
            arr[0]="Cash In Hand";
            arr[1]="0.00";
            bdTot=bdTot.add(bd);
            dtm2.addRow(arr);
        }
    

        qry="Select distinct(dp_Code) from dc_chq_details where receiving_date='"+setDate1+"' order by dp_Code";
        String getDp[]=object1.getResultSetAs_1D_Array(qry,Main.year);
        if(getDp!=null)
        {
             bd=new java.math.BigDecimal("0");
            for(int x=0;x<getDp.length;x++)
            {
                qry="select chq_amt,clearance_date from dc_chq_details where dp_code="+Integer.parseInt(getDp[x])+" and receiving_date='"+setDate1+"' ";
                System.out.println("qry="+qry);
                String chequeAmtArr[][]=object1.getInformationDD(qry,2, Main.year);
                System.out.println("chequeAmtArr[].length="+chequeAmtArr.length);
                if(chequeAmtArr!=null)
                {
                    arr=new String[2];
                    bd=new java.math.BigDecimal("0");
                    for(int j=0;j<chequeAmtArr.length;j++)
                    {
                        System.out.println("chequeAmtArr["+j+"][0]="+chequeAmtArr[j][0]);
                        System.out.println("chequeAmtArr["+j+"][1]="+chequeAmtArr[j][1]);
                        //if(chequeAmtArr[j][1]!=null)
                        if(chequeAmtArr[j][1]==null || chequeAmtArr[j][1].equals(setDate1)==false)
                                bd=bd.add(new java.math.BigDecimal(chequeAmtArr[j][0]));
                    }
                    bdTot=bdTot.add(bd);
                    System.out.println("bdTot="+bdTot);
                    if(getDp[x].equals("1"))
                    {
                        arr[0]="Chq-DFM/MGS";
                        arr[1]=""+bd;
                        dtm2.addRow(arr);
                    }
                    if(getDp[x].equals("2"))
                    {
                        arr[0]="Chq-PD/MGS";
                        arr[1]=""+bd;
                        dtm2.addRow(arr);
                    }
                    if(getDp[x].equals("3"))
                    {
                        arr[0]="Chq-Hajipur/MGS";
                        arr[1]=""+bd;
                        dtm2.addRow(arr);
                    }
                }
                /*qry="select distinct(bill_Code) from build_distribution where dp_Code="+Integer.parseInt(getDp[x])+" and edate='"+setDate1+"' order by bill_Code asc";
                String getBillNo[]=object1.getResultSetAs_1D_Array(qry,Main.year);
                if(getBillNo!=null)
                {
                  //  String arr[]=new String[2];
                    arr=new String[2];
                    bd=new java.math.BigDecimal("0");

                    for(int j=0;j<getBillNo.length;j++)
                    {
                        ///qry="Select sum(chq_amt) from cheque_details where status<>1 and bill_Code="+Integer.parseInt(getBillNo[j]);
                        qry="Select sum(chq_Amt) from build_distribution where bill_Code="+Integer.parseInt(getBillNo[j]);
                        getAmt=object1.getSigetngleValue(qry,Main.year);
                        if(getAmt!=null)
                            bd=bd.add(new java.math.BigDecimal(getAmt));
                    }
                    bdTot=bdTot.add(bd);
                    System.out.println("getDp[x]="+getDp[x]+";"+getAmt);
                    if(getDp[x].equals("1"))
                    {
                        arr[0]="Chq-DFM/MGS";
                        arr[1]=""+bd;
                        dtm2.addRow(arr);
                    }
                    if(getDp[x].equals("2"))
                    {
                        arr[0]="Chq-PD/MGS";
                        arr[1]=""+bd;
                        dtm2.addRow(arr);
                    }
                    if(getDp[x].equals("3"))
                    {
                        arr[0]="Chq-Hajipur/MGS";
                        arr[1]=""+bd;
                        dtm2.addRow(arr);
                    }
                }
                 *
                 */
            }
        }

        /*
        if(dtm.getRowCount()>0)
        {
            for(int i=0;i<dtm.getRowCount();i++)
            {
                bd=new java.math.BigDecimal("0");
              //  String arr[]=new String[2];
                arr=new String[2];
                String getVal=""+jTable1.getValueAt(i,4);
                if((""+jTable1.getValueAt(i,1)).equals("TOTAL DUE AMOUNT")==true)
                {
                        if(Integer.parseInt(""+jTable1.getValueAt(i,4))<0)
                        {
                             bd=bd.add(new java.math.BigDecimal(""+jTable1.getValueAt(i,4)));
                             String tempStr=""+jTable1.getValueAt(i,1);
                             arr[0]="Advance ("+tempStr+")";
                             arr[1]=(""+ new java.math.BigDecimal(""+jTable1.getValueAt(i,4)).setScale(2,5));
                             bdTot=bdTot.add(bd);
                             dtm2.addRow(arr);
                        }
                }
               
            }
           
        }
         *
         */
        bd=new java.math.BigDecimal("0");
        for(int i=0;i<dtm2.getRowCount();i++)
        {
            bd=bd.add(new java.math.BigDecimal(""+jTable3.getValueAt(i,1)));
        }
        jLabel9.setText(""+bd.setScale(2, 5));
    }
    catch(Exception e)
    {
        System.out.println("Error ! In loadCashDetail Method."+e);
    }
    loadDueAmount lD=new loadDueAmount();
    lD.start();

}
/*class loadDueAmount extends Thread
{
    String qry="";
   
    public void run()
    {
         dtm1.setRowCount(0);
        try
        {

             interfaceRailway object1=(interfaceRailway)java.rmi.Naming.lookup("rmi://127.0.0.1/railwayMethods");
             String qry="Select dp_code from department_detail where dp_name='"+(""+jComboBox1.getSelectedItem())+"'";
             String getDpCode=object1.getSigetngleValue(qry,Main.year);

             qry="Select cashier_code from cashier_detail";
             String load[]=object1.getResultSetAs_1D_Array(qry,Main.year);

             String getStr[]=jLabel2.getText().split("-");
             String setDate1=getStr[2]+"-"+getStr[1]+"-"+getStr[0];

             if(getDpCode.length()>0)
             {
                String arr[]=new String[4];
                int ind=0,index=0;
                String getCurrentAmt[]=null,getChequeAmt[]=null,receivedAmt[]=null;
                double tot=0.0,dueamt=0.0,totdue=0.0;
                jProgressBar2.setVisible(true);
                jProgressBar2.setMaximum(load.length);
                jProgressBar2.setMinimum(0);
                jProgressBar2.setValue(0);


            for(int i=0;i<=load.length-1;i++)
            {
                qry="select cashier_number from cashier_detail where cashier_code="+Integer.parseInt(load[i]);
                String getCashierNo=object1.getSigetngleValue(qry,Main.year);
               
                for(int j=0;j<=1;j++)
                {
                    System.out.println("j..3333....."+j);
                    if(j==0)
                    {
                        arr[0]=""+(++ind);
                        arr[1]=getCashierNo;
                    }
                    else
                    {
                        arr[0]="  ";
                        arr[1]="  ";
                    }
                    //if(j==0 && index>1)
                    if(j==0)
                    {
                        arr[2]="Last due amount";
                        dueamt=dueAmount(load[i],getDpCode);
                        //System.out.println("dueamt.........."+dueamt);
                        totdue=totdue+dueamt;
                        arr[3]=(""+new java.math.BigDecimal(dueamt).setScale(2,5));
                    }
                    if(j==1)
                    {

                        arr[2]="Current amount";
                        qry="select sum(amount) from build_distribution where cashier_code="+Integer.parseInt(load[i])+" and dp_code="+Integer.parseInt(getDpCode)+" and edate='"+setDate1+"'";
                        getCurrentAmt=object1.getResultSetAs_1D_Array(qry,Main.year);
                        if(getCurrentAmt[0]!=null)
                        {
                           arr[3]=(""+new java.math.BigDecimal(Double.valueOf(getCurrentAmt[0])).setScale(2,5));
                           tot=tot+Double.valueOf(getCurrentAmt[0]);
                        }
                        else
                           arr[3]="0.00";
                    }
                    //if(j==2 && index>1)
                        dtm1.addRow(arr);

                }
                jProgressBar2.setValue(i+1);

             //jLabel11.setText(""+new java.math.BigDecimal(totalDueAmt).setScale(3,java.math.BigDecimal.ROUND_HALF_UP));
          }
           jLabel6.setText(""+new java.math.BigDecimal(totdue).setScale(2,5));
           jLabel4.setText(""+new java.math.BigDecimal(tot).setScale(2,5));
           
        }
        }
        catch(Exception e)
        {
            System.out.println("Error ! In loadDueAmount class."+e);
        }
    }
}*/

//-----------------------------------------------------------------------------
class printReport extends javax.swing.JFrame
{

        PrintWriter pw;
        int assetLine;
        boolean flag2;
           public printReport()
           {
                    boolean first=true;
                    boolean blanklineflag=false;
                    assetLine=-2;
                    int ternLine=1;
                     FileOutputStream fos=null;
                        try
                        {
                                String space="";
                                String temp="";
                              
                                int rep=0;
                                int maxrows=68;
                                System.out.println("Start printing...");
                              //  fos=new FileOutputStream("LPT1");


                                try
                                {
                                        fos=new java.io.FileOutputStream("LPT1");
                                  // fos=new java.io.FileOutputStream("LPT1");//LPT1");
                                   // fos=new java.io.FileOutputStream("IntegratedRpt.in");
                                        System.out.println("inside find port...LPT1");
                                }
                                catch(Exception ex)
                                {
                                        System.out.println("port not found...");
                                        fos=new java.io.FileOutputStream("IntegratedRpt.in");//LPT1");
                                }

                                pw=new PrintWriter(fos);
                                int countLine=1;
                                String line="";
                                int l=0;
                                pw.println("");
                                pw.println("");
                                pw.println("");
                                pw.println("");

                                //pw.println("                                                        SECTION REPORT");
                                pw.println("EAST CENTRAL RAILWAY                    DIVISIONAL CASH PAY OFFICE      ECR MUGHALSARAI");
                                //pw.println("Dept. Name - "+jComboBox1.getSelectedItem());
                                pw.println("Cash Report Cashier Wise :          "+jLabel2.getText().toUpperCase());
                               // pw.println("DATE : "+dateValuelb.getText());
                                pw.println("");
                                pw.println("---------------------------------------------------------------------------------------------------------------------------------");

                                String str="";
                                for(int i=0;i<dtm3.getRowCount();i++)
                                {
                                    space="";
                                    str=""+jTable4.getValueAt(i, 0);
                                    for(int j=1;j<=95;j++)
                                        space=space+" ";
                                    pw.print(space+str);

                                    space="";
                                    for(int j=1;j<=(30-str.length()-(""+jTable4.getValueAt(i, 1)).length());j++)
                                        space=space+" ";
                                    str=""+jTable4.getValueAt(i, 1);
                                    pw.println(space+str);

                                }
                                if(dtm3.getRowCount()>0)
                                {
                                    space="";
                                    for(int j=1;j<=110;j++)
                                        space=space+" ";
                                    pw.println(space+"---------------");
                                    space="";
                                    str=""+jLabel13.getText();
                                    for(int j=1;j<=(125-str.length());j++)
                                        space=space+" ";
                                    pw.println(space+str);
                                    pw.println();

                                }

                                str="Cashier No.   Purpose                    Amount";
                                pw.print(str);
                                for(int i=str.length();i<75;i++)
                                    pw.print(" ");
                                str="Cashier No.   Due Retained             Bill Account";
                                pw.println(str);
                                int nxt=0,nxt1=-1;
                                for(int i=0;i<=dtm.getRowCount()||i<=dtm1.getRowCount();i++)
                                {
                                    boolean flag1=true;
                                    flag2=true;
                                    if(flag2)
                                    {
                                        /*if(nxt==0)
                                         nxt=0;*/
                                        if(nxt1 == -2)
                                        {
                                            nxt=-1;
                                            nxt1=0;
                                        }

                                        
                                    }
                                    
                                    String data[]=new String[6];
                                    for(int x=0;x<data.length;x++)
                                        data[x]="";
                                    if(i<dtm.getRowCount())
                                    {
                                        flag1=false;
                                        data[0]=""+jTable1.getValueAt(i,1);
                                        pw.print(data[0]);
                                        for(int s=0;s<12-data[0].length();s++)
                                            data[1]+=" ";
                                        data[1]+=""+jTable1.getValueAt(i,2);
                                        pw.print(data[1]);
                                        int len=60-((""+jTable1.getValueAt(i,3)).length()+(""+jTable1.getValueAt(i,4)).length());
                                        int init=(data[0].length()+data[1].length());
                                       for(int s=init;s<len;s++)
                                            data[2]+=" ";
                                        data[2]+=""+jTable1.getValueAt(i,3)+""+jTable1.getValueAt(i,4);
                                        pw.print(data[2]);
                                    }
                                    if(flag1)
                                    {
                                        flag1=false;

                                        for(int s=0;s<60;s++)
                                        {
                                            pw.print(" ");
                                            data[2]+=" ";
                                        }
                                    }
                                    if(i<dtm1.getRowCount())
                                    {
                                        flag2=false;
                                        nxt=0;
                                        for(int ii=0;ii<15;ii++)
                                            data[3]+=" ";
                                        data[3]+=""+jTable2.getValueAt(i,1);
                                        pw.print(data[3]);
                                        int len=100-((""+jTable2.getValueAt(i,2)).length());
                                        int init=(data[0].length()+data[1].length()+data[2].length()+data[3].length());
                                        for(int s=init;s<len;s++)
                                            data[4]+=" ";
                                        data[4]+=""+jTable2.getValueAt(i,2);
                                        pw.print(data[4]);
                                        len=125-((""+jTable2.getValueAt(i,3)).length());
                                        init=(data[0].length()+data[1].length()+data[2].length()+data[3].length()+data[4].length());
                                        for(int s=init;s<len;s++)
                                            data[5]+=" ";
                                        data[5]+=""+jTable2.getValueAt(i,3);
                                        pw.print(data[5]);
                                    }
                                    if(i==dtm1.getRowCount())
                                    {
                                        flag2=false;
                                    }
                                    if(i==(dtm1.getRowCount()+1))
                                    {

                                        flag2=false;
                                        nxt=0;
                                        for(int ii=0;ii<15;ii++)
                                            data[3]+=" ";
                                        data[3]+="TOTAL : -";
                                        pw.print(data[3].toUpperCase());
                                        int len=100-((""+jLabel6.getText()).length());
                                        //System.out.println(""+(jLabel6.getText()).length());
                                        int init=(data[0].length()+data[1].length()+data[2].length()+data[3].length());
                                        for(int s=init;s<len;s++)
                                            data[4]+=" ";
                                        data[4]+=""+jLabel6.getText();
                                        pw.print(data[4]);
                                        len=125-((""+jLabel4.getText()).length());
                                        init=(data[0].length()+data[1].length()+data[2].length()+data[3].length()+data[4].length());
                                        for(int s=init;s<len;s++)
                                            data[5]+=" ";
                                        data[5]+=""+jLabel4.getText();
                                        pw.print(data[5]);
                                        System.out.println("a"+jLabel6.getText()+"b");
                                        System.out.println("a"+jLabel4.getText()+"b");
                                        blanklineflag=true;
                                    }
                                    if(flag2)
                                    {
                                        if(blanklineflag==true)
                                        {
                                            blanklineflag=false;
                                        }
                                        else
                                        {
                                            flag2 = false;
                                        int len=0,init=0;
                                        if(nxt==0)
                                        {
                                             pw.print(" ");
                                             pw.print("LIABILITIES : -".toUpperCase());
                                             for(int ii=0;ii<19;ii++)
                                             pw.print(" ");
                                             pw.print(" ");
                                             pw.print("ASSETS : -".toUpperCase());
                                             nxt1=-2;
                                             nxt=-1;
                                        }
                                        if(nxt1!=-1 && nxt1<dtm2.getRowCount())
                                        {
                                           //javax.swing.JOptionPane.showMessageDialog(rootPane,"coming here accessline>>"+assetLine+"   dtm copunt>>>>"+dtm2.getRowCount());
                                         // printAssets(assetLine);
                                           
                                            if(nxt1==0)
                                            {
                                               pw.print(" ");
                                               String tempt="TOTAL DUE : -";
                                               pw.print("TOTAL DUE : -".toUpperCase());
                                                //   for(int ii=0;ii<12;ii++)
                                                //       pw.print(" ");
                                               len=125-(jLabel6.getText().length());
                                                // init=85+(tempt.length());
                                                init=91+(tempt.length());
                                                for(int s=init;s<len;s++)
                                                pw.print(" ");
                                                pw.print(""+jLabel6.getText());
                                                pw.print(" ");
                                            //    pw.print(""+jLabel13.getText());
                                             pw.print(""+jTable3.getValueAt(nxt1,0));
                                             temp=""+jTable3.getValueAt(nxt1,0);

                                            //    init=76+(tempt.length())+(jLabel13.getText().length())+(jLabel6.getText().length())-1;
                                                 init=76+(tempt.length())+(temp.length())+(jLabel6.getText().length())-1;
                                                //len=125-(""+jTextField1.getText()).length();
                                                 len=125-(""+jTable3.getValueAt(nxt1,1)).length();
                                                for(int s=init;s<len;s++)
                                                pw.print(" ");
                                               // pw.print(""+jTextField1.getText());
                                                  pw.print(""+jTable3.getValueAt(nxt1,1));
                                            }
                                            if(nxt1==1)
                                            {
                                                 pw.print(" ");
                                                 String tempt="LIEU CASH : -";
                                                 LieuAmt="0.00";
                                                 pw.print("LIEU CASH : -".toUpperCase());
                                                 len=125-LieuAmt.length();
                                                    // init=85+tempt.length();
                                                 init=91+tempt.length();
                                                 for(int s=init;s<len;s++)
                                                 pw.print(" ");
                                                 pw.print(LieuAmt);
                                                 pw.print(" ");
                                                 ////pw.print(""+jLabel14.getText());
                                                 pw.print(""+jTable3.getValueAt(nxt1,0));
                                                 temp=""+jTable3.getValueAt(nxt1,0);
                                                 //len=125-((""+jTextField2.getText()).length());
                                                 len=125-((""+jTable3.getValueAt(nxt1,1)).length());
                                                    //init=85+tempt.length()+jLabel14.getText().length()+LieuAmt.length();
                                                 init=79+tempt.length()+temp.length()+LieuAmt.length();
                                                 for(int s=init;s<len;s++)
                                                 pw.print(" ");
                                                 //pw.print(""+jTextField2.getText());
                                                 pw.print(""+jTable3.getValueAt(nxt1,1));
                                            }
                                            else if(nxt1>1)
                                            {
                                                for(int ii=0;ii<25+11;ii++)
                                                pw.print(" ");
                                                //pw.print(""+jLabel15.getText());
                                                System.out.println("printing here>>>>>>>>>>"+(""+jTable3.getValueAt(nxt1,0)));
                                                pw.print(""+jTable3.getValueAt(nxt1,0));
                                                temp=""+jTable3.getValueAt(nxt1,0);
                                                //len=125-((""+jTextField3.getText()).length());
                                                len=125-((""+jTable3.getValueAt(nxt1,1)).length());
                                                //init=(85+(jLabel15.getText().length()))+11;
                                                init=(85+(temp.length()))+11;
                                                for(int s=init;s<len;s++)
                                                pw.print(" ");
                                                //pw.print(""+jTextField3.getText());
                                                pw.print(""+jTable3.getValueAt(nxt1,1));
                                            }
                                            if(nxt1==-2)
                                            {
                                                 nxt1=-1;
                                            }
                                                 nxt1++;
                                          assetLine++;
                                        }
                                      }
                                    }
                                    pw.println("");
                                }


                             //  printingRestOfAssets();
                               lastAssetTotalAmtPrint();
                                pw.close();
                                fos.close();

                                System.out.println("End printing");


                    }
                    catch(Exception x)
                    {
                                System.out.println("Error 123..."+x);
                    }

         }
   
         private void printAssets(int i)
         {
             int len,init;
            switch(i)
            {
                case 0:
                /*     pw.print(" ");
                    pw.print("LIABILITIES : -".toUpperCase());
                for(int ii=0;ii<19;ii++)
                    pw.print(" ");
                    pw.print(" ");
                    pw.print("ASSETS : -".toUpperCase());*/
                    break;
                case 1:
                 /*    pw.print(" ");
                     String tempt="TOTAL DUE : -";
                    pw.print("TOTAL DUE : -".toUpperCase());
                 //   for(int ii=0;ii<12;ii++)
                 //       pw.print(" ");
                    len=125-(jLabel6.getText().length());
                   // init=85+(tempt.length());
                    init=91+(tempt.length());
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jLabel6.getText());
                    pw.print(" ");
                    pw.print(""+jLabel13.getText());
                   // pw.print(""+jTable3.getValueAt(len, len));
                    //init=85+(tempt.length())+(jLabel13.getText().length())+(jLabel6.getText().length())-1;
                    init=76+(tempt.length())+(jLabel13.getText().length())+(jLabel6.getText().length())-1;
                    len=125-(""+jTextField1.getText()).length();
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jTextField1.getText());*////////////open here
                    //pw.print(""+jLabel6.getText());

                   /* for(int ii=0;ii<25;ii++)
                        pw.print(" ");
                    pw.print(""+jLabel13.getText());
                    len=125-((""+jTextField1.getText()).length());
                    init=(85+(jLabel13.getText().length()));
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jTextField1.getText());*////////////
                    break;
                case 2:
                 /*    pw.print(" ");
                     tempt="LIEU CASH : -";
                     LieuAmt="0.00";
                    pw.print("LIEU CASH : -".toUpperCase());
                    len=125-LieuAmt.length();
                   // init=85+tempt.length();
                    init=91+tempt.length();
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(LieuAmt);
                          pw.print(" ");
                    pw.print(""+jLabel14.getText());
                    len=125-((""+jTextField2.getText()).length());
                    //init=85+tempt.length()+jLabel14.getText().length()+LieuAmt.length();
                    init=79+tempt.length()+jLabel14.getText().length()+LieuAmt.length();
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jTextField2.getText());*///////////open here
                    //for(int ii=0;ii<25;ii++)
                /*        pw.print(" ");
                    pw.print(""+jLabel14.getText());
                    len=125-((""+jTextField2.getText()).length());
                    init=(85+(jLabel14.getText().length()));
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jTextField2.getText());*///////////////
                    break;
                case 3:
                  /*  for(int ii=0;ii<25+11;ii++)
                        pw.print(" ");
                    pw.print(""+jLabel15.getText());
                    len=125-((""+jTextField3.getText()).length());
                    init=(85+(jLabel15.getText().length()))+11;
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jTextField3.getText());*/
                    break;
               case 4:
                /*    for(int ii=0;ii<25+11;ii++)
                        pw.print(" ");
                    pw.print(""+jTextField4.getText());
                    len=125-((""+jTextField5.getText()).length());
                    init=(85+(jTextField4.getText().length()))+11;
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jTextField5.getText());*/
                    break;
              case 5:
                 /*   for(int ii=0;ii<25+11;ii++)
                        pw.print(" ");
                    pw.print(""+jTextField6.getText());
                    len=125-((""+jTextField7.getText()).length());
                    init=(85+(jTextField6.getText().length()))+11;
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jTextField7.getText());*/
                    break;
              case 6:
                  /*  for(int ii=0;ii<25+11;ii++)
                        pw.print(" ");
                    pw.print(""+jTextField8.getText());
                    len=125-((""+jTextField9.getText()).length());
                    init=(85+(jTextField8.getText().length()))+11;
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jTextField9.getText());*/
                    break;
               case 7:
                 /*   for(int ii=0;ii<25+11;ii++)
                        pw.print(" ");
                    pw.print(""+jTextField10.getText());
                    len=125-((""+jTextField11.getText()).length());
                    init=(85+(jTextField10.getText().length()))+11;
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jTextField11.getText());*/
                    break;
              case 8:
                 /*   for(int ii=0;ii<25+11;ii++)
                        pw.print(" ");
                    pw.print(""+jTextField12.getText());
                    len=125-((""+jTextField13.getText()).length());
                    init=(85+(jTextField12.getText().length()))+11;
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    pw.print(""+jTextField13.getText());*/
                    break;
            }
         }
        /* private void printingRestOfAssets()
         {
             if(assetLine<=8)
             {
                 for(int i=assetLine;i<=8;i++)
                 {
                    for(int s=0;s<60-25;s++)
                        pw.print(" ");
                    printAssets(i);
                    pw.println("");
                 }
             }
         }*/
         private void lastAssetTotalAmtPrint()
         {
              pw.print(" ");
             String temp="Total Amount";
             double tot=Double.valueOf(jLabel6.getText())+Double.valueOf(LieuAmt);
             String tempAmt=("" +new java.math.BigDecimal(tot).setScale(2,5));
             System.out.println("lastAssetTotalAmtPrint.........>>>>>");
             for(int s=0;s<=59;s++)
                        pw.print(" ");
             //pw.print(""+jLabel9.getText().toUpperCase());
             //pw.print(""+jLabel8.getText().toUpperCase());
             pw.print(temp.toUpperCase());
           
            // pw.print(tempAmt);
             int len=125-(tempAmt.length());
            // int init=85+jLabel9.getText().length();
            //  int init=85+jLabel8.getText().length();
               int init=85+temp.length()+6;
             
             for(int s=init;s<len;s++)
                  pw.print(" ");
             pw.print(tempAmt);
             pw.print(" ");
           
             //len=125-(jLabel9.getText().length());
           //  len=125-(jLabel8.getText().length());
               len=125-(temp.length())-8;
             //init=85+jLabel9.getText().length()+tempAmt.length();
             //init=85+jLabel8.getText().length()+tempAmt.length();
               init=85+temp.length()+tempAmt.length();
            
             
             for(int s=init;s<len;s++)
                     pw.print(" ");
              pw.print(""+temp.toUpperCase());
             //for(int s=0;s<85;s++)
               //         pw.print(" ");
             //len=125-((""+jLabel8.getText()).length());
              len=125-(temp.length());
                   // init=(85+(jLabel9.getText().length()))+tempAmt.length();
              //init=(85+(jLabel8.getText().length()))+tempAmt.length();
              init=(85+(temp.length()))+tempAmt.length()+3;
                  //  pw.print(""+jLabel9.getText().toUpperCase());
                    //len=125-((""+jLabel8.getText()).length());
                   // init=(85+(jLabel9.getText().length()))+jLabel9.getText().length()+tempAmt.length();
                     System.out.println("init.........."+init+" len...."+len);
                    for(int s=init;s<len;s++)
                        pw.print(" ");
                    //pw.print(""+jLabel8.getText().toUpperCase());
                     pw.print(""+jLabel9.getText().toUpperCase());
         }
   public void scroll()
     {
            for(int i=1;i<=6;i++)
            {
                pw.println();
            }
     }
     public void scroll(int n)
     {
            for(int i=1;i<=n;i++)
            {
                pw.println();
            }
     }

  }
//---------------------------------------------------------------------------------

}
